use std::path::{Path, PathBuf};
use std::fmt::Write;

fn module_name(path: &Path, base: &Path) -> String {
    let rel = path.strip_prefix(base).unwrap().with_extension("");
    let mut s = rel.to_string_lossy().replace('/', ".");
    if s.ends_with(".init") {
        s.truncate(s.len() - 5);
    }
    if s.is_empty() {
        s = base.file_name().unwrap().to_string_lossy().to_string();
    }
    s
}

fn collect(dir: &Path, base: &Path, out: &mut Vec<(String, String)>) {
    for entry in std::fs::read_dir(dir).unwrap() {
        let entry = entry.unwrap();
        let path = entry.path();
        if path.is_dir() {
            collect(&path, base, out);
        } else if path.extension().is_some_and(|e| e == "lua") {
            out.push((module_name(&path, base), path.to_string_lossy().to_string()));
        }
    }
}

fn build_luajit() -> PathBuf {
    let src = Path::new(".vendor/LuaJIT/src");
    let abs = std::fs::canonicalize(src).unwrap();

    // Force clean rebuild to ensure PIC is applied
    std::process::Command::new("make")
        .args(["-C", &abs.to_string_lossy(), "clean"])
        .status().ok();
    let status = std::process::Command::new("make")
        .args([
            "-C", &abs.to_string_lossy(),
            "-j", &std::thread::available_parallelism().map(|n| n.get()).unwrap_or(4).to_string(),
        ])
        .env("CFLAGS", "-fPIC")
        .status()
        .unwrap();
    assert!(status.success(), "LuaJIT build failed");

    // Create a symlink so mlua-sys can find it as libluajit-5.1.a
    let symlink = abs.join("libluajit-5.1.a");
    if !symlink.exists() {
        std::os::unix::fs::symlink(abs.join("libluajit.a"), &symlink).ok();
    }

    println!("cargo:rustc-link-search={}", abs.display());
    println!("cargo:rustc-link-lib=static=luajit");
    // Force static linking of luajit-5.1 specifically for the moonlift binary
    // (mlua-sys emits a dynamic -lluajit-5.1; we override to static)
    println!("cargo:rustc-link-arg-bin=moonlift=-Wl,-Bstatic");
    println!("cargo:rustc-link-arg-bin=moonlift=-lluajit-5.1");
    println!("cargo:rustc-link-arg-bin=moonlift=-Wl,-Bdynamic");
    // Export all symbols so dynamic C modules (cjson, etc.) can find Lua API
    println!("cargo:rustc-link-arg-bin=moonlift=-Wl,--export-dynamic");
    abs
}

fn main() {
    println!("cargo::rerun-if-changed=lua/");
    println!("cargo::rerun-if-changed=.vendor/LuaJIT/src");
    println!("cargo::rerun-if-env-changed=CFLAGS");

    build_luajit();

    let lua_dir = Path::new("lua");
    let mut modules = Vec::new();
    collect(lua_dir, lua_dir, &mut modules);
    modules.sort_by(|a, b| a.0.cmp(&b.0));

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — do not edit.\n");
    code.push_str("pub fn embedded_modules() -> Vec<(&'static str, &'static str)> {\n");
    code.push_str("    vec![\n");
    for (name, path) in &modules {
        let rel = format!("../{}", path);
        write!(code, "        ({:?}, include_str!({:?})),\n", name, rel).unwrap();
    }
    code.push_str("    ]\n");
    code.push_str("}\n");

    std::fs::write("src/embedded_lua.rs", &code).unwrap();
}
