use std::path::{Path, PathBuf};
use std::fmt::Write;

fn module_name(path: &Path, base: &Path) -> String {
    let rel = path.strip_prefix(base).unwrap().with_extension("");
    let mut s = rel.to_string_lossy().replace('/', ".");
    if s.ends_with(".init") {
        s.truncate(s.len() - 5);
    }
    if s.is_empty() {
        s = base.file_name().unwrap().to_string_lossy().to_string();
    }
    s
}

fn collect(dir: &Path, base: &Path, ext: &str, out: &mut Vec<(String, String)>) {
    for entry in std::fs::read_dir(dir).unwrap() {
        let entry = entry.unwrap();
        let path = entry.path();
        if path.is_dir() {
            collect(&path, base, ext, out);
        } else if path.extension().is_some_and(|e| e == ext) {
            out.push((module_name(&path, base), path.to_string_lossy().to_string()));
        }
    }
}

fn collect_paths(dir: &Path, ext: &str, out: &mut Vec<String>) {
    for entry in std::fs::read_dir(dir).unwrap() {
        let entry = entry.unwrap();
        let path = entry.path();
        if path.is_dir() {
            collect_paths(&path, ext, out);
        } else if path.extension().is_some_and(|e| e == ext) {
            out.push(path.to_string_lossy().to_string());
        }
    }
}

fn build_luajit() -> PathBuf {
    let src = Path::new(".vendor/LuaJIT/src");
    let abs = std::fs::canonicalize(src).unwrap();

    // Force clean rebuild to ensure PIC is applied
    std::process::Command::new("make")
        .args(["-C", &abs.to_string_lossy(), "clean"])
        .status().ok();
    let status = std::process::Command::new("make")
        .args([
            "-C", &abs.to_string_lossy(),
            "-j", &std::thread::available_parallelism().map(|n| n.get()).unwrap_or(4).to_string(),
        ])
        .env("CFLAGS", "-fPIC")
        .status()
        .unwrap();
    assert!(status.success(), "LuaJIT build failed");

    // Create a symlink so mlua-sys can find it as libluajit-5.1.a
    let symlink = abs.join("libluajit-5.1.a");
    if !symlink.exists() {
        std::os::unix::fs::symlink(abs.join("libluajit.a"), &symlink).ok();
    }

    println!("cargo:rustc-link-search={}", abs.display());
    println!("cargo:rustc-link-lib=static=luajit");
    // Force static linking of luajit-5.1 specifically for the moonlift binary
    // (mlua-sys emits a dynamic -lluajit-5.1; we override to static)
    for bin in ["moonlift", "mom"] {
        println!("cargo:rustc-link-arg-bin={bin}=-Wl,-Bstatic");
        println!("cargo:rustc-link-arg-bin={bin}=-lluajit-5.1");
        println!("cargo:rustc-link-arg-bin={bin}=-Wl,-Bdynamic");
        // Export all symbols so dynamic C modules and LuaJIT FFI can find APIs.
        println!("cargo:rustc-link-arg-bin={bin}=-Wl,--export-dynamic");
    }
    abs
}


fn link_mom_precompiled() {
    let mom_obj = PathBuf::from("target/libmom_precompiled.o");

    if mom_obj.exists() {
        let mom_obj_abs = std::fs::canonicalize(&mom_obj).unwrap_or_else(|_| mom_obj.clone());
        println!("cargo:rustc-link-search=native=target/");
        println!("cargo:rustc-link-arg-bin=mom=-Wl,--whole-archive");
        println!("cargo:rustc-link-arg-bin=mom={}", mom_obj_abs.display());
        println!("cargo:rustc-link-arg-bin=mom=-Wl,--no-whole-archive");
    } else {
        println!("cargo:warning=libmom_precompiled.o not found; generate it with: ./target/release/moonlift scripts/emit_mom_precompiled.mlua");
    }
}

fn main() {
    println!("cargo::rerun-if-changed=lua/");
    println!("cargo::rerun-if-changed=.vendor/LuaJIT/src");
    println!("cargo::rerun-if-env-changed=CFLAGS");

    build_luajit();

    let lua_dir = Path::new("lua");
    let mut modules = Vec::new();
    collect(lua_dir, lua_dir, "lua", &mut modules);
    modules.sort_by(|a, b| a.0.cmp(&b.0));

    // Also include MOM modules that need to be available via require() in scripts
    let mom_modules_to_embed = vec![
        ("moonlift.mom.init", "lua/moonlift/mom/init.lua"),
        ("moonlift.mom.back.back_tags", "lua/moonlift/mom/back/back_tags.lua"),
    ];
    for (name, path) in mom_modules_to_embed {
        if !modules.iter().any(|(n, _)| n == name) {
            if Path::new(path).exists() {
                modules.push((name.to_string(), path.to_string()));
            }
        }
    }

    let mut mlua_sources = Vec::new();
    collect_paths(Path::new("lua/moonlift/mom"), "mlua", &mut mlua_sources);
    mlua_sources.sort();

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — do not edit.\n");
    code.push_str("pub fn embedded_modules() -> Vec<(&'static str, &'static str)> {\n");
    code.push_str("    vec![\n");
    for (name, path) in &modules {
        let rel = format!("../{}", path);
        write!(code, "        ({:?}, include_str!({:?})),\n", name, rel).unwrap();
    }
    code.push_str("    ]\n");
    code.push_str("}\n\n");

    code.push_str("pub fn embedded_mlua_sources() -> Vec<(&'static str, &'static str)> {\n");
    code.push_str("    vec![\n");
    for path in &mlua_sources {
        let rel = format!("../{}", path);
        write!(code, "        ({:?}, include_str!({:?})),\n", path, rel).unwrap();
    }
    code.push_str("    ]\n");
    code.push_str("}\n");

    std::fs::write("src/embedded_lua.rs", &code).unwrap();

    link_mom_precompiled();
}
