package.path = "./?.lua;./?/init.lua;./lua/?.lua;./lua/?/init.lua;" .. package.path

local moon = require("moonlift")
local pvm = require("moonlift.pvm")
local Schema = require("moonlift.schema")
local Pipeline = require("moonlift.frontend_pipeline")

local function exec_ok(cmd)
    local a = os.execute(cmd)
    return a == true or a == 0
end

local function syntax_check(c_src, label)
    if not exec_ok("command -v cc >/dev/null 2>&1") then
        io.write("cc not found; skipping " .. label .. " syntax check\n")
        return
    end
    local path = os.tmpname() .. ".c"
    local f = assert(io.open(path, "wb"))
    f:write(c_src)
    f:close()
    local ok = exec_ok("cc -std=c99 -fsyntax-only " .. path)
    os.remove(path)
    assert(ok, label .. " failed cc -std=c99 -fsyntax-only")
end

local src = [[
func add_i32(a: i32, b: i32): i32
    return a + b
end

func choose_i32(x: i32): i32
    return block choose(): i32
        if x > 0 then yield x else yield 1 end
    end
end
]]

local out_path = os.tmpname() .. ".c"
local c_src = moon.emit_c(src, out_path, "emit_c_api")
assert(type(c_src) == "string" and #c_src > 0, "emit_c should return C source text")
assert(c_src:match("generated by moonlift C backend"), "expected generated comment")
assert(c_src:match("target: pointer_bits=64 index_bits=64"), "expected target facts")
assert(c_src:find("/%* typedefs %*/") < c_src:find("/%* signatures %*/"), "typedefs should precede signatures")
assert(c_src:find("/%* helpers %*/") < c_src:find("/%* prototypes %*/"), "helpers should precede prototypes")
assert(c_src:match("int32_t add_i32%("), "expected add_i32 in emitted C")
local f = assert(io.open(out_path, "rb"))
local written = f:read("*a")
f:close()
os.remove(out_path)
assert(written == c_src, "emit_c should write the same source it returns")
syntax_check(c_src, "moon.emit_c output")

local T = pvm.context(); Schema.Define(T)
local lowered = Pipeline.Define(T).parse_and_lower_c(src, { site = "emit_c_api_lower" })
assert(#lowered.c_report.issues == 0, "expected no validation issues from API source")
assert(lowered.c_unit.target.pointer_bits == 64 and lowered.c_unit.target.index_bits == 64, "expected native64 default target")

local Host = require("moonlift.mlua_run")
local bundle = Host.eval [[
local add = func hosted_add(a: i32, b: i32): i32
    return a + b
end
local M = moon.module("emit_c_host_bundle")
M:add_func(add)
return M
]]

local bundle_path = os.tmpname() .. ".c"
local bundle_src = bundle:c_source(bundle_path)
assert(bundle_src:match("int32_t hosted_add%("), "expected hosted_add in bundle C source")
local bf = assert(io.open(bundle_path, "rb"))
local bundle_written = bf:read("*a")
bf:close()
os.remove(bundle_path)
assert(bundle_written == bundle_src, "BundleValue:c_source should write the returned source")
syntax_check(bundle_src, "BundleValue:c_source output")

io.write("moonlift emit_c_api ok\n")
