package.path = "./?.lua;./?/init.lua;./lua/?.lua;./lua/?/init.lua;" .. package.path

local asdl = require("lalin.asdl")
local A = require("lalin.schema_projection")
local Ops = require("lalin.core_operator")

local T = asdl.context()
A(T)
local L = Ops(T)
local C = T.LalinCore

assert(L.unary(C.UnaryNeg) == C.UnaryFamilyArithmetic)
assert(L.unary(C.UnaryNot) == C.UnaryFamilyLogical)
assert(L.unary(C.UnaryBitNot) == C.UnaryFamilyBitwise)

assert(L.binary(C.BinAdd) == C.BinaryFamilyArithmetic)
assert(L.binary(C.BinSub) == C.BinaryFamilyArithmetic)
assert(L.binary(C.BinMul) == C.BinaryFamilyArithmetic)
assert(L.binary(C.BinDiv) == C.BinaryFamilyDivision)
assert(L.binary(C.BinRem) == C.BinaryFamilyRemainder)
assert(L.binary(C.BinBitAnd) == C.BinaryFamilyBitwise)
assert(L.binary(C.BinBitOr) == C.BinaryFamilyBitwise)
assert(L.binary(C.BinBitXor) == C.BinaryFamilyBitwise)
assert(L.binary(C.BinShl) == C.BinaryFamilyShift)
assert(L.binary(C.BinLShr) == C.BinaryFamilyShift)
assert(L.binary(C.BinAShr) == C.BinaryFamilyShift)

assert(L.cmp(C.CmpEq) == C.CmpFamilyEquality)
assert(L.cmp(C.CmpNe) == C.CmpFamilyEquality)
assert(L.cmp(C.CmpLt) == C.CmpFamilyOrdering)
assert(L.cmp(C.CmpLe) == C.CmpFamilyOrdering)
assert(L.cmp(C.CmpGt) == C.CmpFamilyOrdering)
assert(L.cmp(C.CmpGe) == C.CmpFamilyOrdering)

assert(L.intrinsic(C.IntrinsicPopcount) == C.IntrinsicFamilyBit)
assert(L.intrinsic(C.IntrinsicClz) == C.IntrinsicFamilyBit)
assert(L.intrinsic(C.IntrinsicCtz) == C.IntrinsicFamilyBit)
assert(L.intrinsic(C.IntrinsicRotl) == C.IntrinsicFamilyBit)
assert(L.intrinsic(C.IntrinsicRotr) == C.IntrinsicFamilyBit)
assert(L.intrinsic(C.IntrinsicBswap) == C.IntrinsicFamilyBit)
assert(L.intrinsic(C.IntrinsicFma) == C.IntrinsicFamilyFused)
assert(L.intrinsic(C.IntrinsicSqrt) == C.IntrinsicFamilyFloat)
assert(L.intrinsic(C.IntrinsicAbs) == C.IntrinsicFamilyFloat)
assert(L.intrinsic(C.IntrinsicFloor) == C.IntrinsicFamilyFloat)
assert(L.intrinsic(C.IntrinsicCeil) == C.IntrinsicFamilyFloat)
assert(L.intrinsic(C.IntrinsicTruncFloat) == C.IntrinsicFamilyFloat)
assert(L.intrinsic(C.IntrinsicRound) == C.IntrinsicFamilyFloat)
assert(L.intrinsic(C.IntrinsicTrap) == C.IntrinsicFamilyControl)
assert(L.intrinsic(C.IntrinsicAssume) == C.IntrinsicFamilyControl)

print("lalin core_operator ok")
