package.path = "./?.lua;./?/init.lua;./lua/?.lua;./lua/?/init.lua;" .. package.path

local Json = require("moonlift.mlua_run").dofile("examples/json/json_lua_stack_decoder.mlua")

assert(type(Json.c_blob) == "string" and #Json.c_blob > 1000)
assert(Json.c_blob:find("json_decode_value_events", 1, true))
assert(not Json.c_blob:find("lua_", 1, true))
assert(Json.c_backend == "gcc-o3" or Json.c_backend == "libtcc")
assert(type(Json.value_fn) == "table")
assert(Json.c_api.decode == "json_decode_value_events")
assert(Json.c_api.typed_arrays.tags == "Int32Array")
assert(Json.c_api.typed_arrays.nums == "Float64Array")
assert(Json.c_api.typed_arrays.strings == "Uint8Array")
assert(Json.tags.NULL == 10)
assert(Json.c_header:find("json_decode_value_events", 1, true))
assert(Json.emcc_args[1] == "-O3")

local doc = Json.decode([[{"empty_object":{},"empty_array":[],"items":[1,true,null,"x"],"text":"line\n"}]])
assert(getmetatable(doc) == Json.object_mt)
assert(getmetatable(doc.empty_object) == Json.object_mt)
assert(getmetatable(doc.empty_array) == Json.array_mt)
assert(getmetatable(doc.items) == Json.array_mt)
assert(doc.items[3] == Json.null)
assert(doc.text == "line\n")

local encoded = Json.encode(doc)
assert(encoded == [[{"empty_array":[],"empty_object":{},"items":[1,true,null,"x"],"text":"line\n"}]])

local invalid, err = Json.decode_or_nil("[1,]")
assert(invalid == nil)
assert(err and err.kind == "syntax" and err.offset >= 1)
assert(Json.valid([[{"ok":true}]]))
assert(not Json.valid("[1,]"))

local out = os.tmpname()
local path, n = Json.write_c(out)
assert(path == out and n == #Json.c_blob)
local f = assert(io.open(out, "rb"))
local written = f:read("*a")
f:close()
os.remove(out)
assert(written == Json.c_blob)

local header_out = os.tmpname()
local header_path, header_n = Json.write_header(header_out)
assert(header_path == header_out and header_n == #Json.c_header)
local hf = assert(io.open(header_out, "rb"))
local header_written = hf:read("*a")
hf:close()
os.remove(header_out)
assert(header_written == Json.c_header)

Json.close()

print("moonlift json library showcase ok")
