print("=== moonlift bench suite ===")
print("")
print("--- control ---")
dofile("examples/bench_control.lua")
print("")
print("--- calls ---")
dofile("examples/bench_calls.lua")
print("")
print("--- aggregate ---")
dofile("examples/bench_aggregate.lua")
print("")
print("--- memory ---")
dofile("examples/bench_mem.lua")
print("")
print("--- frontend ---")
dofile("examples/bench_frontend.lua")
