package.path = "./?.lua;./?/init.lua;./lua/?.lua;./lua/?/init.lua;" .. package.path

local pvm = require("moonlift.pvm")
local CompilerPackage = require("moonlift.compiler_package")
local Plan = require("moonlift.phase_plan")

local T = pvm.context()
local pkg = CompilerPackage(T)
local P = T.MoonPhase

assert(pvm.classof(pkg) == P.Package)
assert(pkg.id.text == "moonlift.compiler")
assert(#pkg.worlds == 10)
assert(#pkg.machines == 8)
assert(#pkg.phases == 8)
assert(#pkg.roots == 4)
assert(pkg.worlds[1].ty.module_name == "MoonTree")
assert(pkg.worlds[1].ty.type_name == "Module")
assert(pkg.worlds[2].ty.module_name == "MoonTree")
assert(pkg.worlds[2].ty.type_name == "TypeModuleResult")
assert(pkg.worlds[3].ty.module_name == "MoonCompiler")
assert(pkg.worlds[3].ty.type_name == "CodeResult")
assert(pkg.worlds[4].ty.module_name == "MoonCompiler")
assert(pkg.worlds[4].ty.type_name == "CodeResult")
assert(pkg.worlds[5].ty.module_name == "MoonBack")
assert(pkg.worlds[5].ty.type_name == "Program")
assert(pkg.worlds[6].ty.module_name == "MoonCompiler")
assert(pkg.worlds[6].ty.type_name == "FlatlineImage")
assert(pkg.worlds[7].ty.module_name == "MoonCompiler")
assert(pkg.worlds[7].ty.type_name == "NativeArtifact")
assert(pkg.worlds[8].ty.module_name == "MoonCompiler")
assert(pkg.worlds[8].ty.type_name == "ObjectArtifact")
assert(pkg.worlds[9].ty.module_name == "MoonC")
assert(pkg.worlds[9].ty.type_name == "CBackendUnit")
assert(pkg.worlds[10].ty.module_name == "MoonDiag")
assert(pkg.worlds[10].ty.type_name == "Report")

local planned = Plan.assert_plan(pkg, "compile")
assert(pvm.classof(planned.plan) == P.Plan)
assert(#planned.plan.steps == 4)
assert(planned.plan.steps[1].machine.text == "hosted_typecheck")
assert(planned.plan.steps[2].machine.text == "hosted_checked_to_back_code")
assert(planned.plan.steps[3].machine.text == "hosted_back_code_to_back")
assert(planned.plan.steps[4].machine.text == "hosted_back_to_flatline")
assert(planned.plan.input.text == "tree")
assert(planned.plan.output.text == "flatline")

local c_plan = Plan.assert_plan(pkg, "emit_c")
assert(pvm.classof(c_plan.plan) == P.Plan)
assert(#c_plan.plan.steps == 3)
assert(c_plan.plan.steps[1].machine.text == "hosted_typecheck")
assert(c_plan.plan.steps[2].machine.text == "hosted_checked_to_c_code")
assert(c_plan.plan.steps[3].machine.text == "hosted_c_code_to_c")
assert(c_plan.plan.output.text == "c")

local jit_plan = Plan.assert_plan(pkg, "jit")
assert(pvm.classof(jit_plan.plan) == P.Plan)
assert(#jit_plan.plan.steps == 5)
assert(jit_plan.plan.steps[1].machine.text == "hosted_typecheck")
assert(jit_plan.plan.steps[2].machine.text == "hosted_checked_to_back_code")
assert(jit_plan.plan.steps[3].machine.text == "hosted_back_code_to_back")
assert(jit_plan.plan.steps[4].machine.text == "hosted_back_to_flatline")
assert(jit_plan.plan.steps[5].machine.text == "hosted_flatline_to_native")
assert(jit_plan.plan.output.text == "native")

local object_plan = Plan.assert_plan(pkg, "emit_object")
assert(pvm.classof(object_plan.plan) == P.Plan)
assert(#object_plan.plan.steps == 5)
assert(object_plan.plan.steps[5].machine.text == "hosted_flatline_to_object")
assert(object_plan.plan.output.text == "object")

io.write("moonlift compiler_package ok\n")
