package.path = "./?.lua;./?/init.lua;./lua/?.lua;./lua/?/init.lua;" .. package.path

local pvm = require("moonlift.pvm")
local Schema = require("moonlift.schema")
local T = pvm.context(); Schema.Define(T)

local Core = T.MoonCore
local C = T.MoonC
local Emit = require("moonlift.c_emit").Define(T)
local Validate = require("moonlift.c_validate").Define(T)
local Helpers = require("moonlift.c_helpers").Define(T)
local CodeType = require("moonlift.code_type").Define(T)

local i32 = C.CBackendScalar(Core.ScalarI32)
local target = CodeType.default_target({})
local sig_id = C.CBackendFuncSigId("sig_i32_i32_i32")
local sig = C.CBackendFuncSig(sig_id, { i32, i32 }, i32)

local a = C.CBackendLocal(C.CBackendLocalId("a"), C.CBackendName("a"), i32)
local b = C.CBackendLocal(C.CBackendLocalId("b"), C.CBackendName("b"), i32)
local r = C.CBackendLocal(C.CBackendLocalId("r"), C.CBackendName("r"), i32)

local helper_kind = C.CBackendHelperIntBinary(Core.BinAdd, i32, C.CBackendIntWrap)
local helper = C.CBackendHelperUse(Helpers.helper_id(helper_kind), helper_kind)

local entry = C.CBackendBlock(
    C.CBackendLabel("entry"),
    {},
    { C.CBackendHelperCall(r.id, helper.id, { C.CBackendAtomLocal(a.id), C.CBackendAtomLocal(b.id) }) },
    C.CBackendReturn(C.CBackendAtomLocal(r.id))
)

local func = C.CBackendFunc(C.CBackendName("add"), "add", Core.VisibilityExport, sig_id, { a, b }, { r }, { entry })
local glob = C.CBackendGlobal(
    C.CBackendGlobalId("blob"),
    C.CBackendName("blob"),
    Core.VisibilityLocal,
    C.CBackendDataPtr(nil),
    8,
    4,
    { C.CBackendDataBytes(0, "moon") }
)
local ext = C.CBackendExtern(C.CBackendName("host_add"), "host_add", sig_id, nil)
local unit = C.CBackendUnit("emit_test", target, { sig }, {}, { glob }, { ext }, { helper }, { func })

local report = Validate.validate(unit)
assert(#report.issues == 0, "hand-built emit unit should validate")

local src = Emit.emit_artifact(unit).source
assert(src:match("/%* generated by moonlift C backend %*/"), "generated banner")
assert(src:match("#include <stdint.h>"), "stdint include")
assert(src:match("typedef int64_t ml_index;"), "target index typedef")
assert(src:match("typedef int32_t %(%*sig_i32_i32_i32%)%(int32_t, int32_t%);"), "signature typedef")
assert(src:match("extern int32_t host_add"), "extern declaration")
assert(src:match("static unsigned char blob%[8%] = { %[0%] = 109, %[1%] = 111, %[2%] = 111, %[3%] = 110 };"), "global declaration")
assert(src:match("static inline int32_t ml_i32_add_intwrap"), "helper definition")
assert(src:match("int32_t add%(int32_t a, int32_t b%)"), "function definition")
assert(src:match("entry:"), "entry label")
assert(src:match("return r;"), "return statement")

local function assert_order(s, ...)
    local last = 0
    for i = 1, select("#", ...) do
        local pat = select(i, ...)
        local pos = assert(s:find(pat, 1, true), "missing section " .. pat)
        assert(pos > last, "section out of order: " .. pat)
        last = pos
    end
end
assert_order(src, "/* target:", "#include <stdint.h>", "/* typedefs */", "/* signatures */", "/* type declarations", "/* externs */", "/* globals */", "/* helpers */", "/* prototypes */", "/* bodies */")

local pair_id = C.CTypeId("m", "Pair")
local pair_ty = C.CBackendNamed(pair_id)
local pair_decl = C.CBackendStructDecl(pair_id, { C.CBackendField(C.CBackendName("x"), i32, 0, 4, 4) }, 4, 4)
local void_sig_id = C.CBackendFuncSigId("sig_void")
local void_sig = C.CBackendFuncSig(void_sig_id, {}, C.CBackendVoid)
local pair_local = C.CBackendLocal(C.CBackendLocalId("p"), C.CBackendName("p"), pair_ty)
local callee = C.CBackendLocal(C.CBackendLocalId("callee"), C.CBackendName("callee"), C.CBackendCodePtr(sig_id))
local out_local = C.CBackendLocal(C.CBackendLocalId("out"), C.CBackendName("out"), i32)
local place = C.CBackendPlaceLocal(pair_local.id, pair_ty)
local join_param = C.CBackendBlockParam(C.CBackendLocalId("jp"), i32)
local entry2 = C.CBackendBlock(
    C.CBackendLabel("entry"),
    {},
    {
        C.CBackendAggregateInit(place, pair_ty, { C.CBackendAggregateFieldInit(C.CBackendName("x"), C.CBackendAtomLiteral(i32, Core.LitInt("7")), 0) }),
        C.CBackendCall(out_local.id, C.CBackendCallIndirect(C.CBackendAtomLocal(callee.id), sig_id), { C.CBackendAtomLiteral(i32, Core.LitInt("1")), C.CBackendAtomLiteral(i32, Core.LitInt("2")) }),
    },
    C.CBackendGoto(C.CBackendLabel("join"), { C.CBackendAtomLocal(out_local.id) })
)
local join = C.CBackendBlock(C.CBackendLabel("join"), { join_param }, {}, C.CBackendReturnVoid)
local func2 = C.CBackendFunc(C.CBackendName("complex"), "complex", Core.VisibilityLocal, void_sig_id, {}, { pair_local, callee, out_local }, { entry2, join })
local scalar_glob = C.CBackendGlobal(C.CBackendGlobalId("counter"), C.CBackendName("counter"), Core.VisibilityLocal, i32, 4, 4, { C.CBackendDataScalar(0, i32, Core.LitInt("99")) })
local reloc_glob = C.CBackendGlobal(C.CBackendGlobalId("rel"), C.CBackendName("rel"), Core.VisibilityLocal, C.CBackendDataPtr(nil), 8, 8, { C.CBackendDataReloc(0, C.CBackendRelocFunc(C.CBackendName("complex")), 0) })
local access = C.CBackendMemoryAccess(i32, 4, C.CBackendMayTrap, false, Core.AtomicSeqCst)
local atomic_kind = C.CBackendHelperAtomicLoad(access)
local atomic_helper = C.CBackendHelperUse(Helpers.helper_id(atomic_kind), atomic_kind)
local complex_unit = C.CBackendUnit("complex", CodeType.default_target({ dialect = "c11", index_bits = 32 }), { sig, void_sig }, { pair_decl }, { scalar_glob, reloc_glob }, {}, { atomic_helper }, { func2 })
local complex_src = Emit.emit_artifact(complex_unit).source
assert(complex_src:match("#include <stdatomic.h>"), "atomics include")
assert(complex_src:match("typedef int32_t ml_index;"), "32-bit index typedef")
assert(complex_src:match("typedef struct m_Pair"), "descriptor/layout type decl")
assert(complex_src:match("ml_assert_size_m_Pair"), "layout size assert")
assert(complex_src:match("/%* scalar init at 0: 99 %*/"), "typed scalar global init comment")
assert(complex_src:match("/%* reloc init at 0 %*/"), "reloc global init comment")
assert(complex_src:match("p%.x = %(int32_t%)7;"), "aggregate init emits field assignment")
assert(complex_src:match("callee%("), "indirect call syntax")
assert(complex_src:match("__xfer_join_1"), "transfer temp emitted")
assert(complex_src:match("atomic_load_explicit"), "atomic helper emitted")
assert_order(complex_src, "/* typedefs */", "/* signatures */", "/* type declarations", "/* globals */", "/* helpers */", "/* prototypes */", "/* bodies */")

local freestanding_src = Emit.emit_artifact(C.CBackendUnit("free", CodeType.default_target({ platform = "freestanding", dialect = "c99" }), {}, {}, {}, {}, { atomic_helper }, {})).source
assert(freestanding_src:match("atomics require C11"), "non-C11/freestanding atomic diagnostic comment")

local cc = os.getenv("CC") or "cc"
local ok_probe = os.execute(cc .. " --version >/dev/null 2>&1")
if ok_probe == true or ok_probe == 0 then
    local function syntax_check(s)
        local path = os.tmpname() .. ".c"
        local f = assert(io.open(path, "wb")); f:write(s); f:close()
        local ok = os.execute(cc .. " -std=c99 -fsyntax-only " .. path .. " >/dev/null 2>&1")
        os.remove(path)
        assert(ok == true or ok == 0, "emitted C should pass cc -std=c99 -fsyntax-only")
    end
    syntax_check(src)
    syntax_check(complex_src)
else
    io.write("skipping cc syntax check; no C compiler found\n")
end

io.write("moonlift c_emit ok\n")
