use crate::source::Span;
use std::mem;

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum TokenKind {
    Eof,
    Newline,
    Ident(String),
    Number(String),
    String(String),
    Splice(String),

    LParen,
    RParen,
    LBracket,
    RBracket,
    LBrace,
    RBrace,
    Comma,
    Colon,
    Semicolon,
    Dot,
    Question,
    At,

    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Amp,
    Pipe,
    Tilde,
    Assign,
    EqEq,
    NotEq,
    Less,
    LessEq,
    Greater,
    GreaterEq,
    Arrow,
    Shl,
    Shr,
    ShrU,

    KwFunc,
    KwExtern,
    KwStruct,
    KwUnion,
    KwTagged,
    KwEnum,
    KwSlice,
    KwOpaque,
    KwType,
    KwImpl,
    KwConst,
    KwLet,
    KwVar,
    KwIf,
    KwThen,
    KwElseIf,
    KwElse,
    KwWhile,
    KwDo,
    KwFor,
    KwIn,
    KwBreak,
    KwContinue,
    KwReturn,
    KwSwitch,
    KwCase,
    KwDefault,
    KwEnd,
    KwTrue,
    KwFalse,
    KwNil,
    KwPub,
    KwAs,
    KwCast,
    KwTrunc,
    KwZext,
    KwSext,
    KwBitcast,
    KwSizeof,
    KwAlignof,
    KwOffsetof,
    KwLoad,
    KwStore,
    KwMemcpy,
    KwMemmove,
    KwMemset,
    KwMemcmp,
    KwAnd,
    KwOr,
    KwNot,
}

impl TokenKind {
    pub fn same_variant(&self, other: &Self) -> bool {
        mem::discriminant(self) == mem::discriminant(other)
    }

    pub fn keyword(ident: &str) -> Option<Self> {
        Some(match ident {
            "func" => Self::KwFunc,
            "extern" => Self::KwExtern,
            "struct" => Self::KwStruct,
            "union" => Self::KwUnion,
            "tagged" => Self::KwTagged,
            "enum" => Self::KwEnum,
            "slice" => Self::KwSlice,
            "opaque" => Self::KwOpaque,
            "type" => Self::KwType,
            "impl" => Self::KwImpl,
            "const" => Self::KwConst,
            "let" => Self::KwLet,
            "var" => Self::KwVar,
            "if" => Self::KwIf,
            "then" => Self::KwThen,
            "elseif" => Self::KwElseIf,
            "else" => Self::KwElse,
            "while" => Self::KwWhile,
            "do" => Self::KwDo,
            "for" => Self::KwFor,
            "in" => Self::KwIn,
            "break" => Self::KwBreak,
            "continue" => Self::KwContinue,
            "return" => Self::KwReturn,
            "switch" => Self::KwSwitch,
            "case" => Self::KwCase,
            "default" => Self::KwDefault,
            "end" => Self::KwEnd,
            "true" => Self::KwTrue,
            "false" => Self::KwFalse,
            "nil" => Self::KwNil,
            "pub" => Self::KwPub,
            "as" => Self::KwAs,
            "cast" => Self::KwCast,
            "trunc" => Self::KwTrunc,
            "zext" => Self::KwZext,
            "sext" => Self::KwSext,
            "bitcast" => Self::KwBitcast,
            "sizeof" => Self::KwSizeof,
            "alignof" => Self::KwAlignof,
            "offsetof" => Self::KwOffsetof,
            "load" => Self::KwLoad,
            "store" => Self::KwStore,
            "memcpy" => Self::KwMemcpy,
            "memmove" => Self::KwMemmove,
            "memset" => Self::KwMemset,
            "memcmp" => Self::KwMemcmp,
            "and" => Self::KwAnd,
            "or" => Self::KwOr,
            "not" => Self::KwNot,
            _ => return None,
        })
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
}

impl Token {
    pub fn new(kind: TokenKind, span: Span) -> Self {
        Self { kind, span }
    }
}
