local S = require("lalin.schema.dsl")
S.use()

return schema. LalinBack {
  sum. BackScalar {
    BackVoid,
    BackBool,
    BackI8,
    BackI16,
    BackI32,
    BackI64,
    BackU8,
    BackU16,
    BackU32,
    BackU64,
    BackF32,
    BackF64,
    BackPtr,
    BackIndex,
  },
  product. BackSigId { interned, text [str], },
  product. BackFuncId { interned, text [str], },
  product. BackExternId { interned, text [str], },
  product. BackDataId { interned, text [str], },
  product. BackBlockId { interned, text [str], },
  product. BackValId { interned, text [str], },
  product. BackStackSlotId { interned, text [str], },
  product. BackSwitchCase { interned, raw [str], dest [LalinBack.BackBlockId], },
  product. BackVec { interned, elem [LalinBack.BackScalar], lanes [number], },
  sum. BackShape {
    BackShapeScalar { variant_unique, scalar [LalinBack.BackScalar], },
    BackShapeVec { variant_unique, vec [LalinBack.BackVec], },
  },
  sum. BackTarget {
    BackTargetNative,
    BackTargetDynasmJit,
    BackTargetNamed { variant_unique, field. name [str], },
  },
  sum. BackEndian { BackEndianLittle, BackEndianBig, },
  sum. BackTargetFeature {
    BackFeatureSSE2,
    BackFeatureAVX2,
    BackFeatureAVX512F,
    BackFeatureFMA,
    BackFeaturePOPCNT,
    BackFeatureBMI1,
    BackFeatureBMI2,
    BackFeatureUnknown { variant_unique, field. name [str], },
  },
  sum. BackTargetFact {
    BackTargetPointerBits { variant_unique, bits [number], },
    BackTargetIndexBits { variant_unique, bits [number], },
    BackTargetEndian { variant_unique, endian [LalinBack.BackEndian], },
    BackTargetCacheLineBytes { variant_unique, bytes [number], },
    BackTargetFeature { variant_unique, feature [LalinBack.BackTargetFeature], },
    BackTargetSupportsShape { variant_unique, shape [LalinBack.BackShape], },
    BackTargetSupportsVectorOp { variant_unique, vec [LalinBack.BackVec], op_class [str], },
    BackTargetSupportsMaskedTail,
    BackTargetPrefersUnroll {
      variant_unique,
      shape [LalinBack.BackShape],
      unroll [number],
      rank [number],
    },
  },
  product. BackTargetModel {
    interned,
    target [LalinBack.BackTarget],
    facts [many [LalinBack.BackTargetFact]],
  },
  sum. BackAddressBase {
    BackAddrValue { variant_unique, field. value [LalinBack.BackValId], },
    BackAddrStack { variant_unique, slot [LalinBack.BackStackSlotId], },
    BackAddrData { variant_unique, data [LalinBack.BackDataId], },
  },
  sum. BackPointerProvenance {
    BackProvUnknown,
    BackProvStack { variant_unique, slot [LalinBack.BackStackSlotId], },
    BackProvData { variant_unique, data [LalinBack.BackDataId], },
    BackProvArg { variant_unique, field. name [str], },
    BackProvView { variant_unique, field. name [str], },
    BackProvDerived { variant_unique, reason [str], },
  },
  sum. BackPointerBounds {
    BackPtrBoundsUnknown,
    BackPtrInBounds { variant_unique, reason [str], },
    BackPtrMayLeaveObject { variant_unique, reason [str], },
  },
  product. BackAddress {
    interned,
    base [LalinBack.BackAddressBase],
    byte_offset [LalinBack.BackValId],
    provenance [LalinBack.BackPointerProvenance],
    formation_bounds [LalinBack.BackPointerBounds],
  },
  product. BackAccessId { interned, text [str], },
  sum. BackAlignment {
    BackAlignUnknown,
    BackAlignKnown { variant_unique, bytes [number], },
    BackAlignAtLeast { variant_unique, bytes [number], },
    BackAlignAssumed { variant_unique, bytes [number], reason [str], },
  },
  sum. BackDereference {
    BackDerefUnknown,
    BackDerefBytes { variant_unique, bytes [number], reason [str], },
    BackDerefAssumed { variant_unique, bytes [number], reason [str], },
  },
  sum. BackTrap {
    BackMayTrap,
    BackNonTrapping { variant_unique, reason [str], },
    BackChecked { variant_unique, reason [str], },
  },
  sum. BackMotion { BackMayNotMove, BackCanMove { variant_unique, reason [str], }, },
  sum. BackAccessEffect { BackAccessRead, BackAccessWrite, BackAccessReadWrite, BackAccessReadonly, },
  sum. BackAtomicOrdering { BackAtomicSeqCst, },
  sum. BackAtomicRmwOp {
    BackAtomicRmwAdd,
    BackAtomicRmwSub,
    BackAtomicRmwAnd,
    BackAtomicRmwOr,
    BackAtomicRmwXor,
    BackAtomicRmwXchg,
  },
  product. BackMemoryInfo {
    interned,
    access [LalinBack.BackAccessId],
    alignment [LalinBack.BackAlignment],
    dereference [LalinBack.BackDereference],
    trap [LalinBack.BackTrap],
    motion [LalinBack.BackMotion],
    effect [LalinBack.BackAccessEffect],
  },
  sum. BackIntOverflow {
    BackIntWrap,
    BackIntNoSignedWrap { variant_unique, reason [str], },
    BackIntNoUnsignedWrap { variant_unique, reason [str], },
    BackIntNoWrap { variant_unique, reason [str], },
  },
  sum. BackIntExact { BackIntMayLose, BackIntExact { variant_unique, reason [str], }, },
  product. BackIntSemantics {
    interned,
    overflow [LalinBack.BackIntOverflow],
    exact [LalinBack.BackIntExact],
  },
  sum. BackIntOp {
    BackIntAdd,
    BackIntSub,
    BackIntMul,
    BackIntSDiv,
    BackIntUDiv,
    BackIntSRem,
    BackIntURem,
  },
  sum. BackBitOp { BackBitAnd, BackBitOr, BackBitXor, },
  sum. BackShiftOp { BackShiftLeft, BackShiftLogicalRight, BackShiftArithmeticRight, },
  sum. BackRotateOp { BackRotateLeft, BackRotateRight, },
  sum. BackFloatSemantics {
    BackFloatStrict,
    BackFloatReassoc { variant_unique, reason [str], },
    BackFloatFastMath { variant_unique, reason [str], },
  },
  sum. BackFloatOp { BackFloatAdd, BackFloatSub, BackFloatMul, BackFloatDiv, },
  sum. BackLiteral {
    BackLitInt { variant_unique, raw [str], },
    BackLitFloat { variant_unique, raw [str], },
    BackLitBool { variant_unique, field. value [bool], },
    BackLitNull,
  },
  sum. BackUnaryOp { BackUnaryIneg, BackUnaryFneg, BackUnaryBnot, BackUnaryBoolNot, },
  sum. BackIntrinsicOp {
    BackIntrinsicPopcount,
    BackIntrinsicClz,
    BackIntrinsicCtz,
    BackIntrinsicBswap,
    BackIntrinsicSqrt,
    BackIntrinsicAbs,
    BackIntrinsicFloor,
    BackIntrinsicCeil,
    BackIntrinsicTruncFloat,
    BackIntrinsicRound,
  },
  sum. BackCompareOp {
    BackIcmpEq,
    BackIcmpNe,
    BackSIcmpLt,
    BackSIcmpLe,
    BackSIcmpGt,
    BackSIcmpGe,
    BackUIcmpLt,
    BackUIcmpLe,
    BackUIcmpGt,
    BackUIcmpGe,
    BackFCmpEq,
    BackFCmpNe,
    BackFCmpLt,
    BackFCmpLe,
    BackFCmpGt,
    BackFCmpGe,
  },
  sum. BackVecCompareOp {
    BackVecIcmpEq,
    BackVecIcmpNe,
    BackVecSIcmpLt,
    BackVecSIcmpLe,
    BackVecSIcmpGt,
    BackVecSIcmpGe,
    BackVecUIcmpLt,
    BackVecUIcmpLe,
    BackVecUIcmpGt,
    BackVecUIcmpGe,
  },
  sum. BackVecBinaryOp {
    BackVecIntAdd,
    BackVecIntSub,
    BackVecIntMul,
    BackVecBitAnd,
    BackVecBitOr,
    BackVecBitXor,
  },
  sum. BackVecMaskOp { BackVecMaskNot, BackVecMaskAnd, BackVecMaskOr, },
  sum. BackCastOp {
    BackBitcast,
    BackIreduce,
    BackSextend,
    BackUextend,
    BackFpromote,
    BackFdemote,
    BackSToF,
    BackUToF,
    BackFToS,
    BackFToU,
  },
  sum. BackCallTarget {
    BackCallDirect { variant_unique, func [LalinBack.BackFuncId], },
    BackCallExtern { variant_unique, func [LalinBack.BackExternId], },
    BackCallIndirect { variant_unique, callee [LalinBack.BackValId], },
  },
  sum. BackCallResult {
    BackCallStmt,
    BackCallValue {
      variant_unique,
      dst [LalinBack.BackValId],
      field. ty [LalinBack.BackScalar],
    },
  },
  sum. Cmd {
    CmdCreateSig {
      variant_unique,
      sig [LalinBack.BackSigId],
      params [many [LalinBack.BackScalar]],
      results [many [LalinBack.BackScalar]],
    },
    CmdDeclareData {
      variant_unique,
      data [LalinBack.BackDataId],
      size [number],
      align [number],
    },
    CmdDataInitZero {
      variant_unique,
      data [LalinBack.BackDataId],
      offset [number],
      size [number],
    },
    CmdDataInit {
      variant_unique,
      data [LalinBack.BackDataId],
      offset [number],
      field. ty [LalinBack.BackScalar],
      field. value [LalinBack.BackLiteral],
    },
    CmdDataAddr { variant_unique, dst [LalinBack.BackValId], data [LalinBack.BackDataId], },
    CmdFuncAddr { variant_unique, dst [LalinBack.BackValId], func [LalinBack.BackFuncId], },
    CmdExternAddr {
      variant_unique,
      dst [LalinBack.BackValId],
      func [LalinBack.BackExternId],
    },
    CmdDeclareFunc {
      variant_unique,
      visibility [LalinCore.Visibility],
      func [LalinBack.BackFuncId],
      sig [LalinBack.BackSigId],
    },
    CmdDeclareExtern {
      variant_unique,
      func [LalinBack.BackExternId],
      symbol [str],
      sig [LalinBack.BackSigId],
    },
    CmdBeginFunc { variant_unique, func [LalinBack.BackFuncId], },
    CmdCreateBlock { variant_unique, block [LalinBack.BackBlockId], },
    CmdSwitchToBlock { variant_unique, block [LalinBack.BackBlockId], },
    CmdSealBlock { variant_unique, block [LalinBack.BackBlockId], },
    CmdBindEntryParams {
      variant_unique,
      block [LalinBack.BackBlockId],
      values [many [LalinBack.BackValId]],
    },
    CmdAppendBlockParam {
      variant_unique,
      block [LalinBack.BackBlockId],
      field. value [LalinBack.BackValId],
      field. ty [LalinBack.BackShape],
    },
    CmdCreateStackSlot {
      variant_unique,
      slot [LalinBack.BackStackSlotId],
      size [number],
      align [number],
    },
    CmdAlias { variant_unique, dst [LalinBack.BackValId], src [LalinBack.BackValId], },
    CmdStackAddr {
      variant_unique,
      dst [LalinBack.BackValId],
      slot [LalinBack.BackStackSlotId],
    },
    CmdConst {
      variant_unique,
      dst [LalinBack.BackValId],
      field. ty [LalinBack.BackScalar],
      field. value [LalinBack.BackLiteral],
    },
    CmdUnary {
      variant_unique,
      dst [LalinBack.BackValId],
      op [LalinBack.BackUnaryOp],
      field. ty [LalinBack.BackShape],
      field. value [LalinBack.BackValId],
    },
    CmdIntrinsic {
      variant_unique,
      dst [LalinBack.BackValId],
      op [LalinBack.BackIntrinsicOp],
      field. ty [LalinBack.BackShape],
      args [many [LalinBack.BackValId]],
    },
    CmdCompare {
      variant_unique,
      dst [LalinBack.BackValId],
      op [LalinBack.BackCompareOp],
      field. ty [LalinBack.BackShape],
      lhs [LalinBack.BackValId],
      rhs [LalinBack.BackValId],
    },
    CmdCast {
      variant_unique,
      dst [LalinBack.BackValId],
      op [LalinBack.BackCastOp],
      field. ty [LalinBack.BackScalar],
      field. value [LalinBack.BackValId],
    },
    CmdPtrOffset {
      variant_unique,
      dst [LalinBack.BackValId],
      base [LalinBack.BackAddressBase],
      index [LalinBack.BackValId],
      elem_size [number],
      const_offset [number],
      provenance [LalinBack.BackPointerProvenance],
      bounds [LalinBack.BackPointerBounds],
    },
    CmdLoadInfo {
      variant_unique,
      dst [LalinBack.BackValId],
      field. ty [LalinBack.BackShape],
      addr [LalinBack.BackAddress],
      memory [LalinBack.BackMemoryInfo],
    },
    CmdStoreInfo {
      variant_unique,
      field. ty [LalinBack.BackShape],
      addr [LalinBack.BackAddress],
      field. value [LalinBack.BackValId],
      memory [LalinBack.BackMemoryInfo],
    },
    CmdAtomicLoad {
      variant_unique,
      dst [LalinBack.BackValId],
      field. ty [LalinBack.BackScalar],
      addr [LalinBack.BackAddress],
      memory [LalinBack.BackMemoryInfo],
      ordering [LalinBack.BackAtomicOrdering],
    },
    CmdAtomicStore {
      variant_unique,
      field. ty [LalinBack.BackScalar],
      addr [LalinBack.BackAddress],
      field. value [LalinBack.BackValId],
      memory [LalinBack.BackMemoryInfo],
      ordering [LalinBack.BackAtomicOrdering],
    },
    CmdAtomicRmw {
      variant_unique,
      dst [LalinBack.BackValId],
      op [LalinBack.BackAtomicRmwOp],
      field. ty [LalinBack.BackScalar],
      addr [LalinBack.BackAddress],
      field. value [LalinBack.BackValId],
      memory [LalinBack.BackMemoryInfo],
      ordering [LalinBack.BackAtomicOrdering],
    },
    CmdAtomicCas {
      variant_unique,
      dst [LalinBack.BackValId],
      field. ty [LalinBack.BackScalar],
      addr [LalinBack.BackAddress],
      expected [LalinBack.BackValId],
      replacement [LalinBack.BackValId],
      memory [LalinBack.BackMemoryInfo],
      ordering [LalinBack.BackAtomicOrdering],
    },
    CmdAtomicFence { variant_unique, ordering [LalinBack.BackAtomicOrdering], },
    CmdIntBinary {
      variant_unique,
      dst [LalinBack.BackValId],
      op [LalinBack.BackIntOp],
      scalar [LalinBack.BackScalar],
      semantics [LalinBack.BackIntSemantics],
      lhs [LalinBack.BackValId],
      rhs [LalinBack.BackValId],
    },
    CmdBitBinary {
      variant_unique,
      dst [LalinBack.BackValId],
      op [LalinBack.BackBitOp],
      scalar [LalinBack.BackScalar],
      lhs [LalinBack.BackValId],
      rhs [LalinBack.BackValId],
    },
    CmdBitNot {
      variant_unique,
      dst [LalinBack.BackValId],
      scalar [LalinBack.BackScalar],
      field. value [LalinBack.BackValId],
    },
    CmdShift {
      variant_unique,
      dst [LalinBack.BackValId],
      op [LalinBack.BackShiftOp],
      scalar [LalinBack.BackScalar],
      lhs [LalinBack.BackValId],
      rhs [LalinBack.BackValId],
    },
    CmdRotate {
      variant_unique,
      dst [LalinBack.BackValId],
      op [LalinBack.BackRotateOp],
      scalar [LalinBack.BackScalar],
      lhs [LalinBack.BackValId],
      rhs [LalinBack.BackValId],
    },
    CmdFloatBinary {
      variant_unique,
      dst [LalinBack.BackValId],
      op [LalinBack.BackFloatOp],
      scalar [LalinBack.BackScalar],
      semantics [LalinBack.BackFloatSemantics],
      lhs [LalinBack.BackValId],
      rhs [LalinBack.BackValId],
    },
    CmdMemcpy {
      variant_unique,
      dst [LalinBack.BackValId],
      src [LalinBack.BackValId],
      len [LalinBack.BackValId],
    },
    CmdMemset {
      variant_unique,
      dst [LalinBack.BackValId],
      byte [LalinBack.BackValId],
      len [LalinBack.BackValId],
    },
    CmdMemcmp {
      variant_unique,
      dst [LalinBack.BackValId],
      left [LalinBack.BackValId],
      right [LalinBack.BackValId],
      len [LalinBack.BackValId],
    },
    CmdSelect {
      variant_unique,
      dst [LalinBack.BackValId],
      field. ty [LalinBack.BackShape],
      cond [LalinBack.BackValId],
      then_value [LalinBack.BackValId],
      else_value [LalinBack.BackValId],
    },
    CmdFma {
      variant_unique,
      dst [LalinBack.BackValId],
      field. ty [LalinBack.BackScalar],
      semantics [LalinBack.BackFloatSemantics],
      a [LalinBack.BackValId],
      b [LalinBack.BackValId],
      c [LalinBack.BackValId],
    },
    CmdVecSplat {
      variant_unique,
      dst [LalinBack.BackValId],
      field. ty [LalinBack.BackVec],
      field. value [LalinBack.BackValId],
    },
    CmdVecBinary {
      variant_unique,
      dst [LalinBack.BackValId],
      op [LalinBack.BackVecBinaryOp],
      field. ty [LalinBack.BackVec],
      lhs [LalinBack.BackValId],
      rhs [LalinBack.BackValId],
    },
    CmdVecCompare {
      variant_unique,
      dst [LalinBack.BackValId],
      op [LalinBack.BackVecCompareOp],
      field. ty [LalinBack.BackVec],
      lhs [LalinBack.BackValId],
      rhs [LalinBack.BackValId],
    },
    CmdVecSelect {
      variant_unique,
      dst [LalinBack.BackValId],
      field. ty [LalinBack.BackVec],
      mask [LalinBack.BackValId],
      then_value [LalinBack.BackValId],
      else_value [LalinBack.BackValId],
    },
    CmdVecMask {
      variant_unique,
      dst [LalinBack.BackValId],
      op [LalinBack.BackVecMaskOp],
      field. ty [LalinBack.BackVec],
      args [many [LalinBack.BackValId]],
    },
    CmdVecInsertLane {
      variant_unique,
      dst [LalinBack.BackValId],
      field. ty [LalinBack.BackVec],
      field. value [LalinBack.BackValId],
      lane_value [LalinBack.BackValId],
      lane [number],
    },
    CmdVecExtractLane {
      variant_unique,
      dst [LalinBack.BackValId],
      field. ty [LalinBack.BackScalar],
      field. value [LalinBack.BackValId],
      lane [number],
    },
    CmdCall {
      variant_unique,
      result [LalinBack.BackCallResult],
      target [LalinBack.BackCallTarget],
      sig [LalinBack.BackSigId],
      args [many [LalinBack.BackValId]],
    },
    CmdJump {
      variant_unique,
      dest [LalinBack.BackBlockId],
      args [many [LalinBack.BackValId]],
    },
    CmdBrIf {
      variant_unique,
      cond [LalinBack.BackValId],
      then_block [LalinBack.BackBlockId],
      then_args [many [LalinBack.BackValId]],
      else_block [LalinBack.BackBlockId],
      else_args [many [LalinBack.BackValId]],
    },
    CmdSwitchInt {
      variant_unique,
      field. value [LalinBack.BackValId],
      field. ty [LalinBack.BackScalar],
      cases [many [LalinBack.BackSwitchCase]],
      default_dest [LalinBack.BackBlockId],
    },
    CmdReturnVoid,
    CmdReturnValue { variant_unique, field. value [LalinBack.BackValId], },
    CmdTrap,
    CmdFinishFunc { variant_unique, func [LalinBack.BackFuncId], },
    CmdFinalizeModule,
  },
  sum. BackShapeRequirement {
    BackShapeRequiresScalar,
    BackShapeRequiresVector,
    BackShapeAllowsScalarOrVector,
  },
  sum. BackProgramFact {
    BackFactCreateSig { variant_unique, index [number], sig [LalinBack.BackSigId], },
    BackFactSigRef { variant_unique, index [number], sig [LalinBack.BackSigId], },
    BackFactDeclareData { variant_unique, index [number], data [LalinBack.BackDataId], },
    BackFactDataRef { variant_unique, index [number], data [LalinBack.BackDataId], },
    BackFactDeclareFunc { variant_unique, index [number], func [LalinBack.BackFuncId], },
    BackFactFuncRef { variant_unique, index [number], func [LalinBack.BackFuncId], },
    BackFactDeclareExtern { variant_unique, index [number], func [LalinBack.BackExternId], },
    BackFactExternRef { variant_unique, index [number], func [LalinBack.BackExternId], },
    BackFactBeginFunc { variant_unique, index [number], func [LalinBack.BackFuncId], },
    BackFactFinishFunc { variant_unique, index [number], func [LalinBack.BackFuncId], },
    BackFactFinalizeModule { variant_unique, index [number], },
    BackFactCreateBlock { variant_unique, index [number], block [LalinBack.BackBlockId], },
    BackFactBlockRef { variant_unique, index [number], block [LalinBack.BackBlockId], },
    BackFactStackSlotDef { variant_unique, index [number], slot [LalinBack.BackStackSlotId], },
    BackFactStackSlotRef { variant_unique, index [number], slot [LalinBack.BackStackSlotId], },
    BackFactValueDef { variant_unique, index [number], field. value [LalinBack.BackValId], },
    BackFactValueUse { variant_unique, index [number], field. value [LalinBack.BackValId], },
    BackFactAccessDef { variant_unique, index [number], access [LalinBack.BackAccessId], },
    BackFactAccessRef { variant_unique, index [number], access [LalinBack.BackAccessId], },
    BackFactShapeUse {
      variant_unique,
      index [number],
      shape [LalinBack.BackShape],
      requirement [LalinBack.BackShapeRequirement],
    },
    BackFactFunctionBodyCommand { variant_unique, index [number], },
  },
  sum. BackValidationIssue {
    BackIssueEmptyProgram,
    BackIssueMissingFinalize,
    BackIssueCommandAfterFinalize { variant_unique, index [number], },
    BackIssueCommandOutsideFunction { variant_unique, index [number], },
    BackIssueNestedFunction {
      variant_unique,
      index [number],
      active [LalinBack.BackFuncId],
      field. next [LalinBack.BackFuncId],
    },
    BackIssueFinishWithoutBegin { variant_unique, index [number], func [LalinBack.BackFuncId], },
    BackIssueFinishWrongFunction {
      variant_unique,
      index [number],
      expected [LalinBack.BackFuncId],
      actual [LalinBack.BackFuncId],
    },
    BackIssueUnfinishedFunction { variant_unique, func [LalinBack.BackFuncId], },
    BackIssueDuplicateSig { variant_unique, index [number], sig [LalinBack.BackSigId], },
    BackIssueDuplicateData { variant_unique, index [number], data [LalinBack.BackDataId], },
    BackIssueDuplicateFunc { variant_unique, index [number], func [LalinBack.BackFuncId], },
    BackIssueDuplicateExtern { variant_unique, index [number], func [LalinBack.BackExternId], },
    BackIssueDuplicateBlock { variant_unique, index [number], block [LalinBack.BackBlockId], },
    BackIssueDuplicateStackSlot {
      variant_unique,
      index [number],
      slot [LalinBack.BackStackSlotId],
    },
    BackIssueDuplicateValue {
      variant_unique,
      index [number],
      field. value [LalinBack.BackValId],
    },
    BackIssueMissingSig { variant_unique, index [number], sig [LalinBack.BackSigId], },
    BackIssueMissingData { variant_unique, index [number], data [LalinBack.BackDataId], },
    BackIssueMissingFunc { variant_unique, index [number], func [LalinBack.BackFuncId], },
    BackIssueMissingExtern { variant_unique, index [number], func [LalinBack.BackExternId], },
    BackIssueMissingBlock { variant_unique, index [number], block [LalinBack.BackBlockId], },
    BackIssueMissingStackSlot {
      variant_unique,
      index [number],
      slot [LalinBack.BackStackSlotId],
    },
    BackIssueMissingValue {
      variant_unique,
      index [number],
      field. value [LalinBack.BackValId],
    },
    BackIssueDuplicateAccess {
      variant_unique,
      index [number],
      access [LalinBack.BackAccessId],
    },
    BackIssueMissingAccess { variant_unique, index [number], access [LalinBack.BackAccessId], },
    BackIssueInvalidAlignment { variant_unique, index [number], bytes [number], },
    BackIssueLoadAccessEffect { variant_unique, index [number], effect [LalinBack.BackAccessEffect], },
    BackIssueStoreAccessEffect {
      variant_unique,
      index [number],
      effect [LalinBack.BackAccessEffect],
    },
    BackIssueDereferenceTooSmall {
      variant_unique,
      index [number],
      dereference_bytes [number],
      access_bytes [number],
    },
    BackIssueIntScalarExpected {
      variant_unique,
      index [number],
      scalar [LalinBack.BackScalar],
    },
    BackIssueFloatScalarExpected {
      variant_unique,
      index [number],
      scalar [LalinBack.BackScalar],
    },
    BackIssueBitScalarExpected {
      variant_unique,
      index [number],
      scalar [LalinBack.BackScalar],
    },
    BackIssueShiftScalarExpected {
      variant_unique,
      index [number],
      scalar [LalinBack.BackScalar],
    },
    BackIssueNonTrappingWithoutDereference { variant_unique, index [number], },
    BackIssueCanMoveWithoutNonTrapping { variant_unique, index [number], },
    BackIssueShapeRequiresScalar {
      variant_unique,
      index [number],
      shape [LalinBack.BackShape],
    },
    BackIssueShapeRequiresVector {
      variant_unique,
      index [number],
      shape [LalinBack.BackShape],
    },
  },
  product. BackValidationReport { interned, issues [many [LalinBack.BackValidationIssue]], },
  product. BackCommandCount { interned, command_kind [str], count [number], },
  product. BackMemoryInspection {
    interned,
    index [number],
    access [LalinBack.BackAccessId],
    alignment [LalinBack.BackAlignment],
    dereference [LalinBack.BackDereference],
    trap [LalinBack.BackTrap],
    motion [LalinBack.BackMotion],
    effect [LalinBack.BackAccessEffect],
  },
  product. BackAddressInspection { interned, index [number], address [LalinBack.BackAddress], },
  product. BackPointerOffsetInspection {
    interned,
    index [number],
    dst [LalinBack.BackValId],
    base [LalinBack.BackAddressBase],
    index_value [LalinBack.BackValId],
    elem_size [number],
    const_offset [number],
    provenance [LalinBack.BackPointerProvenance],
    bounds [LalinBack.BackPointerBounds],
  },
  product. BackIntSemanticsInspection {
    interned,
    index [number],
    dst [LalinBack.BackValId],
    op [LalinBack.BackIntOp],
    scalar [LalinBack.BackScalar],
    semantics [LalinBack.BackIntSemantics],
  },
  sum. BackFloatSemanticOp {
    BackFloatSemanticBinary { variant_unique, op [LalinBack.BackFloatOp], },
    BackFloatSemanticFma,
  },
  product. BackFloatSemanticsInspection {
    interned,
    index [number],
    dst [LalinBack.BackValId],
    op [LalinBack.BackFloatSemanticOp],
    scalar [LalinBack.BackScalar],
    semantics [LalinBack.BackFloatSemantics],
  },
  product. BackInspectionReport {
    interned,
    command_counts [many [LalinBack.BackCommandCount]],
    memory [many [LalinBack.BackMemoryInspection]],
    addresses [many [LalinBack.BackAddressInspection]],
    pointer_offsets [many [LalinBack.BackPointerOffsetInspection]],
    int_semantics [many [LalinBack.BackIntSemanticsInspection]],
    float_semantics [many [LalinBack.BackFloatSemanticsInspection]],
  },
  product. BackDisasmInspection { interned, func [LalinBack.BackFuncId], text [str], },
  product. BackDiagnosticsReport {
    interned,
    inspection [LalinBack.BackInspectionReport],
    disassembly [many [LalinBack.BackDisasmInspection]],
  },
  sum. BackFlow { BackFallsThrough, BackTerminates, },
  product. BackSigSpec {
    interned,
    params [many [LalinBack.BackScalar]],
    results [many [LalinBack.BackScalar]],
  },
  product. BackStackSlotSpec { interned, size [number], align [number], },
  sum. BackExprLowering {
    BackExprPlan {
      variant_unique,
      cmds [many [LalinBack.Cmd]],
      field. value [LalinBack.BackValId],
      field. ty [LalinBack.BackScalar],
    },
    BackExprTerminated { variant_unique, cmds [many [LalinBack.Cmd]], },
  },
  sum. BackAddrLowering {
    BackAddrWrites { variant_unique, cmds [many [LalinBack.Cmd]], },
    BackAddrTerminated { variant_unique, cmds [many [LalinBack.Cmd]], },
  },
  sum. BackViewLowering {
    BackViewPlan {
      variant_unique,
      cmds [many [LalinBack.Cmd]],
      data [LalinBack.BackValId],
      len [LalinBack.BackValId],
      stride [LalinBack.BackValId],
    },
    BackViewTerminated { variant_unique, cmds [many [LalinBack.Cmd]], },
  },
  sum. BackReturnTarget {
    BackReturnValue,
    BackReturnSret { variant_unique, addr [LalinBack.BackValId], },
  },
  product. BackStmtPlan {
    interned,
    cmds [many [LalinBack.Cmd]],
    flow [LalinBack.BackFlow],
  },
  product. BackFuncPlan { interned, cmds [many [LalinBack.Cmd]], },
  product. BackItemPlan { interned, cmds [many [LalinBack.Cmd]], },
  product. BackProgram { interned, cmds [many [LalinBack.Cmd]], },
  product. BackCommandTape { interned, version [number], command_count [number], payload [str], },
}
