local S = require("lalin.schema.dsl")
S.use()

return schema. LalinBind {
  sum. BindingRole {
    BindingRoleLocalValue,
    BindingRoleLocalCell,
    BindingRoleArg { variant_unique, index [number], },
    BindingRoleBlockParam { variant_unique, region_id [str], block_name [str], index [number], },
    BindingRoleEntryBlockParam {
      variant_unique,
      region_id [str],
      block_name [str],
      index [number],
    },
    BindingRoleContParam { variant_unique, region_id [str], cont_name [str], index [number], },
    BindingRoleGlobalFunc { variant_unique, module_name [str], item_name [str], },
    BindingRoleGlobalConst { variant_unique, module_name [str], item_name [str], },
    BindingRoleGlobalStatic { variant_unique, module_name [str], item_name [str], },
    BindingRoleExtern { variant_unique, symbol [str], },
  },
  product. Binding {
    interned,
    field. id [LalinCore.Id],
    field. name [str],
    field. ty [LalinType.Type],
    role [LalinBind.BindingRole],
  },
  sum. Residence { ResidenceUnknown, ResidenceValue, ResidenceStack, ResidenceCell, },
  sum. ResidenceReason {
    ResidenceBecauseDefault,
    ResidenceBecauseAddressTaken,
    ResidenceBecauseMutableCell,
    ResidenceBecauseNonScalarAbi,
    ResidenceBecauseMaterializedTemporary,
    ResidenceBecauseBackendRequired,
  },
  sum. ResidenceFact {
    ResidenceFactBinding { variant_unique, binding [LalinBind.Binding], },
    ResidenceFactAddressTaken { variant_unique, binding [LalinBind.Binding], },
    ResidenceFactMutableCell { variant_unique, binding [LalinBind.Binding], },
    ResidenceFactNonScalarAbi { variant_unique, binding [LalinBind.Binding], },
    ResidenceFactMaterializedTemporary { variant_unique, binding [LalinBind.Binding], },
    ResidenceFactBackendRequired { variant_unique, binding [LalinBind.Binding], },
  },
  product. ResidenceFactSet { interned, facts [many [LalinBind.ResidenceFact]], },
  product. ResidenceDecision {
    interned,
    binding [LalinBind.Binding],
    residence [LalinBind.Residence],
    reason [LalinBind.ResidenceReason],
  },
  product. ResidencePlan { interned, decisions [many [LalinBind.ResidenceDecision]], },
  product. MachineBinding {
    interned,
    binding [LalinBind.Binding],
    residence [LalinBind.Residence],
  },
  product. MachineBindingSet { interned, bindings [many [LalinBind.MachineBinding]], },
  sum. ValueRef {
    ValueRefName { variant_unique, field. name [str], },
    ValueRefPath { variant_unique, path [LalinCore.Path], },
    ValueRefBinding { variant_unique, binding [LalinBind.Binding], },
  },
  product. ValueEntry { interned, field. name [str], binding [LalinBind.Binding], },
  product. TypeEntry { interned, field. name [str], field. ty [LalinType.Type], },
  product. Env {
    interned,
    module_name [str],
    values [many [LalinBind.ValueEntry]],
    types [many [LalinBind.TypeEntry]],
    layouts [many [LalinSem.TypeLayout]],
  },
  product. ConstEntry {
    interned,
    module_name [str],
    item_name [str],
    field. ty [LalinType.Type],
    field. value [LalinTree.Expr],
  },
  product. ConstEnv { interned, entries [many [LalinBind.ConstEntry]], },
  sum. StmtEnvEffect {
    StmtEnvNoBinding,
    StmtEnvAddBinding { variant_unique, entry [LalinBind.ValueEntry], },
    StmtEnvAddBindings { variant_unique, entries [many [LalinBind.ValueEntry]], },
  },
}
