local S = require("lalin.schema.dsl")
S.use()

return schema. LalinC {
  product. CTypeId { interned, module_name [str], spelling [str], },
  sum. CTypeKind {
    CVoid,
    CScalar { variant_unique, scalar [LalinBack.BackScalar], },
    CPointer { variant_unique, pointee [LalinC.CTypeId], },
    CEnum { variant_unique, scalar [LalinBack.BackScalar], },
    CArray { variant_unique, elem [LalinC.CTypeId], count [number], },
    CStruct,
    CUnion,
    COpaque,
    CFuncPtr { variant_unique, sig [LalinC.CFuncSigId], },
  },
  product. CTypeFact {
    interned,
    field. id [LalinC.CTypeId],
    kind [LalinC.CTypeKind],
    complete [bool],
    size [optional [number]],
    align [optional [number]],
  },
  product. CFieldLayout {
    interned,
    owner [LalinC.CTypeId],
    field. name [str],
    field. type [LalinC.CTypeId],
    offset [number],
    size [number],
    align [number],
    bit_offset [optional [number]],
    bit_width [optional [number]],
  },
  product. CLayoutFact {
    interned,
    field. type [LalinC.CTypeId],
    size [number],
    align [number],
    fields [many [LalinC.CFieldLayout]],
  },
  product. CFuncSigId { interned, text [str], },
  product. CFuncSig {
    interned,
    field. id [LalinC.CFuncSigId],
    params [many [LalinC.CTypeId]],
    result [LalinC.CTypeId],
  },
  product. CExternFunc {
    interned,
    lalin_name [str],
    symbol [str],
    sig [LalinC.CFuncSigId],
    library [optional [str]],
  },
  product. CLibrary {
    interned,
    field. name [str],
    link_name [optional [str]],
    path [optional [str]],
    symbols [many [str]],
  },
  product. CBackendName { interned, text [str], },
  product. CBackendLabel { interned, text [str], },
  product. CBackendLocalId { interned, text [str], },
  product. CBackendGlobalId { interned, text [str], },
  product. CBackendHelperId { interned, text [str], },
  product. CBackendFuncSigId { interned, text [str], },
  sum. CBackendDialect { CBackendC99, CBackendC11, CBackendGnuC, CBackendClangC, },
  sum. CBackendPlatform {
    CBackendHostedNative,
    CBackendFreestanding,
    CBackendWasmCapable,
    CBackendEmbedded,
  },
  sum. CBackendEndian { CBackendLittleEndian, CBackendBigEndian, },
  product. CBackendTarget {
    interned,
    dialect [LalinC.CBackendDialect],
    platform [LalinC.CBackendPlatform],
    pointer_bits [number],
    index_bits [number],
    endian [LalinC.CBackendEndian],
    hosted [bool],
  },
  sum. CBackendType {
    CBackendVoid,
    CBackendBool8,
    CBackendScalar { variant_unique, scalar [LalinCore.Scalar], },
    CBackendIndex,
    CBackendDataPtr { variant_unique, pointee [optional [LalinC.CBackendType]], },
    CBackendCodePtr { variant_unique, sig [LalinC.CBackendFuncSigId], },
    CBackendNamed { variant_unique, field. id [LalinC.CTypeId], },
    CBackendArray { variant_unique, elem [LalinC.CBackendType], count [number], },
    CBackendSliceDescriptor { variant_unique, elem [LalinC.CBackendType], },
    CBackendByteSpanDescriptor,
    CBackendViewDescriptor { variant_unique, elem [LalinC.CBackendType], },
    CBackendClosureDescriptor {
      variant_unique,
      sig [LalinC.CBackendFuncSigId],
      ctx [optional [LalinC.CBackendType]],
    },
    CBackendAbiHiddenOutPtr { variant_unique, result [LalinC.CBackendType], },
    CBackendImportedCodePtr { variant_unique, sig [LalinC.CFuncSigId], },
    CBackendVector { variant_unique, elem [LalinC.CBackendType], lanes [number], },
  },
  product. CBackendParam {
    interned,
    field. name [LalinC.CBackendName],
    field. ty [LalinC.CBackendType],
  },
  sum. CBackendFuncLinkage {
    CBackendLinkInternal,
    CBackendLinkExport,
    CBackendLinkExtern,
    CBackendLinkDecl,
    CBackendLinkWrapper,
    CBackendLinkIndirect,
  },
  sum. CBackendAbiParamRole {
    CBackendAbiParamDirect,
    CBackendAbiParamByAddress,
    CBackendAbiParamDescriptor,
    CBackendAbiParamHiddenOut,
  },
  sum. CBackendAbiResultRole {
    CBackendAbiResultVoid,
    CBackendAbiResultDirect,
    CBackendAbiResultByAddress,
    CBackendAbiResultHiddenOut,
    CBackendAbiResultDescriptor,
  },
  product. CBackendAbiParam {
    interned,
    field. name [LalinC.CBackendName],
    source_ty [LalinC.CBackendType],
    lowered_ty [LalinC.CBackendType],
    role [LalinC.CBackendAbiParamRole],
  },
  product. CBackendAbiResult {
    interned,
    source_ty [LalinC.CBackendType],
    lowered_ty [LalinC.CBackendType],
    role [LalinC.CBackendAbiResultRole],
  },
  product. CBackendFuncAbi {
    interned,
    field. id [LalinC.CBackendFuncSigId],
    linkage [LalinC.CBackendFuncLinkage],
    params [many [LalinC.CBackendAbiParam]],
    result [LalinC.CBackendAbiResult],
    imported_sig [optional [LalinC.CFuncSigId]],
  },
  product. CBackendFuncSig {
    interned,
    field. id [LalinC.CBackendFuncSigId],
    params [many [LalinC.CBackendType]],
    result [LalinC.CBackendType],
  },
  product. CBackendField {
    interned,
    field. name [LalinC.CBackendName],
    field. ty [LalinC.CBackendType],
    offset [optional [number]],
    size [optional [number]],
    align [optional [number]],
  },
  sum. CBackendTypeDecl {
    CBackendTypedef {
      variant_unique,
      field. id [LalinC.CTypeId],
      field. ty [LalinC.CBackendType],
    },
    CBackendStructDecl {
      variant_unique,
      field. id [LalinC.CTypeId],
      fields [many [LalinC.CBackendField]],
      size [optional [number]],
      align [optional [number]],
    },
    CBackendUnionDecl {
      variant_unique,
      field. id [LalinC.CTypeId],
      fields [many [LalinC.CBackendField]],
      size [optional [number]],
      align [optional [number]],
    },
    CBackendOpaqueDecl { variant_unique, field. id [LalinC.CTypeId], },
  },
  sum. CBackendResidence {
    CBackendResidenceValue,
    CBackendResidenceAddressed,
    CBackendResidenceAggregate,
    CBackendResidenceDescriptor,
  },
  sum. CBackendLocalInitState {
    CBackendLocalUninitialized,
    CBackendLocalZeroInitialized,
    CBackendLocalInitialized,
  },
  sum. CBackendPlace {
    CBackendPlaceLocal {
      variant_unique,
      field. local_id [LalinC.CBackendLocalId],
      field. ty [LalinC.CBackendType],
    },
    CBackendPlaceGlobal {
      variant_unique,
      global [LalinC.CBackendGlobalId],
      field. ty [LalinC.CBackendType],
    },
    CBackendPlaceDeref {
      variant_unique,
      addr [LalinC.CBackendAtom],
      field. ty [LalinC.CBackendType],
      align [optional [number]],
    },
    CBackendPlaceField {
      variant_unique,
      base [LalinC.CBackendPlace],
      field. field [LalinC.CBackendName],
      field. ty [LalinC.CBackendType],
      offset [number],
      size [optional [number]],
      align [optional [number]],
    },
    CBackendPlaceIndex {
      variant_unique,
      base [LalinC.CBackendPlace],
      index [LalinC.CBackendAtom],
      field. ty [LalinC.CBackendType],
      elem_size [number],
    },
    CBackendPlaceBytes {
      variant_unique,
      base [LalinC.CBackendAtom],
      offset [number],
      field. ty [LalinC.CBackendType],
      size [number],
      align [number],
    },
  },
  product. CBackendLocalStorage {
    interned,
    field. id [LalinC.CBackendLocalId],
    field. name [LalinC.CBackendName],
    field. ty [LalinC.CBackendType],
    residence [LalinC.CBackendResidence],
    init_state [LalinC.CBackendLocalInitState],
    address_taken [bool],
  },
  sum. CBackendRelocTarget {
    CBackendRelocGlobal { variant_unique, global [LalinC.CBackendGlobalId], },
    CBackendRelocFunc { variant_unique, func [LalinC.CBackendName], },
    CBackendRelocExtern { variant_unique, extern [LalinC.CBackendName], },
  },
  sum. CBackendDataInit {
    CBackendDataZero { variant_unique, offset [number], size [number], },
    CBackendDataBytes { variant_unique, offset [number], bytes [str], },
    CBackendDataScalar {
      variant_unique,
      offset [number],
      field. ty [LalinC.CBackendType],
      literal [LalinCore.Literal],
    },
    CBackendDataReloc {
      variant_unique,
      offset [number],
      target [LalinC.CBackendRelocTarget],
      addend [number],
    },
  },
  product. CBackendGlobal {
    interned,
    field. id [LalinC.CBackendGlobalId],
    field. name [LalinC.CBackendName],
    visibility [LalinCore.Visibility],
    field. ty [LalinC.CBackendType],
    size [number],
    align [number],
    inits [many [LalinC.CBackendDataInit]],
  },
  product. CBackendExtern {
    interned,
    field. name [LalinC.CBackendName],
    symbol [str],
    sig [LalinC.CBackendFuncSigId],
    header [optional [str]],
  },
  sum. CBackendAtom {
    CBackendAtomLocal { variant_unique, field. local_id [LalinC.CBackendLocalId], },
    CBackendAtomGlobal { variant_unique, global [LalinC.CBackendGlobalId], },
    CBackendAtomLiteral {
      variant_unique,
      field. ty [LalinC.CBackendType],
      literal [LalinCore.Literal],
    },
    CBackendAtomNull { variant_unique, field. ty [LalinC.CBackendType], },
  },
  sum. CBackendRValue {
    CBackendRAtom { variant_unique, atom [LalinC.CBackendAtom], },
    CBackendRCompare {
      variant_unique,
      op [LalinCore.CmpOp],
      field. ty [LalinC.CBackendType],
      lhs [LalinC.CBackendAtom],
      rhs [LalinC.CBackendAtom],
    },
    CBackendRCast {
      variant_unique,
      op [LalinCore.MachineCastOp],
      to [LalinC.CBackendType],
      field. value [LalinC.CBackendAtom],
    },
    CBackendRSelect {
      variant_unique,
      field. ty [LalinC.CBackendType],
      cond [LalinC.CBackendAtom],
      then_value [LalinC.CBackendAtom],
      else_value [LalinC.CBackendAtom],
    },
    CBackendRFuncAddr {
      variant_unique,
      func [LalinC.CBackendName],
      sig [LalinC.CBackendFuncSigId],
    },
    CBackendRExternAddr {
      variant_unique,
      extern [LalinC.CBackendName],
      sig [LalinC.CBackendFuncSigId],
    },
    CBackendRPtrOffset {
      variant_unique,
      base [LalinC.CBackendAtom],
      index [LalinC.CBackendAtom],
      elem_size [number],
      const_offset [number],
    },
    CBackendRAddrOfPlace { variant_unique, place [LalinC.CBackendPlace], },
  },
  sum. CBackendTrapMode { CBackendMayTrap, CBackendMustNotTrap, CBackendCheckedTrap, },
  product. CBackendMemoryAccess {
    interned,
    field. ty [LalinC.CBackendType],
    align [number],
    trap [LalinC.CBackendTrapMode],
    volatile [bool],
    ordering [optional [LalinCore.AtomicOrdering]],
  },
  sum. CBackendIntOverflow {
    CBackendIntWrap,
    CBackendIntTrapOnOverflow,
    CBackendIntAssumeNoOverflow,
  },
  sum. CBackendDivMode { CBackendDivTrapOnZero, CBackendDivTrapOnZeroOrOverflow, },
  sum. CBackendShiftMode { CBackendShiftMaskCount, CBackendShiftTrapOutOfRange, },
  sum. CBackendTargetFeature {
    CBackendFeatureC11Atomics,
    CBackendFeatureLibm,
    CBackendFeatureBuiltinOverflow,
    CBackendFeatureBuiltinBitops,
    CBackendFeatureUnalignedAccess,
    CBackendFeatureStaticAssert,
    CBackendFeatureHostedRuntime,
  },
  product. CBackendLayoutAssertion {
    interned,
    field. id [LalinC.CTypeId],
    size [number],
    align [number],
  },
  sum. CBackendHelperKind {
    CBackendHelperUnary {
      variant_unique,
      op [LalinCore.UnaryOp],
      field. ty [LalinC.CBackendType],
    },
    CBackendHelperBoolNormalize { variant_unique, field. ty [LalinC.CBackendType], },
    CBackendHelperCast {
      variant_unique,
      op [LalinCore.MachineCastOp],
      from [LalinC.CBackendType],
      to [LalinC.CBackendType],
    },
    CBackendHelperPtrOffset {
      variant_unique,
      pointee [LalinC.CBackendType],
      elem_size [number],
      checked [bool],
    },
    CBackendHelperIntBinary {
      variant_unique,
      op [LalinCore.BinaryOp],
      field. ty [LalinC.CBackendType],
      overflow [LalinC.CBackendIntOverflow],
    },
    CBackendHelperDivRem {
      variant_unique,
      op [LalinCore.BinaryOp],
      field. ty [LalinC.CBackendType],
      mode [LalinC.CBackendDivMode],
    },
    CBackendHelperShift {
      variant_unique,
      op [LalinCore.BinaryOp],
      field. ty [LalinC.CBackendType],
      mode [LalinC.CBackendShiftMode],
    },
    CBackendHelperIntrinsic {
      variant_unique,
      intrinsic [LalinCore.Intrinsic],
      field. ty [LalinC.CBackendType],
    },
    CBackendHelperLoad { variant_unique, access [LalinC.CBackendMemoryAccess], },
    CBackendHelperStore { variant_unique, access [LalinC.CBackendMemoryAccess], },
    CBackendHelperAtomicLoad { variant_unique, access [LalinC.CBackendMemoryAccess], },
    CBackendHelperAtomicStore { variant_unique, access [LalinC.CBackendMemoryAccess], },
    CBackendHelperAtomicRmw {
      variant_unique,
      op [LalinCore.AtomicRmwOp],
      access [LalinC.CBackendMemoryAccess],
    },
    CBackendHelperAtomicCas {
      variant_unique,
      access [LalinC.CBackendMemoryAccess],
      success_ordering [LalinCore.AtomicOrdering],
      failure_ordering [LalinCore.AtomicOrdering],
    },
    CBackendHelperAtomicFence { variant_unique, ordering [LalinCore.AtomicOrdering], },
    CBackendHelperMemcpy,
    CBackendHelperTypedMemcpy {
      variant_unique,
      field. ty [LalinC.CBackendType],
      size [number],
      align [number],
    },
    CBackendHelperMemset,
    CBackendHelperTypedMemset {
      variant_unique,
      field. ty [LalinC.CBackendType],
      size [number],
      align [number],
    },
    CBackendHelperMemcmp,
    CBackendHelperLayoutAssert { variant_unique, assertion [LalinC.CBackendLayoutAssertion], },
    CBackendHelperRequireFeature {
      variant_unique,
      feature [LalinC.CBackendTargetFeature],
      reason [str],
    },
    CBackendHelperTrap,
  },
  product. CBackendHelperUse {
    interned,
    field. id [LalinC.CBackendHelperId],
    kind [LalinC.CBackendHelperKind],
  },
  product. CBackendLocal {
    interned,
    field. id [LalinC.CBackendLocalId],
    field. name [LalinC.CBackendName],
    field. ty [LalinC.CBackendType],
  },
  product. CBackendAggregateFieldInit {
    interned,
    field. field [LalinC.CBackendName],
    field. value [LalinC.CBackendAtom],
    offset [optional [number]],
  },
  product. CBackendArrayElemInit {
    interned,
    index [number],
    field. value [LalinC.CBackendAtom],
  },
  sum. CBackendCallTarget {
    CBackendCallDirect { variant_unique, func [LalinC.CBackendName], },
    CBackendCallExtern { variant_unique, extern [LalinC.CBackendName], },
    CBackendCallIndirect {
      variant_unique,
      callee [LalinC.CBackendAtom],
      sig [LalinC.CBackendFuncSigId],
    },
    CBackendCallClosure {
      variant_unique,
      closure [LalinC.CBackendAtom],
      sig [LalinC.CBackendFuncSigId],
    },
  },
  sum. CBackendStmt {
    CBackendAssign {
      variant_unique,
      dst [LalinC.CBackendLocalId],
      rhs [LalinC.CBackendRValue],
    },
    CBackendHelperCall {
      variant_unique,
      dst [optional [LalinC.CBackendLocalId]],
      helper [LalinC.CBackendHelperId],
      args [many [LalinC.CBackendAtom]],
    },
    CBackendLoad {
      variant_unique,
      dst [LalinC.CBackendLocalId],
      addr [LalinC.CBackendAtom],
      access [LalinC.CBackendMemoryAccess],
    },
    CBackendStore {
      variant_unique,
      addr [LalinC.CBackendAtom],
      field. value [LalinC.CBackendAtom],
      access [LalinC.CBackendMemoryAccess],
    },
    CBackendPlaceLoad {
      variant_unique,
      dst [LalinC.CBackendLocalId],
      place [LalinC.CBackendPlace],
    },
    CBackendPlaceStore {
      variant_unique,
      place [LalinC.CBackendPlace],
      field. value [LalinC.CBackendAtom],
    },
    CBackendZeroInit {
      variant_unique,
      place [LalinC.CBackendPlace],
      field. ty [LalinC.CBackendType],
      size [number],
    },
    CBackendAggregateInit {
      variant_unique,
      place [LalinC.CBackendPlace],
      field. ty [LalinC.CBackendType],
      fields [many [LalinC.CBackendAggregateFieldInit]],
    },
    CBackendArrayInit {
      variant_unique,
      place [LalinC.CBackendPlace],
      field. ty [LalinC.CBackendType],
      elems [many [LalinC.CBackendArrayElemInit]],
    },
    CBackendCall {
      variant_unique,
      dst [optional [LalinC.CBackendLocalId]],
      target [LalinC.CBackendCallTarget],
      args [many [LalinC.CBackendAtom]],
    },
    CBackendComment { variant_unique, text [str], },
  },
  product. CBackendSwitchCase {
    interned,
    literal [LalinCore.Literal],
    dest [LalinC.CBackendLabel],
    args [many [LalinC.CBackendAtom]],
  },
  sum. CBackendTerminator {
    CBackendGoto {
      variant_unique,
      dest [LalinC.CBackendLabel],
      args [many [LalinC.CBackendAtom]],
    },
    CBackendIfGoto {
      variant_unique,
      cond [LalinC.CBackendAtom],
      then_dest [LalinC.CBackendLabel],
      then_args [many [LalinC.CBackendAtom]],
      else_dest [LalinC.CBackendLabel],
      else_args [many [LalinC.CBackendAtom]],
    },
    CBackendSwitchGoto {
      variant_unique,
      field. value [LalinC.CBackendAtom],
      cases [many [LalinC.CBackendSwitchCase]],
      default_dest [LalinC.CBackendLabel],
      default_args [many [LalinC.CBackendAtom]],
    },
    CBackendReturnVoid,
    CBackendReturn { variant_unique, field. value [LalinC.CBackendAtom], },
    CBackendTrap,
  },
  product. CBackendBlockParam {
    interned,
    field. local_id [LalinC.CBackendLocalId],
    field. ty [LalinC.CBackendType],
  },
  product. CBackendBlock {
    interned,
    label [LalinC.CBackendLabel],
    params [many [LalinC.CBackendBlockParam]],
    stmts [many [LalinC.CBackendStmt]],
    term [LalinC.CBackendTerminator],
  },
  product. CBackendExecArg {
    interned,
    field. name [str],
    field. atom [LalinC.CBackendAtom],
    field. ty [LalinC.CBackendType],
  },
  sum. CBackendExecResult {
    CBackendExecResultVoid,
    CBackendExecResultLocal {
      variant_unique,
      dst [LalinC.CBackendLocalId],
      field. ty [LalinC.CBackendType],
    },
  },
  sum. CBackendExecEmission {
    CBackendExecEmitInline,
    CBackendExecEmitFunction,
    CBackendExecEmitExternCall,
  },
  product. CBackendExecSite {
    interned,
    fragment [LalinExec.ExecFragment],
    emission [LalinC.CBackendExecEmission],
    args [many [LalinC.CBackendExecArg]],
    result [LalinC.CBackendExecResult],
  },
  sum. CBackendFuncBody {
    CBackendBodyBlocks {
      variant_unique,
      entry [LalinC.CBackendLabel],
      blocks [many [LalinC.CBackendBlock]],
    },
    CBackendBodyExec {
      variant_unique,
      fragment [LalinC.CBackendExecSite],
    },
    CBackendBodyMixed {
      variant_unique,
      entry [LalinC.CBackendLabel],
      blocks [many [LalinC.CBackendBlock]],
      fragments [many [LalinC.CBackendExecSite]],
    },
  },
  product. CBackendFunc {
    interned,
    field. name [LalinC.CBackendName],
    symbol [str],
    visibility [LalinCore.Visibility],
    sig [LalinC.CBackendFuncSigId],
    params [many [LalinC.CBackendLocal]],
    locals [many [LalinC.CBackendLocal]],
    body [LalinC.CBackendFuncBody],
  },
  product. CBackendUnit {
    interned,
    module_name [str],
    target [LalinC.CBackendTarget],
    sigs [many [LalinC.CBackendFuncSig]],
    types [many [LalinC.CBackendTypeDecl]],
    globals [many [LalinC.CBackendGlobal]],
    externs [many [LalinC.CBackendExtern]],
    helpers [many [LalinC.CBackendHelperUse]],
    funcs [many [LalinC.CBackendFunc]],
  },
  sum. CBackendValidationIssue {
    CBackendIssueDuplicateSig { variant_unique, sig [LalinC.CBackendFuncSigId], },
    CBackendIssueMissingSig { variant_unique, sig [LalinC.CBackendFuncSigId], },
    CBackendIssueDuplicateFunc { variant_unique, func [LalinC.CBackendName], },
    CBackendIssueMissingFunc { variant_unique, func [LalinC.CBackendName], },
    CBackendIssueDuplicateExtern { variant_unique, extern [LalinC.CBackendName], },
    CBackendIssueMissingExtern { variant_unique, extern [LalinC.CBackendName], },
    CBackendIssueDuplicateGlobal { variant_unique, global [LalinC.CBackendGlobalId], },
    CBackendIssueMissingGlobal { variant_unique, global [LalinC.CBackendGlobalId], },
    CBackendIssueDuplicateHelper { variant_unique, helper [LalinC.CBackendHelperId], },
    CBackendIssueMissingHelper { variant_unique, helper [LalinC.CBackendHelperId], },
    CBackendIssueDuplicateLocal {
      variant_unique,
      func [LalinC.CBackendName],
      field. local_id [LalinC.CBackendLocalId],
    },
    CBackendIssueMissingLocal {
      variant_unique,
      func [LalinC.CBackendName],
      field. local_id [LalinC.CBackendLocalId],
    },
    CBackendIssueDuplicateLabel {
      variant_unique,
      func [LalinC.CBackendName],
      label [LalinC.CBackendLabel],
    },
    CBackendIssueMissingLabel {
      variant_unique,
      func [LalinC.CBackendName],
      label [LalinC.CBackendLabel],
    },
    CBackendIssueInvalidCName {
      variant_unique,
      site [str],
      field. name [LalinC.CBackendName],
    },
    CBackendIssueDuplicateCName {
      variant_unique,
      site [str],
      field. name [LalinC.CBackendName],
    },
    CBackendIssueFuncSigMismatch {
      variant_unique,
      func [LalinC.CBackendName],
      expected [LalinC.CBackendType],
      actual [LalinC.CBackendType],
    },
    CBackendIssueBlockArgCount {
      variant_unique,
      func [LalinC.CBackendName],
      label [LalinC.CBackendLabel],
      expected [number],
      actual [number],
    },
    CBackendIssueBlockArgType {
      variant_unique,
      func [LalinC.CBackendName],
      label [LalinC.CBackendLabel],
      index [number],
      expected [LalinC.CBackendType],
      actual [LalinC.CBackendType],
    },
    CBackendIssueCallArgCount {
      variant_unique,
      site [str],
      sig [LalinC.CBackendFuncSigId],
      expected [number],
      actual [number],
    },
    CBackendIssueCallArgType {
      variant_unique,
      site [str],
      sig [LalinC.CBackendFuncSigId],
      index [number],
      expected [LalinC.CBackendType],
      actual [LalinC.CBackendType],
    },
    CBackendIssueCallResultType {
      variant_unique,
      site [str],
      sig [LalinC.CBackendFuncSigId],
      expected [LalinC.CBackendType],
      actual [LalinC.CBackendType],
    },
    CBackendIssueIndirectCallNonCodePtr {
      variant_unique,
      site [str],
      actual [LalinC.CBackendType],
    },
    CBackendIssueDataCodePtrConfusion {
      variant_unique,
      site [str],
      field. ty [LalinC.CBackendType],
    },
    CBackendIssueHelperMismatch {
      variant_unique,
      helper [LalinC.CBackendHelperId],
      message [str],
    },
    CBackendIssueInvalidAlignment { variant_unique, site [str], align [number], },
    CBackendIssueDataInitOutOfBounds {
      variant_unique,
      global [LalinC.CBackendGlobalId],
      offset [number],
      size [number],
      global_size [number],
    },
    CBackendIssueCoverageMissing { variant_unique, field. sum [str], variant [str], },
    CBackendIssueInvalidTargetFeature {
      variant_unique,
      feature [LalinC.CBackendTargetFeature],
      reason [str],
    },
    CBackendIssueLayoutAssertionMissing { variant_unique, field. id [LalinC.CTypeId], },
    CBackendIssueLayoutAssertionMismatch {
      variant_unique,
      field. id [LalinC.CTypeId],
      expected_size [number],
      actual_size [number],
      expected_align [number],
      actual_align [number],
    },
    CBackendIssuePlaceTypeMismatch {
      variant_unique,
      site [str],
      place [LalinC.CBackendPlace],
      expected [LalinC.CBackendType],
      actual [LalinC.CBackendType],
    },
    CBackendIssueLoadStoreTypeMismatch {
      variant_unique,
      site [str],
      expected [LalinC.CBackendType],
      actual [LalinC.CBackendType],
    },
    CBackendIssueUnmaterializedAddressTakenValue {
      variant_unique,
      func [LalinC.CBackendName],
      field. local_id [LalinC.CBackendLocalId],
    },
    CBackendIssueUninitializedLocal {
      variant_unique,
      func [LalinC.CBackendName],
      field. local_id [LalinC.CBackendLocalId],
    },
    CBackendIssueHelperSignatureMismatch {
      variant_unique,
      helper [LalinC.CBackendHelperId],
      expected [many [LalinC.CBackendType]],
      actual [many [LalinC.CBackendType]],
    },
    CBackendIssueDataInitPrecisionFailure {
      variant_unique,
      global [LalinC.CBackendGlobalId],
      offset [number],
      field. ty [LalinC.CBackendType],
      literal [LalinCore.Literal],
      reason [str],
    },
    CBackendIssueDataRelocFailure {
      variant_unique,
      global [LalinC.CBackendGlobalId],
      offset [number],
      target [LalinC.CBackendRelocTarget],
      reason [str],
    },
    CBackendIssueAbiMismatch {
      variant_unique,
      site [str],
      sig [LalinC.CBackendFuncSigId],
      reason [str],
    },
    CBackendIssueUnsupportedConstruct {
      variant_unique,
      field. sum [str],
      variant [str],
      reason [str],
    },
    CBackendIssueUnreachableConstruct {
      variant_unique,
      field. sum [str],
      variant [str],
      reason [str],
    },
  },
  product. CBackendStorageRecord {
    interned,
    func [LalinC.CBackendName],
    storage [many [LalinC.CBackendLocalStorage]],
  },
  product. CBackendValidationInput {
    interned,
    unit [LalinC.CBackendUnit],
    storage [many [LalinC.CBackendStorageRecord]],
    abi_issues [many [LalinC.CBackendValidationIssue]],
  },
  product. CBackendValidationReport {
    interned,
    issues [many [LalinC.CBackendValidationIssue]],
  },
}
