local S = require("lalin.schema.dsl")
S.use()

return schema. LalinCAst {
  sum. CKeyword {
    CKwAuto,
    CKwBreak,
    CKwCase,
    CKwChar,
    CKwConst,
    CKwContinue,
    CKwDefault,
    CKwDo,
    CKwDouble,
    CKwElse,
    CKwEnum,
    CKwExtern,
    CKwFloat,
    CKwFor,
    CKwGoto,
    CKwIf,
    CKwInline,
    CKwInt,
    CKwLong,
    CKwRegister,
    CKwRestrict,
    CKwReturn,
    CKwShort,
    CKwSigned,
    CKwSizeof,
    CKwStatic,
    CKwStruct,
    CKwSwitch,
    CKwTypedef,
    CKwUnion,
    CKwUnsigned,
    CKwVoid,
    CKwVolatile,
    CKwWhile,
    CKwBool,
    CKwComplex,
    CKwInline2,
    CKwRestrict2,
  },
  sum. CDirectiveToken {
    CDirDefine,
    CDirUndef,
    CDirInclude,
    CDirIf,
    CDirIfdef,
    CDirIfndef,
    CDirElif,
    CDirElse,
    CDirEndif,
    CDirError,
    CDirPragma,
    CDirLine,
  },
  sum. CToken {
    CTokIdent { variant_unique, field. name [str], },
    CTokKeyword { variant_unique, kw [LalinCAst.CKeyword], },
    CTokIntLiteral { variant_unique, raw [str], suffix [str], },
    CTokFloatLiteral { variant_unique, raw [str], suffix [str], },
    CTokCharLiteral { variant_unique, raw [str], },
    CTokStringLiteral { variant_unique, raw [str], prefix [str], },
    CTokPunct { variant_unique, text [str], },
    CTokDirective { variant_unique, directive [LalinCAst.CDirectiveToken], },
    CTokNewline,
    CTokEOF,
  },
  sum. CppDirective {
    CCppDefine { variant_unique, macro [LalinCAst.CMacro], },
    CCppUndef { variant_unique, field. name [str], },
    CCppInclude { variant_unique, delimiter [LalinCAst.CIncludeDelimiter], path [str], },
    CCppIf { variant_unique, tokens [many [LalinCAst.CToken]], },
    CCppIfdef { variant_unique, field. name [str], },
    CCppIfndef { variant_unique, field. name [str], },
    CCppElif { variant_unique, tokens [many [LalinCAst.CToken]], },
    CCppElse,
    CCppEndif,
    CCppError { variant_unique, message [str], },
    CCppPragma { variant_unique, tokens [many [LalinCAst.CToken]], },
    CCppLine { variant_unique, line [number], file [optional [str]], },
  },
  sum. CIncludeDelimiter { CIncludeAngle, CIncludeQuoted, },
  sum. CMacroForm {
    CObjectLike,
    CFunctionLike { variant_unique, params [many [str]], variadic [bool], },
  },
  product. CMacro {
    interned,
    field. name [str],
    form [LalinCAst.CMacroForm],
    body [many [LalinCAst.CToken]],
    location [LalinSource.SourceRange],
  },
  product. TranslationUnit { interned, items [many [LalinCAst.TopLevelItem]], },
  sum. TopLevelItem {
    CATopDecl { variant_unique, decl [LalinCAst.Decl], },
    CATopFuncDef { variant_unique, func [LalinCAst.FuncDef], },
    CATopCpp { variant_unique, directive [LalinCAst.CppDirective], },
  },
  sum. StorageClass {
    CStorageTypedef,
    CStorageExtern,
    CStorageStatic,
    CStorageAuto,
    CStorageRegister,
  },
  sum. Qualifier { CQualConst, CQualRestrict, CQualVolatile, CQualInline, },
  sum. TypeSpec {
    CTyVoid,
    CTyChar,
    CTyShort,
    CTyInt,
    CTyLong,
    CTyLongLong,
    CTyFloat,
    CTyDouble,
    CTyLongDouble,
    CTySigned,
    CTyUnsigned,
    CTyBool,
    CTyComplex,
    CTyStructOrUnion {
      variant_unique,
      form [LalinCAst.StructForm],
      field. name [optional [str]],
      members [optional [many [LalinCAst.FieldDecl]]],
    },
    CTyEnum {
      variant_unique,
      field. name [optional [str]],
      enumerators [optional [many [LalinCAst.Enumerator]]],
    },
    CTyNamed { variant_unique, field. name [str], },
    CTyTypeof { variant_unique, field. expr [LalinCAst.Expr], },
  },
  sum. StructForm { CStructKindStruct, CStructKindUnion, },
  product. Decl {
    interned,
    storage [optional [LalinCAst.StorageClass]],
    qualifiers [many [LalinCAst.Qualifier]],
    type_spec [LalinCAst.TypeSpec],
    declarators [many [LalinCAst.Declarator]],
  },
  product. Declarator {
    interned,
    field. name [optional [str]],
    derived [many [LalinCAst.DerivedType]],
    initializer [optional [LalinCAst.Initializer]],
  },
  sum. DerivedType {
    CDerivedPointer { variant_unique, qualifiers [many [LalinCAst.Qualifier]], },
    CDerivedArray { variant_unique, size [optional [LalinCAst.Expr]], },
    CDerivedFunction { variant_unique, params [many [LalinCAst.ParamDecl]], variadic [bool], },
  },
  product. FieldDecl {
    interned,
    type_spec [LalinCAst.TypeSpec],
    declarators [many [LalinCAst.FieldDeclarator]],
  },
  product. FieldDeclarator {
    interned,
    declarator [optional [LalinCAst.Declarator]],
    bit_width [optional [LalinCAst.Expr]],
  },
  product. Enumerator {
    interned,
    field. name [str],
    field. value [optional [LalinCAst.Expr]],
  },
  product. ParamDecl {
    interned,
    type_spec [LalinCAst.TypeSpec],
    qualifiers [many [LalinCAst.Qualifier]],
    declarator [optional [LalinCAst.Declarator]],
  },
  product. FuncDef {
    interned,
    storage [optional [LalinCAst.StorageClass]],
    qualifiers [many [LalinCAst.Qualifier]],
    type_spec [LalinCAst.TypeSpec],
    declarator [LalinCAst.Declarator],
    body [LalinCAst.Stmt],
  },
  product. TypeName {
    interned,
    type_spec [LalinCAst.TypeSpec],
    derived [many [LalinCAst.DerivedType]],
  },
  sum. Expr {
    CEIntLit { variant_unique, raw [str], suffix [str], },
    CEFloatLit { variant_unique, raw [str], suffix [str], },
    CECharLit { variant_unique, raw [str], },
    CEStrLit { variant_unique, raw [str], },
    CEBoolLit { variant_unique, field. value [bool], },
    CEIdent { variant_unique, field. name [str], },
    CEParen { variant_unique, field. expr [LalinCAst.Expr], },
    CEPreInc { variant_unique, operand [LalinCAst.Expr], },
    CEPreDec { variant_unique, operand [LalinCAst.Expr], },
    CEPostInc { variant_unique, operand [LalinCAst.Expr], },
    CEPostDec { variant_unique, operand [LalinCAst.Expr], },
    CEAddrOf { variant_unique, operand [LalinCAst.Expr], },
    CEDeref { variant_unique, operand [LalinCAst.Expr], },
    CEPlus { variant_unique, operand [LalinCAst.Expr], },
    CEMinus { variant_unique, operand [LalinCAst.Expr], },
    CEBitNot { variant_unique, operand [LalinCAst.Expr], },
    CENot { variant_unique, operand [LalinCAst.Expr], },
    CESizeofExpr { variant_unique, field. expr [LalinCAst.Expr], },
    CESizeofType { variant_unique, type_name [LalinCAst.TypeName], },
    CECast {
      variant_unique,
      type_name [LalinCAst.TypeName],
      field. expr [LalinCAst.Expr],
    },
    CEBinary {
      variant_unique,
      op [LalinCAst.BinaryOp],
      left [LalinCAst.Expr],
      right [LalinCAst.Expr],
    },
    CETernary {
      variant_unique,
      cond [LalinCAst.Expr],
      then_expr [LalinCAst.Expr],
      else_expr [LalinCAst.Expr],
    },
    CEAssign {
      variant_unique,
      op [LalinCAst.AssignOp],
      left [LalinCAst.Expr],
      right [LalinCAst.Expr],
    },
    CEDot { variant_unique, base [LalinCAst.Expr], field. field [str], },
    CEArrow { variant_unique, base [LalinCAst.Expr], field. field [str], },
    CESubscript { variant_unique, base [LalinCAst.Expr], index [LalinCAst.Expr], },
    CECall { variant_unique, callee [LalinCAst.Expr], args [many [LalinCAst.Expr]], },
    CECompoundLit {
      variant_unique,
      type_name [LalinCAst.TypeName],
      initializer [LalinCAst.Initializer],
    },
    CEStmtExpr {
      variant_unique,
      items [many [LalinCAst.BlockItem]],
      result [LalinCAst.Expr],
    },
    CEComma { variant_unique, left [LalinCAst.Expr], right [LalinCAst.Expr], },
  },
  sum. BinaryOp {
    CBinAdd,
    CBinSub,
    CBinMul,
    CBinDiv,
    CBinMod,
    CBinShl,
    CBinShr,
    CBinLt,
    CBinLe,
    CBinGt,
    CBinGe,
    CBinEq,
    CBinNe,
    CBinBitAnd,
    CBinBitXor,
    CBinBitOr,
    CBinLogAnd,
    CBinLogOr,
  },
  sum. AssignOp {
    CAssign,
    CAddAssign,
    CSubAssign,
    CMulAssign,
    CDivAssign,
    CModAssign,
    CShlAssign,
    CShrAssign,
    CAndAssign,
    CXorAssign,
    COrAssign,
  },
  sum. Stmt {
    CSLabeled { variant_unique, label [str], stmt [LalinCAst.Stmt], },
    CSCase { variant_unique, field. value [LalinCAst.Expr], stmt [LalinCAst.Stmt], },
    CSDefault { variant_unique, stmt [LalinCAst.Stmt], },
    CSExpr { variant_unique, field. expr [optional [LalinCAst.Expr]], },
    CSCompound { variant_unique, items [many [LalinCAst.BlockItem]], },
    CSIf {
      variant_unique,
      cond [LalinCAst.Expr],
      then_stmt [LalinCAst.Stmt],
      else_stmt [optional [LalinCAst.Stmt]],
    },
    CSSwitch { variant_unique, cond [LalinCAst.Expr], body [LalinCAst.Stmt], },
    CSWhile { variant_unique, cond [LalinCAst.Expr], body [LalinCAst.Stmt], },
    CSDoWhile { variant_unique, body [LalinCAst.Stmt], cond [LalinCAst.Expr], },
    CSFor {
      variant_unique,
      init [optional [LalinCAst.ForInit]],
      cond [optional [LalinCAst.Expr]],
      incr [optional [LalinCAst.Expr]],
      body [LalinCAst.Stmt],
    },
    CSGoto { variant_unique, label [str], },
    CSContinue,
    CSBreak,
    CSReturn { variant_unique, field. expr [optional [LalinCAst.Expr]], },
  },
  sum. ForInit {
    CFInitExpr { variant_unique, field. expr [LalinCAst.Expr], },
    CFInitDecl { variant_unique, decl [LalinCAst.Decl], },
  },
  sum. BlockItem {
    CBlockDecl { variant_unique, decl [LalinCAst.Decl], },
    CBlockStmt { variant_unique, stmt [LalinCAst.Stmt], },
  },
  sum. Initializer {
    CInitExpr { variant_unique, field. expr [LalinCAst.Expr], },
    CInitList { variant_unique, items [many [LalinCAst.InitItem]], },
  },
  product. InitItem {
    interned,
    designator [optional [many [LalinCAst.Designator]]],
    field. value [LalinCAst.Initializer],
  },
  sum. Designator {
    CDesigField { variant_unique, field. name [str], },
    CDesigIndex { variant_unique, index [LalinCAst.Expr], },
    CDesigRange { variant_unique, lo [LalinCAst.Expr], hi [LalinCAst.Expr], },
  },
}
