local S = require("lalin.schema.dsl")
S.use()

return schema. LalinCode {
  product. CodeModuleId { interned, text [str], },
  product. CodeFuncId { interned, text [str], },
  product. CodeExternId { interned, text [str], },
  product. CodeGlobalId { interned, text [str], },
  product. CodeDataId { interned, text [str], },
  product. CodeRelocId { interned, text [str], },
  product. CodeSigId { interned, text [str], },
  product. CodeBlockId { interned, text [str], },
  product. CodeInstId { interned, text [str], },
  product. CodeTermId { interned, text [str], },
  product. CodeValueId { interned, text [str], },
  product. CodeLocalId { interned, text [str], },
  product. CodeTypeId { interned, text [str], },
  sum. CodeOrigin {
    CodeOriginUnknown,
    CodeOriginSource { variant_unique, label [str], },
    CodeOriginBinding { variant_unique, binding [LalinBind.Binding], },
    CodeOriginGenerated { variant_unique, reason [str], },
  },
  sum. CodeIntSignedness { CodeSigned, CodeUnsigned, },
  sum. CodeType {
    CodeTyVoid,
    CodeTyBool8,
    CodeTyInt { variant_unique, bits [number], signedness [LalinCode.CodeIntSignedness], },
    CodeTyFloat { variant_unique, bits [number], },
    CodeTyIndex,
    CodeTyDataPtr { variant_unique, pointee [optional [LalinCode.CodeType]], },
    CodeTyCodePtr { variant_unique, sig [LalinCode.CodeSigId], },
    CodeTyNamed {
      variant_unique,
      module_name [str],
      type_name [str],
      source_ty [LalinType.Type],
    },
    CodeTyArray { variant_unique, elem [LalinCode.CodeType], count [number], },
    CodeTySlice { variant_unique, elem [LalinCode.CodeType], },
    CodeTyView { variant_unique, elem [LalinCode.CodeType], },
    CodeTyByteSpan,
    CodeTyHandle { variant_unique, repr [LalinCode.CodeType], source_ty [LalinType.Type], },
    CodeTyLease { variant_unique, base [LalinCode.CodeType], source_ty [LalinType.Type], },
    CodeTyClosure { variant_unique, sig [LalinCode.CodeSigId], },
    CodeTyImportedC { variant_unique, field. id [LalinC.CTypeId], },
    CodeTyImportedCFuncPtr { variant_unique, sig [LalinC.CFuncSigId], },
    CodeTyVector { variant_unique, elem [LalinCode.CodeType], lanes [number], },
  },
  product. CodeTypeDecl {
    interned,
    field. id [LalinCode.CodeTypeId],
    field. name [str],
    field. ty [LalinCode.CodeType],
    origin [LalinCode.CodeOrigin],
  },
  product. CodeParam {
    interned,
    field. value [LalinCode.CodeValueId],
    field. name [str],
    field. ty [LalinCode.CodeType],
    origin [LalinCode.CodeOrigin],
  },
  product. CodeSig {
    interned,
    field. id [LalinCode.CodeSigId],
    params [many [LalinCode.CodeType]],
    results [many [LalinCode.CodeType]],
  },
  sum. CodeResidence {
    CodeResidenceValue,
    CodeResidenceAddressed,
    CodeResidenceAggregate,
    CodeResidenceDescriptor,
    CodeResidenceStatic,
  },
  product. CodeLocal {
    interned,
    field. id [LalinCode.CodeLocalId],
    field. name [str],
    field. ty [LalinCode.CodeType],
    residence [LalinCode.CodeResidence],
    origin [LalinCode.CodeOrigin],
  },
  sum. CodePlace {
    CodePlaceLocal {
      variant_unique,
      field. local_id [LalinCode.CodeLocalId],
      field. ty [LalinCode.CodeType],
    },
    CodePlaceGlobal {
      variant_unique,
      global [LalinCode.CodeGlobalId],
      field. ty [LalinCode.CodeType],
    },
    CodePlaceData {
      variant_unique,
      data [LalinCode.CodeDataId],
      field. ty [LalinCode.CodeType],
    },
    CodePlaceDeref {
      variant_unique,
      addr [LalinCode.CodeValueId],
      field. ty [LalinCode.CodeType],
      align [optional [number]],
    },
    CodePlaceField {
      variant_unique,
      base [LalinCode.CodePlace],
      field. field [LalinSem.FieldRef],
      field. ty [LalinCode.CodeType],
      offset [number],
      size [optional [number]],
      align [optional [number]],
    },
    CodePlaceIndex {
      variant_unique,
      base [LalinCode.CodePlace],
      index [LalinCode.CodeValueId],
      field. ty [LalinCode.CodeType],
      elem_size [number],
    },
    CodePlaceBytes {
      variant_unique,
      base [LalinCode.CodeValueId],
      offset [number],
      field. ty [LalinCode.CodeType],
      size [number],
      align [number],
    },
  },
  sum. CodeTrapMode { CodeMayTrap, CodeMustNotTrap, CodeCheckedTrap, },
  sum. CodeMemoryMode { CodeMemoryRead, CodeMemoryWrite, CodeMemoryReadWrite, },
  product. CodeMemoryAccess {
    interned,
    mode [LalinCode.CodeMemoryMode],
    field. ty [LalinCode.CodeType],
    align [number],
    trap [LalinCode.CodeTrapMode],
    volatile [bool],
    ordering [optional [LalinCore.AtomicOrdering]],
  },
  sum. CodeConst {
    CodeConstLiteral {
      variant_unique,
      field. ty [LalinCode.CodeType],
      literal [LalinCore.Literal],
    },
    CodeConstNull { variant_unique, field. ty [LalinCode.CodeType], },
    CodeConstUndef { variant_unique, field. ty [LalinCode.CodeType], reason [str], },
  },
  sum. CodeIntOverflow {
    CodeIntWrap,
    CodeIntTrapOnOverflow,
    CodeIntAssumeNoOverflow { variant_unique, reason [str], },
  },
  sum. CodeDivMode { CodeDivTrapOnZero, CodeDivTrapOnZeroOrOverflow, },
  sum. CodeShiftMode { CodeShiftMaskCount, CodeShiftTrapOutOfRange, },
  product. CodeIntSemantics {
    interned,
    overflow [LalinCode.CodeIntOverflow],
    div [LalinCode.CodeDivMode],
    shift [LalinCode.CodeShiftMode],
  },
  sum. CodeFloatMode {
    CodeFloatStrict,
    CodeFloatReassoc { variant_unique, reason [str], },
    CodeFloatFastMath { variant_unique, reason [str], },
  },
  sum. CodeCallTarget {
    CodeCallDirect { variant_unique, func [LalinCode.CodeFuncId], },
    CodeCallExtern { variant_unique, extern [LalinCode.CodeExternId], },
    CodeCallIndirect {
      variant_unique,
      callee [LalinCode.CodeValueId],
      sig [LalinCode.CodeSigId],
    },
    CodeCallClosure {
      variant_unique,
      closure [LalinCode.CodeValueId],
      sig [LalinCode.CodeSigId],
    },
  },
  sum. CodeGlobalRef {
    CodeGlobalRefData { variant_unique, data [LalinCode.CodeDataId], },
    CodeGlobalRefGlobal { variant_unique, global [LalinCode.CodeGlobalId], },
    CodeGlobalRefFunc { variant_unique, func [LalinCode.CodeFuncId], },
    CodeGlobalRefExtern { variant_unique, extern [LalinCode.CodeExternId], },
  },
  product. CodeReloc {
    interned,
    field. id [LalinCode.CodeRelocId],
    offset [number],
    target [LalinCode.CodeGlobalRef],
    addend [number],
    origin [LalinCode.CodeOrigin],
  },
  product. CodeFieldValue {
    interned,
    field. field [LalinSem.FieldRef],
    field. value [LalinCode.CodeValueId],
  },
  product. CodeArrayValue { interned, index [number], field. value [LalinCode.CodeValueId], },
  product. CodeVariantRef {
    interned,
    owner_ty [LalinCode.CodeType],
    variant_name [str],
    tag_value [number],
    payload_ty [optional [LalinCode.CodeType]],
  },
  product. CodeVariantCase {
    interned,
    variant [LalinCode.CodeVariantRef],
    dest [LalinCode.CodeBlockId],
    args [many [LalinCode.CodeValueId]],
  },
  product. CodeSwitchCase {
    interned,
    literal [LalinCore.Literal],
    dest [LalinCode.CodeBlockId],
    args [many [LalinCode.CodeValueId]],
  },
  sum. CodeInstKind {
    CodeInstConst {
      variant_unique,
      dst [LalinCode.CodeValueId],
      const [LalinCode.CodeConst],
    },
    CodeInstAlias {
      variant_unique,
      dst [LalinCode.CodeValueId],
      field. ty [LalinCode.CodeType],
      src [LalinCode.CodeValueId],
    },
    CodeInstUnary {
      variant_unique,
      dst [LalinCode.CodeValueId],
      op [LalinCore.UnaryOp],
      field. ty [LalinCode.CodeType],
      field. value [LalinCode.CodeValueId],
    },
    CodeInstBinary {
      variant_unique,
      dst [LalinCode.CodeValueId],
      op [LalinCore.BinaryOp],
      field. ty [LalinCode.CodeType],
      semantics [LalinCode.CodeIntSemantics],
      lhs [LalinCode.CodeValueId],
      rhs [LalinCode.CodeValueId],
    },
    CodeInstFloatBinary {
      variant_unique,
      dst [LalinCode.CodeValueId],
      op [LalinCore.BinaryOp],
      field. ty [LalinCode.CodeType],
      mode [LalinCode.CodeFloatMode],
      lhs [LalinCode.CodeValueId],
      rhs [LalinCode.CodeValueId],
    },
    CodeInstCompare {
      variant_unique,
      dst [LalinCode.CodeValueId],
      op [LalinCore.CmpOp],
      operand_ty [LalinCode.CodeType],
      lhs [LalinCode.CodeValueId],
      rhs [LalinCode.CodeValueId],
    },
    CodeInstCast {
      variant_unique,
      dst [LalinCode.CodeValueId],
      op [LalinCore.MachineCastOp],
      from [LalinCode.CodeType],
      to [LalinCode.CodeType],
      field. value [LalinCode.CodeValueId],
    },
    CodeInstSelect {
      variant_unique,
      dst [LalinCode.CodeValueId],
      field. ty [LalinCode.CodeType],
      cond [LalinCode.CodeValueId],
      then_value [LalinCode.CodeValueId],
      else_value [LalinCode.CodeValueId],
    },
    CodeInstIntrinsic {
      variant_unique,
      dst [optional [LalinCode.CodeValueId]],
      op [LalinCore.Intrinsic],
      field. ty [LalinCode.CodeType],
      args [many [LalinCode.CodeValueId]],
    },
    CodeInstAddrOf {
      variant_unique,
      dst [LalinCode.CodeValueId],
      ptr_ty [LalinCode.CodeType],
      place [LalinCode.CodePlace],
    },
    CodeInstGlobalRef {
      variant_unique,
      dst [LalinCode.CodeValueId],
      field. ref [LalinCode.CodeGlobalRef],
      ptr_ty [LalinCode.CodeType],
    },
    CodeInstPtrOffset {
      variant_unique,
      dst [LalinCode.CodeValueId],
      ptr_ty [LalinCode.CodeType],
      base [LalinCode.CodeValueId],
      index [LalinCode.CodeValueId],
      elem_size [number],
      const_offset [number],
    },
    CodeInstLoad {
      variant_unique,
      dst [LalinCode.CodeValueId],
      place [LalinCode.CodePlace],
      access [LalinCode.CodeMemoryAccess],
    },
    CodeInstStore {
      variant_unique,
      place [LalinCode.CodePlace],
      field. value [LalinCode.CodeValueId],
      access [LalinCode.CodeMemoryAccess],
    },
    CodeInstAggregate {
      variant_unique,
      dst [LalinCode.CodeValueId],
      field. ty [LalinCode.CodeType],
      fields [many [LalinCode.CodeFieldValue]],
    },
    CodeInstArray {
      variant_unique,
      dst [LalinCode.CodeValueId],
      field. ty [LalinCode.CodeType],
      elems [many [LalinCode.CodeArrayValue]],
    },
    CodeInstViewMake {
      variant_unique,
      dst [LalinCode.CodeValueId],
      elem_ty [LalinCode.CodeType],
      data [LalinCode.CodeValueId],
      len [LalinCode.CodeValueId],
      stride [LalinCode.CodeValueId],
    },
    CodeInstViewData {
      variant_unique,
      dst [LalinCode.CodeValueId],
      view [LalinCode.CodeValueId],
    },
    CodeInstViewLen {
      variant_unique,
      dst [LalinCode.CodeValueId],
      view [LalinCode.CodeValueId],
    },
    CodeInstViewStride {
      variant_unique,
      dst [LalinCode.CodeValueId],
      view [LalinCode.CodeValueId],
    },
    CodeInstSliceMake {
      variant_unique,
      dst [LalinCode.CodeValueId],
      elem_ty [LalinCode.CodeType],
      data [LalinCode.CodeValueId],
      len [LalinCode.CodeValueId],
    },
    CodeInstSliceData {
      variant_unique,
      dst [LalinCode.CodeValueId],
      slice [LalinCode.CodeValueId],
    },
    CodeInstSliceLen {
      variant_unique,
      dst [LalinCode.CodeValueId],
      slice [LalinCode.CodeValueId],
    },
    CodeInstByteSpanMake {
      variant_unique,
      dst [LalinCode.CodeValueId],
      data [LalinCode.CodeValueId],
      len [LalinCode.CodeValueId],
    },
    CodeInstByteSpanData {
      variant_unique,
      dst [LalinCode.CodeValueId],
      span [LalinCode.CodeValueId],
    },
    CodeInstByteSpanLen {
      variant_unique,
      dst [LalinCode.CodeValueId],
      span [LalinCode.CodeValueId],
    },
    CodeInstClosure {
      variant_unique,
      dst [LalinCode.CodeValueId],
      field. ty [LalinCode.CodeType],
      fn [LalinCode.CodeValueId],
      ctx [LalinCode.CodeValueId],
      sig [LalinCode.CodeSigId],
    },
    CodeInstVariantCtor {
      variant_unique,
      dst [LalinCode.CodeValueId],
      field. ty [LalinCode.CodeType],
      variant [LalinCode.CodeVariantRef],
      payload [optional [LalinCode.CodeValueId]],
    },
    CodeInstVariantTag {
      variant_unique,
      dst [LalinCode.CodeValueId],
      tag_ty [LalinCode.CodeType],
      field. value [LalinCode.CodeValueId],
    },
    CodeInstVariantPayload {
      variant_unique,
      dst [LalinCode.CodeValueId],
      variant [LalinCode.CodeVariantRef],
      field. value [LalinCode.CodeValueId],
    },
    CodeInstCall {
      variant_unique,
      dst [optional [LalinCode.CodeValueId]],
      target [LalinCode.CodeCallTarget],
      sig [LalinCode.CodeSigId],
      args [many [LalinCode.CodeValueId]],
    },
    CodeInstAtomicLoad {
      variant_unique,
      dst [LalinCode.CodeValueId],
      place [LalinCode.CodePlace],
      access [LalinCode.CodeMemoryAccess],
      ordering [LalinCore.AtomicOrdering],
    },
    CodeInstAtomicStore {
      variant_unique,
      place [LalinCode.CodePlace],
      field. value [LalinCode.CodeValueId],
      access [LalinCode.CodeMemoryAccess],
      ordering [LalinCore.AtomicOrdering],
    },
    CodeInstAtomicRmw {
      variant_unique,
      dst [LalinCode.CodeValueId],
      op [LalinCore.AtomicRmwOp],
      place [LalinCode.CodePlace],
      field. value [LalinCode.CodeValueId],
      access [LalinCode.CodeMemoryAccess],
      ordering [LalinCore.AtomicOrdering],
    },
    CodeInstAtomicCas {
      variant_unique,
      dst [LalinCode.CodeValueId],
      place [LalinCode.CodePlace],
      expected [LalinCode.CodeValueId],
      replacement [LalinCode.CodeValueId],
      access [LalinCode.CodeMemoryAccess],
      ordering [LalinCore.AtomicOrdering],
    },
    CodeInstAtomicFence { variant_unique, ordering [LalinCore.AtomicOrdering], },
  },
  product. CodeInst {
    interned,
    field. id [LalinCode.CodeInstId],
    kind [LalinCode.CodeInstKind],
    origin [LalinCode.CodeOrigin],
  },
  sum. CodeTermKind {
    CodeTermJump {
      variant_unique,
      dest [LalinCode.CodeBlockId],
      args [many [LalinCode.CodeValueId]],
    },
    CodeTermBranch {
      variant_unique,
      cond [LalinCode.CodeValueId],
      then_dest [LalinCode.CodeBlockId],
      then_args [many [LalinCode.CodeValueId]],
      else_dest [LalinCode.CodeBlockId],
      else_args [many [LalinCode.CodeValueId]],
    },
    CodeTermSwitch {
      variant_unique,
      field. value [LalinCode.CodeValueId],
      cases [many [LalinCode.CodeSwitchCase]],
      default_dest [LalinCode.CodeBlockId],
      default_args [many [LalinCode.CodeValueId]],
    },
    CodeTermVariantSwitch {
      variant_unique,
      tag [LalinCode.CodeValueId],
      cases [many [LalinCode.CodeVariantCase]],
      default_dest [LalinCode.CodeBlockId],
      default_args [many [LalinCode.CodeValueId]],
    },
    CodeTermReturn { variant_unique, values [many [LalinCode.CodeValueId]], },
    CodeTermTrap { variant_unique, reason [str], },
    CodeTermUnreachable { variant_unique, reason [str], },
  },
  product. CodeTerm {
    interned,
    field. id [LalinCode.CodeTermId],
    kind [LalinCode.CodeTermKind],
    origin [LalinCode.CodeOrigin],
  },
  product. CodeBackSigAbi {
    interned,
    sret [bool],
    result_ty [optional [LalinCode.CodeType]],
    params [many [LalinBack.BackScalar]],
    results [many [LalinBack.BackScalar]],
  },
  product. CodeBackLocalSlot {
    interned,
    slot [LalinBack.BackStackSlotId],
    field. ty [LalinCode.CodeType],
    size [number],
    align [number],
  },
  product. CodeBackModuleFacts {
    sigs [map [str] [LalinCode.CodeSig]],
    sig_abi_by_sig [map [str] [LalinCode.CodeBackSigAbi]],
    mem_backend_by_inst [map [str] [LalinMem.MemBackendAccessInfo]],
    value_int_semantics_by_value [map [str] [LalinCode.CodeIntSemantics]],
    value_float_mode_by_value [map [str] [LalinCode.CodeFloatMode]],
    effect_by_inst [map [str] [LalinEffect.InstEffect]],
    readonly_inst [map [str] [bool]],
    layout_env [optional [LalinSem.LayoutEnv]],
    target [optional [LalinBack.BackTarget]],
  },
  product. CodeBackFunctionFacts {
    func [LalinCode.CodeFuncId],
    current_return_sret [optional [LalinBack.BackValId]],
    value_types [map [str] [LalinCode.CodeType]],
    block_params [map [str] [many [LalinCode.CodeParam]]],
  },
  product. CodeBackFunctionState {
    cmds [many [LalinBack.Cmd]],
    aggregate_local_addr [map [str] [LalinBack.BackValId]],
    aggregate_value_addr [map [str] [LalinBack.BackValId]],
    aggregate_value_size [map [str] [number]],
    closure_value_has_captures [map [str] [bool]],
    local_stack_slots [map [str] [LalinCode.CodeBackLocalSlot]],
    tmp_index [number],
    next_tmp [number],
  },
  product. CodeBackInstInput {
    field. module [LalinCode.CodeBackModuleFacts],
    func [LalinCode.CodeBackFunctionFacts],
    state [LalinCode.CodeBackFunctionState],
    inst [LalinCode.CodeInstId],
  },
  product. CodeBackTermInput {
    field. module [LalinCode.CodeBackModuleFacts],
    func [LalinCode.CodeBackFunctionFacts],
    state [LalinCode.CodeBackFunctionState],
    term [LalinCode.CodeTermId],
  },
  product. CodeBackPlaceInput {
    field. module [LalinCode.CodeBackModuleFacts],
    func [LalinCode.CodeBackFunctionFacts],
    state [LalinCode.CodeBackFunctionState],
    owner [LalinCode.CodeInstId],
    access [optional [LalinMem.MemBackendAccessInfo]],
  },
  product. CodeBackStateResult {
    state [LalinCode.CodeBackFunctionState],
  },
  product. CodeBackValueResult {
    field. value [LalinBack.BackValId],
    state [LalinCode.CodeBackFunctionState],
  },
  product. CodeBackAddressResult {
    address [LalinBack.BackAddress],
    state [LalinCode.CodeBackFunctionState],
  },
  product. CodeBackMemoryInfoResult {
    memory [LalinBack.BackMemoryInfo],
    state [LalinCode.CodeBackFunctionState],
  },
  product. CodeBackPlaceResult {
    address [LalinBack.BackAddress],
    state [LalinCode.CodeBackFunctionState],
  },
  product. CodeBlock {
    interned,
    field. id [LalinCode.CodeBlockId],
    field. name [str],
    params [many [LalinCode.CodeParam]],
    insts [many [LalinCode.CodeInst]],
    term [LalinCode.CodeTerm],
    origin [LalinCode.CodeOrigin],
  },
  sum. CodeLinkage {
    CodeLinkageLocal,
    CodeLinkageExport,
    CodeLinkageImport,
    CodeLinkageDeclaration,
  },
  sum. CodeDataInit {
    CodeDataZero { variant_unique, offset [number], size [number], },
    CodeDataBytes { variant_unique, offset [number], bytes [str], },
    CodeDataScalar {
      variant_unique,
      offset [number],
      field. ty [LalinCode.CodeType],
      literal [LalinCore.Literal],
    },
    CodeDataReloc { variant_unique, reloc [LalinCode.CodeReloc], },
  },
  product. CodeData {
    interned,
    field. id [LalinCode.CodeDataId],
    field. name [str],
    linkage [LalinCode.CodeLinkage],
    size [number],
    align [number],
    inits [many [LalinCode.CodeDataInit]],
    origin [LalinCode.CodeOrigin],
  },
  product. CodeGlobal {
    interned,
    field. id [LalinCode.CodeGlobalId],
    field. name [str],
    field. ty [LalinCode.CodeType],
    linkage [LalinCode.CodeLinkage],
    size [optional [number]],
    align [optional [number]],
    inits [many [LalinCode.CodeDataInit]],
    origin [LalinCode.CodeOrigin],
  },
  product. CodeExtern {
    interned,
    field. id [LalinCode.CodeExternId],
    field. name [str],
    symbol [str],
    sig [LalinCode.CodeSigId],
    origin [LalinCode.CodeOrigin],
  },
  sum. CodeContractFact {
    CodeContractBounds {
      variant_unique,
      base [LalinCode.CodeValueId],
      len [LalinCode.CodeValueId],
    },
    CodeContractWindowBounds {
      variant_unique,
      base [LalinCode.CodeValueId],
      base_len [LalinCode.CodeValueId],
      start [LalinCode.CodeValueId],
      len [LalinCode.CodeValueId],
    },
    CodeContractDisjoint {
      variant_unique,
      a [LalinCode.CodeValueId],
      b [LalinCode.CodeValueId],
    },
    CodeContractSameLen {
      variant_unique,
      a [LalinCode.CodeValueId],
      b [LalinCode.CodeValueId],
    },
    CodeContractSoAComponent {
      variant_unique,
      base [LalinCode.CodeValueId],
      record_ty [LalinCode.CodeType],
      field_name [str],
      component_index [number],
    },
    CodeContractNoAlias { variant_unique, base [LalinCode.CodeValueId], },
    CodeContractReadonly { variant_unique, base [LalinCode.CodeValueId], },
    CodeContractWriteonly { variant_unique, base [LalinCode.CodeValueId], },
    CodeContractInvalidate { variant_unique, base [LalinCode.CodeValueId], },
    CodeContractPreserve { variant_unique, base [LalinCode.CodeValueId], },
    CodeContractRejected { variant_unique, reason [str], },
  },
  product. CodeFuncContractFact {
    interned,
    func [LalinCode.CodeFuncId],
    fact [LalinCode.CodeContractFact],
    origin [LalinCode.CodeOrigin],
  },
  product. CodeContractFactSet {
    interned,
    field. module [LalinCode.CodeModuleId],
    facts [many [LalinCode.CodeFuncContractFact]],
  },
  product. CodeFunc {
    interned,
    field. id [LalinCode.CodeFuncId],
    field. name [str],
    linkage [LalinCode.CodeLinkage],
    sig [LalinCode.CodeSigId],
    params [many [LalinCode.CodeParam]],
    locals [many [LalinCode.CodeLocal]],
    entry [LalinCode.CodeBlockId],
    blocks [many [LalinCode.CodeBlock]],
    origin [LalinCode.CodeOrigin],
  },
  product. CodeModule {
    interned,
    field. id [LalinCode.CodeModuleId],
    sigs [many [LalinCode.CodeSig]],
    types [many [LalinCode.CodeTypeDecl]],
    data [many [LalinCode.CodeData]],
    globals [many [LalinCode.CodeGlobal]],
    externs [many [LalinCode.CodeExtern]],
    funcs [many [LalinCode.CodeFunc]],
    origin [LalinCode.CodeOrigin],
  },
  sum. CodeIssue {
    CodeIssueMissingValue { variant_unique, field. value [LalinCode.CodeValueId], },
    CodeIssueDuplicateValue { variant_unique, field. value [LalinCode.CodeValueId], },
    CodeIssueMissingBlock { variant_unique, block [LalinCode.CodeBlockId], },
    CodeIssueDuplicateBlock { variant_unique, block [LalinCode.CodeBlockId], },
    CodeIssueMissingSig { variant_unique, sig [LalinCode.CodeSigId], },
    CodeIssueMissingFunc { variant_unique, func [LalinCode.CodeFuncId], },
    CodeIssueMissingExtern { variant_unique, extern [LalinCode.CodeExternId], },
    CodeIssueMissingGlobal { variant_unique, global [LalinCode.CodeGlobalId], },
    CodeIssueMissingData { variant_unique, data [LalinCode.CodeDataId], },
    CodeIssueDuplicateSig { variant_unique, sig [LalinCode.CodeSigId], },
    CodeIssueDuplicateFunc { variant_unique, func [LalinCode.CodeFuncId], },
    CodeIssueDuplicateExtern { variant_unique, extern [LalinCode.CodeExternId], },
    CodeIssueDuplicateGlobal { variant_unique, global [LalinCode.CodeGlobalId], },
    CodeIssueDuplicateData { variant_unique, data [LalinCode.CodeDataId], },
    CodeIssueDuplicateInst { variant_unique, inst [LalinCode.CodeInstId], },
    CodeIssueDuplicateTerm { variant_unique, term [LalinCode.CodeTermId], },
    CodeIssueJumpArity {
      variant_unique,
      block [LalinCode.CodeBlockId],
      expected [number],
      actual [number],
    },
    CodeIssueCallArity {
      variant_unique,
      sig [LalinCode.CodeSigId],
      expected [number],
      actual [number],
    },
    CodeIssueTypeMismatch {
      variant_unique,
      site [str],
      expected [LalinCode.CodeType],
      actual [LalinCode.CodeType],
    },
    CodeIssueBlockParamMismatch {
      variant_unique,
      block [LalinCode.CodeBlockId],
      index [number],
      expected [LalinCode.CodeType],
      actual [LalinCode.CodeType],
    },
    CodeIssueUnterminatedBlock { variant_unique, block [LalinCode.CodeBlockId], },
    CodeIssueInvalidTerminator { variant_unique, site [str], term [LalinCode.CodeTermId], },
    CodeIssueInvalidMemoryAccess {
      variant_unique,
      site [str],
      access [LalinCode.CodeMemoryAccess],
    },
    CodeIssueInvalidReloc { variant_unique, reloc [LalinCode.CodeReloc], reason [str], },
    CodeIssueDataCodePointerConfusion {
      variant_unique,
      site [str],
      field. ty [LalinCode.CodeType],
    },
    CodeIssueUnsupportedSource { variant_unique, site [str], reason [str], },
  },
  product. CodeValidationReport { interned, issues [many [LalinCode.CodeIssue]], },
}
