local S = require("lalin.schema.dsl")
S.use()

return schema. LalinDasm {
  product. DModuleId { interned, text [str], },
  product. DBlockId { interned, text [str], },
  product. DValId { interned, text [str], },
  product. DLabelId { interned, text [str], },
  product. DVirtualRegId { interned, text [str], },
  product. DPhysRegId { interned, field. number [number], },
  sum. DRegClass { DGpr, DXmm, DFlags, },
  sum. DValueClass {
    DValueGpr { variant_unique, scalar [LalinBack.BackScalar], },
    DValueXmm { variant_unique, scalar [LalinBack.BackScalar], },
    DValueFlags,
    DValueVector { variant_unique, elem [LalinBack.BackScalar], lanes [number], },
  },
  product. DSigEntry {
    interned,
    key [str],
    params [many [LalinBack.BackScalar]],
    results [many [LalinBack.BackScalar]],
  },
  product. DFuncEntry {
    interned,
    key [str],
    sig [str],
    visibility [str],
    body [many [LalinBack.Cmd]],
  },
  product. DExternEntry { interned, key [str], symbol [str], sig [str], },
  product. DDataEntry { interned, key [str], buf [any], size [number], align [number], },
  product. DLabelPair { interned, key [str], label [str], },
  product. DLabelMap {
    interned,
    funcs [many [LalinDasm.DLabelPair]],
    externs [many [LalinDasm.DLabelPair]],
    datas [many [LalinDasm.DLabelPair]],
  },
  product. DPhaseModule {
    interned,
    sigs [many [LalinDasm.DSigEntry]],
    funcs [many [LalinDasm.DFuncEntry]],
    externs [many [LalinDasm.DExternEntry]],
    datas [many [LalinDasm.DDataEntry]],
    func_order [many [str]],
    extern_order [many [str]],
    data_order [many [str]],
    labels [LalinDasm.DLabelMap],
  },
  product. DTargetFacts {
    interned,
    target [LalinBack.BackTargetModel],
    pointer_bits [number],
    index_bits [number],
    endianness [str],
    features [many [str]],
  },
  product. DFuncBody { interned, func [LalinBack.BackFuncId], cmds [many [LalinBack.Cmd]], },
  product. DPhaseFunc {
    interned,
    func [optional [LalinBack.BackFuncId]],
    cmds [many [LalinBack.Cmd]],
  },
  product. DScalarMapEntry { interned, key [str], scalar [str], },
  product. DTypedFunc {
    interned,
    func [LalinBack.BackFuncId],
    cmds [many [LalinBack.Cmd]],
    value_scalars [many [LalinDasm.DScalarMapEntry]],
  },
  product. DBlockParam {
    interned,
    field. value [LalinBack.BackValId],
    field. ty [LalinBack.BackShape],
  },
  product. DEdgeArg {
    interned,
    src [LalinBack.BackValId],
    dst_param [LalinBack.BackValId],
  },
  product. DSwitchCase { interned, raw [str], dest [LalinBack.BackBlockId], },
  sum. DTerminator {
    DTermJump {
      variant_unique,
      dest [LalinBack.BackBlockId],
      args [many [LalinDasm.DEdgeArg]],
    },
    DTermBrIf {
      variant_unique,
      cond [LalinBack.BackValId],
      then_block [LalinBack.BackBlockId],
      then_args [many [LalinDasm.DEdgeArg]],
      else_block [LalinBack.BackBlockId],
      else_args [many [LalinDasm.DEdgeArg]],
    },
    DTermSwitch {
      variant_unique,
      field. value [LalinBack.BackValId],
      field. ty [LalinBack.BackScalar],
      cases [many [LalinDasm.DSwitchCase]],
      default_dest [LalinBack.BackBlockId],
    },
    DTermReturnVoid,
    DTermReturnValue { variant_unique, field. value [LalinBack.BackValId], },
    DTermTrap,
  },
  product. DCfgBlock {
    interned,
    field. id [LalinBack.BackBlockId],
    params [many [LalinDasm.DBlockParam]],
    body [many [LalinBack.Cmd]],
    term [LalinDasm.DTerminator],
  },
  product. DFuncCFG {
    interned,
    func [LalinBack.BackFuncId],
    sig [LalinBack.BackSigId],
    entry [LalinBack.BackBlockId],
    blocks [many [LalinDasm.DCfgBlock]],
    stack_slots [many [LalinBack.BackStackSlotId]],
  },
  sum. DValueFact {
    DValueShapeFact {
      variant_unique,
      field. value [LalinBack.BackValId],
      shape [LalinBack.BackShape],
    },
    DValueClassFact {
      variant_unique,
      field. value [LalinBack.BackValId],
      class [LalinDasm.DValueClass],
    },
    DValueDefFact {
      variant_unique,
      field. value [LalinBack.BackValId],
      block [LalinBack.BackBlockId],
      index [number],
    },
    DValueUseFact {
      variant_unique,
      field. value [LalinBack.BackValId],
      block [LalinBack.BackBlockId],
      index [number],
      slot [number],
    },
    DValueConstIntFact { variant_unique, field. value [LalinBack.BackValId], raw [str], },
    DValueConstFloatFact { variant_unique, field. value [LalinBack.BackValId], raw [str], },
  },
  sum. DEdgeKind {
    DEdgeEntry,
    DEdgeJump,
    DEdgeThen,
    DEdgeElse,
    DEdgeSwitchCase,
    DEdgeSwitchDefault,
    DEdgeCriticalSplit,
  },
  product. DEdgeRef {
    interned,
    pred [LalinBack.BackBlockId],
    succ [LalinBack.BackBlockId],
    kind [LalinDasm.DEdgeKind],
    ordinal [number],
  },
  product. DParallelMove {
    interned,
    dst [LalinBack.BackValId],
    src [LalinBack.BackValId],
    class [LalinDasm.DValueClass],
  },
  product. DParallelCopy {
    interned,
    edge [LalinDasm.DEdgeRef],
    moves [many [LalinDasm.DParallelMove]],
  },
  sum. DControlFact {
    DControlEdgeFact {
      variant_unique,
      edge [LalinDasm.DEdgeRef],
      args [many [LalinDasm.DEdgeArg]],
    },
    DParallelCopyFact { variant_unique, copy [LalinDasm.DParallelCopy], },
  },
  sum. DMemoryFact {
    DMemoryLoadFact {
      variant_unique,
      dst [LalinBack.BackValId],
      addr [LalinBack.BackAddress],
      memory [LalinBack.BackMemoryInfo],
      field. ty [LalinBack.BackShape],
    },
    DMemoryStoreFact {
      variant_unique,
      addr [LalinBack.BackAddress],
      field. value [LalinBack.BackValId],
      memory [LalinBack.BackMemoryInfo],
      field. ty [LalinBack.BackShape],
    },
  },
  sum. DCallFact {
    DCallSiteFact {
      variant_unique,
      index [number],
      sig [LalinBack.BackSigId],
      target [LalinBack.BackCallTarget],
      args [many [LalinBack.BackValId]],
      result [optional [LalinBack.BackCallResult]],
    },
    DCallClobberFact { variant_unique, index [number], clobbers [many [LalinDasm.DPhysRegId]], },
  },
  product. DFuncFacts {
    interned,
    cfg [LalinDasm.DFuncCFG],
    value_facts [many [LalinDasm.DValueFact]],
    control_facts [many [LalinDasm.DControlFact]],
    memory_facts [many [LalinDasm.DMemoryFact]],
    call_facts [many [LalinDasm.DCallFact]],
  },
  sum. DConstKind {
    DConstUnknown,
    DConstInt { variant_unique, raw [str], },
    DConstFloat { variant_unique, raw [str], },
    DConstBool { variant_unique, field. value [bool], },
    DConstNull,
  },
  sum. DAddrBaseKind { DBaseValue, DBaseStack, DBaseData, DBaseUnknown, },
  sum. DFamilyKind {
    DFamilyCopy,
    DFamilyIntBin,
    DFamilyBitBin,
    DFamilyShiftRotate,
    DFamilyCompareBranch,
    DFamilyLoadStore,
    DFamilyAddress,
    DFamilyCall,
    DFamilyControl,
    DFamilyReturn,
    DFamilyOther,
  },
  sum. DFamilyKey {
    DKeyCopy {
      variant_unique,
      class [LalinDasm.DValueClass],
      src_const [LalinDasm.DConstKind],
      same_value [bool],
    },
    DKeyIntBin {
      variant_unique,
      op [str],
      scalar [LalinBack.BackScalar],
      lhs_const [LalinDasm.DConstKind],
      rhs_const [LalinDasm.DConstKind],
      commutative [bool],
      rhs_pow2 [bool],
    },
    DKeyBitBin {
      variant_unique,
      op [str],
      scalar [LalinBack.BackScalar],
      rhs_const [LalinDasm.DConstKind],
    },
    DKeyShiftRotate {
      variant_unique,
      op [str],
      scalar [LalinBack.BackScalar],
      rhs_const [LalinDasm.DConstKind],
      rhs_small_imm [bool],
    },
    DKeyCompareBranch {
      variant_unique,
      op [str],
      scalar [LalinBack.BackScalar],
      rhs_const [LalinDasm.DConstKind],
      fused_branch [bool],
      rhs_is_zero [bool],
    },
    DKeyLoadStore {
      variant_unique,
      is_load [bool],
      shape [LalinBack.BackShape],
      base_kind [LalinDasm.DAddrBaseKind],
      has_index [bool],
      const_disp [bool],
      align_bytes [number],
      trap_kind [str],
    },
    DKeyAddress {
      variant_unique,
      base_kind [LalinDasm.DAddrBaseKind],
      elem_size [number],
      const_offset [number],
    },
    DKeyCall {
      variant_unique,
      target_kind [str],
      argc [number],
      has_result [bool],
      result_class [LalinDasm.DValueClass],
    },
    DKeyControl { variant_unique, kind [str], },
    DKeyReturn { variant_unique, has_value [bool], class [LalinDasm.DValueClass], },
    DKeyOther { variant_unique, kind [str], },
  },
  product. DFamilyInstance {
    interned,
    cmd_index [number],
    block [optional [LalinBack.BackBlockId]],
    family [LalinDasm.DFamilyKind],
    key [LalinDasm.DFamilyKey],
  },
  sum. DFactAtom {
    DFactCmdKind { variant_unique, cmd_index [number], kind [str], },
    DFactValueShape {
      variant_unique,
      field. value [LalinBack.BackValId],
      shape [LalinBack.BackShape],
    },
    DFactValueClass {
      variant_unique,
      field. value [LalinBack.BackValId],
      class [LalinDasm.DValueClass],
    },
    DFactValueConst {
      variant_unique,
      field. value [LalinBack.BackValId],
      const_kind [LalinDasm.DConstKind],
    },
    DFactUse {
      variant_unique,
      field. value [LalinBack.BackValId],
      cmd_index [number],
      slot [number],
    },
    DFactDef { variant_unique, field. value [LalinBack.BackValId], cmd_index [number], },
    DFactBlockAt { variant_unique, cmd_index [number], block [LalinBack.BackBlockId], },
  },
  product. DFactSet {
    interned,
    func [optional [LalinBack.BackFuncId]],
    cmds [many [LalinBack.Cmd]],
    atoms [many [LalinDasm.DFactAtom]],
    families [many [LalinDasm.DFamilyInstance]],
  },
  product. DLowerDecision {
    interned,
    cmd_index [number],
    rule [str],
    cost [number],
    shape [LalinDasm.DAsmShape],
  },
  product. DLoweredFunc {
    interned,
    func [optional [LalinBack.BackFuncId]],
    cmds [many [LalinBack.Cmd]],
    facts [LalinDasm.DFactSet],
    decisions [many [LalinDasm.DLowerDecision]],
    asm [LalinDasm.DAsmFunc],
  },
  product. DAddress {
    interned,
    base [optional [LalinDasm.DPhysRegId]],
    index [optional [LalinDasm.DPhysRegId]],
    scale [number],
    disp [number],
  },
  sum. DOperand {
    DOpVReg { variant_unique, vreg [LalinDasm.DVirtualRegId], },
    DOpPReg { variant_unique, preg [LalinDasm.DPhysRegId], },
    DOpImmI64 { variant_unique, raw [str], },
    DOpLabel { variant_unique, label [LalinDasm.DLabelId], },
    DOpMem { variant_unique, addr [LalinDasm.DAddress], },
  },
  sum. DCondCode { DccE, DccNE, DccL, DccLE, DccG, DccGE, DccB, DccBE, DccA, DccAE, DccP, DccNP, },
  sum. DAsmShape {
    DAsmLabel { variant_unique, label [LalinDasm.DLabelId], },
    DAsmMove {
      variant_unique,
      dst [LalinDasm.DOperand],
      src [LalinDasm.DOperand],
      class [LalinDasm.DValueClass],
    },
    DAsmUnary {
      variant_unique,
      op [str],
      dst [LalinDasm.DOperand],
      src [LalinDasm.DOperand],
      scalar [LalinBack.BackScalar],
    },
    DAsmBinary {
      variant_unique,
      op [str],
      dst [LalinDasm.DOperand],
      lhs [LalinDasm.DOperand],
      rhs [LalinDasm.DOperand],
      scalar [LalinBack.BackScalar],
    },
    DAsmCompareSet {
      variant_unique,
      cc [LalinDasm.DCondCode],
      dst [LalinDasm.DOperand],
      lhs [LalinDasm.DOperand],
      rhs [LalinDasm.DOperand],
      scalar [LalinBack.BackScalar],
    },
    DAsmLoad {
      variant_unique,
      dst [LalinDasm.DOperand],
      addr [LalinDasm.DOperand],
      field. ty [LalinBack.BackShape],
    },
    DAsmStore {
      variant_unique,
      addr [LalinDasm.DOperand],
      field. value [LalinDasm.DOperand],
      field. ty [LalinBack.BackShape],
    },
    DAsmLea { variant_unique, dst [LalinDasm.DOperand], addr [LalinDasm.DOperand], },
    DAsmJump { variant_unique, dest [LalinDasm.DLabelId], },
    DAsmBrIf {
      variant_unique,
      cond [LalinDasm.DOperand],
      then_label [LalinDasm.DLabelId],
      else_label [LalinDasm.DLabelId],
    },
    DAsmCall {
      variant_unique,
      target [LalinDasm.DOperand],
      args [many [LalinDasm.DOperand]],
      result [optional [LalinDasm.DOperand]],
    },
    DAsmRetVoid,
    DAsmRetValue { variant_unique, field. value [LalinDasm.DOperand], },
    DAsmPrologue,
    DAsmEpilogue,
    DAsmTrap,
    DAsmComment { variant_unique, text [str], },
  },
  product. DAsmInst {
    interned,
    shape [LalinDasm.DAsmShape],
    defs [many [LalinDasm.DVirtualRegId]],
    uses [many [LalinDasm.DVirtualRegId]],
    clobbers [many [LalinDasm.DPhysRegId]],
  },
  product. DAsmBlock {
    interned,
    field. id [LalinBack.BackBlockId],
    insts [many [LalinDasm.DAsmInst]],
  },
  product. DAsmFunc {
    interned,
    func [LalinBack.BackFuncId],
    blocks [many [LalinDasm.DAsmBlock]],
  },
  sum. DAllocLoc {
    DLocReg { variant_unique, preg [LalinDasm.DPhysRegId], },
    DLocStack { variant_unique, offset [number], size [number], align [number], },
  },
  product. DValueAlloc {
    interned,
    vreg [LalinDasm.DVirtualRegId],
    loc [LalinDasm.DAllocLoc],
    class [LalinDasm.DValueClass],
  },
  product. DBankedRegalloc {
    interned,
    allocs [many [LalinDasm.DValueAlloc]],
    used_callee_saved [many [LalinDasm.DPhysRegId]],
    spill_size [number],
  },
  product. DFrameSlot {
    interned,
    slot [LalinBack.BackStackSlotId],
    offset [number],
    size [number],
    align [number],
  },
  product. DFramePlan {
    interned,
    stack_size [number],
    spill_size [number],
    slot_size [number],
    callee_saved [many [LalinDasm.DPhysRegId]],
    slots [many [LalinDasm.DFrameSlot]],
  },
  product. DFragment { interned, offset [number], args [many [number]], bytes [str], },
  product. DFragmentBundle { interned, fragments [many [LalinDasm.DFragment]], },
  product. DGlobalEntry { interned, kind [str], key [str], label [str], slot_index [number], },
  product. DFuncPtrEntry { interned, func [LalinBack.BackFuncId], global_slot [number], },
  product. DEmitPlan {
    interned,
    globals [many [LalinDasm.DGlobalEntry]],
    fragments [many [LalinDasm.DFragment]],
    func_ptrs [many [LalinDasm.DFuncPtrEntry]],
    code_size_hint [number],
  },
}
