local S = require("lalin.schema.dsl")
S.use()

return schema. LalinEditor {
  sum. ServerMode {
    ServerCreated,
    ServerInitializing,
    ServerReady,
    ServerShutdownRequested,
    ServerStopped,
  },
  sum. ClientCapability {
    ClientCapability { variant_unique, field. name [str], field. value [str], },
  },
  product. WorkspaceRoot { interned, uri [LalinSource.DocUri], },
  sum. WorkspaceFileOrigin { WorkspaceFileOpen, WorkspaceFileDisk, },
  product. WorkspaceFile {
    uri [LalinSource.DocUri],
    path [str],
    language [LalinSource.LanguageId],
    version [LalinSource.DocVersion],
    origin [LalinEditor.WorkspaceFileOrigin],
    fingerprint [str],
  },
  product. WorkspaceIndex { generation [number], files [many [LalinEditor.WorkspaceFile]], },
  product. WorkspaceState {
    mode [LalinEditor.ServerMode],
    roots [many [LalinEditor.WorkspaceRoot]],
    capabilities [many [LalinEditor.ClientCapability]],
    open_docs [many [LalinSource.DocumentSnapshot]],
    index [LalinEditor.WorkspaceIndex],
  },
  sum. RpcId {
    RpcIdNone,
    RpcIdNumber { variant_unique, field. value [number], },
    RpcIdString { variant_unique, field. value [str], },
  },
  product. PositionQuery {
    uri [LalinSource.DocUri],
    version [LalinSource.DocVersion],
    pos [LalinSource.SourcePos],
  },
  product. RangeQuery {
    uri [LalinSource.DocUri],
    version [LalinSource.DocVersion],
    range [LalinSource.SourceRange],
  },
  product. ReferenceQuery { position [LalinEditor.PositionQuery], include_declaration [bool], },
  product. RenameQuery { position [LalinEditor.PositionQuery], new_name [str], },
  product. CodeActionQuery {
    range [LalinEditor.RangeQuery],
    diagnostics [many [LalinEditor.DiagnosticFact]],
  },
  sum. ClientEvent {
    ClientInitialize {
      field. id [LalinEditor.RpcId],
      roots [many [LalinEditor.WorkspaceRoot]],
      capabilities [many [LalinEditor.ClientCapability]],
    },
    ClientInitialized,
    ClientShutdown { field. id [LalinEditor.RpcId], },
    ClientExit,
    ClientDidOpen { document [LalinSource.DocumentSnapshot], },
    ClientDidChange { edit [LalinSource.DocumentEdit], },
    ClientDidClose { uri [LalinSource.DocUri], },
    ClientDidSave { uri [LalinSource.DocUri], },
    ClientHover { field. id [LalinEditor.RpcId], query [LalinEditor.PositionQuery], },
    ClientDefinition { field. id [LalinEditor.RpcId], query [LalinEditor.PositionQuery], },
    ClientReferences { field. id [LalinEditor.RpcId], query [LalinEditor.ReferenceQuery], },
    ClientDocumentHighlight {
      field. id [LalinEditor.RpcId],
      query [LalinEditor.PositionQuery],
    },
    ClientDocumentSymbol { field. id [LalinEditor.RpcId], uri [LalinSource.DocUri], },
    ClientWorkspaceSymbol { field. id [LalinEditor.RpcId], query [str], },
    ClientDiagnostic { field. id [LalinEditor.RpcId], uri [LalinSource.DocUri], },
    ClientCompletion { field. id [LalinEditor.RpcId], query [LalinEditor.PositionQuery], },
    ClientSignatureHelp {
      field. id [LalinEditor.RpcId],
      query [LalinEditor.PositionQuery],
    },
    ClientSemanticTokensFull { field. id [LalinEditor.RpcId], uri [LalinSource.DocUri], },
    ClientSemanticTokensRange {
      field. id [LalinEditor.RpcId],
      query [LalinEditor.RangeQuery],
    },
    ClientPrepareRename {
      field. id [LalinEditor.RpcId],
      query [LalinEditor.PositionQuery],
    },
    ClientRename { field. id [LalinEditor.RpcId], query [LalinEditor.RenameQuery], },
    ClientCodeAction {
      field. id [LalinEditor.RpcId],
      query [LalinEditor.CodeActionQuery],
    },
    ClientFoldingRange { field. id [LalinEditor.RpcId], uri [LalinSource.DocUri], },
    ClientSelectionRange {
      field. id [LalinEditor.RpcId],
      positions [many [LalinEditor.PositionQuery]],
    },
    ClientInlayHint { field. id [LalinEditor.RpcId], query [LalinEditor.RangeQuery], },
    ClientUnsupported { field. id [LalinEditor.RpcId], method [str], },
    ClientIgnoredNotification { method [str], },
  },
  product. Transition {
    before [LalinEditor.WorkspaceState],
    event [LalinEditor.ClientEvent],
    after [LalinEditor.WorkspaceState],
  },
  sum. DiagnosticSeverity {
    DiagnosticError,
    DiagnosticWarning,
    DiagnosticInformation,
    DiagnosticHint,
  },
  sum. DiagnosticOrigin {
    DiagFromParse { variant_unique, issue [LalinParse.ParseIssue], },
    DiagFromHost { variant_unique, issue [LalinHost.HostIssue], },
    DiagFromOpen { variant_unique, issue [LalinOpen.ValidationIssue], },
    DiagFromType { variant_unique, issue [LalinTree.TypeIssue], },
    DiagFromBack { variant_unique, issue [LalinBack.BackValidationIssue], },
    DiagFromBindingResolution { variant_unique, resolution [LalinEditor.BindingResolution], },
    DiagFromSource { variant_unique, issue [LalinSource.SourceApplyIssue], },
    DiagFromTransport { variant_unique, code [str], message [str], },
  },
  product. DiagnosticContextFrame {
    label [str],
    message [str],
    range [optional [LalinSource.SourceRange]],
  },
  product. DiagnosticFact {
    interned,
    severity [LalinEditor.DiagnosticSeverity],
    origin [LalinEditor.DiagnosticOrigin],
    code [str],
    message [str],
    range [LalinSource.SourceRange],
    context [many [LalinEditor.DiagnosticContextFrame]],
  },
  sum. Subject {
    SubjectKeyword { variant_unique, text [str], },
    SubjectScalar { variant_unique, scalar [LalinCore.Scalar], },
    SubjectType { variant_unique, field. ty [LalinType.Type], },
    SubjectHostStruct { variant_unique, decl [LalinHost.HostStructDecl], },
    SubjectHostField {
      variant_unique,
      owner [LalinHost.HostStructDecl],
      field. field [LalinHost.HostFieldDecl],
    },
    SubjectHostExpose { variant_unique, decl [LalinHost.HostExposeDecl], },
    SubjectHostAccessor { variant_unique, decl [LalinHost.HostAccessorDecl], },
    SubjectTreeFunc { variant_unique, func [LalinTree.Func], },
    SubjectTreeExtern { variant_unique, func [LalinTree.ExternFunc], },
    SubjectTreeModule { variant_unique, field. module [LalinTree.Module], },
    SubjectRegionFrag { variant_unique, frag [LalinOpen.RegionFrag], },
    SubjectExprFrag { variant_unique, frag [LalinOpen.ExprFrag], },
    SubjectBinding { variant_unique, binding [LalinBind.Binding], },
    SubjectContinuation {
      variant_unique,
      scope [LalinSource.AnchorId],
      label [LalinTree.BlockLabel],
    },
    SubjectBuiltin { variant_unique, field. name [str], },
    SubjectDiagnostic { variant_unique, diagnostic [LalinEditor.DiagnosticFact], },
    SubjectMissing { variant_unique, reason [str], },
  },
  product. SubjectPick {
    query [LalinEditor.PositionQuery],
    anchors [many [LalinSource.AnchorSpan]],
    subject [LalinEditor.Subject],
  },
  sum. SymbolKind {
    SymFile,
    SymModule,
    SymNamespace,
    SymPackage,
    SymClass,
    SymMethod,
    SymProperty,
    SymField,
    SymConstructor,
    SymEnum,
    SymInterface,
    SymFunction,
    SymVariable,
    SymConstant,
    SymString,
    SymNumber,
    SymBoolean,
    SymArray,
    SymObject,
    SymKey,
    SymNull,
    SymEnumMember,
    SymStruct,
    SymEvent,
    SymOperator,
    SymTypeParameter,
  },
  product. SymbolId { interned, text [str], },
  product. SymbolFact {
    interned,
    field. id [LalinEditor.SymbolId],
    parent [LalinEditor.SymbolId],
    field. name [str],
    kind [LalinEditor.SymbolKind],
    detail [str],
    range [LalinSource.SourceRange],
    selection_range [LalinSource.SourceRange],
    subject [LalinEditor.Subject],
  },
  product. SymbolTree { interned, symbols [many [LalinEditor.SymbolFact]], },
  sum. BindingRole {
    BindingDef,
    BindingUse,
    BindingRead,
    BindingWrite,
    BindingCall,
    BindingTypeUse,
  },
  product. BindingScopeId { interned, text [str], },
  sum. BindingScopeKind {
    BindingScopeDocument,
    BindingScopeIsland,
    BindingScopeFunction,
    BindingScopeRegion,
    BindingScopeExpr,
    BindingScopeControlBlock,
    BindingScopeBranch,
    BindingScopeModule,
    BindingScopeOpaque { variant_unique, field. name [str], },
  },
  product. BindingScopeFact {
    interned,
    field. id [LalinEditor.BindingScopeId],
    parent [LalinEditor.BindingScopeId],
    kind [LalinEditor.BindingScopeKind],
    range [LalinSource.SourceRange],
  },
  product. ScopedBinding {
    interned,
    binding [LalinBind.Binding],
    scope [LalinEditor.BindingScopeId],
    visible_range [LalinSource.SourceRange],
    anchor [LalinSource.AnchorSpan],
  },
  product. BindingUseSite {
    interned,
    anchor [LalinSource.AnchorSpan],
    role [LalinEditor.BindingRole],
    scope [LalinEditor.BindingScopeId],
  },
  sum. BindingResolution {
    BindingResolved {
      variant_unique,
      use [LalinEditor.BindingUseSite],
      binding [LalinEditor.ScopedBinding],
    },
    BindingUnresolved { variant_unique, use [LalinEditor.BindingUseSite], reason [str], },
  },
  product. BindingScopeReport {
    interned,
    scopes [many [LalinEditor.BindingScopeFact]],
    bindings [many [LalinEditor.ScopedBinding]],
    resolutions [many [LalinEditor.BindingResolution]],
  },
  product. BindingFact {
    interned,
    field. id [LalinEditor.SymbolId],
    role [LalinEditor.BindingRole],
    subject [LalinEditor.Subject],
    anchor [LalinSource.AnchorSpan],
  },
  sum. DefinitionResult {
    DefinitionHit {
      variant_unique,
      subject [LalinEditor.Subject],
      ranges [many [LalinSource.SourceRange]],
    },
    DefinitionMiss { variant_unique, reason [str], },
  },
  sum. ReferenceResult {
    ReferenceHit {
      variant_unique,
      subject [LalinEditor.Subject],
      ranges [many [LalinSource.SourceRange]],
    },
    ReferenceMiss { variant_unique, reason [str], },
  },
  sum. DocumentHighlightKind { HighlightText, HighlightRead, HighlightWrite, },
  product. DocumentHighlight {
    interned,
    range [LalinSource.SourceRange],
    kind [LalinEditor.DocumentHighlightKind],
  },
  product. RenameEdit { interned, range [LalinSource.SourceRange], new_text [str], },
  sum. RenameResult {
    RenameOk { variant_unique, edits [many [LalinEditor.RenameEdit]], },
    RenameRejected { variant_unique, reason [str], },
  },
  sum. PrepareRenameResult {
    PrepareRenameOk { variant_unique, range [LalinSource.SourceRange], placeholder [str], },
    PrepareRenameRejected { variant_unique, reason [str], },
  },
  sum. MarkupKind { MarkupPlainText, MarkupMarkdown, },
  sum. HoverInfo {
    HoverInfo {
      variant_unique,
      kind [LalinEditor.MarkupKind],
      field. value [str],
      range [LalinSource.SourceRange],
    },
    HoverMissing { variant_unique, reason [str], },
  },
  sum. CompletionContext {
    CompletionTopLevel,
    CompletionModuleItem,
    CompletionStructField,
    CompletionTypePosition,
    CompletionExprPosition,
    CompletionPlacePosition,
    CompletionExposeSubject,
    CompletionExposeTarget,
    CompletionExposeMode,
    CompletionRegionStatement,
    CompletionContinuationArgs,
    CompletionBuiltinPath,
    CompletionLuaOpaque,
    CompletionInvalid { variant_unique, reason [str], },
  },
  sum. CompletionKind {
    CompletionText,
    CompletionMethod,
    CompletionFunction,
    CompletionConstructor,
    CompletionField,
    CompletionVariable,
    CompletionClass,
    CompletionInterface,
    CompletionModule,
    CompletionProperty,
    CompletionUnit,
    CompletionValue,
    CompletionEnum,
    CompletionKeyword,
    CompletionSnippet,
    CompletionColor,
    CompletionFile,
    CompletionReference,
    CompletionFolder,
    CompletionEnumMember,
    CompletionConstant,
    CompletionStruct,
    CompletionEvent,
    CompletionOperator,
    CompletionTypeParameter,
  },
  sum. CompletionInsertFormat { CompletionInsertPlainText, CompletionInsertSnippet, },
  product. CompletionQuery {
    position [LalinEditor.PositionQuery],
    context [LalinEditor.CompletionContext],
  },
  product. CompletionItem {
    interned,
    label [str],
    kind [LalinEditor.CompletionKind],
    detail [str],
    documentation [str],
    insert_text [str],
    insert_format [LalinEditor.CompletionInsertFormat],
  },
  sum. SignatureContext {
    SignatureCall {
      variant_unique,
      callee [str],
      active_parameter [number],
      callee_range [LalinSource.SourceRange],
    },
    SignatureNoCall { variant_unique, reason [str], },
  },
  product. SignatureParameter { interned, label [str], documentation [str], },
  product. SignatureInfo {
    interned,
    label [str],
    documentation [str],
    params [many [LalinEditor.SignatureParameter]],
  },
  sum. SignatureHelp {
    SignatureHelp {
      variant_unique,
      signatures [many [LalinEditor.SignatureInfo]],
      active_signature [number],
      active_parameter [number],
    },
    SignatureHelpMissing { variant_unique, reason [str], },
  },
  sum. SemanticTokenType {
    TokNamespace,
    TokType,
    TokClass,
    TokEnum,
    TokInterface,
    TokStruct,
    TokTypeParameter,
    TokParameter,
    TokVariable,
    TokProperty,
    TokEnumMember,
    TokEvent,
    TokFunction,
    TokMethod,
    TokMacro,
    TokKeyword,
    TokModifier,
    TokComment,
    TokString,
    TokNumber,
    TokRegexp,
    TokOperator,
    TokDecorator,
  },
  sum. SemanticTokenModifier {
    TokModDeclaration,
    TokModDefinition,
    TokModReadonly,
    TokModStatic,
    TokModDeprecated,
    TokModAbstract,
    TokModAsync,
    TokModModification,
    TokModDocumentation,
    TokModDefaultLibrary,
    TokModMutable,
    TokModExported,
    TokModStorage,
    TokModDiagnostic,
  },
  product. SemanticTokenSpan {
    interned,
    range [LalinSource.SourceRange],
    token_type [LalinEditor.SemanticTokenType],
    modifiers [many [LalinEditor.SemanticTokenModifier]],
  },
  sum. CodeActionKind {
    CodeActionQuickFix,
    CodeActionRefactor,
    CodeActionSource,
    CodeActionOrganizeImports,
  },
  product. TextEdit { interned, range [LalinSource.SourceRange], new_text [str], },
  product. WorkspaceEdit { interned, edits [many [LalinEditor.TextEdit]], },
  product. CodeAction {
    interned,
    title [str],
    kind [LalinEditor.CodeActionKind],
    diagnostics [many [LalinEditor.DiagnosticFact]],
    edit [LalinEditor.WorkspaceEdit],
  },
  product. FoldingRange { interned, range [LalinSource.SourceRange], kind [str], },
  product. SelectionRange {
    interned,
    range [LalinSource.SourceRange],
    parents [many [LalinSource.SourceRange]],
  },
  product. InlayHint { interned, pos [LalinSource.SourcePos], label [str], kind [str], },
}
