local S = require("lalin.schema.dsl")
S.use()

return schema. LalinHost {
  sum. HostIssue {
    HostIssueInvalidName { variant_unique, site [str], field. name [str], },
    HostIssueExpected { variant_unique, site [str], expected [str], actual [str], },
    HostIssueDuplicateField { variant_unique, type_name [str], field_name [str], },
    HostIssueDuplicateType { variant_unique, module_name [str], type_name [str], },
    HostIssueDuplicateDecl { variant_unique, field. name [str], },
    HostIssueDuplicateFunc { variant_unique, module_name [str], func_name [str], },
    HostIssueUnsealedType { variant_unique, module_name [str], type_name [str], },
    HostIssueSealedMutation { variant_unique, type_name [str], },
    HostIssueAlreadySealed { variant_unique, type_name [str], },
    HostIssueUnknownBinding { variant_unique, site [str], field. name [str], },
    HostIssueInvalidEmitFill { variant_unique, fragment_name [str], fill_name [str], },
    HostIssueMissingEmitFill { variant_unique, fragment_name [str], fill_name [str], },
    HostIssueInvalidPackedAlign { variant_unique, type_name [str], align [number], },
    HostIssueBareBoolInBoundaryStruct { variant_unique, type_name [str], field_name [str], },
    HostIssueArgCount { variant_unique, site [str], expected [number], actual [number], },
    HostIssueSpliceExpected { variant_unique, splice_id [str], expected [str], actual [str], },
    HostIssueSpliceEvalError { variant_unique, splice_id [str], message [str], },
    HostIssueLuaStepError { variant_unique, step_id [str], message [str], },
    HostIssueTemplateParseError { variant_unique, template_id [str], message [str], },
    HostIssueRegionComposeMissingExit { variant_unique, fragment_name [str], exit_name [str], },
    HostIssueRegionComposeIncompatibleCont {
      variant_unique,
      fragment_name [str],
      exit_name [str],
      expected [str],
      actual [str],
    },
    HostIssueRegionComposeIncompleteRoute { variant_unique, fragment_name [str], exit_name [str], },
    HostIssueRegionComposeContextMismatch { variant_unique, left [str], right [str], },
  },
  product. HostReport { interned, issues [many [LalinHost.HostIssue]], },
  product. HostLayoutId { interned, key [str], field. name [str], },
  product. HostFieldId { interned, key [str], field. name [str], },
  sum. HostEndian { HostEndianLittle, HostEndianBig, },
  product. HostTargetModel {
    interned,
    pointer_bits [number],
    index_bits [number],
    endian [LalinHost.HostEndian],
  },
  sum. HostLayoutKind {
    HostLayoutStruct,
    HostLayoutSlice,
    HostLayoutArray,
    HostLayoutViewDescriptor,
    HostLayoutOpaque,
  },
  sum. HostOwner {
    HostOwnerBufferView,
    HostOwnerHostSession,
    HostOwnerBorrowed,
    HostOwnerStatic,
    HostOwnerOpaque,
  },
  sum. HostBoolEncoding { HostBoolU8, HostBoolI32, HostBoolNative, },
  sum. HostRepr {
    HostReprC,
    HostReprPacked { variant_unique, align [number], },
    HostReprOpaque { variant_unique, field. name [str], },
  },
  sum. HostFieldAttr {
    HostFieldReadonly,
    HostFieldMutable,
    HostFieldNoalias,
    HostFieldOpaque { variant_unique, field. name [str], },
  },
  sum. HostStorageRep {
    HostStorageSame,
    HostStorageScalar { variant_unique, scalar [LalinCore.Scalar], },
    HostStorageBool {
      variant_unique,
      encoding [LalinHost.HostBoolEncoding],
      scalar [LalinCore.Scalar],
    },
    HostStoragePtr { variant_unique, pointee [LalinType.Type], },
    HostStorageSlice { variant_unique, elem [LalinType.Type], },
    HostStorageView { variant_unique, elem [LalinType.Type], },
    HostStorageOpaque { variant_unique, field. name [str], },
  },
  product. HostStructDecl {
    interned,
    field. id [LalinHost.HostLayoutId],
    field. name [str],
    repr [LalinHost.HostRepr],
    fields [many [LalinHost.HostFieldDecl]],
  },
  product. HostFieldDecl {
    interned,
    field. id [LalinHost.HostFieldId],
    field. name [str],
    expose_ty [LalinType.Type],
    storage [LalinHost.HostStorageRep],
    attrs [many [LalinHost.HostFieldAttr]],
  },
  sum. HostAccessorDecl {
    HostAccessorField { variant_unique, owner_name [str], field. name [str], field_name [str], },
    HostAccessorLua { variant_unique, owner_name [str], field. name [str], lua_symbol [str], },
    HostAccessorLalin {
      variant_unique,
      owner_name [str],
      field. name [str],
      func [LalinTree.Func],
    },
  },
  sum. HostDecl {
    HostDeclStruct { variant_unique, decl [LalinHost.HostStructDecl], },
    HostDeclExpose { variant_unique, decl [LalinHost.HostExposeDecl], },
    HostDeclAccessor { variant_unique, decl [LalinHost.HostAccessorDecl], },
  },
  product. HostDeclSet { interned, field. decls [many [LalinHost.HostDecl]], },
  sum. HostDeclSource {
    HostDeclSourceSet { variant_unique, set [LalinHost.HostDeclSet], },
    HostDeclSourceDecls { variant_unique, field. decls [many [LalinHost.HostDecl]], },
  },
  product. MluaSource { interned, field. name [str], source [str], },
  product. MluaParseResult {
    interned,
    field. decls [LalinHost.HostDeclSet],
    field. module [LalinTree.Module],
    region_frags [many [LalinOpen.RegionFrag]],
    expr_frags [many [LalinOpen.ExprFrag]],
    issues [many [LalinParse.ParseIssue]],
  },
  product. MluaHostPipelineResult {
    interned,
    parsed [LalinHost.MluaParseResult],
    report [LalinHost.HostReport],
    layout_env [LalinHost.HostLayoutEnv],
  },
  product. HostValueId { interned, key [str], pretty [str], },
  sum. HostValueKind {
    HostValueRegionFrag,
    HostValueExprFrag,
    HostValueType,
    HostValueDecl,
    HostValueModule,
    HostValueLua,
  },
  product. HostValueRef {
    interned,
    field. id [LalinHost.HostValueId],
    kind [LalinHost.HostValueKind],
  },
  product. ProtocolRole { interned, role [str], target [str], },
  product. RegionProtocol {
    interned,
    field. name [str],
    roles [many [LalinHost.ProtocolRole]],
  },
  product. FragmentDeps {
    interned,
    region_frags [many [LalinOpen.RegionFrag]],
    expr_frags [many [LalinOpen.ExprFrag]],
  },
  product. RegionFragMeta {
    interned,
    field. name [str],
    frag [LalinOpen.RegionFrag],
    protocol [optional [LalinHost.RegionProtocol]],
    deps [LalinHost.FragmentDeps],
  },
  product. MluaRegionTypeResult {
    interned,
    frag [LalinOpen.RegionFrag],
    issues [many [LalinTree.TypeIssue]],
  },
  product. MluaLoopExpandResult {
    interned,
    entry [LalinTree.EntryControlBlock],
    blocks [many [LalinTree.ControlBlock]],
    issues [many [LalinTree.TypeIssue]],
  },
  sum. MluaLoopSource {
    MluaLoopControlStmt { variant_unique, region [LalinTree.ControlStmtRegion], },
    MluaLoopControlExpr { variant_unique, region [LalinTree.ControlExprRegion], },
  },
  sum. HostFieldRep {
    HostRepScalar { variant_unique, scalar [LalinCore.Scalar], },
    HostRepBool {
      variant_unique,
      encoding [LalinHost.HostBoolEncoding],
      storage [LalinCore.Scalar],
    },
    HostRepPtr { variant_unique, pointee [LalinType.Type], },
    HostRepRef { variant_unique, layout [LalinHost.HostLayoutId], },
    HostRepSlice { variant_unique, elem [LalinHost.HostFieldRep], },
    HostRepView { variant_unique, elem [LalinType.Type], },
    HostRepStruct { variant_unique, layout [LalinHost.HostLayoutId], },
    HostRepOpaque { variant_unique, field. name [str], },
  },
  product. HostFieldLayout {
    interned,
    field. id [LalinHost.HostFieldId],
    field. name [str],
    cfield [str],
    rep [LalinHost.HostFieldRep],
    offset [number],
    size [number],
    align [number],
  },
  product. HostTypeLayout {
    interned,
    field. id [LalinHost.HostLayoutId],
    field. name [str],
    ctype [str],
    kind [LalinHost.HostLayoutKind],
    size [number],
    align [number],
    fields [many [LalinHost.HostFieldLayout]],
  },
  product. HostLayoutEnv { interned, layouts [many [LalinHost.HostTypeLayout]], },
  product. HostCdef { interned, layout [LalinHost.HostLayoutId], source [str], },
  product. HostLuaFfiPlan {
    interned,
    module_name [str],
    cdefs [many [LalinHost.HostCdef]],
    access_plans [many [LalinHost.HostAccessPlan]],
  },
  product. HostTerraPlan {
    interned,
    module_name [str],
    source [str],
    layouts [many [LalinHost.HostTypeLayout]],
    views [many [LalinHost.HostViewDescriptor]],
  },
  product. HostCPlan {
    interned,
    header_name [str],
    source [str],
    layouts [many [LalinHost.HostTypeLayout]],
    views [many [LalinHost.HostViewDescriptor]],
  },
  sum. HostExportAbi {
    HostExportDescriptorPtr { variant_unique, descriptor [LalinHost.HostViewDescriptor], },
    HostExportExpandedScalars { variant_unique, field. ty [LalinType.Type], },
  },
  sum. HostExposeSubject {
    HostExposeType { variant_unique, field. ty [LalinType.Type], },
    HostExposePtr { variant_unique, pointee [LalinType.Type], },
    HostExposeView { variant_unique, elem [LalinType.Type], },
  },
  sum. HostStrideUnit { HostStrideElements, HostStrideBytes, },
  sum. HostViewAbi {
    HostViewAbiContiguous { variant_unique, elem_layout [LalinHost.HostTypeLayout], },
    HostViewAbiStrided {
      variant_unique,
      elem_layout [LalinHost.HostTypeLayout],
      stride_unit [LalinHost.HostStrideUnit],
    },
  },
  product. HostViewDescriptor {
    interned,
    field. id [LalinHost.HostLayoutId],
    field. name [str],
    abi [LalinHost.HostViewAbi],
    descriptor_layout [LalinHost.HostTypeLayout],
  },
  sum. HostExposeTarget { HostExposeLua, HostExposeTerra, HostExposeC, HostExposeLalin, },
  sum. HostMutability { HostReadonly, HostMutable, HostInteriorMutable, },
  sum. HostBoundsPolicy { HostBoundsChecked, HostBoundsUnchecked, },
  sum. HostProxyKind {
    HostProxyPtr,
    HostProxyView,
    HostProxyBufferView,
    HostProxyTypedRecord,
    HostProxyOpaque,
  },
  sum. HostProxyCachePolicy { HostProxyCacheNone, HostProxyCacheLazy, HostProxyCacheEager, },
  sum. HostMaterializePolicy {
    HostMaterializeProjectedFields,
    HostMaterializeFullCopy,
    HostMaterializeBorrowedView,
  },
  sum. HostExposeMode {
    HostExposeProxy {
      variant_unique,
      kind [LalinHost.HostProxyKind],
      cache [LalinHost.HostProxyCachePolicy],
      mutability [LalinHost.HostMutability],
      bounds [LalinHost.HostBoundsPolicy],
    },
    HostExposeEagerTable { variant_unique, policy [LalinHost.HostMaterializePolicy], },
    HostExposeScalar { variant_unique, rep [LalinHost.HostFieldRep], },
    HostExposeOpaque { variant_unique, reason [str], },
  },
  sum. HostExposeAbi {
    HostExposeAbiDefault,
    HostExposeAbiPointer,
    HostExposeAbiDescriptor,
    HostExposeAbiDataLenStride,
    HostExposeAbiExpandedScalars,
    HostExposeAbiOpaque { variant_unique, reason [str], },
  },
  product. HostExposeFacet {
    interned,
    target [LalinHost.HostExposeTarget],
    abi [LalinHost.HostExposeAbi],
    mode [LalinHost.HostExposeMode],
  },
  product. HostExposeDecl {
    interned,
    subject [LalinHost.HostExposeSubject],
    public_name [str],
    facets [many [LalinHost.HostExposeFacet]],
  },
  sum. HostLifetime {
    HostLifetimeStatic,
    HostLifetimeOwned,
    HostLifetimeBorrowed { variant_unique, owner_name [str], },
    HostLifetimeGeneration { variant_unique, session_id [number], generation [number], },
    HostLifetimeExternal { variant_unique, field. name [str], },
  },
  sum. HostAccessSubject {
    HostAccessRecord { variant_unique, layout [LalinHost.HostTypeLayout], },
    HostAccessPtr { variant_unique, layout [LalinHost.HostTypeLayout], },
    HostAccessView { variant_unique, descriptor [LalinHost.HostViewDescriptor], },
  },
  sum. HostAccessKey {
    HostAccessField { variant_unique, field. name [str], },
    HostAccessIndex,
    HostAccessLen,
    HostAccessData,
    HostAccessStride,
    HostAccessMethod { variant_unique, field. name [str], },
    HostAccessPairs,
    HostAccessIpairs,
    HostAccessToTable,
  },
  sum. HostAccessOp {
    HostAccessDirectField { variant_unique, field. field [LalinHost.HostFieldLayout], },
    HostAccessDecodeBool { variant_unique, field. field [LalinHost.HostFieldLayout], },
    HostAccessEncodeBool { variant_unique, field. field [LalinHost.HostFieldLayout], },
    HostAccessViewIndex { variant_unique, descriptor [LalinHost.HostViewDescriptor], },
    HostAccessViewFieldAt {
      variant_unique,
      descriptor [LalinHost.HostViewDescriptor],
      field. field [LalinHost.HostFieldLayout],
    },
    HostAccessViewLen { variant_unique, descriptor [LalinHost.HostViewDescriptor], },
    HostAccessViewData { variant_unique, descriptor [LalinHost.HostViewDescriptor], },
    HostAccessViewStride { variant_unique, descriptor [LalinHost.HostViewDescriptor], },
    HostAccessPointerCast { variant_unique, layout [LalinHost.HostTypeLayout], },
    HostAccessIterateFields { variant_unique, layout [LalinHost.HostLayoutId], },
    HostAccessMaterializeTable { variant_unique, subject [LalinHost.HostAccessSubject], },
    HostAccessReject { variant_unique, reason [str], },
  },
  product. HostAccessEntry {
    interned,
    key [LalinHost.HostAccessKey],
    op [LalinHost.HostAccessOp],
  },
  product. HostAccessPlan {
    interned,
    subject [LalinHost.HostAccessSubject],
    entries [many [LalinHost.HostAccessEntry]],
  },
  product. HostViewPlan {
    interned,
    layout [LalinHost.HostTypeLayout],
    owner [LalinHost.HostOwner],
    expose [LalinHost.HostExposeMode],
    access [LalinHost.HostAccessPlan],
  },
  sum. HostProducerKind {
    HostProducerLowLevelLalin,
    HostProducerLuaFfi,
    HostProducerTypedRecordMemory,
    HostProducerExternal,
  },
  product. HostProducerPlan {
    interned,
    field. name [str],
    kind [LalinHost.HostProducerKind],
    outputs [many [LalinHost.HostTypeLayout]],
  },
  sum. HostLayoutFact {
    HostFactTypeLayout { variant_unique, layout [LalinHost.HostTypeLayout], },
    HostFactCdef { variant_unique, cdef [LalinHost.HostCdef], },
    HostFactField {
      variant_unique,
      owner [LalinHost.HostLayoutId],
      field. field [LalinHost.HostFieldLayout],
    },
    HostFactViewDescriptor { variant_unique, descriptor [LalinHost.HostViewDescriptor], },
    HostFactExpose {
      variant_unique,
      public_name [str],
      layout [LalinHost.HostLayoutId],
      facet [LalinHost.HostExposeFacet],
    },
    HostFactAccessPlan { variant_unique, plan [LalinHost.HostAccessPlan], },
    HostFactViewPlan { variant_unique, plan [LalinHost.HostViewPlan], },
    HostFactLuaFfi { variant_unique, plan [LalinHost.HostLuaFfiPlan], },
    HostFactTerra { variant_unique, plan [LalinHost.HostTerraPlan], },
    HostFactC { variant_unique, plan [LalinHost.HostCPlan], },
    HostFactProducer { variant_unique, plan [LalinHost.HostProducerPlan], },
  },
  product. HostFactSet { interned, facts [many [LalinHost.HostLayoutFact]], },
  sum. HostLayoutReject {
    HostRejectJsonInTypedRecordMemory,
    HostRejectDynamicObjectArena { variant_unique, reason [str], },
    HostRejectUnknownFieldKind { variant_unique, kind [str], },
    HostRejectInvalidLayout { variant_unique, reason [str], },
    HostRejectBareBoolInBoundaryStruct { variant_unique, type_name [str], field_name [str], },
    HostRejectInvalidPackedAlign { variant_unique, type_name [str], align [number], },
    HostRejectConflictingCdef { variant_unique, layout [LalinHost.HostLayoutId], },
  },
}
