local S = require("lalin.schema.dsl")
S.use()

return schema. LalinLink {
  product. LinkPath { interned, text [str], },
  product. LinkSymbol { interned, field. name [str], },
  product. LinkEnv { interned, key [str], field. value [str], },
  sum. LinkPlatform {
    LinkPlatformLinux,
    LinkPlatformMacOS,
    LinkPlatformWindows,
    LinkPlatformWasm,
    LinkPlatformUnknown { variant_unique, field. name [str], },
  },
  sum. LinkArch {
    LinkArchX86_64,
    LinkArchAArch64,
    LinkArchX86,
    LinkArchArm,
    LinkArchWasm32,
    LinkArchUnknown { variant_unique, field. name [str], },
  },
  sum. LinkObjectFormat {
    LinkFormatElf,
    LinkFormatMachO,
    LinkFormatCoff,
    LinkFormatWasm,
    LinkFormatUnknown { variant_unique, field. name [str], },
  },
  sum. LinkRelocationModel { LinkRelocStatic, LinkRelocPic, LinkRelocPie, },
  product. LinkTargetModel {
    interned,
    backend [LalinBack.BackTargetModel],
    platform [LalinLink.LinkPlatform],
    arch [LalinLink.LinkArch],
    object_format [LalinLink.LinkObjectFormat],
    relocation [LalinLink.LinkRelocationModel],
  },
  sum. LinkOutputForm {
    LinkArtifactObject,
    LinkArtifactStaticArchive,
    LinkArtifactSharedLibrary,
    LinkArtifactExecutable,
  },
  sum. LinkToolDriver {
    LinkerSystemCc,
    LinkerCc,
    LinkerClang,
    LinkerGcc,
    LinkerLd,
    LinkerLld,
    LinkerAr,
    LinkerLibtool,
    LinkerCustom { variant_unique, field. name [str], },
  },
  product. LinkTool { interned, driver [LalinLink.LinkToolDriver], path [LalinLink.LinkPath], },
  sum. LinkInput {
    LinkInputObject { variant_unique, path [LalinLink.LinkPath], },
    LinkInputStaticArchive { variant_unique, path [LalinLink.LinkPath], },
    LinkInputSharedLibrary { variant_unique, path [LalinLink.LinkPath], },
    LinkInputSystemLibrary { variant_unique, field. name [str], },
    LinkInputFramework { variant_unique, field. name [str], },
    LinkInputLibrarySearchPath { variant_unique, path [LalinLink.LinkPath], },
    LinkInputLinkerScript { variant_unique, path [LalinLink.LinkPath], },
  },
  sum. LinkExportPolicy {
    LinkExportAll,
    LinkExportNone,
    LinkExportSymbols { variant_unique, symbols [many [LalinLink.LinkSymbol]], },
    LinkExportVersionScript { variant_unique, path [LalinLink.LinkPath], },
  },
  sum. LinkExternPolicy { LinkExternRequireResolved, LinkExternAllowUnresolved, },
  sum. LinkDebugPolicy { LinkDebugDefault, LinkDebugKeep, LinkDebugStrip, },
  sum. LinkRuntimePath {
    LinkRpath { variant_unique, path [LalinLink.LinkPath], },
    LinkRunpath { variant_unique, path [LalinLink.LinkPath], },
  },
  sum. LinkOption {
    LinkOptRuntimePath { variant_unique, path [LalinLink.LinkRuntimePath], },
    LinkOptEntry { variant_unique, symbol [LalinLink.LinkSymbol], },
    LinkOptSoname { variant_unique, field. name [str], },
    LinkOptInstallName { variant_unique, field. name [str], },
    LinkOptOutputImplib { variant_unique, path [LalinLink.LinkPath], },
    LinkOptDebug { variant_unique, policy [LalinLink.LinkDebugPolicy], },
    LinkOptWholeArchiveBegin,
    LinkOptWholeArchiveEnd,
    LinkOptNoDefaultLibs,
    LinkOptStaticLibgcc,
    LinkOptCustomArg { variant_unique, },
  },
  product. LinkPlan {
    interned,
    target [LalinLink.LinkTargetModel],
    output_form [LalinLink.LinkOutputForm],
    tool [LalinLink.LinkTool],
    output [LalinLink.LinkPath],
    inputs [many [LalinLink.LinkInput]],
    exports [LalinLink.LinkExportPolicy],
    externs [LalinLink.LinkExternPolicy],
    options [many [LalinLink.LinkOption]],
  },
  sum. LinkIssue {
    LinkIssueMissingOutput,
    LinkIssueNoInputs,
    LinkIssueMissingInput { variant_unique, path [LalinLink.LinkPath], },
    LinkIssueUnsupportedPlatform {
      variant_unique,
      platform [LalinLink.LinkPlatform],
      output_form [LalinLink.LinkOutputForm],
    },
    LinkIssueUnsupportedInput { variant_unique, input [LalinLink.LinkInput], reason [str], },
    LinkIssueUnsupportedOption { variant_unique, option [LalinLink.LinkOption], reason [str], },
    LinkIssueUnresolvedSymbol { variant_unique, symbol [LalinLink.LinkSymbol], },
    LinkIssueDuplicateSymbol { variant_unique, symbol [LalinLink.LinkSymbol], },
    LinkIssueToolUnavailable { variant_unique, tool [LalinLink.LinkTool], },
    LinkIssueCommandFailed { variant_unique, index [number], code [number], stderr [str], },
  },
  product. LinkReport { interned, issues [many [LalinLink.LinkIssue]], },
  sum. LinkCommand {
    LinkCmdRun {
      variant_unique,
      tool [LalinLink.LinkTool],
      args [many [str]],
      env [many [LalinLink.LinkEnv]],
    },
    LinkCmdWriteFile { variant_unique, path [LalinLink.LinkPath], contents [str], },
    LinkCmdRemoveFile { variant_unique, path [LalinLink.LinkPath], },
  },
  product. LinkCommandPlan {
    interned,
    plan [LalinLink.LinkPlan],
    commands [many [LalinLink.LinkCommand]],
  },
  sum. LinkResult {
    LinkOk { variant_unique, output [LalinLink.LinkPath], },
    LinkFailed { variant_unique, report [LalinLink.LinkReport], },
  },
}
