local S = require("lalin.schema.dsl")
S.use()

return schema. LalinLsp {
  product. ProtocolPosition { line [number], character [number], },
  product. ProtocolRange {
    start [LalinLsp.ProtocolPosition],
    stop [LalinLsp.ProtocolPosition],
  },
  product. Location { uri [LalinSource.DocUri], range [LalinLsp.ProtocolRange], },
  product. InitializeResult {
    interned,
    server_name [str],
    position_encoding [str],
    capabilities_json [str],
  },
  product. DiagnosticContextPayload {
    label [str],
    message [str],
    range [optional [LalinLsp.ProtocolRange]],
  },
  product. DiagnosticPayload {
    range [LalinLsp.ProtocolRange],
    severity [number],
    code [str],
    message [str],
    context [many [LalinLsp.DiagnosticContextPayload]],
  },
  product. DiagnosticReport {
    uri [LalinSource.DocUri],
    version [LalinSource.DocVersion],
    diagnostics [many [LalinLsp.DiagnosticPayload]],
  },
  product. DiagnosticDocumentReport { kind [str], items [many [LalinLsp.DiagnosticPayload]], },
  sum. Hover {
    Hover {
      kind [LalinEditor.MarkupKind],
      field. value [str],
      range [LalinLsp.ProtocolRange],
    },
    HoverNull,
  },
  product. CompletionPayload {
    label [str],
    kind [number],
    detail [str],
    documentation [str],
    insert_text [str],
    insert_text_format [number],
  },
  product. CompletionList { incomplete [bool], items [many [LalinLsp.CompletionPayload]], },
  product. DocumentSymbolPayload {
    field. name [str],
    detail [str],
    kind [number],
    range [LalinLsp.ProtocolRange],
    selection_range [LalinLsp.ProtocolRange],
    children [many [LalinLsp.DocumentSymbolPayload]],
  },
  product. WorkspaceSymbolPayload {
    field. name [str],
    detail [str],
    kind [number],
    location [LalinLsp.Location],
    container_name [str],
  },
  product. SignatureParameterPayload { label [str], documentation [str], },
  product. SignatureInformationPayload {
    label [str],
    documentation [str],
    params [many [LalinLsp.SignatureParameterPayload]],
  },
  product. SignatureHelpPayload {
    signatures [many [LalinLsp.SignatureInformationPayload]],
    active_signature [number],
    active_parameter [number],
  },
  product. SemanticTokens { data [many [number]], },
  product. DocumentHighlightPayload { range [LalinLsp.ProtocolRange], kind [number], },
  product. PrepareRenamePayload { range [LalinLsp.ProtocolRange], placeholder [str], },
  product. TextEditPayload { range [LalinLsp.ProtocolRange], new_text [str], },
  product. WorkspaceEditPayload {
    uri [LalinSource.DocUri],
    edits [many [LalinLsp.TextEditPayload]],
  },
  product. CodeActionPayload {
    title [str],
    kind [str],
    diagnostics [many [LalinLsp.DiagnosticPayload]],
    edits [many [LalinLsp.WorkspaceEditPayload]],
  },
  product. FoldingRangePayload {
    start_line [number],
    start_character [number],
    end_line [number],
    end_character [number],
    kind [str],
  },
  product. SelectionRangePayload {
    range [LalinLsp.ProtocolRange],
    parents [many [LalinLsp.SelectionRangePayload]],
  },
  product. InlayHintPayload { position [LalinLsp.ProtocolPosition], label [str], kind [str], },
  sum. Payload {
    PayloadNull,
    PayloadInitialize { result [LalinLsp.InitializeResult], },
    PayloadDiagnostics { report [LalinLsp.DiagnosticReport], },
    PayloadDiagnosticDocumentReport { report [LalinLsp.DiagnosticDocumentReport], },
    PayloadHover { hover [LalinLsp.Hover], },
    PayloadCompletion { completion [LalinLsp.CompletionList], },
    PayloadDocumentSymbols { symbols [many [LalinLsp.DocumentSymbolPayload]], },
    PayloadWorkspaceSymbols { symbols [many [LalinLsp.WorkspaceSymbolPayload]], },
    PayloadSignatureHelp { help [LalinLsp.SignatureHelpPayload], },
    PayloadLocations { locations [many [LalinLsp.Location]], },
    PayloadDocumentHighlights { highlights [many [LalinLsp.DocumentHighlightPayload]], },
    PayloadPrepareRename { result [LalinLsp.PrepareRenamePayload], },
    PayloadSemanticTokens { tokens [LalinLsp.SemanticTokens], },
    PayloadWorkspaceEdit { edits [many [LalinLsp.WorkspaceEditPayload]], },
    PayloadCodeActions { actions [many [LalinLsp.CodeActionPayload]], },
    PayloadFoldingRanges { ranges [many [LalinLsp.FoldingRangePayload]], },
    PayloadSelectionRanges { ranges [many [LalinLsp.SelectionRangePayload]], },
    PayloadInlayHints { hints [many [LalinLsp.InlayHintPayload]], },
    PayloadError { code [str], message [str], },
  },
}
