local S = require("lalin.schema.dsl")
S.use()

return schema. LalinMem {
  product. MemAccessId { interned, text [str], },
  product. MemObjectId { interned, text [str], },
  product. MemBaseId { interned, text [str], },
  product. MemScopeId { interned, text [str], },
  product. MemProofId { interned, text [str], },
  product. MemLeaseId { interned, text [str], },
  sum. MemAccessKind {
    MemLoad,
    MemStore,
    MemAtomicLoad,
    MemAtomicStore,
    MemAtomicRmw,
    MemAtomicCas,
  },
  sum. MemBase {
    MemBaseValue { variant_unique, field. value [LalinCode.CodeValueId], },
    MemBaseLocal { variant_unique, field. local_id [LalinCode.CodeLocalId], },
    MemBaseGlobal { variant_unique, global [LalinCode.CodeGlobalId], },
    MemBaseData { variant_unique, data [LalinCode.CodeDataId], },
    MemBaseArgument {
      variant_unique,
      field. name [str],
      field. value [LalinCode.CodeValueId],
    },
    MemBaseProjection {
      variant_unique,
      base [LalinMem.MemBase],
      projection [LalinMem.MemProjectionKind],
      byte_offset [number],
    },
    MemBaseUnknown { variant_unique, reason [str], },
  },
  sum. MemObjectKind {
    MemObjectParam,
    MemObjectLocal,
    MemObjectGlobal,
    MemObjectData,
    MemObjectView,
    MemObjectSlice,
    MemObjectByteSpan,
    MemObjectContract,
    MemObjectDerived,
    MemObjectLease,
    MemObjectUnknown,
  },
  sum. MemProjectionKind {
    MemProjectField,
    MemProjectBytes,
    MemProjectPtrOffset,
    MemProjectViewData,
    MemProjectSlice,
    MemProjectWindow,
    MemProjectElement,
    MemProjectUnknown { variant_unique, reason [str], },
  },
  sum. MemObjectProvenance {
    MemProvValue { variant_unique, field. value [LalinCode.CodeValueId], },
    MemProvLocal { variant_unique, field. local_id [LalinCode.CodeLocalId], },
    MemProvGlobal { variant_unique, global [LalinCode.CodeGlobalId], },
    MemProvData { variant_unique, data [LalinCode.CodeDataId], },
    MemProvView {
      variant_unique,
      view [LalinCode.CodeValueId],
      data [LalinCode.CodeValueId],
      len [LalinCode.CodeValueId],
      stride [optional [LalinCode.CodeValueId]],
    },
    MemProvSlice {
      variant_unique,
      slice [LalinCode.CodeValueId],
      data [LalinCode.CodeValueId],
      len [LalinCode.CodeValueId],
    },
    MemProvByteSpan {
      variant_unique,
      span [LalinCode.CodeValueId],
      data [LalinCode.CodeValueId],
      len [LalinCode.CodeValueId],
    },
    MemProvContract { variant_unique, fact [LalinCode.CodeFuncContractFact], },
    MemProvLease { variant_unique, lease [LalinMem.MemLeaseId], },
    MemProvProjection {
      variant_unique,
      parent [LalinMem.MemObjectId],
      projection [LalinMem.MemProjectionKind],
      byte_offset [number],
    },
    MemProvUnknown { variant_unique, reason [str], },
  },
  sum. MemObjectExtent {
    MemExtentUnknown { variant_unique, reason [str], },
    MemExtentElements {
      variant_unique,
      len [LalinCode.CodeValueId],
      elem_ty [LalinCode.CodeType],
      reason [str],
    },
    MemExtentBytes { variant_unique, bytes [number], reason [str], },
    MemExtentContract { variant_unique, fact [LalinCode.CodeFuncContractFact], reason [str], },
  },
  sum. MemObjectStride {
    MemStrideUnknown { variant_unique, reason [str], },
    MemStrideUnit,
    MemStrideConstElems { variant_unique, elems [number], },
    MemStrideValue { variant_unique, field. value [LalinCode.CodeValueId], },
  },
  product. MemObjectFact {
    interned,
    field. id [LalinMem.MemObjectId],
    func [optional [LalinCode.CodeFuncId]],
    kind [LalinMem.MemObjectKind],
    provenance [LalinMem.MemObjectProvenance],
    elem_ty [optional [LalinCode.CodeType]],
    extent [LalinMem.MemObjectExtent],
    stride [LalinMem.MemObjectStride],
  },
  product. MemLeaseGrant {
    interned,
    field. id [LalinMem.MemLeaseId],
    domain [optional [LalinFlow.FlowDomain]],
    lease_value [LalinCode.CodeValueId],
    handle [optional [LalinCode.CodeValueId]],
    object [LalinMem.MemObjectId],
    base [LalinMem.MemBase],
    extent [LalinMem.MemObjectExtent],
    stride [LalinMem.MemObjectStride],
    proof [LalinMem.MemProof],
  },
  sum. MemIndex {
    MemIndexNone,
    MemIndexValue {
      variant_unique,
      field. value [LalinCode.CodeValueId],
      elem_size [number],
      const_offset [number],
    },
    MemIndexInduction {
      variant_unique,
      induction [LalinFlow.FlowInduction],
      elem_size [number],
      const_offset [number],
    },
  },
  sum. MemAccessPattern {
    MemAccessScalar,
    MemAccessContiguous,
    MemAccessStrided { variant_unique, stride_elems [number], },
    MemAccessGather,
    MemAccessScatter,
    MemAccessUnknown,
  },
  sum. MemAlignment {
    MemAlignUnknown,
    MemAlignKnown { variant_unique, bytes [number], },
    MemAlignAtLeast { variant_unique, bytes [number], },
    MemAlignAssumed { variant_unique, bytes [number], proof [LalinMem.MemProof], },
  },
  sum. MemBounds {
    MemBoundsUnknown { variant_unique, reason [str], },
    MemBoundsInObject { variant_unique, reason [str], },
    MemBoundsRange {
      variant_unique,
      start [LalinCode.CodeValueId],
      len [LalinCode.CodeValueId],
      reason [str],
    },
    MemBoundsAssumed { variant_unique, proof [LalinMem.MemProof], },
  },
  sum. MemTrap {
    MemMayTrap,
    MemNonTrapping { variant_unique, reason [str], },
    MemCheckedTrap { variant_unique, reason [str], },
  },
  product. MemAccessFact {
    interned,
    field. id [LalinMem.MemAccessId],
    func [LalinCode.CodeFuncId],
    block [LalinGraph.GraphBlockId],
    inst [optional [LalinCode.CodeInstId]],
    kind [LalinMem.MemAccessKind],
    place [LalinCode.CodePlace],
    access [LalinCode.CodeMemoryAccess],
    base [LalinMem.MemBase],
    index [LalinMem.MemIndex],
    pattern [LalinMem.MemAccessPattern],
    alignment [LalinMem.MemAlignment],
    bounds [LalinMem.MemBounds],
    trap [LalinMem.MemTrap],
  },
  product. MemAccessInterval {
    interned,
    access [LalinMem.MemAccessId],
    object [LalinMem.MemObjectId],
    loop [optional [LalinGraph.GraphLoopId]],
    start [LalinMem.MemIndex],
    length_elems [LalinFlow.FlowBound],
    elem_size [number],
    const_byte_offset [number],
    reason [str],
  },
  sum. MemAccessSafetyFact {
    MemAccessInBounds {
      variant_unique,
      interval [LalinMem.MemAccessInterval],
      proof [LalinMem.MemProof],
    },
    MemAccessNonTrap {
      variant_unique,
      access [LalinMem.MemAccessId],
      proof [LalinMem.MemProof],
    },
    MemAccessMovable {
      variant_unique,
      access [LalinMem.MemAccessId],
      proof [LalinMem.MemProof],
    },
    MemAccessDerefBytes {
      variant_unique,
      access [LalinMem.MemAccessId],
      bytes [number],
      proof [LalinMem.MemProof],
    },
    MemAccessAlignKnown {
      variant_unique,
      access [LalinMem.MemAccessId],
      bytes [number],
      proof [LalinMem.MemProof],
    },
  },
  sum. MemObjectEffectFact {
    MemObjectReadonly {
      variant_unique,
      object [LalinMem.MemObjectId],
      proof [LalinMem.MemProof],
    },
    MemObjectWriteonly {
      variant_unique,
      object [LalinMem.MemObjectId],
      proof [LalinMem.MemProof],
    },
  },
  sum. MemObjectRelation {
    MemObjectsSameLen {
      variant_unique,
      a [LalinMem.MemObjectId],
      b [LalinMem.MemObjectId],
      proof [LalinMem.MemProof],
    },
    MemObjectWindowOf {
      variant_unique,
      window [LalinMem.MemObjectId],
      parent [LalinMem.MemObjectId],
      start [LalinCode.CodeValueId],
      len [LalinCode.CodeValueId],
      proof [LalinMem.MemProof],
    },
    MemObjectSliceOf {
      variant_unique,
      slice [LalinMem.MemObjectId],
      parent [LalinMem.MemObjectId],
      start [LalinCode.CodeValueId],
      len [LalinCode.CodeValueId],
      proof [LalinMem.MemProof],
    },
    MemObjectSameStore {
      variant_unique,
      a [LalinMem.MemObjectId],
      b [LalinMem.MemObjectId],
      proof [LalinMem.MemProof],
    },
  },
  sum. MemAliasFact {
    MemAliasUnknown {
      variant_unique,
      a [LalinMem.MemAccessId],
      b [LalinMem.MemAccessId],
      reason [str],
    },
    MemMayAlias {
      variant_unique,
      a [LalinMem.MemAccessId],
      b [LalinMem.MemAccessId],
      reason [str],
    },
    MemNoAlias {
      variant_unique,
      a [LalinMem.MemAccessId],
      b [LalinMem.MemAccessId],
      proof [LalinMem.MemProof],
    },
    MemSameBaseSameIndexSafe {
      variant_unique,
      a [LalinMem.MemAccessId],
      b [LalinMem.MemAccessId],
      proof [LalinMem.MemProof],
    },
    MemAliasScope {
      variant_unique,
      access [LalinMem.MemAccessId],
      scope [LalinMem.MemScopeId],
    },
  },
  sum. MemDependenceFact {
    MemDependenceUnknown {
      variant_unique,
      before [LalinMem.MemAccessId],
      after [LalinMem.MemAccessId],
      reason [str],
    },
    MemReadReadIndependent {
      variant_unique,
      a [LalinMem.MemAccessId],
      b [LalinMem.MemAccessId],
      reason [str],
    },
    MemNoDependence {
      variant_unique,
      before [LalinMem.MemAccessId],
      after [LalinMem.MemAccessId],
      proof [LalinMem.MemProof],
    },
    MemNoLoopCarriedDependence {
      variant_unique,
      before [LalinMem.MemAccessId],
      after [LalinMem.MemAccessId],
      loop [LalinGraph.GraphLoopId],
      proof [LalinMem.MemProof],
    },
    MemDependenceDistance {
      variant_unique,
      before [LalinMem.MemAccessId],
      after [LalinMem.MemAccessId],
      loop [LalinGraph.GraphLoopId],
      distance_elems [str],
      proof [LalinMem.MemProof],
    },
    MemLoopCarriedDependence {
      variant_unique,
      before [LalinMem.MemAccessId],
      after [LalinMem.MemAccessId],
      loop [LalinGraph.GraphLoopId],
      reason [str],
    },
  },
  sum. MemProof {
    MemProofBounds { variant_unique, reason [str], },
    MemProofAlignment { variant_unique, reason [str], },
    MemProofAlias { variant_unique, fact [LalinMem.MemAliasFact], reason [str], },
    MemProofNoDependence {
      variant_unique,
      accesses [many [LalinMem.MemAccessId]],
      reason [str],
    },
    MemProofContract { variant_unique, fact [LalinCode.CodeFuncContractFact], reason [str], },
    MemProofFlow { variant_unique, loop [LalinGraph.GraphLoopId], reason [str], },
    MemProofObject { variant_unique, object [LalinMem.MemObjectId], reason [str], },
    MemProofInterval { variant_unique, interval [LalinMem.MemAccessInterval], reason [str], },
    MemProofBackend { variant_unique, access [LalinMem.MemAccessId], reason [str], },
  },
  product. MemBackendAccessInfo {
    interned,
    access [LalinMem.MemAccessId],
    trap [LalinMem.MemTrap],
    alignment [LalinMem.MemAlignment],
    bounds [LalinMem.MemBounds],
    deref_bytes [optional [number]],
    movable [bool],
    proofs [many [LalinMem.MemProof]],
  },
  product. MemSemanticFactSet {
    interned,
    field. module [LalinCode.CodeModuleId],
    objects [many [LalinMem.MemObjectFact]],
    leases [many [LalinMem.MemLeaseGrant]],
    accesses [many [LalinMem.MemAccessFact]],
    intervals [many [LalinMem.MemAccessInterval]],
    safety [many [LalinMem.MemAccessSafetyFact]],
    effects [many [LalinMem.MemObjectEffectFact]],
    dependences [many [LalinMem.MemDependenceFact]],
    relations [many [LalinMem.MemObjectRelation]],
    backend_info [many [LalinMem.MemBackendAccessInfo]],
    proofs [many [LalinMem.MemProof]],
  },
  product. MemFactSet {
    interned,
    field. module [LalinCode.CodeModuleId],
    accesses [many [LalinMem.MemAccessFact]],
    aliases [many [LalinMem.MemAliasFact]],
    dependences [many [LalinMem.MemDependenceFact]],
    proofs [many [LalinMem.MemProof]],
  },
}
