local S = require("lalin.schema.dsl")
S.use()

return schema. LalinOpen {
  product. TypeSlot { interned, key [str], pretty_name [str], },
  product. ValueSlot { interned, key [str], pretty_name [str], field. ty [LalinType.Type], },
  product. ExprSlot {
    interned,
    key [str],
    pretty_name [str],
    field. ty [optional [LalinType.Type]],
  },
  product. PlaceSlot {
    interned,
    key [str],
    pretty_name [str],
    field. ty [optional [LalinType.Type]],
  },
  product. DomainSlot { interned, key [str], pretty_name [str], },
  product. RegionSlot { interned, key [str], pretty_name [str], },
  product. ContSlot {
    interned,
    key [str],
    pretty_name [str],
    params [many [LalinTree.BlockParam]],
  },
  product. FuncSlot { interned, key [str], pretty_name [str], fn_ty [LalinType.Type], },
  product. ConstSlot { interned, key [str], pretty_name [str], field. ty [LalinType.Type], },
  product. StaticSlot { interned, key [str], pretty_name [str], field. ty [LalinType.Type], },
  product. TypeDeclSlot { interned, key [str], pretty_name [str], },
  product. ItemsSlot { interned, key [str], pretty_name [str], },
  product. ModuleSlot { interned, key [str], pretty_name [str], },
  product. NameSlot { interned, key [str], pretty_name [str], },
  product. RegionFragSlot { interned, key [str], pretty_name [str], },
  product. ExprFragSlot { interned, key [str], pretty_name [str], },
  sum. RegionFragRef {
    RegionFragRefName { variant_unique, field. name [str], },
    RegionFragRefSlot { variant_unique, slot [LalinOpen.RegionFragSlot], },
  },
  sum. ExprFragRef {
    ExprFragRefName { variant_unique, field. name [str], },
    ExprFragRefSlot { variant_unique, slot [LalinOpen.ExprFragSlot], },
  },
  sum. NameRef {
    NameRefText { variant_unique, text [str], },
    NameRefSlot { variant_unique, slot [LalinOpen.NameSlot], },
  },
  sum. Slot {
    SlotType { variant_unique, slot [LalinOpen.TypeSlot], },
    SlotValue { variant_unique, slot [LalinOpen.ValueSlot], },
    SlotExpr { variant_unique, slot [LalinOpen.ExprSlot], },
    SlotPlace { variant_unique, slot [LalinOpen.PlaceSlot], },
    SlotDomain { variant_unique, slot [LalinOpen.DomainSlot], },
    SlotRegion { variant_unique, slot [LalinOpen.RegionSlot], },
    SlotCont { variant_unique, slot [LalinOpen.ContSlot], },
    SlotFunc { variant_unique, slot [LalinOpen.FuncSlot], },
    SlotConst { variant_unique, slot [LalinOpen.ConstSlot], },
    SlotStatic { variant_unique, slot [LalinOpen.StaticSlot], },
    SlotTypeDecl { variant_unique, slot [LalinOpen.TypeDeclSlot], },
    SlotItems { variant_unique, slot [LalinOpen.ItemsSlot], },
    SlotModule { variant_unique, slot [LalinOpen.ModuleSlot], },
    SlotRegionFrag { variant_unique, slot [LalinOpen.RegionFragSlot], },
    SlotExprFrag { variant_unique, slot [LalinOpen.ExprFragSlot], },
    SlotName { variant_unique, slot [LalinOpen.NameSlot], },
  },
  sum. ModuleNameFacet { ModuleNameOpen, ModuleNameFixed { variant_unique, module_name [str], }, },
  product. OpenParam { interned, key [str], field. name [str], field. ty [LalinType.Type], },
  sum. ValueImport {
    ImportValue { variant_unique, key [str], field. name [str], field. ty [LalinType.Type], },
    ImportGlobalFunc {
      variant_unique,
      key [str],
      module_name [str],
      item_name [str],
      field. ty [LalinType.Type],
    },
    ImportGlobalConst {
      variant_unique,
      key [str],
      module_name [str],
      item_name [str],
      field. ty [LalinType.Type],
    },
    ImportGlobalStatic {
      variant_unique,
      key [str],
      module_name [str],
      item_name [str],
      field. ty [LalinType.Type],
    },
    ImportExtern { variant_unique, key [str], symbol [str], field. ty [LalinType.Type], },
  },
  product. TypeImport { interned, key [str], local_name [str], field. ty [LalinType.Type], },
  product. OpenSet {
    interned,
    value_imports [many [LalinOpen.ValueImport]],
    type_imports [many [LalinOpen.TypeImport]],
    layouts [many [LalinSem.TypeLayout]],
    slots [many [LalinOpen.Slot]],
  },
  sum. SourceBinding {
    SourceParamBinding { variant_unique, param [LalinOpen.OpenParam], },
    SourceValueImportBinding { variant_unique, import [LalinOpen.ValueImport], },
    SourceExprSlotBinding { variant_unique, slot [LalinOpen.ExprSlot], },
    SourceFuncSlotBinding { variant_unique, slot [LalinOpen.FuncSlot], },
    SourceConstSlotBinding { variant_unique, slot [LalinOpen.ConstSlot], },
    SourceStaticSlotBinding { variant_unique, slot [LalinOpen.StaticSlot], },
  },
  product. SourceBindingEntry {
    interned,
    binding [LalinBind.Binding],
    source [LalinOpen.SourceBinding],
  },
  product. SourceTypeEntry {
    interned,
    field. ty [LalinType.Type],
    meta_ty [LalinType.Type],
  },
  product. HostPath { interned, path [LalinCore.Path], },
  sum. HostFacet {
    HostFacetType { variant_unique, slot [LalinOpen.TypeSlot], },
    HostFacetLocalType { variant_unique, local_name [str], },
    HostFacetExpr { variant_unique, slot [LalinOpen.ExprSlot], },
    HostFacetFunc { variant_unique, slot [LalinOpen.ExprSlot], },
    HostFacetRegionFrag { variant_unique, slot [LalinOpen.RegionFragSlot], },
    HostFacetExprFrag { variant_unique, slot [LalinOpen.ExprFragSlot], },
    HostFacetModule { variant_unique, slot [LalinOpen.ModuleSlot], },
  },
  product. HostBinding {
    interned,
    path [LalinOpen.HostPath],
    facets [many [LalinOpen.HostFacet]],
  },
  product. SourceEnv {
    interned,
    module_name [str],
    bindings [many [LalinOpen.SourceBindingEntry]],
    types [many [LalinOpen.SourceTypeEntry]],
    host_bindings [many [LalinOpen.HostBinding]],
  },
  product. FragId { interned, key [str], pretty_name [str], },
  product. UseId { interned, path [str], },
  sum. ContTarget {
    ContTargetLabel { variant_unique, label [LalinTree.BlockLabel], },
    ContTargetSlot { variant_unique, slot [LalinOpen.ContSlot], },
  },
  product. ContBinding { interned, field. name [str], target [LalinOpen.ContTarget], },
  product. ParamBinding {
    interned,
    param [LalinOpen.OpenParam],
    field. value [LalinTree.Expr],
  },
  product. FillSet { interned, bindings [many [LalinOpen.SlotBinding]], },
  product. ExpandEnv {
    interned,
    region_frags [many [LalinOpen.RegionFrag]],
    expr_frags [many [LalinOpen.ExprFrag]],
    fills [LalinOpen.FillSet],
    conts [many [LalinOpen.ContBinding]],
    params [many [LalinOpen.ParamBinding]],
    rebase_prefix [str],
  },
  product. SealParamEntry { interned, param [LalinOpen.OpenParam], index [number], },
  product. SealEnv { interned, module_name [str], params [many [LalinOpen.SealParamEntry]], },
  product. ExprFrag {
    interned,
    field. name [LalinOpen.NameRef],
    params [many [LalinOpen.OpenParam]],
    open [LalinOpen.OpenSet],
    body [LalinTree.Expr],
    result [LalinType.Type],
  },
  product. RegionFrag {
    interned,
    field. name [LalinOpen.NameRef],
    params [many [LalinOpen.OpenParam]],
    conts [many [LalinOpen.ContSlot]],
    open [LalinOpen.OpenSet],
    entry [LalinTree.EntryControlBlock],
    blocks [many [LalinTree.ControlBlock]],
  },
  product. RegionFragDecl {
    interned,
    field. name [LalinOpen.NameRef],
    params [many [LalinOpen.OpenParam]],
    conts [many [LalinOpen.ContSlot]],
  },
  sum. SlotValue {
    SlotValueType { variant_unique, field. ty [LalinType.Type], },
    SlotValueExpr { variant_unique, field. expr [LalinTree.Expr], },
    SlotValueExprs { variant_unique, exprs [many [LalinTree.Expr]], },
    SlotValueTypes { variant_unique, types [many [LalinType.Type]], },
    SlotValueParams { variant_unique, params [many [LalinType.Param]], },
    SlotValueFields { variant_unique, fields [many [LalinType.FieldDecl]], },
    SlotValueVariants { variant_unique, variants [many [LalinType.VariantDecl]], },
    SlotValueBlockParams { variant_unique, params [many [LalinTree.BlockParam]], },
    SlotValueEntryParams { variant_unique, params [many [LalinTree.EntryBlockParam]], },
    SlotValueOpenParams { variant_unique, params [many [LalinOpen.OpenParam]], },
    SlotValueContSlots { variant_unique, conts [many [LalinOpen.ContSlot]], },
    SlotValueControlBlocks { variant_unique, blocks [many [LalinTree.ControlBlock]], },
    SlotValueSwitchStmtArms { variant_unique, arms [many [LalinTree.SwitchStmtArm]], },
    SlotValueSwitchExprArms { variant_unique, arms [many [LalinTree.SwitchExprArm]], },
    SlotValuePlace { variant_unique, place [LalinTree.Place], },
    SlotValueDomain { variant_unique, domain [LalinTree.Domain], },
    SlotValueRegion { variant_unique, body [many [LalinTree.Stmt]], },
    SlotValueCont { variant_unique, label [LalinTree.BlockLabel], },
    SlotValueContSlot { variant_unique, slot [LalinOpen.ContSlot], },
    SlotValueFunc { variant_unique, func [LalinTree.Func], },
    SlotValueConst { variant_unique, c [LalinTree.ConstItem], },
    SlotValueStatic { variant_unique, s [LalinTree.StaticItem], },
    SlotValueTypeDecl { variant_unique, t [LalinTree.TypeDecl], },
    SlotValueItems { variant_unique, items [many [LalinTree.Item]], },
    SlotValueModule { variant_unique, field. module [LalinTree.Module], },
    SlotValueRegionFrag { variant_unique, frag [LalinOpen.RegionFrag], },
    SlotValueExprFrag { variant_unique, frag [LalinOpen.ExprFrag], },
    SlotValueName { variant_unique, text [str], },
  },
  product. SlotBinding {
    interned,
    slot [LalinOpen.Slot],
    field. value [LalinOpen.SlotValue],
  },
  sum. RewriteRule {
    RewriteType { variant_unique, from [LalinType.Type], to [LalinType.Type], },
    RewriteBinding { variant_unique, from [LalinBind.Binding], to [LalinBind.Binding], },
    RewritePlace { variant_unique, from [LalinTree.Place], to [LalinTree.Place], },
    RewriteDomain { variant_unique, from [LalinTree.Domain], to [LalinTree.Domain], },
    RewriteExpr { variant_unique, from [LalinTree.Expr], to [LalinTree.Expr], },
    RewriteStmt { variant_unique, from [LalinTree.Stmt], to [many [LalinTree.Stmt]], },
    RewriteItem { variant_unique, from [LalinTree.Item], to [many [LalinTree.Item]], },
  },
  product. RewriteSet { interned, rules [many [LalinOpen.RewriteRule]], },
  sum. MetaFact {
    MetaFactSlot { variant_unique, slot [LalinOpen.Slot], },
    MetaFactParamUse { variant_unique, param [LalinOpen.OpenParam], },
    MetaFactValueImportUse { variant_unique, import [LalinOpen.ValueImport], },
    MetaFactLocalValue { variant_unique, field. id [str], field. name [str], },
    MetaFactLocalCell { variant_unique, field. id [str], field. name [str], },
    MetaFactBlockParam {
      variant_unique,
      region_id [str],
      block_name [str],
      index [number],
      field. name [str],
    },
    MetaFactEntryBlockParam {
      variant_unique,
      region_id [str],
      block_name [str],
      index [number],
      field. name [str],
    },
    MetaFactGlobalFunc { variant_unique, module_name [str], item_name [str], },
    MetaFactGlobalConst { variant_unique, module_name [str], item_name [str], },
    MetaFactGlobalStatic { variant_unique, module_name [str], item_name [str], },
    MetaFactExtern { variant_unique, symbol [str], },
    MetaFactExprFragUse { variant_unique, use_id [str], },
    MetaFactRegionFragUse { variant_unique, use_id [str], },
    MetaFactRegionFragSlotUse { variant_unique, slot [LalinOpen.RegionFragSlot], },
    MetaFactExprFragSlotUse { variant_unique, slot [LalinOpen.ExprFragSlot], },
    MetaFactModuleUse { variant_unique, use_id [str], },
    MetaFactModuleSlotUse { variant_unique, use_id [str], slot [LalinOpen.ModuleSlot], },
    MetaFactOpenModuleName,
    MetaFactLocalType { variant_unique, sym [LalinCore.TypeSym], },
  },
  product. MetaFactSet { interned, facts [many [LalinOpen.MetaFact]], },
  sum. ValidationIssue {
    IssueOpenSlot { variant_unique, slot [LalinOpen.Slot], },
    IssueUnfilledTypeSlot { variant_unique, slot [LalinOpen.TypeSlot], },
    IssueUnfilledExprSlot { variant_unique, slot [LalinOpen.ExprSlot], },
    IssueUnfilledPlaceSlot { variant_unique, slot [LalinOpen.PlaceSlot], },
    IssueUnfilledDomainSlot { variant_unique, slot [LalinOpen.DomainSlot], },
    IssueUnfilledRegionSlot { variant_unique, slot [LalinOpen.RegionSlot], },
    IssueUnfilledContSlot { variant_unique, slot [LalinOpen.ContSlot], },
    IssueUnfilledFuncSlot { variant_unique, slot [LalinOpen.FuncSlot], },
    IssueUnfilledConstSlot { variant_unique, slot [LalinOpen.ConstSlot], },
    IssueUnfilledStaticSlot { variant_unique, slot [LalinOpen.StaticSlot], },
    IssueUnfilledTypeDeclSlot { variant_unique, slot [LalinOpen.TypeDeclSlot], },
    IssueUnfilledItemsSlot { variant_unique, slot [LalinOpen.ItemsSlot], },
    IssueUnfilledModuleSlot { variant_unique, slot [LalinOpen.ModuleSlot], },
    IssueUnexpandedExprFragUse { variant_unique, use_id [str], },
    IssueUnexpandedRegionFragUse { variant_unique, use_id [str], },
    IssueUnfilledRegionFragSlot { variant_unique, slot [LalinOpen.RegionFragSlot], },
    IssueUnfilledExprFragSlot { variant_unique, slot [LalinOpen.ExprFragSlot], },
    IssueUnfilledNameSlot { variant_unique, slot [LalinOpen.NameSlot], },
    IssueUnexpandedModuleUse { variant_unique, use_id [str], },
    IssueOpenModuleName,
    IssueGenericValueImport { variant_unique, import [LalinOpen.ValueImport], },
  },
  product. ValidationReport { interned, issues [many [LalinOpen.ValidationIssue]], },
}
