local S = require("lalin.schema.dsl")
S.use()

return schema. LalinStencilMachine {
  product. StencilMachineKernelInput {
    interned,
    loop_plan [bool],
    owns_loop [bool],
    planned [bool],
    has_reduce_provider [bool],
    has_store_provider [bool],
    has_skeleton_provider [bool],
    counted_positive [bool],
    result_reduction [bool],
    returns_reduction [bool],
    returns_void [bool],
    stencil_reduce_ready [bool],
    single_store [bool],
    store_dst_base [bool],
    stencil_store_ready [bool],
    stencil_skeleton_ready [bool],
    reject_reason [str],
  },

  sum. StencilMachineKernelSelection {
    StencilMachineKernelReduce,
    StencilMachineKernelStore,
    StencilMachineKernelSkeleton,
    StencilMachineKernelNoPlan { variant_unique, reason [str], },
  },

  sum. StencilMachineSkeletonReduction {
    StencilMachineSkeletonReductionFact { variant_unique, reduction [LalinValue.ReductionFact], },
    StencilMachineSkeletonReducer { variant_unique, reducer [LalinStencil.StencilReducer], },
  },

  product. StencilMachineStoreNDescriptor {
    interned,
    step_num [number],
    producer [LalinStencil.StencilProducer],
    result_ty [LalinCode.CodeType],
    dst [optional [LalinCode.CodeValueId]],
    dst_layout [optional [LalinStencil.StencilAccessLayout]],
    inputs [many [LalinStencilMachine.StencilMachinePointInput]],
    field. expr [optional [LalinStencil.StencilPointExpr]],
    store_mode [optional [LalinStencil.StencilStoreSemantics]],
    tag [str],
    start_expr [optional [LalinLuaJIT.LJExpr]],
    stop_expr [optional [LalinLuaJIT.LJExpr]],
    kernel_schedule [optional [LalinSchedule.SchedulePlanned]],
    schedule [optional [LalinSchedule.ScheduleForm]],
  },

  product. StencilMachineReduceNDescriptor {
    interned,
    step_num [number],
    producer [LalinStencil.StencilProducer],
    result_ty [LalinCode.CodeType],
    item_ty [LalinCode.CodeType],
    init [LalinValue.ValueExpr],
    inputs [many [LalinStencilMachine.StencilMachinePointInput]],
    field. expr [LalinStencil.StencilPointExpr],
    dst_layout [optional [LalinStencil.StencilAccessLayout]],
    tag [str],
    start_expr [optional [LalinLuaJIT.LJExpr]],
    stop_expr [optional [LalinLuaJIT.LJExpr]],
    kernel_schedule [optional [LalinSchedule.SchedulePlanned]],
    schedule [optional [LalinSchedule.ScheduleForm]],
  },

  product. StencilMachineScanArrayDescriptor {
    interned,
    step_num [number],
    producer [LalinStencil.StencilProducer],
    elem_ty [LalinCode.CodeType],
    result_ty [LalinCode.CodeType],
    init [LalinValue.ValueExpr],
    mode [optional [LalinStencil.StencilScanMode]],
    axis [optional [LalinStencil.StencilAxisRef]],
    dst [LalinCode.CodeValueId],
    array [LalinCode.CodeValueId],
    dst_layout [optional [LalinStencil.StencilAccessLayout]],
    array_layout [optional [LalinStencil.StencilAccessLayout]],
    start_expr [LalinLuaJIT.LJExpr],
    stop_expr [LalinLuaJIT.LJExpr],
    kernel_schedule [optional [LalinSchedule.SchedulePlanned]],
    schedule [optional [LalinSchedule.ScheduleForm]],
  },

  product. StencilMachineFindArrayDescriptor {
    interned,
    step_num [number],
    producer [LalinStencil.StencilProducer],
    elem_ty [LalinCode.CodeType],
    array [LalinCode.CodeValueId],
    array_layout [optional [LalinStencil.StencilAccessLayout]],
    start_expr [LalinLuaJIT.LJExpr],
    stop_expr [LalinLuaJIT.LJExpr],
    kernel_schedule [optional [LalinSchedule.SchedulePlanned]],
    schedule [optional [LalinSchedule.ScheduleForm]],
  },

  product. StencilMachinePartitionArrayDescriptor {
    interned,
    step_num [number],
    producer [LalinStencil.StencilProducer],
    elem_ty [LalinCode.CodeType],
    dst [LalinCode.CodeValueId],
    array [LalinCode.CodeValueId],
    dst_layout [optional [LalinStencil.StencilAccessLayout]],
    array_layout [optional [LalinStencil.StencilAccessLayout]],
    start_expr [LalinLuaJIT.LJExpr],
    stop_expr [LalinLuaJIT.LJExpr],
    semantics [optional [LalinStencil.StencilPartitionSemantics]],
    kernel_schedule [optional [LalinSchedule.SchedulePlanned]],
    schedule [optional [LalinSchedule.ScheduleForm]],
  },

  product. StencilMachineCountArrayDescriptor {
    interned,
    step_num [number],
    producer [LalinStencil.StencilProducer],
    elem_ty [LalinCode.CodeType],
    result_ty [LalinCode.CodeType],
    init [LalinValue.ValueExpr],
    array [LalinCode.CodeValueId],
    array_layout [optional [LalinStencil.StencilAccessLayout]],
    start_expr [LalinLuaJIT.LJExpr],
    stop_expr [LalinLuaJIT.LJExpr],
    kernel_schedule [optional [LalinSchedule.SchedulePlanned]],
    schedule [optional [LalinSchedule.ScheduleForm]],
  },

  product. StencilMachineScatterReduceNDescriptor {
    interned,
    step_num [number],
    producer [LalinStencil.StencilProducer],
    result_ty [LalinCode.CodeType],
    item_ty [LalinCode.CodeType],
    index_ty [LalinCode.CodeType],
    dst [LalinCode.CodeValueId],
    index [LalinCode.CodeValueId],
    dst_name [str],
    index_name [str],
    dst_layout [optional [LalinStencil.StencilAccessLayout]],
    index_layout [optional [LalinStencil.StencilAccessLayout]],
    inputs [many [LalinStencilMachine.StencilMachinePointInput]],
    field. expr [LalinStencil.StencilPointExpr],
    conflicts [optional [LalinStencil.StencilScatterReduceConflictSemantics]],
    tag [str],
    start_expr [optional [LalinLuaJIT.LJExpr]],
    stop_expr [optional [LalinLuaJIT.LJExpr]],
    kernel_schedule [optional [LalinSchedule.SchedulePlanned]],
    schedule [optional [LalinSchedule.ScheduleForm]],
  },

  sum. StencilMachineSelected {
    StencilMachineSelectStoreN { variant_unique, descriptor [LalinStencilMachine.StencilMachineStoreNDescriptor], args [many [LalinLuaJIT.LJExpr]], },
    StencilMachineSelectReduceN { variant_unique, descriptor [LalinStencilMachine.StencilMachineReduceNDescriptor], args [many [LalinLuaJIT.LJExpr]], },
    StencilMachineSelectScan {
      variant_unique,
      reduction [LalinValue.ReductionFact],
      descriptor [LalinStencilMachine.StencilMachineScanArrayDescriptor],
      args [many [LalinLuaJIT.LJExpr]],
    },
    StencilMachineSelectFind {
      variant_unique,
      op [LalinStencil.StencilPredicate],
      descriptor [LalinStencilMachine.StencilMachineFindArrayDescriptor],
      args [many [LalinLuaJIT.LJExpr]],
    },
    StencilMachineSelectPartition {
      variant_unique,
      op [LalinStencil.StencilPredicate],
      descriptor [LalinStencilMachine.StencilMachinePartitionArrayDescriptor],
      args [many [LalinLuaJIT.LJExpr]],
    },
    StencilMachineSelectCount {
      variant_unique,
      op [LalinStencil.StencilPredicate],
      descriptor [LalinStencilMachine.StencilMachineCountArrayDescriptor],
      args [many [LalinLuaJIT.LJExpr]],
    },
    StencilMachineSelectScatterReduce { variant_unique, descriptor [LalinStencilMachine.StencilMachineScatterReduceNDescriptor], args [many [LalinLuaJIT.LJExpr]], },
  },

  product. StencilMachineSkeletonPlan {
    interned,
    selection [LalinStencilMachine.StencilMachineSelected],
    reduction [optional [LalinStencilMachine.StencilMachineSkeletonReduction]],
    result_ty [optional [LalinCode.CodeType]],
  },

  product. StencilMachineStorePlan {
    interned,
    selection [LalinStencilMachine.StencilMachineSelected],
  },

  product. StencilMachineReducePlan {
    interned,
    reduction [LalinValue.ReductionFact],
    selection [LalinStencilMachine.StencilMachineSelected],
  },

  sum. StencilMachineSkeletonSelection {
    StencilMachineSkeletonScan { variant_unique, planned [LalinStencilMachine.StencilMachineSkeletonPlan], },
    StencilMachineSkeletonFind { variant_unique, planned [LalinStencilMachine.StencilMachineSkeletonPlan], },
    StencilMachineSkeletonPartition { variant_unique, planned [LalinStencilMachine.StencilMachineSkeletonPlan], },
    StencilMachineSkeletonCopy { variant_unique, planned [LalinStencilMachine.StencilMachineSkeletonPlan], },
    StencilMachineSkeletonScatterReduce { variant_unique, planned [LalinStencilMachine.StencilMachineSkeletonPlan], },
    StencilMachineSkeletonNoPlan { variant_unique, reason [str], },
  },

  sum. StencilMachineSkeletonCandidate {
    StencilMachineSkeletonScanCandidate { variant_unique, planned [LalinStencilMachine.StencilMachineSkeletonPlan], },
    StencilMachineSkeletonFindCandidate { variant_unique, planned [LalinStencilMachine.StencilMachineSkeletonPlan], },
    StencilMachineSkeletonPartitionCandidate { variant_unique, planned [LalinStencilMachine.StencilMachineSkeletonPlan], },
    StencilMachineSkeletonCopyCandidate { variant_unique, planned [LalinStencilMachine.StencilMachineSkeletonPlan], },
    StencilMachineSkeletonScatterReduceCandidate { variant_unique, planned [LalinStencilMachine.StencilMachineSkeletonPlan], },
  },

  product. StencilMachineSkeletonInput {
    interned,
    candidates [many [LalinStencilMachine.StencilMachineSkeletonCandidate]],
    reject_reason [str],
  },

  product. StencilMachinePointInput {
    interned,
    field. name [str],
    lane [optional [LalinKernel.KernelLane]],
    index [optional [LalinValue.ValueExpr]],
    scalar_value [optional [LalinValue.ValueExpr]],
    base [optional [LalinCode.CodeValueId]],
    base_expr [optional [LalinLuaJIT.LJExpr]],
    field. ty [optional [LalinCode.CodeType]],
    elem_ty [optional [LalinCode.CodeType]],
    layout [optional [LalinStencil.StencilAccessLayout]],
    role [optional [LalinStencil.StencilAccessRole]],
    index_primary [bool],
    index_lane [optional [LalinStencilMachine.StencilMachinePointInput]],
    window_offsets [many [LalinStencil.StencilWindowOffset]],
  },

  product. StencilMachinePointExprFacts {
    interned,
    field. expr [LalinStencil.StencilPointExpr],
    inputs [many [LalinStencilMachine.StencilMachinePointInput]],
    result_ty [optional [LalinCode.CodeType]],
    const_int [optional [number]],
  },

  product. StencilMachineExprBinding {
    interned,
    value_id [LalinKernel.KernelValueId],
    kernel_expr [LalinKernel.KernelExpr],
  },

  product. StencilMachineExprBindings {
    interned,
    bindings [many [LalinStencilMachine.StencilMachineExprBinding]],
  },

  product. StencilMachineExprFactInput {
    interned,
    kernel_expr [LalinKernel.KernelExpr],
    bindings [LalinStencilMachine.StencilMachineExprBindings],
    seen [many [LalinKernel.KernelValueId]],
  },

  sum. StencilMachineExprFact {
    StencilMachineExprKernelValue {
      variant_unique,
      field. id [LalinKernel.KernelValueId],
      binding [LalinStencilMachine.StencilMachineExprFact],
    },
    StencilMachineExprLoad {
      variant_unique,
      lane [LalinKernel.KernelLane],
      index [LalinValue.ValueExpr],
    },
    StencilMachineExprFill { variant_unique, field. value [LalinValue.ValueExpr], },
    StencilMachineExprUnary {
      variant_unique,
      op [optional [LalinStencil.StencilUnaryOp]],
      field. value [LalinStencilMachine.StencilMachineExprFact],
      result_ty [LalinCode.CodeType],
    },
    StencilMachineExprCast {
      variant_unique,
      op [LalinCore.MachineCastOp],
      field. value [LalinStencilMachine.StencilMachineExprFact],
      src_ty [LalinCode.CodeType],
      result_ty [LalinCode.CodeType],
    },
    StencilMachineExprBinary {
      variant_unique,
      op [optional [LalinStencil.StencilBinaryOp]],
      lhs [LalinStencilMachine.StencilMachineExprFact],
      rhs [LalinStencilMachine.StencilMachineExprFact],
      result_ty [LalinCode.CodeType],
      int_semantics [optional [LalinCode.CodeIntSemantics]],
    },
    StencilMachineExprCmp {
      variant_unique,
      op [LalinCore.CmpOp],
      lhs [LalinStencilMachine.StencilMachineExprFact],
      rhs [LalinStencilMachine.StencilMachineExprFact],
      result_ty [LalinCode.CodeType],
    },
    StencilMachineExprSelect {
      variant_unique,
      cond [LalinStencilMachine.StencilMachineExprFact],
      then_fact [LalinStencilMachine.StencilMachineExprFact],
      else_fact [LalinStencilMachine.StencilMachineExprFact],
    },
  },

  product. StencilMachineIndexLane {
    interned,
    base [LalinCode.CodeValueId],
    base_expr [LalinLuaJIT.LJExpr],
    elem_ty [LalinCode.CodeType],
    layout [LalinStencil.StencilAccessLayout],
    index_primary [bool],
  },

  product. StencilMachineStoreSelectionFacts {
    interned,
    producer [LalinStencil.StencilProducer],
    step_num [number],
    dst_elem_ty [LalinCode.CodeType],
    dst [LalinCode.CodeValueId],
    dst_expr [LalinLuaJIT.LJExpr],
    dst_layout [optional [LalinStencil.StencilAccessLayout]],
    start [LalinCode.CodeValueId],
    stop [LalinCode.CodeValueId],
    start_expr [LalinLuaJIT.LJExpr],
    stop_expr [LalinLuaJIT.LJExpr],
    store_index_primary [bool],
    store_index_lane [optional [LalinStencilMachine.StencilMachineIndexLane]],
    scatter_conflicts [LalinStencil.StencilScatterConflictSemantics],
    copy_semantics [optional [LalinStencil.StencilCopySemantics]],
    point_facts [LalinStencilMachine.StencilMachinePointExprFacts],
  },

  product. StencilMachineScanSelectionFacts {
    interned,
    producer [LalinStencil.StencilProducer],
    step_num [number],
    dst_elem_ty [LalinCode.CodeType],
    result_ty [LalinCode.CodeType],
    dst [LalinCode.CodeValueId],
    dst_expr [LalinLuaJIT.LJExpr],
    dst_layout [optional [LalinStencil.StencilAccessLayout]],
    start [LalinCode.CodeValueId],
    stop [LalinCode.CodeValueId],
    start_expr [LalinLuaJIT.LJExpr],
    stop_expr [LalinLuaJIT.LJExpr],
    store_index_primary [bool],
    reduction [LalinValue.ReductionFact],
    reduction_op [LalinValue.ReductionOp],
    init [LalinValue.ValueExpr],
    init_expr [LalinLuaJIT.LJExpr],
    mode [LalinStencil.StencilScanMode],
    axis [optional [LalinStencil.StencilAxisRef]],
    point_facts [LalinStencilMachine.StencilMachinePointExprFacts],
  },

  product. StencilMachineFindSelectionFacts {
    interned,
    producer [LalinStencil.StencilProducer],
    step_num [number],
    start [LalinCode.CodeValueId],
    stop [LalinCode.CodeValueId],
    start_expr [LalinLuaJIT.LJExpr],
    stop_expr [LalinLuaJIT.LJExpr],
    pred [LalinStencil.StencilPredicate],
    not_found_minus_one [bool],
    point_facts [LalinStencilMachine.StencilMachinePointExprFacts],
  },

  product. StencilMachinePartitionSelectionFacts {
    interned,
    producer [LalinStencil.StencilProducer],
    step_num [number],
    dst_elem_ty [LalinCode.CodeType],
    dst [LalinCode.CodeValueId],
    dst_expr [LalinLuaJIT.LJExpr],
    dst_layout [optional [LalinStencil.StencilAccessLayout]],
    start [LalinCode.CodeValueId],
    stop [LalinCode.CodeValueId],
    start_expr [LalinLuaJIT.LJExpr],
    stop_expr [LalinLuaJIT.LJExpr],
    store_index_primary [bool],
    pred [LalinStencil.StencilPredicate],
    semantics [LalinStencil.StencilPartitionSemantics],
    point_facts [LalinStencilMachine.StencilMachinePointExprFacts],
  },

  product. StencilMachineReduceSelectionFacts {
    interned,
    producer [LalinStencil.StencilProducer],
    step_num [number],
    result_ty [LalinCode.CodeType],
    init [LalinValue.ValueExpr],
    init_expr [LalinLuaJIT.LJExpr],
    start [LalinCode.CodeValueId],
    stop [LalinCode.CodeValueId],
    start_expr [LalinLuaJIT.LJExpr],
    stop_expr [LalinLuaJIT.LJExpr],
    reduction_op [LalinValue.ReductionOp],
    reduction_add [bool],
    init_zero [bool],
    result_i32 [bool],
    point_facts [LalinStencilMachine.StencilMachinePointExprFacts],
  },

  product. StencilMachineStorePlanInput {
    interned,
    planned [bool],
    returns_void [bool],
    counted_positive [bool],
    single_store [bool],
    dst_base_present [bool],
    point_facts_ready [bool],
    selection [LalinStencilMachine.StencilMachineStoreSelectionFacts],
  },

  product. StencilMachineReducePlanInput {
    interned,
    planned [bool],
    result_reduction [bool],
    returns_reduction [bool],
    counted_positive [bool],
    point_facts_ready [bool],
    reduction [LalinValue.ReductionFact],
    selection [LalinStencilMachine.StencilMachineReduceSelectionFacts],
  },
}
