local S = require("lalin.schema.dsl")
S.use()

return schema. LalinStencil {
  product. StencilInstanceId { interned, text [str], },
  product. StencilSymbolId { interned, text [str], },
  product. StencilProviderId { interned, text [str], },
  sum. StencilProvider {
    StencilProviderC,
    StencilProviderLuaTrace,
    StencilProviderNamed {
      variant_unique,
      field. id [LalinStencil.StencilProviderId],
      field. name [str],
    },
  },
  sum. StencilSinkVocab { StencilStore, StencilReduce, StencilScan, StencilScatterReduce, },
  sum. StencilUnaryOp {
    StencilUnaryIdentity,
    StencilUnaryNeg,
    StencilUnaryBitNot,
    StencilUnaryBoolNot,
  },
  sum. StencilBinaryOp {
    StencilBinaryAdd,
    StencilBinarySub,
    StencilBinaryMul,
    StencilBinaryDiv,
    StencilBinaryMod,
    StencilBinaryAnd,
    StencilBinaryOr,
    StencilBinaryXor,
    StencilBinaryShl,
    StencilBinaryLShr,
    StencilBinaryAShr,
    StencilBinaryMin,
    StencilBinaryMax,
  },
  sum. StencilPredicate {
    StencilPredNonZero,
    StencilPredCompareConst {
      variant_unique,
      cmp [LalinCore.CmpOp],
      operand_ty [LalinCode.CodeType],
      field. value [LalinValue.ValueExpr],
    },
    StencilPredRange {
      variant_unique,
      operand_ty [LalinCode.CodeType],
      lower_cmp [LalinCore.CmpOp],
      lower [LalinValue.ValueExpr],
      upper_cmp [LalinCore.CmpOp],
      upper [LalinValue.ValueExpr],
    },
    StencilPredAnd { variant_unique, terms [many [LalinStencil.StencilPredicate]], },
    StencilPredOr { variant_unique, terms [many [LalinStencil.StencilPredicate]], },
    StencilPredNot { variant_unique, term [LalinStencil.StencilPredicate], },
    StencilPredIsNaN { variant_unique, operand_ty [LalinCode.CodeType], },
    StencilPredIsInf { variant_unique, operand_ty [LalinCode.CodeType], },
    StencilPredIsFinite { variant_unique, operand_ty [LalinCode.CodeType], },
  },
  sum. StencilScanMode { StencilScanInclusive, StencilScanExclusive, },
  sum. StencilCopySemantics {
    StencilCopyNoOverlap,
    StencilCopyMayOverlapForward,
    StencilCopyMayOverlapBackward,
    StencilCopyMemMove,
  },
  sum. StencilPartitionSemantics { StencilPartitionStable, StencilPartitionUnstable, },
  sum. StencilScatterConflictSemantics {
    StencilScatterUniqueIndices,
    StencilScatterLastWriteWins,
    StencilScatterConflictUndefined,
  },
  sum. StencilScatterReduceConflictSemantics {
    StencilScatterReduceSequential,
    StencilScatterReduceUniqueIndices,
    StencilScatterReduceAtomic { variant_unique, ordering [LalinCore.AtomicOrdering], },
    StencilScatterReducePrivatized,
  },
  sum. StencilProducerOrder { StencilProducerForward, StencilProducerBackward, },
  product. StencilProducerAxis {
    interned,
    index_ty [LalinCode.CodeType],
    start [optional [LalinValue.ValueExpr]],
    stop [optional [LalinValue.ValueExpr]],
    step [number],
    order [LalinStencil.StencilProducerOrder],
    index_name [optional [str]],
  },
  product. StencilAxisRef { interned, index [number], },
  sum. StencilWindowBoundary {
    StencilWindowBoundaryReject,
    StencilWindowBoundaryClamp,
    StencilWindowBoundaryWrap,
    StencilWindowBoundaryZero,
  },
  product. StencilWindowAxis {
    interned,
    before [number],
    after [number],
    boundary [LalinStencil.StencilWindowBoundary],
  },
  product. StencilWindowOffset {
    interned,
    axis [LalinStencil.StencilAxisRef],
    offset [number],
  },
  product. StencilAffineAxisTerm {
    interned,
    axis [LalinStencil.StencilAxisRef],
    coeff [LalinValue.ValueExpr],
  },
  sum. StencilProducerShape {
    StencilProduceRange1D {
      variant_unique,
      index_ty [LalinCode.CodeType],
      start [optional [LalinValue.ValueExpr]],
      stop [optional [LalinValue.ValueExpr]],
      step [number],
      order [LalinStencil.StencilProducerOrder],
    },
    StencilProduceRangeND { variant_unique, axes [many [LalinStencil.StencilProducerAxis]], },
    StencilProduceWindowND {
      variant_unique,
      axes [many [LalinStencil.StencilProducerAxis]],
      windows [many [LalinStencil.StencilWindowAxis]],
    },
    StencilProduceTiledND {
      variant_unique,
      axes [many [LalinStencil.StencilProducerAxis]],
      tile_sizes [many [number]],
    },
  },
  product. StencilProducer {
    interned,
    origin [optional [LalinFlow.FlowDomain]],
    shape [LalinStencil.StencilProducerShape],
  },
  sum. StencilProducerFactOrigin {
    StencilProducerCheckerDerived,
    StencilProducerAuthorAsserted { variant_unique, reason [str], },
    StencilProducerFrontendFact { variant_unique, reason [str], },
  },
  product. StencilProducerFact {
    interned,
    domain [LalinFlow.FlowDomain],
    producer [LalinStencil.StencilProducer],
    proofs [many [LalinKernel.KernelProof]],
    origin [LalinStencil.StencilProducerFactOrigin],
  },
  product. StencilProducerFactSet {
    interned,
    field. module [LalinCode.CodeModuleId],
    facts [many [LalinStencil.StencilProducerFact]],
  },
  sum. StencilAccessRole {
    StencilAccessRead,
    StencilAccessWrite,
    StencilAccessIndex,
    StencilAccessReadWrite,
    StencilAccessReduce,
    StencilAccessControlResult,
  },
  sum. StencilAccessLayout {
    StencilLayoutScalar { variant_unique, field. value [optional [LalinValue.ValueExpr]], },
    StencilLayoutContiguous { variant_unique, stride [number], },
    StencilLayoutIndexed {
      variant_unique,
      parent [LalinStencil.StencilAccessLayout],
      index [LalinStencil.StencilAccessRef],
      index_ty [LalinCode.CodeType],
      stride [number],
    },
    StencilLayoutAffine1D {
      variant_unique,
      parent [LalinStencil.StencilAccessLayout],
      scale [number],
      offset [optional [LalinValue.ValueExpr]],
    },
    StencilLayoutAffineND {
      variant_unique,
      parent [LalinStencil.StencilAccessLayout],
      terms [many [LalinStencil.StencilAffineAxisTerm]],
      offset [optional [LalinValue.ValueExpr]],
    },
    StencilLayoutFieldProjection {
      variant_unique,
      parent [LalinStencil.StencilAccessLayout],
      record_ty [LalinCode.CodeType],
      field_name [str],
      field_offset [number],
    },
    StencilLayoutSoAComponent {
      variant_unique,
      parent [LalinStencil.StencilAccessLayout],
      record_ty [LalinCode.CodeType],
      field_name [str],
      component_index [number],
    },
    StencilLayoutSliceDescriptor {
      variant_unique,
      slice [LalinCode.CodeValueId],
      data [LalinCode.CodeValueId],
      len [LalinCode.CodeValueId],
    },
    StencilLayoutByteSpanDescriptor {
      variant_unique,
      span [LalinCode.CodeValueId],
      data [LalinCode.CodeValueId],
      len [LalinCode.CodeValueId],
    },
    StencilLayoutViewDescriptor {
      variant_unique,
      view [LalinCode.CodeValueId],
      data [LalinCode.CodeValueId],
      len [LalinCode.CodeValueId],
      stride [LalinCode.CodeValueId],
      stride_const [optional [number]],
    },
  },
  product. StencilAccess {
    interned,
    field. name [str],
    role [LalinStencil.StencilAccessRole],
    ty [LalinCode.CodeType],
    layout [LalinStencil.StencilAccessLayout],
  },
  product. StencilAccessRef { interned, field. name [str], },
  sum. StencilPointExpr {
    StencilPointInput { variant_unique, access [LalinStencil.StencilAccessRef], },
    StencilPointWindowInput {
      variant_unique,
      access [LalinStencil.StencilAccessRef],
      offsets [many [LalinStencil.StencilWindowOffset]],
    },
    StencilPointConst {
      variant_unique,
      field. value [LalinValue.ValueExpr],
      ty [LalinCode.CodeType],
    },
    StencilPointUnary {
      variant_unique,
      op [LalinStencil.StencilUnaryOp],
      field. arg [LalinStencil.StencilPointExpr],
      result_ty [optional [LalinCode.CodeType]],
      int_semantics [optional [LalinCode.CodeIntSemantics]],
      float_mode [optional [LalinCode.CodeFloatMode]],
    },
    StencilPointBinary {
      variant_unique,
      op [LalinStencil.StencilBinaryOp],
      left [LalinStencil.StencilPointExpr],
      right [LalinStencil.StencilPointExpr],
      result_ty [optional [LalinCode.CodeType]],
      int_semantics [optional [LalinCode.CodeIntSemantics]],
      float_mode [optional [LalinCode.CodeFloatMode]],
    },
    StencilPointCast {
      variant_unique,
      op [LalinCore.MachineCastOp],
      field. arg [LalinStencil.StencilPointExpr],
      from [LalinCode.CodeType],
      to [LalinCode.CodeType],
    },
    StencilPointPredicate {
      variant_unique,
      pred [LalinStencil.StencilPredicate],
      field. arg [LalinStencil.StencilPointExpr],
      result_ty [LalinCode.CodeType],
    },
    StencilPointCompare {
      variant_unique,
      cmp [LalinCore.CmpOp],
      left [LalinStencil.StencilPointExpr],
      right [LalinStencil.StencilPointExpr],
      result_ty [LalinCode.CodeType],
    },
    StencilPointSelect {
      variant_unique,
      pred [LalinStencil.StencilPredicate],
      cond [LalinStencil.StencilPointExpr],
      then_expr [LalinStencil.StencilPointExpr],
      else_expr [LalinStencil.StencilPointExpr],
      result_ty [LalinCode.CodeType],
    },
  },
  product. StencilReducer {
    interned,
    reduction [LalinValue.ReductionOp],
    result_ty [LalinCode.CodeType],
    field. identity [LalinValue.ValueExpr],
    int_semantics [optional [LalinCode.CodeIntSemantics]],
    float_mode [optional [LalinCode.CodeFloatMode]],
  },
  sum. StencilStoreSemantics {
    StencilStoreElementwise,
    StencilStoreCopy { variant_unique, semantics [LalinStencil.StencilCopySemantics], },
    StencilStoreScatter {
      variant_unique,
      conflicts [LalinStencil.StencilScatterConflictSemantics],
    },
    StencilStorePartition { variant_unique, semantics [LalinStencil.StencilPartitionSemantics], },
  },
  sum. StencilReductionSemantics {
    StencilReduceFold { variant_unique, reducer [LalinStencil.StencilReducer], },
    StencilReduceCount { variant_unique, pred [LalinStencil.StencilPredicate], },
    StencilReduceFind {
      variant_unique,
      pred [LalinStencil.StencilPredicate],
      not_found [LalinValue.ValueExpr],
    },
  },
  sum. StencilReduceScope {
    StencilReduceScopeDomain,
    StencilReduceScopeAxes {
      variant_unique,
      axes [many [LalinStencil.StencilAxisRef]],
      dst [LalinStencil.StencilAccessRef],
    },
    StencilReduceScopeWindow {
      variant_unique,
      axes [many [LalinStencil.StencilAxisRef]],
      dst [LalinStencil.StencilAccessRef],
    },
  },
  sum. StencilCompiler { StencilCompilerGcc, StencilCompilerClang, StencilCompilerSystemC, },
  sum. StencilOptLevel {
    StencilOptO0,
    StencilOptO1,
    StencilOptO2,
    StencilOptO3,
    StencilOptOs,
    StencilOptOz,
  },
  sum. StencilMachineTarget {
    StencilMachineNative,
    StencilMachineBaseline,
    StencilMachineNamed { variant_unique, field. name [str], },
  },
  product. StencilCompilerPolicy {
    interned,
    compiler [LalinStencil.StencilCompiler],
    opt_level [LalinStencil.StencilOptLevel],
    machine [LalinStencil.StencilMachineTarget],
    flags [many [str]],
  },
  sum. StencilAliasFact { StencilAliasUnknown, StencilAliasNoAlias, StencilAliasMayAlias, },
  sum. StencilAlignmentFact {
    StencilAlignmentUnknown,
    StencilAlignmentKnown { variant_unique, bytes [number], },
  },
  sum. StencilTripCountFact {
    StencilTripCountUnknown,
    StencilTripCountDynamic,
    StencilTripCountMultipleOf { variant_unique, factor [number], },
    StencilTripCountExact { variant_unique, count [number], },
  },
  sum. StencilProofOrigin {
    StencilProofCheckerDerived,
    StencilProofBoundaryContract,
    StencilProofAuthorAsserted,
  },
  sum. StencilProofRequirement {
    StencilProofNoAlias {
      variant_unique,
      left [LalinStencil.StencilAccessRef],
      right [LalinStencil.StencilAccessRef],
    },
    StencilProofAlignment {
      variant_unique,
      access [LalinStencil.StencilAccessRef],
      alignment [LalinStencil.StencilAlignmentFact],
    },
    StencilProofTripCount { variant_unique, trip_count [LalinStencil.StencilTripCountFact], },
    StencilProofReductionReassociable,
    StencilProofUnitStride { variant_unique, access [LalinStencil.StencilAccessRef], },
  },
  product. StencilProofObligation {
    interned,
    requirement [LalinStencil.StencilProofRequirement],
    origin [LalinStencil.StencilProofOrigin],
    proof [optional [LalinKernel.KernelProof]],
  },
  product. StencilAccessVectorFact {
    interned,
    access [LalinStencil.StencilAccessRef],
    alignment [LalinStencil.StencilAlignmentFact],
    readonly [bool],
    unit_stride [bool],
  },
  product. StencilAccessAliasFact {
    interned,
    left [LalinStencil.StencilAccessRef],
    right [LalinStencil.StencilAccessRef],
    relation [LalinStencil.StencilAliasFact],
  },
  product. StencilArithmeticVectorFact {
    interned,
    reduction_reassociable [bool],
    int_semantics [optional [LalinCode.CodeIntSemantics]],
    float_mode [optional [LalinCode.CodeFloatMode]],
  },
  product. StencilVectorizationFacts {
    interned,
    access_facts [many [LalinStencil.StencilAccessVectorFact]],
    alias_facts [many [LalinStencil.StencilAccessAliasFact]],
    trip_count [LalinStencil.StencilTripCountFact],
    arithmetic [LalinStencil.StencilArithmeticVectorFact],
    proof_obligations [many [LalinStencil.StencilProofObligation]],
  },
  sum. StencilVectorFeatureRequirement {
    StencilVectorFeatureNative,
    StencilVectorFeatureSSE2,
    StencilVectorFeatureAVX2,
    StencilVectorFeatureAVX512F,
    StencilVectorFeatureNamed { variant_unique, field. name [str], },
  },
  sum. StencilLanePolicy {
    StencilLaneFromTarget,
    StencilLaneNative,
    StencilLaneFixed { variant_unique, lanes [number], },
  },
  sum. StencilVectorAlignmentPolicy {
    StencilVectorAlignmentUnknown,
    StencilVectorUnaligned,
    StencilVectorAligned { variant_unique, bytes [number], },
  },
  sum. StencilVectorTailPolicy {
    StencilVectorScalarTail,
    StencilVectorMaskTail,
    StencilVectorOverreadProvenSafe,
  },
  sum. StencilVectorReductionStrategy {
    StencilVectorReductionTree,
    StencilVectorReductionHorizontal,
    StencilVectorReductionScalarFinish,
  },
  sum. StencilVectorCompilerPolicy {
    StencilVectorCompilerGccAutovec,
    StencilVectorCompilerHandwritten,
    StencilVectorCompilerCompiledStencil,
  },
  sum. StencilMaterializer {
    StencilMaterializerResidualBC,
    StencilMaterializerResidualMC,
    StencilMaterializerNamed { variant_unique, field. name [str], },
  },
  sum. StencilRealizedScheduleEvidence {
    StencilRealizedByConstruction { variant_unique, reason [str], },
    StencilRealizedCompilerRemark { variant_unique, remark [str], },
    StencilRealizedDisassembly { variant_unique, classification [str], },
  },
  sum. StencilRealizedSchedule {
    StencilRealizedScalar {
      variant_unique,
      materializer [LalinStencil.StencilMaterializer],
      evidence [many [LalinStencil.StencilRealizedScheduleEvidence]],
    },
    StencilRealizedUnrolled {
      variant_unique,
      factor [number],
      materializer [LalinStencil.StencilMaterializer],
      evidence [many [LalinStencil.StencilRealizedScheduleEvidence]],
    },
    StencilRealizedVector {
      variant_unique,
      feature [LalinStencil.StencilVectorFeatureRequirement],
      lanes [number],
      unroll [number],
      interleave [number],
      tail [LalinStencil.StencilVectorTailPolicy],
      materializer [LalinStencil.StencilMaterializer],
      evidence [many [LalinStencil.StencilRealizedScheduleEvidence]],
    },
  },
  sum. StencilScheduleReject {
    StencilScheduleRejectUnsupportedFeature {
      variant_unique,
      feature [LalinStencil.StencilVectorFeatureRequirement],
      compiler [LalinStencil.StencilCompilerPolicy],
      reason [str],
    },
    StencilScheduleRejectIllegalLaneCount { variant_unique, lanes [number], reason [str], },
    StencilScheduleRejectUnprovableTail {
      variant_unique,
      tail [LalinStencil.StencilVectorTailPolicy],
      reason [str],
    },
    StencilScheduleRejectUnprovableAlignment {
      variant_unique,
      access [optional [LalinStencil.StencilAccessRef]],
      alignment [LalinStencil.StencilVectorAlignmentPolicy],
      reason [str],
    },
    StencilScheduleRejectCompilerMatrix {
      variant_unique,
      compiler [LalinStencil.StencilCompilerPolicy],
      vector_compiler [LalinStencil.StencilVectorCompilerPolicy],
      reason [str],
    },
    StencilScheduleRejectRequestedRealizedMismatch {
      variant_unique,
      requested [LalinStencil.StencilSchedule],
      realized [optional [LalinStencil.StencilRealizedSchedule]],
      reason [str],
    },
  },
  sum. StencilSchedule {
    StencilScheduleScalar { variant_unique, compiler [LalinStencil.StencilCompilerPolicy], },
    StencilScheduleAutoVector {
      variant_unique,
      compiler [LalinStencil.StencilCompilerPolicy],
      facts [LalinStencil.StencilVectorizationFacts],
    },
    StencilScheduleUnrolled {
      variant_unique,
      factor [number],
      compiler [LalinStencil.StencilCompilerPolicy],
      facts [LalinStencil.StencilVectorizationFacts],
    },
    StencilScheduleVector {
      variant_unique,
      feature [LalinStencil.StencilVectorFeatureRequirement],
      lane_policy [LalinStencil.StencilLanePolicy],
      required_alignment [LalinStencil.StencilVectorAlignmentPolicy],
      tail [LalinStencil.StencilVectorTailPolicy],
      reduction [LalinStencil.StencilVectorReductionStrategy],
      vector_compiler [LalinStencil.StencilVectorCompilerPolicy],
      vector_unroll [number],
      interleave [number],
      compiler [LalinStencil.StencilCompilerPolicy],
      facts [LalinStencil.StencilVectorizationFacts],
    },
  },
  sum. StencilBody {
    StencilBodyPoint {
      variant_unique,
      field. expr [LalinStencil.StencilPointExpr],
    },
  },
  sum. StencilSink {
    StencilSinkStore {
      variant_unique,
      dst [LalinStencil.StencilAccessRef],
      semantics [LalinStencil.StencilStoreSemantics],
    },
    StencilSinkReduce {
      variant_unique,
      result_ty [LalinCode.CodeType],
      scope [LalinStencil.StencilReduceScope],
      semantics [LalinStencil.StencilReductionSemantics],
    },
    StencilSinkScan {
      variant_unique,
      dst [LalinStencil.StencilAccessRef],
      axis [LalinStencil.StencilAxisRef],
      reducer [LalinStencil.StencilReducer],
      mode [LalinStencil.StencilScanMode],
      result_ty [LalinCode.CodeType],
    },
    StencilSinkScatterReduce {
      variant_unique,
      dst [LalinStencil.StencilAccessRef],
      reducer [LalinStencil.StencilReducer],
      conflicts [LalinStencil.StencilScatterReduceConflictSemantics],
      result_ty [LalinCode.CodeType],
    },
  },
  product. StencilDescriptor {
    interned,
    producer [LalinStencil.StencilProducer],
    accesses [many [LalinStencil.StencilAccess]],
    body [LalinStencil.StencilBody],
    sink [LalinStencil.StencilSink],
  },
  product. StencilAbi {
    interned,
    params [many [LalinCode.CodeType]],
    result [optional [LalinCode.CodeType]],
  },
  product. StencilInstance {
    interned,
    field. id [LalinStencil.StencilInstanceId],
    descriptor [LalinStencil.StencilDescriptor],
    schedule [LalinStencil.StencilSchedule],
    abi [LalinStencil.StencilAbi],
    proofs [many [LalinKernel.KernelProof]],
  },
  sum. StencilReject {
    StencilRejectUnsupportedVocab {
      variant_unique,
      vocab [LalinStencil.StencilSinkVocab],
      reason [str],
    },
    StencilRejectUnsupportedType { variant_unique, ty [LalinCode.CodeType], reason [str], },
    StencilRejectUnsupportedReduction {
      variant_unique,
      reduction [LalinValue.ReductionOp],
      reason [str],
    },
    StencilRejectUnsupportedProducer {
      variant_unique,
      producer [LalinStencil.StencilProducer],
      reason [str],
    },
    StencilRejectUnsupportedSink {
      variant_unique,
      sink [LalinStencil.StencilSink],
      reason [str],
    },
    StencilRejectMissingProof {
      variant_unique,
      requirement [LalinStencil.StencilProofRequirement],
    },
    StencilRejectProvider { variant_unique, provider [LalinStencil.StencilProvider], reason [str], },
    StencilRejectSchedule { variant_unique, reject [LalinStencil.StencilScheduleReject], },
  },
  sum. StencilScheduleCandidateStatus {
    StencilScheduleCandidateSelected,
    StencilScheduleCandidateViable,
    StencilScheduleCandidateRejected,
  },
  sum. StencilScheduleSelectionOrigin {
    StencilScheduleSelectionHeuristic,
    StencilScheduleSelectionCostModel,
    StencilScheduleSelectionAuthorAnnotated,
    StencilScheduleSelectionFallback,
  },
  product. StencilScheduleCandidate {
    interned,
    field. name [str],
    schedule [optional [LalinStencil.StencilSchedule]],
    cost [number],
    status [LalinStencil.StencilScheduleCandidateStatus],
    rejects [many [LalinStencil.StencilScheduleReject]],
    reason [str],
  },
  product. StencilScheduleSelectionProvenance {
    interned,
    origin [LalinStencil.StencilScheduleSelectionOrigin],
    winner [str],
    candidates [many [LalinStencil.StencilScheduleCandidate]],
    reason [str],
  },
  sum. StencilSelection {
    StencilSelected {
      variant_unique,
      instance [LalinStencil.StencilInstance],
      provenance [LalinStencil.StencilScheduleSelectionProvenance],
    },
    StencilNoSelection {
      variant_unique,
      vocab [LalinStencil.StencilSinkVocab],
      rejects [many [LalinStencil.StencilReject]],
      provenance [LalinStencil.StencilScheduleSelectionProvenance],
    },
  },
  product. StencilPlanEntry {
    interned,
    kernel [LalinKernel.KernelId],
    selection [LalinStencil.StencilSelection],
  },
  product. StencilArtifactFingerprint { interned, text [str], },
  sum. StencilArtifactDiagnosticSeverity {
    StencilArtifactDiagnosticNote,
    StencilArtifactDiagnosticWarning,
    StencilArtifactDiagnosticRemark,
  },
  product. StencilArtifactDiagnostic {
    interned,
    severity [LalinStencil.StencilArtifactDiagnosticSeverity],
    source [str],
    message [str],
  },
  product. StencilArtifact {
    interned,
    instance [LalinStencil.StencilInstance],
    provider [LalinStencil.StencilProvider],
    symbol [LalinStencil.StencilSymbolId],
    c_signature [str],
    fingerprint [LalinStencil.StencilArtifactFingerprint],
    realized [optional [LalinStencil.StencilRealizedSchedule]],
    diagnostics [many [LalinStencil.StencilArtifactDiagnostic]],
    schedule_rejects [many [LalinStencil.StencilScheduleReject]],
  },
  product. StencilProducerExecutionAxis {
    interned,
    index_ty [LalinCode.CodeType],
    step [number],
    start_param [str],
    stop_param [str],
  },
  sum. StencilProducerExecution {
    StencilProducerExecRange1D {
      variant_unique,
      stride [number],
      order [LalinStencil.StencilProducerOrder],
    },
    StencilProducerExecRangeND {
      variant_unique,
      rank [number],
      axes [many [LalinStencil.StencilProducerExecutionAxis]],
    },
    StencilProducerExecWindowND {
      variant_unique,
      rank [number],
      axes [many [LalinStencil.StencilProducerExecutionAxis]],
      windows [many [LalinStencil.StencilWindowAxis]],
    },
    StencilProducerExecTiledND {
      variant_unique,
      rank [number],
      axes [many [LalinStencil.StencilProducerExecutionAxis]],
      tile_sizes [many [number]],
    },
  },
  sum. StencilReduceExecutionScope {
    StencilReduceExecDomain,
    StencilReduceExecAxes {
      variant_unique,
      dst_name [str],
      axes [many [LalinStencil.StencilAxisRef]],
    },
    StencilReduceExecWindow {
      variant_unique,
      dst_name [str],
      axes [many [LalinStencil.StencilAxisRef]],
    },
  },
  sum. StencilReduceInitMode {
    StencilReduceInitExternal,
    StencilReduceInitIdentity,
  },
  sum. StencilArtifactShape {
    StencilArtifactStoreN {
      variant_unique,
      inputs [many [LalinStencil.StencilAccess]],
      result_ty [LalinCode.CodeType],
      dst_name [str],
      store_mode [LalinStencil.StencilStoreSemantics],
      field. expr [LalinStencil.StencilPointExpr],
      producer [LalinStencil.StencilProducerExecution],
      stride [optional [number]],
    },
    StencilArtifactReduceN {
      variant_unique,
      inputs [many [LalinStencil.StencilAccess]],
      field. expr [LalinStencil.StencilPointExpr],
      item_ty [LalinCode.CodeType],
      result_ty [LalinCode.CodeType],
      reduction [LalinValue.ReductionOp],
      int_semantics [optional [LalinCode.CodeIntSemantics]],
      float_mode [optional [LalinCode.CodeFloatMode]],
      field. identity [LalinValue.ValueExpr],
      scope [LalinStencil.StencilReduceScope],
      reduce_scope [LalinStencil.StencilReduceExecutionScope],
      init_mode [LalinStencil.StencilReduceInitMode],
      producer [LalinStencil.StencilProducerExecution],
      stride [optional [number]],
    },
    StencilArtifactFindN {
      variant_unique,
      inputs [many [LalinStencil.StencilAccess]],
      field. expr [LalinStencil.StencilPointExpr],
      result_ty [LalinCode.CodeType],
      pred [LalinStencil.StencilPredicate],
      not_found [LalinValue.ValueExpr],
      producer [LalinStencil.StencilProducerExecution],
      stride [optional [number]],
    },
    StencilArtifactPartitionN {
      variant_unique,
      inputs [many [LalinStencil.StencilAccess]],
      field. expr [LalinStencil.StencilPointExpr],
      result_ty [LalinCode.CodeType],
      dst_name [str],
      mode [LalinStencil.StencilPartitionSemantics],
      producer [LalinStencil.StencilProducerExecution],
      stride [optional [number]],
    },
    StencilArtifactScanN {
      variant_unique,
      inputs [many [LalinStencil.StencilAccess]],
      field. expr [LalinStencil.StencilPointExpr],
      result_ty [LalinCode.CodeType],
      reduction [LalinValue.ReductionOp],
      int_semantics [optional [LalinCode.CodeIntSemantics]],
      float_mode [optional [LalinCode.CodeFloatMode]],
      field. identity [LalinValue.ValueExpr],
      mode [LalinStencil.StencilScanMode],
      axis [LalinStencil.StencilAxisRef],
      producer [LalinStencil.StencilProducerExecution],
      stride [optional [number]],
    },
    StencilArtifactScatterReduceN {
      variant_unique,
      inputs [many [LalinStencil.StencilAccess]],
      field. expr [LalinStencil.StencilPointExpr],
      result_ty [LalinCode.CodeType],
      reduction [LalinValue.ReductionOp],
      int_semantics [optional [LalinCode.CodeIntSemantics]],
      float_mode [optional [LalinCode.CodeFloatMode]],
      field. identity [LalinValue.ValueExpr],
      dst_name [str],
      conflicts [LalinStencil.StencilScatterReduceConflictSemantics],
      producer [LalinStencil.StencilProducerExecution],
      stride [optional [number]],
    },
  },
  product. StencilMetastencilId { interned, text [str], },
  product. StencilMetastencilNodeId { interned, text [str], },
  product. StencilMetastencilWireId { interned, text [str], },
  sum. StencilMetastencilPortFlow {
    StencilMetastencilPortInput,
    StencilMetastencilPortOutput,
    StencilMetastencilPortInOut,
  },
  product. StencilMetastencilPortRef {
    interned,
    node [optional [LalinStencil.StencilMetastencilNodeId]],
    field. name [str],
  },
  product. StencilMetastencilPort {
    interned,
    field. ref [LalinStencil.StencilMetastencilPortRef],
    flow [LalinStencil.StencilMetastencilPortFlow],
    ty [LalinCode.CodeType],
    access [optional [LalinStencil.StencilAccessRef]],
  },
  product. StencilMetastencilNode {
    interned,
    field. id [LalinStencil.StencilMetastencilNodeId],
    artifact [LalinStencil.StencilArtifact],
    inputs [many [LalinStencil.StencilMetastencilPort]],
    outputs [many [LalinStencil.StencilMetastencilPort]],
  },
  product. StencilMetastencilWire {
    interned,
    field. id [LalinStencil.StencilMetastencilWireId],
    src [LalinStencil.StencilMetastencilPortRef],
    dst [LalinStencil.StencilMetastencilPortRef],
    ty [LalinCode.CodeType],
  },
  sum. StencilFusionLegalityFact {
    StencilFusionSameProducer {
      variant_unique,
      left [LalinStencil.StencilMetastencilNodeId],
      right [LalinStencil.StencilMetastencilNodeId],
    },
    StencilFusionCompatibleAbi {
      variant_unique,
      wire [LalinStencil.StencilMetastencilWireId],
      ty [LalinCode.CodeType],
    },
    StencilFusionNoIntermediateMaterialization { variant_unique, wire [LalinStencil.StencilMetastencilWireId], },
    StencilFusionAliasRelation {
      variant_unique,
      left [LalinStencil.StencilMetastencilPortRef],
      right [LalinStencil.StencilMetastencilPortRef],
      relation [LalinStencil.StencilAliasFact],
    },
    StencilFusionProofObligation { variant_unique, obligation [LalinStencil.StencilProofObligation], },
  },
  sum. StencilFusionReject {
    StencilFusionRejectTypeMismatch {
      variant_unique,
      wire [LalinStencil.StencilMetastencilWireId],
      src_ty [LalinCode.CodeType],
      dst_ty [LalinCode.CodeType],
    },
    StencilFusionRejectMissingPort {
      variant_unique,
      port [LalinStencil.StencilMetastencilPortRef],
    },
    StencilFusionRejectCycle {
      variant_unique,
      wire [LalinStencil.StencilMetastencilWireId],
      reason [str],
    },
    StencilFusionRejectAliasConflict {
      variant_unique,
      left [LalinStencil.StencilMetastencilPortRef],
      right [LalinStencil.StencilMetastencilPortRef],
      relation [LalinStencil.StencilAliasFact],
      reason [str],
    },
    StencilFusionRejectMissingProof {
      variant_unique,
      requirement [LalinStencil.StencilProofRequirement],
    },
    StencilFusionRejectUnsupportedComposition {
      variant_unique,
      left [optional [LalinStencil.StencilMetastencilNodeId]],
      right [optional [LalinStencil.StencilMetastencilNodeId]],
      reason [str],
    },
  },
  product. StencilFusionLegality {
    interned,
    facts [many [LalinStencil.StencilFusionLegalityFact]],
    proof_obligations [many [LalinStencil.StencilProofObligation]],
    rejects [many [LalinStencil.StencilFusionReject]],
  },
  product. StencilMetastencilFingerprint { interned, text [str], },
  product. StencilMetastencilDescriptor {
    interned,
    field. id [LalinStencil.StencilMetastencilId],
    external_ports [many [LalinStencil.StencilMetastencilPort]],
    nodes [many [LalinStencil.StencilMetastencilNode]],
    wires [many [LalinStencil.StencilMetastencilWire]],
    abi [LalinStencil.StencilAbi],
    legality [LalinStencil.StencilFusionLegality],
  },
  sum. StencilMetastencilCandidateStatus {
    StencilMetastencilCandidateSelected,
    StencilMetastencilCandidateViable,
    StencilMetastencilCandidateRejected,
  },
  product. StencilMetastencilCandidate {
    interned,
    descriptor [LalinStencil.StencilMetastencilDescriptor],
    fingerprint [LalinStencil.StencilMetastencilFingerprint],
    covered_nodes [number],
    cost [number],
    status [LalinStencil.StencilMetastencilCandidateStatus],
    rejects [many [LalinStencil.StencilFusionReject]],
    reason [str],
  },
  product. StencilMetastencilCoverProvenance {
    interned,
    origin [LalinStencil.StencilScheduleSelectionOrigin],
    winner [str],
    candidates [many [LalinStencil.StencilMetastencilCandidate]],
    reason [str],
  },
  sum. StencilMetastencilCoverSelection {
    StencilMetastencilCoverSelected {
      variant_unique,
      candidate [LalinStencil.StencilMetastencilCandidate],
      provenance [LalinStencil.StencilMetastencilCoverProvenance],
    },
    StencilMetastencilNoCover {
      variant_unique,
      rejects [many [LalinStencil.StencilFusionReject]],
      provenance [LalinStencil.StencilMetastencilCoverProvenance],
    },
  },
  product. StencilModulePlan {
    interned,
    field. module [LalinCode.CodeModuleId],
    kernel [LalinKernel.KernelModulePlan],
    selections [many [LalinStencil.StencilPlanEntry]],
  },
}
