local S = require("lalin.schema.dsl")
S.use()

return schema. LalinTree {
  sum. ExprHeader {
    ExprSurface,
    ExprTyped { variant_unique, field. ty [LalinType.Type], },
  },
  sum. PlaceHeader {
    PlaceSurface,
    PlaceTyped { variant_unique, field. ty [LalinType.Type], },
  },
  sum. StmtHeader {
    StmtSurface,
    StmtFlow { variant_unique, flow [LalinSem.FlowClass], },
  },
  product. FieldInit {
    interned,
    field. name [str],
    field. value [LalinTree.Expr],
    offset [number],
  },
  product. VariantBind { interned, field. name [str], field. ty [LalinType.Type], },
  sum. SwitchKey {
    SwitchKeyInt { variant_unique, raw [str], },
    SwitchKeyBool { variant_unique, field. value [bool], },
    SwitchKeyName { variant_unique, field. name [str], },
    SwitchKeyExpr { variant_unique, field. expr [LalinTree.Expr], },
  },
  sum. SwitchKeyDecision {
    SwitchConstKeys { variant_unique, keys [many [LalinTree.SwitchKey]], },
    SwitchExprKeys { variant_unique, keys [many [LalinTree.SwitchKey]], },
    SwitchCompareFallback { variant_unique, keys [many [LalinTree.SwitchKey]], reason [str], },
  },
  product. SwitchStmtArm { interned, key [LalinTree.SwitchKey], body [many [LalinTree.Stmt]], },
  product. SwitchExprArm {
    interned,
    key [LalinTree.SwitchKey],
    body [many [LalinTree.Stmt]],
    result [LalinTree.Expr],
  },
  product. SwitchVariantStmtArm {
    interned,
    variant_name [str],
    binds [many [LalinTree.VariantBind]],
    body [many [LalinTree.Stmt]],
  },
  product. SwitchVariantExprArm {
    interned,
    variant_name [str],
    binds [many [LalinTree.VariantBind]],
    body [many [LalinTree.Stmt]],
    result [LalinTree.Expr],
  },
  sum. View {
    ViewFromExpr { variant_unique, base [LalinTree.Expr], elem [LalinType.Type], },
    ViewContiguous {
      variant_unique,
      data [LalinTree.Expr],
      elem [LalinType.Type],
      len [LalinTree.Expr],
    },
    ViewStrided {
      variant_unique,
      data [LalinTree.Expr],
      elem [LalinType.Type],
      len [LalinTree.Expr],
      stride [LalinTree.Expr],
    },
    ViewRestrided {
      variant_unique,
      base [LalinTree.View],
      elem [LalinType.Type],
      stride [LalinTree.Expr],
    },
    ViewWindow {
      variant_unique,
      base [LalinTree.View],
      start [LalinTree.Expr],
      len [LalinTree.Expr],
    },
    ViewRowBase {
      variant_unique,
      base [LalinTree.View],
      row_offset [LalinTree.Expr],
      elem [LalinType.Type],
    },
    ViewInterleaved {
      variant_unique,
      data [LalinTree.Expr],
      elem [LalinType.Type],
      len [LalinTree.Expr],
      stride [LalinTree.Expr],
      lane [LalinTree.Expr],
    },
    ViewInterleavedView {
      variant_unique,
      base [LalinTree.View],
      elem [LalinType.Type],
      stride [LalinTree.Expr],
      lane [LalinTree.Expr],
    },
  },
  sum. Domain {
    DomainRange { variant_unique, stop [LalinTree.Expr], },
    DomainRange2 { variant_unique, start [LalinTree.Expr], stop [LalinTree.Expr], },
    DomainZipEqValues { variant_unique, values [many [LalinTree.Expr]], },
    DomainValue { variant_unique, field. value [LalinTree.Expr], },
    DomainView { variant_unique, view [LalinTree.View], },
    DomainZipEqViews { variant_unique, views [many [LalinTree.View]], },
  },
  sum. IndexBase {
    IndexBaseExpr { variant_unique, base [LalinTree.Expr], },
    IndexBasePlace { variant_unique, base [LalinTree.Place], elem [LalinType.Type], },
    IndexBaseView { variant_unique, view [LalinTree.View], },
  },
  sum. Place {
    PlaceRef {
      variant_unique,
      h [LalinTree.PlaceHeader],
      field. ref [LalinBind.ValueRef],
    },
    PlaceDeref { variant_unique, h [LalinTree.PlaceHeader], base [LalinTree.Expr], },
    PlaceDot {
      variant_unique,
      h [LalinTree.PlaceHeader],
      base [LalinTree.Place],
      field. name [str],
    },
    PlaceField {
      variant_unique,
      h [LalinTree.PlaceHeader],
      base [LalinTree.Place],
      field. field [LalinSem.FieldRef],
    },
    PlaceIndex {
      variant_unique,
      h [LalinTree.PlaceHeader],
      base [LalinTree.IndexBase],
      index [LalinTree.Expr],
    },
  },
  product. RegionCont { interned, key [str], field. name [str], params [many [LalinTree.BlockParam]], },
  product. BlockLabel { interned, field. name [str], },
  product. BlockParam { interned, field. name [str], field. ty [LalinType.Type], },
  product. EntryBlockParam {
    interned,
    field. name [str],
    field. ty [LalinType.Type],
    init [LalinTree.Expr],
  },
  product. JumpArg { interned, field. name [str], field. value [LalinTree.Expr], },
  sum. FuncContract {
    ContractBounds { variant_unique, base [LalinTree.Expr], len [LalinTree.Expr], },
    ContractWindowBounds {
      variant_unique,
      base [LalinTree.Expr],
      base_len [LalinTree.Expr],
      start [LalinTree.Expr],
      len [LalinTree.Expr],
    },
    ContractDisjoint { variant_unique, a [LalinTree.Expr], b [LalinTree.Expr], },
    ContractSameLen { variant_unique, a [LalinTree.Expr], b [LalinTree.Expr], },
    ContractSoAComponent {
      variant_unique,
      base [LalinTree.Expr],
      record_ty [LalinType.Type],
      field_name [str],
      component_index [number],
    },
    ContractNoAlias { variant_unique, base [LalinTree.Expr], },
    ContractReadonly { variant_unique, base [LalinTree.Expr], },
    ContractWriteonly { variant_unique, base [LalinTree.Expr], },
    ContractInvalidate { variant_unique, base [LalinTree.Expr], },
    ContractPreserve { variant_unique, base [LalinTree.Expr], },
  },
  sum. ContractFact {
    ContractFactBounds {
      variant_unique,
      base [LalinBind.Binding],
      len [LalinBind.Binding],
    },
    ContractFactWindowBounds {
      variant_unique,
      base [LalinBind.Binding],
      base_len [LalinTree.Expr],
      start [LalinTree.Expr],
      len [LalinTree.Expr],
    },
    ContractFactDisjoint { variant_unique, a [LalinBind.Binding], b [LalinBind.Binding], },
    ContractFactSameLen { variant_unique, a [LalinBind.Binding], b [LalinBind.Binding], },
    ContractFactSoAComponent {
      variant_unique,
      base [LalinBind.Binding],
      record_ty [LalinType.Type],
      field_name [str],
      component_index [number],
    },
    ContractFactNoAlias { variant_unique, base [LalinBind.Binding], },
    ContractFactReadonly { variant_unique, base [LalinBind.Binding], },
    ContractFactWriteonly { variant_unique, base [LalinBind.Binding], },
    ContractFactInvalidate { variant_unique, base [LalinBind.Binding], },
    ContractFactPreserve { variant_unique, base [LalinBind.Binding], },
    ContractFactRejected { variant_unique, issue [LalinTree.TypeIssue], },
  },
  product. ContractFactSet { interned, facts [many [LalinTree.ContractFact]], },
  product. EntryControlBlock {
    interned,
    label [LalinTree.BlockLabel],
    params [many [LalinTree.EntryBlockParam]],
    body [many [LalinTree.Stmt]],
  },
  product. ControlBlock {
    interned,
    label [LalinTree.BlockLabel],
    params [many [LalinTree.BlockParam]],
    body [many [LalinTree.Stmt]],
  },
  product. ControlStmtRegion {
    interned,
    region_id [str],
    entry [LalinTree.EntryControlBlock],
    blocks [many [LalinTree.ControlBlock]],
  },
  product. ControlExprRegion {
    interned,
    region_id [str],
    result_ty [LalinType.Type],
    entry [LalinTree.EntryControlBlock],
    blocks [many [LalinTree.ControlBlock]],
  },
  product. Region {
    interned,
    field. name [str],
    params [many [LalinType.Param]],
    conts [many [LalinTree.RegionCont]],
    entry [LalinTree.EntryControlBlock],
    blocks [many [LalinTree.ControlBlock]],
  },
  sum. ControlFact {
    ControlFactEntryBlock { variant_unique, region_id [str], label [LalinTree.BlockLabel], },
    ControlFactBlock { variant_unique, region_id [str], label [LalinTree.BlockLabel], },
    ControlFactEntryParam {
      variant_unique,
      region_id [str],
      label [LalinTree.BlockLabel],
      index [number],
      field. name [str],
      field. ty [LalinType.Type],
    },
    ControlFactBlockParam {
      variant_unique,
      region_id [str],
      label [LalinTree.BlockLabel],
      index [number],
      field. name [str],
      field. ty [LalinType.Type],
    },
    ControlFactJump {
      variant_unique,
      region_id [str],
      from_label [LalinTree.BlockLabel],
      to_label [LalinTree.BlockLabel],
    },
    ControlFactJumpArg {
      variant_unique,
      region_id [str],
      from_label [LalinTree.BlockLabel],
      to_label [LalinTree.BlockLabel],
      field. name [str],
      field. ty [LalinType.Type],
    },
    ControlFactYieldVoid { variant_unique, region_id [str], from_label [LalinTree.BlockLabel], },
    ControlFactYieldValue {
      variant_unique,
      region_id [str],
      from_label [LalinTree.BlockLabel],
      field. ty [LalinType.Type],
    },
    ControlFactReturn { variant_unique, region_id [str], from_label [LalinTree.BlockLabel], },
    ControlFactBackedge {
      variant_unique,
      region_id [str],
      from_label [LalinTree.BlockLabel],
      to_label [LalinTree.BlockLabel],
    },
    ControlFactVariantSwitch {
      variant_unique,
      region_id [str],
      from_label [LalinTree.BlockLabel],
      switch_on [str],
      arms [many [LalinTree.ControlVariantArmFact]],
      default_label [LalinTree.BlockLabel],
    },
  },
  product. ControlVariantArmFact {
    interned,
    variant_name [str],
    tag_value [number],
    label [LalinTree.BlockLabel],
    binds [many [LalinTree.BlockParam]],
  },
  product. ControlFactSet { interned, facts [many [LalinTree.ControlFact]], },
  sum. ControlReject {
    ControlRejectDuplicateLabel {
      variant_unique,
      region_id [str],
      label [LalinTree.BlockLabel],
    },
    ControlRejectMissingLabel { variant_unique, region_id [str], label [LalinTree.BlockLabel], },
    ControlRejectMissingJumpArg {
      variant_unique,
      region_id [str],
      label [LalinTree.BlockLabel],
      field. name [str],
    },
    ControlRejectExtraJumpArg {
      variant_unique,
      region_id [str],
      label [LalinTree.BlockLabel],
      field. name [str],
    },
    ControlRejectDuplicateJumpArg {
      variant_unique,
      region_id [str],
      label [LalinTree.BlockLabel],
      field. name [str],
    },
    ControlRejectJumpType {
      variant_unique,
      region_id [str],
      label [LalinTree.BlockLabel],
      field. name [str],
      expected [LalinType.Type],
      actual [LalinType.Type],
    },
    ControlRejectYieldOutsideRegion { variant_unique, reason [str], },
    ControlRejectYieldType {
      variant_unique,
      region_id [str],
      expected [LalinType.Type],
      actual [LalinType.Type],
    },
    ControlRejectUnterminatedBlock {
      variant_unique,
      region_id [str],
      label [LalinTree.BlockLabel],
    },
    ControlRejectIrreducible { variant_unique, region_id [str], reason [str], },
    ControlRejectUnknownVariant { variant_unique, region_id [str], variant_name [str], },
  },
  product. ControlRejectExplanation {
    interned,
    code [str],
    primary [str],
    notes [many [str]],
    suggestions [many [str]],
  },
  sum. ControlDecision {
    ControlDecisionReducible {
      variant_unique,
      region_id [str],
      facts [many [LalinTree.ControlFact]],
    },
    ControlDecisionIrreducible {
      variant_unique,
      region_id [str],
      reject [LalinTree.ControlReject],
    },
  },
  sum. Expr {
    ExprLit { variant_unique, h [LalinTree.ExprHeader], field. value [LalinCore.Literal], },
    ExprRef { variant_unique, h [LalinTree.ExprHeader], field. ref [LalinBind.ValueRef], },
    ExprDot {
      variant_unique,
      h [LalinTree.ExprHeader],
      base [LalinTree.Expr],
      field. name [str],
    },
    ExprUnary {
      variant_unique,
      h [LalinTree.ExprHeader],
      op [LalinCore.UnaryOp],
      field. value [LalinTree.Expr],
    },
    ExprBinary {
      variant_unique,
      h [LalinTree.ExprHeader],
      op [LalinCore.BinaryOp],
      lhs [LalinTree.Expr],
      rhs [LalinTree.Expr],
    },
    ExprCompare {
      variant_unique,
      h [LalinTree.ExprHeader],
      op [LalinCore.CmpOp],
      lhs [LalinTree.Expr],
      rhs [LalinTree.Expr],
    },
    ExprLogic {
      variant_unique,
      h [LalinTree.ExprHeader],
      op [LalinCore.LogicOp],
      lhs [LalinTree.Expr],
      rhs [LalinTree.Expr],
    },
    ExprCast {
      variant_unique,
      h [LalinTree.ExprHeader],
      op [LalinCore.SurfaceCastOp],
      field. ty [LalinType.Type],
      field. value [LalinTree.Expr],
    },
    ExprMachineCast {
      variant_unique,
      h [LalinTree.ExprHeader],
      op [LalinCore.MachineCastOp],
      field. ty [LalinType.Type],
      field. value [LalinTree.Expr],
    },
    ExprIntrinsic {
      variant_unique,
      h [LalinTree.ExprHeader],
      op [LalinCore.Intrinsic],
      args [many [LalinTree.Expr]],
    },
    ExprAddrOf { variant_unique, h [LalinTree.ExprHeader], place [LalinTree.Place], },
    ExprDeref { variant_unique, h [LalinTree.ExprHeader], field. value [LalinTree.Expr], },
    ExprCall {
      variant_unique,
      h [LalinTree.ExprHeader],
      callee [LalinTree.Expr],
      args [many [LalinTree.Expr]],
    },
    ExprLen { variant_unique, h [LalinTree.ExprHeader], field. value [LalinTree.Expr], },
    ExprField {
      variant_unique,
      h [LalinTree.ExprHeader],
      base [LalinTree.Expr],
      field. field [LalinSem.FieldRef],
    },
    ExprIndex {
      variant_unique,
      h [LalinTree.ExprHeader],
      base [LalinTree.IndexBase],
      index [LalinTree.Expr],
    },
    ExprAgg {
      variant_unique,
      h [LalinTree.ExprHeader],
      field. ty [LalinType.Type],
      fields [many [LalinTree.FieldInit]],
    },
    ExprArray {
      variant_unique,
      h [LalinTree.ExprHeader],
      elem_ty [LalinType.Type],
      elems [many [LalinTree.Expr]],
    },
    ExprIf {
      variant_unique,
      h [LalinTree.ExprHeader],
      cond [LalinTree.Expr],
      then_expr [LalinTree.Expr],
      else_expr [LalinTree.Expr],
    },
    ExprSelect {
      variant_unique,
      h [LalinTree.ExprHeader],
      cond [LalinTree.Expr],
      then_expr [LalinTree.Expr],
      else_expr [LalinTree.Expr],
    },
    ExprSwitch {
      variant_unique,
      h [LalinTree.ExprHeader],
      field. value [LalinTree.Expr],
      arms [many [LalinTree.SwitchExprArm]],
      variant_arms [many [LalinTree.SwitchVariantExprArm]],
      default_body [many [LalinTree.Stmt]],
      default_expr [LalinTree.Expr],
    },
    ExprControl {
      variant_unique,
      h [LalinTree.ExprHeader],
      region [LalinTree.ControlExprRegion],
    },
    ExprBlock {
      variant_unique,
      h [LalinTree.ExprHeader],
      stmts [many [LalinTree.Stmt]],
      result [LalinTree.Expr],
    },
    ExprClosure {
      variant_unique,
      h [LalinTree.ExprHeader],
      params [many [LalinType.Param]],
      result [LalinType.Type],
      body [many [LalinTree.Stmt]],
    },
    ExprView { variant_unique, h [LalinTree.ExprHeader], view [LalinTree.View], },
    ExprLoad {
      variant_unique,
      h [LalinTree.ExprHeader],
      field. ty [LalinType.Type],
      addr [LalinTree.Expr],
    },
    ExprAtomicLoad {
      variant_unique,
      h [LalinTree.ExprHeader],
      field. ty [LalinType.Type],
      addr [LalinTree.Expr],
      ordering [LalinCore.AtomicOrdering],
    },
    ExprAtomicRmw {
      variant_unique,
      h [LalinTree.ExprHeader],
      op [LalinCore.AtomicRmwOp],
      field. ty [LalinType.Type],
      addr [LalinTree.Expr],
      field. value [LalinTree.Expr],
      ordering [LalinCore.AtomicOrdering],
    },
    ExprAtomicCas {
      variant_unique,
      h [LalinTree.ExprHeader],
      field. ty [LalinType.Type],
      addr [LalinTree.Expr],
      expected [LalinTree.Expr],
      replacement [LalinTree.Expr],
      ordering [LalinCore.AtomicOrdering],
    },
    ExprCtor {
      variant_unique,
      h [LalinTree.ExprHeader],
      type_name [str],
      variant_name [str],
      args [many [LalinTree.Expr]],
    },
    ExprNull { variant_unique, h [LalinTree.ExprHeader], elem [LalinType.Type], },
    ExprSizeOf { variant_unique, h [LalinTree.ExprHeader], field. ty [LalinType.Type], },
    ExprAlignOf { variant_unique, h [LalinTree.ExprHeader], field. ty [LalinType.Type], },
    ExprIsNull { variant_unique, h [LalinTree.ExprHeader], field. value [LalinTree.Expr], },
  },
  sum. Stmt {
    StmtLet {
      variant_unique,
      h [LalinTree.StmtHeader],
      binding [LalinBind.Binding],
      init [LalinTree.Expr],
    },
    StmtVar {
      variant_unique,
      h [LalinTree.StmtHeader],
      binding [LalinBind.Binding],
      init [LalinTree.Expr],
    },
    StmtSet {
      variant_unique,
      h [LalinTree.StmtHeader],
      place [LalinTree.Place],
      field. value [LalinTree.Expr],
    },
    StmtAtomicStore {
      variant_unique,
      h [LalinTree.StmtHeader],
      field. ty [LalinType.Type],
      addr [LalinTree.Expr],
      field. value [LalinTree.Expr],
      ordering [LalinCore.AtomicOrdering],
    },
    StmtAtomicFence {
      variant_unique,
      h [LalinTree.StmtHeader],
      ordering [LalinCore.AtomicOrdering],
    },
    StmtExpr { variant_unique, h [LalinTree.StmtHeader], field. expr [LalinTree.Expr], },
    StmtAssert { variant_unique, h [LalinTree.StmtHeader], cond [LalinTree.Expr], },
    StmtIf {
      variant_unique,
      h [LalinTree.StmtHeader],
      cond [LalinTree.Expr],
      then_body [many [LalinTree.Stmt]],
      else_body [many [LalinTree.Stmt]],
    },
    StmtSwitch {
      variant_unique,
      h [LalinTree.StmtHeader],
      field. value [LalinTree.Expr],
      arms [many [LalinTree.SwitchStmtArm]],
      variant_arms [many [LalinTree.SwitchVariantStmtArm]],
      default_body [many [LalinTree.Stmt]],
    },
    StmtJump {
      variant_unique,
      h [LalinTree.StmtHeader],
      target [LalinTree.BlockLabel],
      args [many [LalinTree.JumpArg]],
    },
    StmtJumpCont {
      variant_unique,
      h [LalinTree.StmtHeader],
      cont [LalinTree.RegionCont],
      args [many [LalinTree.JumpArg]],
    },
    StmtYieldVoid { variant_unique, h [LalinTree.StmtHeader], },
    StmtYieldValue {
      variant_unique,
      h [LalinTree.StmtHeader],
      field. value [LalinTree.Expr],
    },
    StmtReturnVoid { variant_unique, h [LalinTree.StmtHeader], },
    StmtReturnValue {
      variant_unique,
      h [LalinTree.StmtHeader],
      field. value [LalinTree.Expr],
    },
    StmtControl {
      variant_unique,
      h [LalinTree.StmtHeader],
      region [LalinTree.ControlStmtRegion],
    },
    StmtTrap { variant_unique, h [LalinTree.StmtHeader], },
  },
  sum. Func {
    FuncLocal {
      variant_unique,
      field. name [str],
      params [many [LalinType.Param]],
      result [LalinType.Type],
      body [many [LalinTree.Stmt]],
    },
    FuncExport {
      variant_unique,
      field. name [str],
      params [many [LalinType.Param]],
      result [LalinType.Type],
      body [many [LalinTree.Stmt]],
    },
    FuncLocalContract {
      variant_unique,
      field. name [str],
      params [many [LalinType.Param]],
      result [LalinType.Type],
      contracts [many [LalinTree.FuncContract]],
      body [many [LalinTree.Stmt]],
    },
    FuncExportContract {
      variant_unique,
      field. name [str],
      params [many [LalinType.Param]],
      result [LalinType.Type],
      contracts [many [LalinTree.FuncContract]],
      body [many [LalinTree.Stmt]],
    },
    FuncDecl {
      variant_unique,
      field. name [str],
      params [many [LalinType.Param]],
      result [LalinType.Type],
    },
  },
  sum. ExternFunc {
    ExternFunc {
      variant_unique,
      field. name [str],
      symbol [str],
      params [many [LalinType.Param]],
      result [LalinType.Type],
    },
  },
  sum. ConstItem {
    ConstItem {
      variant_unique,
      field. name [str],
      field. ty [LalinType.Type],
      field. value [LalinTree.Expr],
    },
  },
  sum. StaticItem {
    StaticItem {
      variant_unique,
      field. name [str],
      field. ty [LalinType.Type],
      field. value [LalinTree.Expr],
    },
  },
  product. ImportItem { interned, path [LalinCore.Path], },
  sum. TypeDecl {
    TypeDeclStruct { variant_unique, field. name [str], fields [many [LalinType.FieldDecl]], },
    TypeDeclUnion { variant_unique, field. name [str], fields [many [LalinType.FieldDecl]], },
    TypeDeclEnumSugar { variant_unique, field. name [str], variants [many [LalinCore.Name]], },
    TypeDeclTaggedUnionSugar {
      variant_unique,
      field. name [str],
      variants [many [LalinType.VariantDecl]],
    },
    TypeDeclHandle {
      variant_unique,
      field. name [str],
      repr [LalinType.HandleRepr],
      invalid [LalinType.HandleInvalid],
      facts [many [LalinType.HandleFact]],
    },
  },
  sum. Item {
    ItemFunc { variant_unique, func [LalinTree.Func], },
    ItemExtern { variant_unique, func [LalinTree.ExternFunc], },
    ItemConst { variant_unique, c [LalinTree.ConstItem], },
    ItemStatic { variant_unique, s [LalinTree.StaticItem], },
    ItemImport { variant_unique, imp [LalinTree.ImportItem], },
    ItemType { variant_unique, t [LalinTree.TypeDecl], },
    ItemRegion { variant_unique, region [LalinTree.Region], },
    ItemData { variant_unique, data [LalinTree.DataItem], },
  },
  product. DataItem {
    interned,
    field. id [LalinCore.DataId],
    size [number],
    align [number],
    bytes [str],
  },
  sum. ModuleHeader {
    ModuleSurface,
    ModuleTyped { variant_unique, module_name [str], },
    ModuleSem { variant_unique, module_name [str], },
    ModuleCode { variant_unique, module_name [str], },
  },
  product. Module { interned, h [LalinTree.ModuleHeader], items [many [LalinTree.Item]], },
  sum. TypeIssue {
    TypeIssueUnresolvedValue { variant_unique, field. name [str], },
    TypeIssueUnresolvedPath { variant_unique, path [LalinCore.Path], },
    TypeIssueExpected {
      variant_unique,
      site [str],
      expected [LalinType.Type],
      actual [LalinType.Type],
    },
    TypeIssueArgCount { variant_unique, site [str], expected [number], actual [number], },
    TypeIssueNotCallable { variant_unique, field. ty [LalinType.Type], },
    TypeIssueNotIndexable { variant_unique, field. ty [LalinType.Type], },
    TypeIssueNotPointer { variant_unique, field. ty [LalinType.Type], },
    TypeIssueInvalidUnary {
      variant_unique,
      reason [LalinTree.TypeUnaryIssueReason],
      field. ty [LalinType.Type],
    },
    TypeIssueInvalidBinary {
      variant_unique,
      op [str],
      lhs [LalinType.Type],
      rhs [LalinType.Type],
    },
    TypeIssueInvalidCompare {
      variant_unique,
      op [str],
      lhs [LalinType.Type],
      rhs [LalinType.Type],
    },
    TypeIssueInvalidLogic {
      variant_unique,
      op [str],
      lhs [LalinType.Type],
      rhs [LalinType.Type],
    },
    TypeIssueMissingJumpTarget {
      variant_unique,
      region_id [str],
      label [LalinTree.BlockLabel],
    },
    TypeIssueMissingJumpArg {
      variant_unique,
      region_id [str],
      label [LalinTree.BlockLabel],
      field. name [str],
    },
    TypeIssueExtraJumpArg {
      variant_unique,
      region_id [str],
      label [LalinTree.BlockLabel],
      field. name [str],
    },
    TypeIssueDuplicateJumpArg {
      variant_unique,
      region_id [str],
      label [LalinTree.BlockLabel],
      field. name [str],
    },
    TypeIssueUnexpectedYield { variant_unique, site [str], },
    TypeIssueInvalidControl {
      variant_unique,
      region_id [str],
      reject [LalinTree.ControlReject],
    },
    TypeIssueUnknownVariant { variant_unique, type_name [str], variant_name [str], },
    TypeIssueVariantPayloadMismatch {
      variant_unique,
      type_name [str],
      variant_name [str],
      expected [LalinType.Type],
      actual [LalinType.Type],
    },
    TypeIssueDuplicateVariant { variant_unique, type_name [str], variant_name [str], },
  },
  sum. TypeUnaryIssueReason {
    TypeUnaryInvalidOperator { variant_unique, op [str], },
    TypeUnaryLeaseEscapeReturn,
    TypeUnaryLeaseEscapeYield,
    TypeUnaryLeaseEscapeStore,
    TypeUnaryLeaseEscapeCall,
    TypeUnaryLeaseInvalidatingCall,
    TypeUnaryLeaseEscapeAggregate,
    TypeUnaryRegionCallLeasePayload,
    TypeUnaryLeaseEscapeDurable,
    TypeUnaryOwnedDropped,
    TypeUnaryOwnedUseAfterMove,
    TypeUnaryOwnedObservedWithoutTransfer,
    TypeUnaryOwnedCapturedDurable,
    TypeUnaryOwnedBranchMismatch,
    TypeUnaryOwnedVarCellUnsupported,
    TypeUnaryOwnedRegionCallPayload,
    TypeUnaryOwnedEmitTargetMismatch,
    TypeUnaryOwnedInvalidComposition,
    TypeUnaryHandleCast,
    TypeUnaryHandleRepr,
    TypeUnaryHandleTargetMismatch,
    TypeUnaryHandleDomainMissing,
    TypeUnaryHandleDomainAccess,
    TypeUnaryHandleLeaseOriginMissing,
    TypeUnaryHandleLeaseOriginMismatch,
    TypeUnaryAtomicRmwPointerOp,
    TypeUnaryAtomicRmwBoolAddSub,
    TypeUnaryAtomicInvalidValue { variant_unique, site [str], },
  },
  product. TypeIssueExplanation {
    interned,
    code [str],
    phase_context [str],
    primary [str],
    notes [many [str]],
    suggestions [many [str]],
  },
  sum. TypeYieldMode {
    TypeYieldNone,
    TypeYieldVoid,
    TypeYieldValue { variant_unique, field. ty [LalinType.Type], },
  },
  product. TypeVariantCase {
    interned,
    field. name [str],
    tag [number],
    payload [LalinType.Type],
    fields [many [LalinType.FieldDecl]],
  },
  product. TypeVariantDef {
    interned,
    type_name [str],
    field. ty [LalinType.Type],
    variants [many [LalinTree.TypeVariantCase]],
  },
  product. TypeHandleDef {
    interned,
    field. name [str],
    field. ty [LalinType.Type],
    repr [LalinType.HandleRepr],
    invalid [LalinType.HandleInvalid],
    domain [optional [LalinType.TypeRef]],
    target [optional [LalinType.TypeRef]],
  },
  product. TypeFuncEffect {
    interned,
    field. name [str],
    params [many [LalinType.Param]],
    readonly [many [str]],
    preserve [many [str]],
    invalidate [many [str]],
  },
  product. TypeModuleFacts {
    interned,
    variants [many [LalinTree.TypeVariantDef]],
    handles [many [LalinTree.TypeHandleDef]],
    effects [many [LalinTree.TypeFuncEffect]],
  },
  product. TypeModuleFactsInput {
    interned,
    module_name [str],
  },
  product. TypeNameScope {
    interned,
    types [many [LalinBind.TypeEntry]],
  },
  product. TypeValueScope {
    interned,
    module_name [str],
    values [many [LalinBind.ValueEntry]],
    types [many [LalinBind.TypeEntry]],
    layouts [many [LalinSem.TypeLayout]],
    facts [LalinTree.TypeModuleFacts],
  },
  product. TypeScopeChange {
    interned,
    scope [LalinTree.TypeValueScope],
  },
  product. TypeExprInput {
    interned,
    scope [LalinTree.TypeValueScope],
  },
  product. TypeExpectedExprInput {
    interned,
    scope [LalinTree.TypeValueScope],
    expected [LalinType.Type],
  },
  product. TypeValueRefInput {
    interned,
    scope [LalinTree.TypeValueScope],
  },
  product. TypeValueRefResult {
    interned,
    field. ref [LalinBind.ValueRef],
    field. ty [LalinType.Type],
    issues [many [LalinTree.TypeIssue]],
  },
  product. TypePlaceInput {
    interned,
    scope [LalinTree.TypeValueScope],
  },
  product. TypeIndexBaseInput {
    interned,
    scope [LalinTree.TypeValueScope],
  },
  product. TypeViewInput {
    interned,
    scope [LalinTree.TypeValueScope],
  },
  product. TypeStmtInput {
    interned,
    scope [LalinTree.TypeValueScope],
    return_ty [LalinType.Type],
    yield [LalinTree.TypeYieldMode],
  },
  product. TypeControlInput {
    interned,
    stmt [LalinTree.TypeStmtInput],
    region_id [str],
  },
  product. TypeFuncInput {
    interned,
    scope [LalinTree.TypeValueScope],
  },
  product. TypeItemInput {
    interned,
    scope [LalinTree.TypeValueScope],
  },
  product. TypePolicyInput {
    interned,
    site [str],
  },
  product. TypePolicyResult {
    interned,
    issues [many [LalinTree.TypeIssue]],
  },
  product. TypeCanonicalInput {
    interned,
    names [LalinTree.TypeNameScope],
  },
  product. TypeCanonicalResult {
    interned,
    field. ty [LalinType.Type],
  },
  product. TypeBinaryInput {
    interned,
    op [LalinCore.BinaryOp],
    rhs [LalinType.Type],
  },
  product. TypeBinaryResult {
    interned,
    field. ty [LalinType.Type],
    issues [many [LalinTree.TypeIssue]],
  },
  product. TypeCompareInput {
    interned,
    op [LalinCore.CmpOp],
    rhs [LalinType.Type],
  },
  product. TypeCompareResult {
    interned,
    field. ty [LalinType.Type],
    issues [many [LalinTree.TypeIssue]],
  },
  sum. TypeViewResult {
    TypeViewResult {
      variant_unique,
      view [LalinTree.View],
      issues [many [LalinTree.TypeIssue]],
    },
  },
  sum. TypeIndexBaseResult {
    TypeIndexBaseResult {
      variant_unique,
      base [LalinTree.IndexBase],
      elem [LalinType.Type],
      issues [many [LalinTree.TypeIssue]],
    },
  },
  sum. TypeControlStmtRegionResult {
    TypeControlStmtRegionResult {
      variant_unique,
      region [LalinTree.ControlStmtRegion],
      issues [many [LalinTree.TypeIssue]],
    },
  },
  sum. TypeControlExprRegionResult {
    TypeControlExprRegionResult {
      variant_unique,
      region [LalinTree.ControlExprRegion],
      issues [many [LalinTree.TypeIssue]],
    },
  },
  sum. TypeExprResult {
    TypeExprResult {
      variant_unique,
      field. expr [LalinTree.Expr],
      field. ty [LalinType.Type],
      issues [many [LalinTree.TypeIssue]],
    },
  },
  sum. TypePlaceResult {
    TypePlaceResult {
      variant_unique,
      place [LalinTree.Place],
      field. ty [LalinType.Type],
      issues [many [LalinTree.TypeIssue]],
    },
  },
  sum. TypeStmtResult {
    TypeStmtResult {
      variant_unique,
      state [LalinTree.TypeStmtInput],
      stmts [many [LalinTree.Stmt]],
      issues [many [LalinTree.TypeIssue]],
    },
  },
  sum. TypeFuncResult {
    TypeFuncResult {
      variant_unique,
      func [LalinTree.Func],
      issues [many [LalinTree.TypeIssue]],
    },
  },
  sum. TypeItemResult {
    TypeItemResult {
      variant_unique,
      items [many [LalinTree.Item]],
      issues [many [LalinTree.TypeIssue]],
    },
  },
  sum. TypeModuleResult {
    TypeModuleResult {
      variant_unique,
      field. module [LalinTree.Module],
      issues [many [LalinTree.TypeIssue]],
    },
  },
  product. TreeCodeModuleContext {
    interned,
    module_name [str],
    layout_env [LalinSem.LayoutEnv],
    target [optional [LalinBack.BackTargetModel]],
    const_env [LalinBind.ConstEnv],
  },
  product. TreeCodeFuncContext {
    interned,
    field. module [LalinTree.TreeCodeModuleContext],
    func_name [str],
  },
  product. TreeCodeItemRegisterInput {
    interned,
    field. module [LalinTree.TreeCodeModuleContext],
    externs [many [LalinCode.CodeExtern]],
  },
  product. TreeCodeItemContractsInput {
    interned,
    field. module [LalinTree.TreeCodeModuleContext],
    facts [many [LalinCode.CodeFuncContractFact]],
  },
  product. TreeCodeItemLowerInput {
    interned,
    field. module [LalinTree.TreeCodeModuleContext],
    mod_name [str],
    funcs [many [LalinCode.CodeFunc]],
    data [many [LalinCode.CodeData]],
    globals [many [LalinCode.CodeGlobal]],
  },
  product. TreeCodeExprInput { interned, func [LalinTree.TreeCodeFuncContext], },
  product. TreeCodePlaceInput { interned, func [LalinTree.TreeCodeFuncContext], },
  product. TreeCodeStmtInput { interned, func [LalinTree.TreeCodeFuncContext], },
  product. TreeCodeControlInput { interned, func [LalinTree.TreeCodeFuncContext], },
  product. TreeCodeContractInput {
    interned,
    field. module [LalinTree.TreeCodeModuleContext],
    func_name [str],
    func_id [LalinCode.CodeFuncId],
  },
  product. TreeCodeExprResult {
    interned,
    field. value [optional [LalinCode.CodeValueId]],
    field. ty [LalinCode.CodeType],
  },
  product. TreeCodePlaceResult {
    interned,
    place [LalinCode.CodePlace],
  },
  product. TreeCodeFuncParts {
    interned,
    field. name [str],
    linkage [LalinCode.CodeLinkage],
    params [many [LalinType.Param]],
    result [LalinType.Type],
    body [many [LalinTree.Stmt]],
  },
  product. TreeCodeContractResult {
    interned,
    fact [LalinCode.CodeFuncContractFact],
  },
  sum. TreeBackLocal {
    TreeBackScalarLocal {
      variant_unique,
      binding [LalinBind.Binding],
      field. value [LalinBack.BackValId],
      field. ty [LalinBack.BackScalar],
    },
    TreeBackStackLocal {
      variant_unique,
      binding [LalinBind.Binding],
      slot [LalinBack.BackStackSlotId],
      field. ty [LalinBack.BackScalar],
    },
    TreeBackViewLocal {
      variant_unique,
      binding [LalinBind.Binding],
      data [LalinBack.BackValId],
      len [LalinBack.BackValId],
    },
    TreeBackStridedViewLocal {
      variant_unique,
      binding [LalinBind.Binding],
      data [LalinBack.BackValId],
      len [LalinBack.BackValId],
      stride [LalinBack.BackValId],
    },
  },
  sum. TreeBackReturn {
    TreeBackReturnScalar,
    TreeBackReturnView { variant_unique, out [LalinBack.BackValId], },
  },
  product. TreeBackEnv {
    interned,
    locals [many [LalinTree.TreeBackLocal]],
    next_value [number],
    next_block [number],
    ret [LalinTree.TreeBackReturn],
  },
  sum. TreeBackExprResult {
    TreeBackExprValue {
      variant_unique,
      env [LalinTree.TreeBackEnv],
      cmds [many [LalinBack.Cmd]],
      field. value [LalinBack.BackValId],
      field. ty [LalinBack.BackScalar],
    },
    TreeBackExprView {
      variant_unique,
      env [LalinTree.TreeBackEnv],
      cmds [many [LalinBack.Cmd]],
      data [LalinBack.BackValId],
      len [LalinBack.BackValId],
    },
    TreeBackExprStridedView {
      variant_unique,
      env [LalinTree.TreeBackEnv],
      cmds [many [LalinBack.Cmd]],
      data [LalinBack.BackValId],
      len [LalinBack.BackValId],
      stride [LalinBack.BackValId],
    },
    TreeBackExprUnsupported {
      variant_unique,
      env [LalinTree.TreeBackEnv],
      cmds [many [LalinBack.Cmd]],
      reason [str],
    },
  },
  sum. TreeBackStmtResult {
    TreeBackStmtResult {
      variant_unique,
      env [LalinTree.TreeBackEnv],
      cmds [many [LalinBack.Cmd]],
      flow [LalinBack.BackFlow],
    },
  },
  sum. TreeBackFuncResult {
    TreeBackFuncResult { variant_unique, cmds [many [LalinBack.Cmd]], },
  },
  sum. TreeBackItemResult {
    TreeBackItemResult { variant_unique, cmds [many [LalinBack.Cmd]], },
  },
}
