local S = require("lalin.schema.dsl")
S.use()

return schema. LalinType {
  sum. TypeRef {
    TypeRefPath { variant_unique, path [LalinCore.Path], },
    TypeRefGlobal { variant_unique, module_name [str], type_name [str], },
    TypeRefLocal { variant_unique, sym [LalinCore.TypeSym], },
    TypeRefSlot { variant_unique, slot [LalinOpen.TypeSlot], },
  },
  sum. ArrayLen {
    ArrayLenExpr { variant_unique, field. expr [LalinTree.Expr], },
    ArrayLenConst { variant_unique, count [number], },
    ArrayLenSlot { variant_unique, slot [LalinOpen.ExprSlot], },
  },
  sum. HandleRepr { HandleReprScalar { variant_unique, scalar [LalinCore.Scalar], }, },
  sum. HandleInvalid { HandleInvalidNone, HandleInvalidInt { variant_unique, raw [str], }, },
  sum. HandleFact {
    HandleDomain { variant_unique, domain [LalinType.TypeRef], },
    HandleTarget { variant_unique, target [LalinType.TypeRef], },
  },
  sum. LeaseOrigin { LeaseOriginUnknown, LeaseOriginParam { variant_unique, field. name [str], }, },
  sum. TypeAccess {
    TypeAccessNoAlias,
    TypeAccessReadonly,
    TypeAccessWriteonly,
    TypeAccessNoEscape,
    TypeAccessInvalidate,
    TypeAccessPreserve,
  },
  sum. Type {
    TScalar { variant_unique, scalar [LalinCore.Scalar], },
    TPtr { variant_unique, elem [LalinType.Type], },
    TArray { variant_unique, count [LalinType.ArrayLen], elem [LalinType.Type], },
    TSlice { variant_unique, elem [LalinType.Type], },
    TView { variant_unique, elem [LalinType.Type], },
    TLease { variant_unique, base [LalinType.Type], origin [LalinType.LeaseOrigin], },
    TOwned { variant_unique, base [LalinType.Type], },
    TAccess { variant_unique, access [LalinType.TypeAccess], base [LalinType.Type], },
    THandle {
      variant_unique,
      field. ref [LalinType.TypeRef],
      repr [LalinType.HandleRepr],
    },
    TFunc { variant_unique, params [many [LalinType.Type]], result [LalinType.Type], },
    TClosure { variant_unique, params [many [LalinType.Type]], result [LalinType.Type], },
    TNamed { variant_unique, field. ref [LalinType.TypeRef], },
    TSlot { variant_unique, slot [LalinOpen.TypeSlot], },
    TCType { variant_unique, field. id [LalinC.CTypeId], },
    TCFuncPtr { variant_unique, sig [LalinC.CFuncSigId], },
  },
  sum. TypeClass {
    TypeClassScalar { variant_unique, scalar [LalinCore.Scalar], },
    TypeClassPointer { variant_unique, elem [LalinType.Type], },
    TypeClassArray { variant_unique, elem [LalinType.Type], count [number], },
    TypeClassSlice { variant_unique, elem [LalinType.Type], },
    TypeClassView { variant_unique, elem [LalinType.Type], },
    TypeClassLease {
      variant_unique,
      base [LalinType.Type],
      origin [LalinType.LeaseOrigin],
    },
    TypeClassOwned { variant_unique, base [LalinType.Type], },
    TypeClassHandle { variant_unique, repr [LalinType.HandleRepr], },
    TypeClassCallable {
      variant_unique,
      params [many [LalinType.Type]],
      result [LalinType.Type],
    },
    TypeClassClosure {
      variant_unique,
      params [many [LalinType.Type]],
      result [LalinType.Type],
    },
    TypeClassAggregate { variant_unique, module_name [str], type_name [str], },
    TypeClassUnknown,
  },
  sum. TypeBackScalarResult {
    TypeBackScalarKnown { variant_unique, scalar [LalinBack.BackScalar], },
    TypeBackScalarUnavailable {
      variant_unique,
      field. ty [LalinType.Type],
      class [LalinType.TypeClass],
    },
  },
  sum. TypeMemLayoutResult {
    TypeMemLayoutKnown { variant_unique, layout [LalinSem.MemLayout], },
    TypeMemLayoutUnknown {
      variant_unique,
      field. ty [LalinType.Type],
      class [LalinType.TypeClass],
    },
  },
  sum. AbiClass {
    AbiIgnore,
    AbiDirect { variant_unique, scalar [LalinBack.BackScalar], },
    AbiIndirect { variant_unique, layout [LalinSem.MemLayout], },
    AbiDescriptor { variant_unique, layout [LalinSem.MemLayout], },
    AbiUnknown { variant_unique, class [LalinType.TypeClass], },
  },
  product. AbiDecision {
    interned,
    field. ty [LalinType.Type],
    class [LalinType.AbiClass],
  },
  sum. AbiParamPlan {
    AbiParamScalar {
      variant_unique,
      field. name [str],
      binding [LalinBind.Binding],
      scalar [LalinBack.BackScalar],
      field. value [LalinBack.BackValId],
    },
    AbiParamView {
      variant_unique,
      field. name [str],
      binding [LalinBind.Binding],
      data [LalinBack.BackValId],
      len [LalinBack.BackValId],
      stride [LalinBack.BackValId],
    },
    AbiParamRejected {
      variant_unique,
      field. name [str],
      field. ty [LalinType.Type],
      reason [str],
    },
  },
  sum. AbiResultPlan {
    AbiResultVoid,
    AbiResultScalar { variant_unique, scalar [LalinBack.BackScalar], },
    AbiResultView { variant_unique, elem [LalinType.Type], out [LalinBack.BackValId], },
    AbiResultRejected { variant_unique, field. ty [LalinType.Type], reason [str], },
  },
  product. FuncAbiPlan {
    interned,
    func_name [str],
    params [many [LalinType.AbiParamPlan]],
    result [LalinType.AbiResultPlan],
  },
  product. Param { interned, field. name [str], field. ty [LalinType.Type], },
  product. FieldDecl { interned, field_name [str], field. ty [LalinType.Type], },
  product. VariantDecl {
    interned,
    field. name [str],
    payload [LalinType.Type],
    fields [many [LalinType.FieldDecl]],
  },
}
