local S = require("lalin.schema.dsl")
S.use()

return schema. LalinValue {
  product. ValueFactId { interned, text [str], },
  product. AlgebraFactId { interned, text [str], },
  sum. ValueExpr {
    ValueExprConst { variant_unique, const [LalinCode.CodeConst], },
    ValueExprValue { variant_unique, field. value [LalinCode.CodeValueId], },
    ValueExprUnary {
      variant_unique,
      op [LalinCore.UnaryOp],
      field. value [LalinValue.ValueExpr],
      field. ty [LalinCode.CodeType],
    },
    ValueExprCast {
      variant_unique,
      op [LalinCore.MachineCastOp],
      from [LalinCode.CodeType],
      to [LalinCode.CodeType],
      field. value [LalinValue.ValueExpr],
    },
    ValueExprAdd {
      variant_unique,
      a [LalinValue.ValueExpr],
      b [LalinValue.ValueExpr],
      field. ty [LalinCode.CodeType],
      sem [optional [LalinCode.CodeIntSemantics]],
    },
    ValueExprSub {
      variant_unique,
      a [LalinValue.ValueExpr],
      b [LalinValue.ValueExpr],
      field. ty [LalinCode.CodeType],
      sem [optional [LalinCode.CodeIntSemantics]],
    },
    ValueExprMul {
      variant_unique,
      a [LalinValue.ValueExpr],
      b [LalinValue.ValueExpr],
      field. ty [LalinCode.CodeType],
      sem [optional [LalinCode.CodeIntSemantics]],
    },
    ValueExprDiv {
      variant_unique,
      a [LalinValue.ValueExpr],
      b [LalinValue.ValueExpr],
      field. ty [LalinCode.CodeType],
      sem [optional [LalinCode.CodeIntSemantics]],
    },
    ValueExprSelect {
      variant_unique,
      cond [LalinValue.ValueExpr],
      t [LalinValue.ValueExpr],
      f [LalinValue.ValueExpr],
    },
    ValueExprCmp {
      variant_unique,
      op [LalinCore.CmpOp],
      field. ty [LalinCode.CodeType],
      a [LalinValue.ValueExpr],
      b [LalinValue.ValueExpr],
    },
    ValueExprAffine { variant_unique, affine [LalinValue.AffineExpr], },
  },
  product. AffineTerm { interned, field. value [LalinCode.CodeValueId], coeff [str], },
  product. AffineExpr {
    interned,
    constant [str],
    terms [many [LalinValue.AffineTerm]],
    field. ty [LalinCode.CodeType],
    sem [optional [LalinCode.CodeIntSemantics]],
  },
  sum. ValueRange {
    ValueRangeUnknown { variant_unique, reason [str], },
    ValueRangeInt {
      variant_unique,
      field. value [LalinCode.CodeValueId],
      lo [LalinValue.ValueExpr],
      hi [LalinValue.ValueExpr],
      inclusive_hi [bool],
      proof [LalinValue.AlgebraProof],
    },
  },
  sum. ReductionKind {
    ReductionAdd,
    ReductionMul,
    ReductionMin,
    ReductionMax,
    ReductionAnd,
    ReductionOr,
    ReductionXor,
  },
  product. ReductionFact {
    interned,
    field. id [LalinValue.AlgebraFactId],
    domain [LalinFlow.FlowDomain],
    accumulator [LalinCode.CodeValueId],
    kind [LalinValue.ReductionKind],
    init [LalinValue.ValueExpr],
    contribution [LalinValue.ValueExpr],
    field. ty [LalinCode.CodeType],
    int_semantics [optional [LalinCode.CodeIntSemantics]],
    float_mode [optional [LalinCode.CodeFloatMode]],
    proof [LalinValue.AlgebraProof],
  },
  product. ClosedFormFact {
    interned,
    field. id [LalinValue.AlgebraFactId],
    reduction [LalinValue.ReductionFact],
    field. expr [LalinValue.ValueExpr],
    proof [LalinValue.AlgebraProof],
  },
  sum. AlgebraProof {
    AlgebraProofFlow { variant_unique, domain [LalinFlow.FlowDomain], reason [str], },
    AlgebraProofNoWrap { variant_unique, field. value [LalinCode.CodeValueId], reason [str], },
    AlgebraProofIdentity { variant_unique, reason [str], },
    AlgebraProofReduction { variant_unique, fact [LalinValue.ReductionFact], reason [str], },
    AlgebraProofComposite {
      variant_unique,
      proofs [many [LalinValue.AlgebraProof]],
      reason [str],
    },
  },
  sum. ValueFact {
    ValueExprFact {
      variant_unique,
      field. value [LalinCode.CodeValueId],
      field. expr [LalinValue.ValueExpr],
      proof [LalinValue.AlgebraProof],
    },
    ValueRangeFact { variant_unique, range [LalinValue.ValueRange], },
    ValueNoWrapFact {
      variant_unique,
      field. value [LalinCode.CodeValueId],
      sem [LalinCode.CodeIntSemantics],
      proof [LalinValue.AlgebraProof],
    },
    ValueFloatModeFact {
      variant_unique,
      field. value [LalinCode.CodeValueId],
      mode [LalinCode.CodeFloatMode],
      proof [LalinValue.AlgebraProof],
    },
  },
  product. ValueFactSet {
    interned,
    field. module [LalinCode.CodeModuleId],
    values [many [LalinValue.ValueFact]],
    reductions [many [LalinValue.ReductionFact]],
    closed_forms [many [LalinValue.ClosedFormFact]],
  },
}
