local S = require("moonlift.schema.dsl")
S.use()

return schema. MoonBack {
  sum. BackScalar {
    BackVoid,
    BackBool,
    BackI8,
    BackI16,
    BackI32,
    BackI64,
    BackU8,
    BackU16,
    BackU32,
    BackU64,
    BackF32,
    BackF64,
    BackPtr,
    BackIndex,
  },
  product. BackSigId { interned, text [str], },
  product. BackFuncId { interned, text [str], },
  product. BackExternId { interned, text [str], },
  product. BackDataId { interned, text [str], },
  product. BackBlockId { interned, text [str], },
  product. BackValId { interned, text [str], },
  product. BackStackSlotId { interned, text [str], },
  product. BackSwitchCase { interned, raw [str], dest [MoonBack.BackBlockId], },
  product. BackVec { interned, elem [MoonBack.BackScalar], lanes [number], },
  sum. BackShape {
    BackShapeScalar { variant_unique, scalar [MoonBack.BackScalar], },
    BackShapeVec { variant_unique, vec [MoonBack.BackVec], },
  },
  sum. BackTarget {
    BackTargetNative,
    BackTargetDynasmJit,
    BackTargetNamed { variant_unique, field. name [str], },
  },
  sum. BackEndian { BackEndianLittle, BackEndianBig, },
  sum. BackTargetFeature {
    BackFeatureSSE2,
    BackFeatureAVX2,
    BackFeatureAVX512F,
    BackFeatureFMA,
    BackFeaturePOPCNT,
    BackFeatureBMI1,
    BackFeatureBMI2,
    BackFeatureUnknown { variant_unique, field. name [str], },
  },
  sum. BackTargetFact {
    BackTargetPointerBits { variant_unique, bits [number], },
    BackTargetIndexBits { variant_unique, bits [number], },
    BackTargetEndian { variant_unique, endian [MoonBack.BackEndian], },
    BackTargetCacheLineBytes { variant_unique, bytes [number], },
    BackTargetFeature { variant_unique, feature [MoonBack.BackTargetFeature], },
    BackTargetSupportsShape { variant_unique, shape [MoonBack.BackShape], },
    BackTargetSupportsVectorOp { variant_unique, vec [MoonBack.BackVec], op_class [str], },
    BackTargetSupportsMaskedTail,
    BackTargetPrefersUnroll {
      variant_unique,
      shape [MoonBack.BackShape],
      unroll [number],
      rank [number],
    },
  },
  product. BackTargetModel {
    interned,
    target [MoonBack.BackTarget],
    facts [many [MoonBack.BackTargetFact]],
  },
  sum. BackAddressBase {
    BackAddrValue { variant_unique, field. value [MoonBack.BackValId], },
    BackAddrStack { variant_unique, slot [MoonBack.BackStackSlotId], },
    BackAddrData { variant_unique, data [MoonBack.BackDataId], },
  },
  sum. BackPointerProvenance {
    BackProvUnknown,
    BackProvStack { variant_unique, slot [MoonBack.BackStackSlotId], },
    BackProvData { variant_unique, data [MoonBack.BackDataId], },
    BackProvArg { variant_unique, field. name [str], },
    BackProvView { variant_unique, field. name [str], },
    BackProvDerived { variant_unique, reason [str], },
  },
  sum. BackPointerBounds {
    BackPtrBoundsUnknown,
    BackPtrInBounds { variant_unique, reason [str], },
    BackPtrMayLeaveObject { variant_unique, reason [str], },
  },
  product. BackAddress {
    interned,
    base [MoonBack.BackAddressBase],
    byte_offset [MoonBack.BackValId],
    provenance [MoonBack.BackPointerProvenance],
    formation_bounds [MoonBack.BackPointerBounds],
  },
  product. BackAccessId { interned, text [str], },
  sum. BackAlignment {
    BackAlignUnknown,
    BackAlignKnown { variant_unique, bytes [number], },
    BackAlignAtLeast { variant_unique, bytes [number], },
    BackAlignAssumed { variant_unique, bytes [number], reason [str], },
  },
  sum. BackDereference {
    BackDerefUnknown,
    BackDerefBytes { variant_unique, bytes [number], reason [str], },
    BackDerefAssumed { variant_unique, bytes [number], reason [str], },
  },
  sum. BackTrap {
    BackMayTrap,
    BackNonTrapping { variant_unique, reason [str], },
    BackChecked { variant_unique, reason [str], },
  },
  sum. BackMotion { BackMayNotMove, BackCanMove { variant_unique, reason [str], }, },
  sum. BackAccessMode { BackAccessRead, BackAccessWrite, BackAccessReadWrite, BackAccessReadonly, },
  sum. BackAtomicOrdering { BackAtomicSeqCst, },
  sum. BackAtomicRmwOp {
    BackAtomicRmwAdd,
    BackAtomicRmwSub,
    BackAtomicRmwAnd,
    BackAtomicRmwOr,
    BackAtomicRmwXor,
    BackAtomicRmwXchg,
  },
  product. BackMemoryInfo {
    interned,
    access [MoonBack.BackAccessId],
    alignment [MoonBack.BackAlignment],
    dereference [MoonBack.BackDereference],
    trap [MoonBack.BackTrap],
    motion [MoonBack.BackMotion],
    mode [MoonBack.BackAccessMode],
  },
  sum. BackIntOverflow {
    BackIntWrap,
    BackIntNoSignedWrap { variant_unique, reason [str], },
    BackIntNoUnsignedWrap { variant_unique, reason [str], },
    BackIntNoWrap { variant_unique, reason [str], },
  },
  sum. BackIntExact { BackIntMayLose, BackIntExact { variant_unique, reason [str], }, },
  product. BackIntSemantics {
    interned,
    overflow [MoonBack.BackIntOverflow],
    exact [MoonBack.BackIntExact],
  },
  sum. BackIntOp {
    BackIntAdd,
    BackIntSub,
    BackIntMul,
    BackIntSDiv,
    BackIntUDiv,
    BackIntSRem,
    BackIntURem,
  },
  sum. BackBitOp { BackBitAnd, BackBitOr, BackBitXor, },
  sum. BackShiftOp { BackShiftLeft, BackShiftLogicalRight, BackShiftArithmeticRight, },
  sum. BackRotateOp { BackRotateLeft, BackRotateRight, },
  sum. BackFloatSemantics {
    BackFloatStrict,
    BackFloatReassoc { variant_unique, reason [str], },
    BackFloatFastMath { variant_unique, reason [str], },
  },
  sum. BackFloatOp { BackFloatAdd, BackFloatSub, BackFloatMul, BackFloatDiv, },
  sum. BackLiteral {
    BackLitInt { variant_unique, raw [str], },
    BackLitFloat { variant_unique, raw [str], },
    BackLitBool { variant_unique, field. value [bool], },
    BackLitNull,
  },
  sum. BackUnaryOp { BackUnaryIneg, BackUnaryFneg, BackUnaryBnot, BackUnaryBoolNot, },
  sum. BackIntrinsicOp {
    BackIntrinsicPopcount,
    BackIntrinsicClz,
    BackIntrinsicCtz,
    BackIntrinsicBswap,
    BackIntrinsicSqrt,
    BackIntrinsicAbs,
    BackIntrinsicFloor,
    BackIntrinsicCeil,
    BackIntrinsicTruncFloat,
    BackIntrinsicRound,
  },
  sum. BackCompareOp {
    BackIcmpEq,
    BackIcmpNe,
    BackSIcmpLt,
    BackSIcmpLe,
    BackSIcmpGt,
    BackSIcmpGe,
    BackUIcmpLt,
    BackUIcmpLe,
    BackUIcmpGt,
    BackUIcmpGe,
    BackFCmpEq,
    BackFCmpNe,
    BackFCmpLt,
    BackFCmpLe,
    BackFCmpGt,
    BackFCmpGe,
  },
  sum. BackVecCompareOp {
    BackVecIcmpEq,
    BackVecIcmpNe,
    BackVecSIcmpLt,
    BackVecSIcmpLe,
    BackVecSIcmpGt,
    BackVecSIcmpGe,
    BackVecUIcmpLt,
    BackVecUIcmpLe,
    BackVecUIcmpGt,
    BackVecUIcmpGe,
  },
  sum. BackVecBinaryOp {
    BackVecIntAdd,
    BackVecIntSub,
    BackVecIntMul,
    BackVecBitAnd,
    BackVecBitOr,
    BackVecBitXor,
  },
  sum. BackVecMaskOp { BackVecMaskNot, BackVecMaskAnd, BackVecMaskOr, },
  sum. BackCastOp {
    BackBitcast,
    BackIreduce,
    BackSextend,
    BackUextend,
    BackFpromote,
    BackFdemote,
    BackSToF,
    BackUToF,
    BackFToS,
    BackFToU,
  },
  sum. BackCallTarget {
    BackCallDirect { variant_unique, func [MoonBack.BackFuncId], },
    BackCallExtern { variant_unique, func [MoonBack.BackExternId], },
    BackCallIndirect { variant_unique, callee [MoonBack.BackValId], },
  },
  sum. BackCallResult {
    BackCallStmt,
    BackCallValue {
      variant_unique,
      dst [MoonBack.BackValId],
      field. ty [MoonBack.BackScalar],
    },
  },
  sum. Cmd {
    CmdCreateSig {
      variant_unique,
      sig [MoonBack.BackSigId],
      params [many [MoonBack.BackScalar]],
      results [many [MoonBack.BackScalar]],
    },
    CmdDeclareData {
      variant_unique,
      data [MoonBack.BackDataId],
      size [number],
      align [number],
    },
    CmdDataInitZero {
      variant_unique,
      data [MoonBack.BackDataId],
      offset [number],
      size [number],
    },
    CmdDataInit {
      variant_unique,
      data [MoonBack.BackDataId],
      offset [number],
      field. ty [MoonBack.BackScalar],
      field. value [MoonBack.BackLiteral],
    },
    CmdDataAddr { variant_unique, dst [MoonBack.BackValId], data [MoonBack.BackDataId], },
    CmdFuncAddr { variant_unique, dst [MoonBack.BackValId], func [MoonBack.BackFuncId], },
    CmdExternAddr {
      variant_unique,
      dst [MoonBack.BackValId],
      func [MoonBack.BackExternId],
    },
    CmdDeclareFunc {
      variant_unique,
      visibility [MoonCore.Visibility],
      func [MoonBack.BackFuncId],
      sig [MoonBack.BackSigId],
    },
    CmdDeclareExtern {
      variant_unique,
      func [MoonBack.BackExternId],
      symbol [str],
      sig [MoonBack.BackSigId],
    },
    CmdBeginFunc { variant_unique, func [MoonBack.BackFuncId], },
    CmdCreateBlock { variant_unique, block [MoonBack.BackBlockId], },
    CmdSwitchToBlock { variant_unique, block [MoonBack.BackBlockId], },
    CmdSealBlock { variant_unique, block [MoonBack.BackBlockId], },
    CmdBindEntryParams {
      variant_unique,
      block [MoonBack.BackBlockId],
      values [many [MoonBack.BackValId]],
    },
    CmdAppendBlockParam {
      variant_unique,
      block [MoonBack.BackBlockId],
      field. value [MoonBack.BackValId],
      field. ty [MoonBack.BackShape],
    },
    CmdCreateStackSlot {
      variant_unique,
      slot [MoonBack.BackStackSlotId],
      size [number],
      align [number],
    },
    CmdAlias { variant_unique, dst [MoonBack.BackValId], src [MoonBack.BackValId], },
    CmdStackAddr {
      variant_unique,
      dst [MoonBack.BackValId],
      slot [MoonBack.BackStackSlotId],
    },
    CmdConst {
      variant_unique,
      dst [MoonBack.BackValId],
      field. ty [MoonBack.BackScalar],
      field. value [MoonBack.BackLiteral],
    },
    CmdUnary {
      variant_unique,
      dst [MoonBack.BackValId],
      op [MoonBack.BackUnaryOp],
      field. ty [MoonBack.BackShape],
      field. value [MoonBack.BackValId],
    },
    CmdIntrinsic {
      variant_unique,
      dst [MoonBack.BackValId],
      op [MoonBack.BackIntrinsicOp],
      field. ty [MoonBack.BackShape],
      args [many [MoonBack.BackValId]],
    },
    CmdCompare {
      variant_unique,
      dst [MoonBack.BackValId],
      op [MoonBack.BackCompareOp],
      field. ty [MoonBack.BackShape],
      lhs [MoonBack.BackValId],
      rhs [MoonBack.BackValId],
    },
    CmdCast {
      variant_unique,
      dst [MoonBack.BackValId],
      op [MoonBack.BackCastOp],
      field. ty [MoonBack.BackScalar],
      field. value [MoonBack.BackValId],
    },
    CmdPtrOffset {
      variant_unique,
      dst [MoonBack.BackValId],
      base [MoonBack.BackAddressBase],
      index [MoonBack.BackValId],
      elem_size [number],
      const_offset [number],
      provenance [MoonBack.BackPointerProvenance],
      bounds [MoonBack.BackPointerBounds],
    },
    CmdLoadInfo {
      variant_unique,
      dst [MoonBack.BackValId],
      field. ty [MoonBack.BackShape],
      addr [MoonBack.BackAddress],
      memory [MoonBack.BackMemoryInfo],
    },
    CmdStoreInfo {
      variant_unique,
      field. ty [MoonBack.BackShape],
      addr [MoonBack.BackAddress],
      field. value [MoonBack.BackValId],
      memory [MoonBack.BackMemoryInfo],
    },
    CmdAtomicLoad {
      variant_unique,
      dst [MoonBack.BackValId],
      field. ty [MoonBack.BackScalar],
      addr [MoonBack.BackAddress],
      memory [MoonBack.BackMemoryInfo],
      ordering [MoonBack.BackAtomicOrdering],
    },
    CmdAtomicStore {
      variant_unique,
      field. ty [MoonBack.BackScalar],
      addr [MoonBack.BackAddress],
      field. value [MoonBack.BackValId],
      memory [MoonBack.BackMemoryInfo],
      ordering [MoonBack.BackAtomicOrdering],
    },
    CmdAtomicRmw {
      variant_unique,
      dst [MoonBack.BackValId],
      op [MoonBack.BackAtomicRmwOp],
      field. ty [MoonBack.BackScalar],
      addr [MoonBack.BackAddress],
      field. value [MoonBack.BackValId],
      memory [MoonBack.BackMemoryInfo],
      ordering [MoonBack.BackAtomicOrdering],
    },
    CmdAtomicCas {
      variant_unique,
      dst [MoonBack.BackValId],
      field. ty [MoonBack.BackScalar],
      addr [MoonBack.BackAddress],
      expected [MoonBack.BackValId],
      replacement [MoonBack.BackValId],
      memory [MoonBack.BackMemoryInfo],
      ordering [MoonBack.BackAtomicOrdering],
    },
    CmdAtomicFence { variant_unique, ordering [MoonBack.BackAtomicOrdering], },
    CmdIntBinary {
      variant_unique,
      dst [MoonBack.BackValId],
      op [MoonBack.BackIntOp],
      scalar [MoonBack.BackScalar],
      semantics [MoonBack.BackIntSemantics],
      lhs [MoonBack.BackValId],
      rhs [MoonBack.BackValId],
    },
    CmdBitBinary {
      variant_unique,
      dst [MoonBack.BackValId],
      op [MoonBack.BackBitOp],
      scalar [MoonBack.BackScalar],
      lhs [MoonBack.BackValId],
      rhs [MoonBack.BackValId],
    },
    CmdBitNot {
      variant_unique,
      dst [MoonBack.BackValId],
      scalar [MoonBack.BackScalar],
      field. value [MoonBack.BackValId],
    },
    CmdShift {
      variant_unique,
      dst [MoonBack.BackValId],
      op [MoonBack.BackShiftOp],
      scalar [MoonBack.BackScalar],
      lhs [MoonBack.BackValId],
      rhs [MoonBack.BackValId],
    },
    CmdRotate {
      variant_unique,
      dst [MoonBack.BackValId],
      op [MoonBack.BackRotateOp],
      scalar [MoonBack.BackScalar],
      lhs [MoonBack.BackValId],
      rhs [MoonBack.BackValId],
    },
    CmdFloatBinary {
      variant_unique,
      dst [MoonBack.BackValId],
      op [MoonBack.BackFloatOp],
      scalar [MoonBack.BackScalar],
      semantics [MoonBack.BackFloatSemantics],
      lhs [MoonBack.BackValId],
      rhs [MoonBack.BackValId],
    },
    CmdMemcpy {
      variant_unique,
      dst [MoonBack.BackValId],
      src [MoonBack.BackValId],
      len [MoonBack.BackValId],
    },
    CmdMemset {
      variant_unique,
      dst [MoonBack.BackValId],
      byte [MoonBack.BackValId],
      len [MoonBack.BackValId],
    },
    CmdMemcmp {
      variant_unique,
      dst [MoonBack.BackValId],
      left [MoonBack.BackValId],
      right [MoonBack.BackValId],
      len [MoonBack.BackValId],
    },
    CmdSelect {
      variant_unique,
      dst [MoonBack.BackValId],
      field. ty [MoonBack.BackShape],
      cond [MoonBack.BackValId],
      then_value [MoonBack.BackValId],
      else_value [MoonBack.BackValId],
    },
    CmdFma {
      variant_unique,
      dst [MoonBack.BackValId],
      field. ty [MoonBack.BackScalar],
      semantics [MoonBack.BackFloatSemantics],
      a [MoonBack.BackValId],
      b [MoonBack.BackValId],
      c [MoonBack.BackValId],
    },
    CmdVecSplat {
      variant_unique,
      dst [MoonBack.BackValId],
      field. ty [MoonBack.BackVec],
      field. value [MoonBack.BackValId],
    },
    CmdVecBinary {
      variant_unique,
      dst [MoonBack.BackValId],
      op [MoonBack.BackVecBinaryOp],
      field. ty [MoonBack.BackVec],
      lhs [MoonBack.BackValId],
      rhs [MoonBack.BackValId],
    },
    CmdVecCompare {
      variant_unique,
      dst [MoonBack.BackValId],
      op [MoonBack.BackVecCompareOp],
      field. ty [MoonBack.BackVec],
      lhs [MoonBack.BackValId],
      rhs [MoonBack.BackValId],
    },
    CmdVecSelect {
      variant_unique,
      dst [MoonBack.BackValId],
      field. ty [MoonBack.BackVec],
      mask [MoonBack.BackValId],
      then_value [MoonBack.BackValId],
      else_value [MoonBack.BackValId],
    },
    CmdVecMask {
      variant_unique,
      dst [MoonBack.BackValId],
      op [MoonBack.BackVecMaskOp],
      field. ty [MoonBack.BackVec],
      args [many [MoonBack.BackValId]],
    },
    CmdVecInsertLane {
      variant_unique,
      dst [MoonBack.BackValId],
      field. ty [MoonBack.BackVec],
      field. value [MoonBack.BackValId],
      lane_value [MoonBack.BackValId],
      lane [number],
    },
    CmdVecExtractLane {
      variant_unique,
      dst [MoonBack.BackValId],
      field. ty [MoonBack.BackScalar],
      field. value [MoonBack.BackValId],
      lane [number],
    },
    CmdCall {
      variant_unique,
      result [MoonBack.BackCallResult],
      target [MoonBack.BackCallTarget],
      sig [MoonBack.BackSigId],
      args [many [MoonBack.BackValId]],
    },
    CmdJump {
      variant_unique,
      dest [MoonBack.BackBlockId],
      args [many [MoonBack.BackValId]],
    },
    CmdBrIf {
      variant_unique,
      cond [MoonBack.BackValId],
      then_block [MoonBack.BackBlockId],
      then_args [many [MoonBack.BackValId]],
      else_block [MoonBack.BackBlockId],
      else_args [many [MoonBack.BackValId]],
    },
    CmdSwitchInt {
      variant_unique,
      field. value [MoonBack.BackValId],
      field. ty [MoonBack.BackScalar],
      cases [many [MoonBack.BackSwitchCase]],
      default_dest [MoonBack.BackBlockId],
    },
    CmdReturnVoid,
    CmdReturnValue { variant_unique, field. value [MoonBack.BackValId], },
    CmdTrap,
    CmdFinishFunc { variant_unique, func [MoonBack.BackFuncId], },
    CmdFinalizeModule,
  },
  sum. BackShapeRequirement {
    BackShapeRequiresScalar,
    BackShapeRequiresVector,
    BackShapeAllowsScalarOrVector,
  },
  sum. BackProgramFact {
    BackFactCreateSig { variant_unique, index [number], sig [MoonBack.BackSigId], },
    BackFactSigRef { variant_unique, index [number], sig [MoonBack.BackSigId], },
    BackFactDeclareData { variant_unique, index [number], data [MoonBack.BackDataId], },
    BackFactDataRef { variant_unique, index [number], data [MoonBack.BackDataId], },
    BackFactDeclareFunc { variant_unique, index [number], func [MoonBack.BackFuncId], },
    BackFactFuncRef { variant_unique, index [number], func [MoonBack.BackFuncId], },
    BackFactDeclareExtern { variant_unique, index [number], func [MoonBack.BackExternId], },
    BackFactExternRef { variant_unique, index [number], func [MoonBack.BackExternId], },
    BackFactBeginFunc { variant_unique, index [number], func [MoonBack.BackFuncId], },
    BackFactFinishFunc { variant_unique, index [number], func [MoonBack.BackFuncId], },
    BackFactFinalizeModule { variant_unique, index [number], },
    BackFactCreateBlock { variant_unique, index [number], block [MoonBack.BackBlockId], },
    BackFactBlockRef { variant_unique, index [number], block [MoonBack.BackBlockId], },
    BackFactStackSlotDef { variant_unique, index [number], slot [MoonBack.BackStackSlotId], },
    BackFactStackSlotRef { variant_unique, index [number], slot [MoonBack.BackStackSlotId], },
    BackFactValueDef { variant_unique, index [number], field. value [MoonBack.BackValId], },
    BackFactValueUse { variant_unique, index [number], field. value [MoonBack.BackValId], },
    BackFactAccessDef { variant_unique, index [number], access [MoonBack.BackAccessId], },
    BackFactAccessRef { variant_unique, index [number], access [MoonBack.BackAccessId], },
    BackFactShapeUse {
      variant_unique,
      index [number],
      shape [MoonBack.BackShape],
      requirement [MoonBack.BackShapeRequirement],
    },
    BackFactFunctionBodyCommand { variant_unique, index [number], },
  },
  sum. BackValidationIssue {
    BackIssueEmptyProgram,
    BackIssueMissingFinalize,
    BackIssueCommandAfterFinalize { variant_unique, index [number], },
    BackIssueCommandOutsideFunction { variant_unique, index [number], },
    BackIssueNestedFunction {
      variant_unique,
      index [number],
      active [MoonBack.BackFuncId],
      field. next [MoonBack.BackFuncId],
    },
    BackIssueFinishWithoutBegin { variant_unique, index [number], func [MoonBack.BackFuncId], },
    BackIssueFinishWrongFunction {
      variant_unique,
      index [number],
      expected [MoonBack.BackFuncId],
      actual [MoonBack.BackFuncId],
    },
    BackIssueUnfinishedFunction { variant_unique, func [MoonBack.BackFuncId], },
    BackIssueDuplicateSig { variant_unique, index [number], sig [MoonBack.BackSigId], },
    BackIssueDuplicateData { variant_unique, index [number], data [MoonBack.BackDataId], },
    BackIssueDuplicateFunc { variant_unique, index [number], func [MoonBack.BackFuncId], },
    BackIssueDuplicateExtern { variant_unique, index [number], func [MoonBack.BackExternId], },
    BackIssueDuplicateBlock { variant_unique, index [number], block [MoonBack.BackBlockId], },
    BackIssueDuplicateStackSlot {
      variant_unique,
      index [number],
      slot [MoonBack.BackStackSlotId],
    },
    BackIssueDuplicateValue {
      variant_unique,
      index [number],
      field. value [MoonBack.BackValId],
    },
    BackIssueMissingSig { variant_unique, index [number], sig [MoonBack.BackSigId], },
    BackIssueMissingData { variant_unique, index [number], data [MoonBack.BackDataId], },
    BackIssueMissingFunc { variant_unique, index [number], func [MoonBack.BackFuncId], },
    BackIssueMissingExtern { variant_unique, index [number], func [MoonBack.BackExternId], },
    BackIssueMissingBlock { variant_unique, index [number], block [MoonBack.BackBlockId], },
    BackIssueMissingStackSlot {
      variant_unique,
      index [number],
      slot [MoonBack.BackStackSlotId],
    },
    BackIssueMissingValue {
      variant_unique,
      index [number],
      field. value [MoonBack.BackValId],
    },
    BackIssueDuplicateAccess {
      variant_unique,
      index [number],
      access [MoonBack.BackAccessId],
    },
    BackIssueMissingAccess { variant_unique, index [number], access [MoonBack.BackAccessId], },
    BackIssueInvalidAlignment { variant_unique, index [number], bytes [number], },
    BackIssueLoadAccessMode { variant_unique, index [number], mode [MoonBack.BackAccessMode], },
    BackIssueStoreAccessMode {
      variant_unique,
      index [number],
      mode [MoonBack.BackAccessMode],
    },
    BackIssueDereferenceTooSmall {
      variant_unique,
      index [number],
      dereference_bytes [number],
      access_bytes [number],
    },
    BackIssueIntScalarExpected {
      variant_unique,
      index [number],
      scalar [MoonBack.BackScalar],
    },
    BackIssueFloatScalarExpected {
      variant_unique,
      index [number],
      scalar [MoonBack.BackScalar],
    },
    BackIssueBitScalarExpected {
      variant_unique,
      index [number],
      scalar [MoonBack.BackScalar],
    },
    BackIssueShiftScalarExpected {
      variant_unique,
      index [number],
      scalar [MoonBack.BackScalar],
    },
    BackIssueNonTrappingWithoutDereference { variant_unique, index [number], },
    BackIssueCanMoveWithoutNonTrapping { variant_unique, index [number], },
    BackIssueShapeRequiresScalar {
      variant_unique,
      index [number],
      shape [MoonBack.BackShape],
    },
    BackIssueShapeRequiresVector {
      variant_unique,
      index [number],
      shape [MoonBack.BackShape],
    },
  },
  product. BackValidationReport { interned, issues [many [MoonBack.BackValidationIssue]], },
  product. BackCommandCount { interned, command_kind [str], count [number], },
  product. BackMemoryInspection {
    interned,
    index [number],
    access [MoonBack.BackAccessId],
    alignment [MoonBack.BackAlignment],
    dereference [MoonBack.BackDereference],
    trap [MoonBack.BackTrap],
    motion [MoonBack.BackMotion],
    mode [MoonBack.BackAccessMode],
  },
  product. BackAddressInspection { interned, index [number], address [MoonBack.BackAddress], },
  product. BackPointerOffsetInspection {
    interned,
    index [number],
    dst [MoonBack.BackValId],
    base [MoonBack.BackAddressBase],
    index_value [MoonBack.BackValId],
    elem_size [number],
    const_offset [number],
    provenance [MoonBack.BackPointerProvenance],
    bounds [MoonBack.BackPointerBounds],
  },
  product. BackIntSemanticsInspection {
    interned,
    index [number],
    dst [MoonBack.BackValId],
    op [MoonBack.BackIntOp],
    scalar [MoonBack.BackScalar],
    semantics [MoonBack.BackIntSemantics],
  },
  sum. BackFloatSemanticOp {
    BackFloatSemanticBinary { variant_unique, op [MoonBack.BackFloatOp], },
    BackFloatSemanticFma,
  },
  product. BackFloatSemanticsInspection {
    interned,
    index [number],
    dst [MoonBack.BackValId],
    op [MoonBack.BackFloatSemanticOp],
    scalar [MoonBack.BackScalar],
    semantics [MoonBack.BackFloatSemantics],
  },
  product. BackInspectionReport {
    interned,
    command_counts [many [MoonBack.BackCommandCount]],
    memory [many [MoonBack.BackMemoryInspection]],
    addresses [many [MoonBack.BackAddressInspection]],
    pointer_offsets [many [MoonBack.BackPointerOffsetInspection]],
    int_semantics [many [MoonBack.BackIntSemanticsInspection]],
    float_semantics [many [MoonBack.BackFloatSemanticsInspection]],
  },
  product. BackDisasmInspection { interned, func [MoonBack.BackFuncId], text [str], },
  product. BackDiagnosticsReport {
    interned,
    inspection [MoonBack.BackInspectionReport],
    disassembly [many [MoonBack.BackDisasmInspection]],
  },
  sum. BackFlow { BackFallsThrough, BackTerminates, },
  product. BackSigSpec {
    interned,
    params [many [MoonBack.BackScalar]],
    results [many [MoonBack.BackScalar]],
  },
  product. BackStackSlotSpec { interned, size [number], align [number], },
  sum. BackExprLowering {
    BackExprPlan {
      variant_unique,
      cmds [many [MoonBack.Cmd]],
      field. value [MoonBack.BackValId],
      field. ty [MoonBack.BackScalar],
    },
    BackExprTerminated { variant_unique, cmds [many [MoonBack.Cmd]], },
  },
  sum. BackAddrLowering {
    BackAddrWrites { variant_unique, cmds [many [MoonBack.Cmd]], },
    BackAddrTerminated { variant_unique, cmds [many [MoonBack.Cmd]], },
  },
  sum. BackViewLowering {
    BackViewPlan {
      variant_unique,
      cmds [many [MoonBack.Cmd]],
      data [MoonBack.BackValId],
      len [MoonBack.BackValId],
      stride [MoonBack.BackValId],
    },
    BackViewTerminated { variant_unique, cmds [many [MoonBack.Cmd]], },
  },
  sum. BackReturnTarget {
    BackReturnValue,
    BackReturnSret { variant_unique, addr [MoonBack.BackValId], },
  },
  product. BackStmtPlan {
    interned,
    cmds [many [MoonBack.Cmd]],
    flow [MoonBack.BackFlow],
  },
  product. BackFuncPlan { interned, cmds [many [MoonBack.Cmd]], },
  product. BackItemPlan { interned, cmds [many [MoonBack.Cmd]], },
  product. BackProgram { interned, cmds [many [MoonBack.Cmd]], },
  product. BackCommandTape { interned, version [number], command_count [number], payload [str], },
}
