local S = require("moonlift.schema.dsl")
S.use()

return schema. MoonC {
  product. CTypeId { interned, module_name [str], spelling [str], },
  sum. CTypeKind {
    CVoid,
    CScalar { variant_unique, scalar [MoonBack.BackScalar], },
    CPointer { variant_unique, pointee [MoonC.CTypeId], },
    CEnum { variant_unique, scalar [MoonBack.BackScalar], },
    CArray { variant_unique, elem [MoonC.CTypeId], count [number], },
    CStruct,
    CUnion,
    COpaque,
    CFuncPtr { variant_unique, sig [MoonC.CFuncSigId], },
  },
  product. CTypeFact {
    interned,
    field. id [MoonC.CTypeId],
    kind [MoonC.CTypeKind],
    complete [bool],
    size [optional [number]],
    align [optional [number]],
  },
  product. CFieldLayout {
    interned,
    owner [MoonC.CTypeId],
    field. name [str],
    field. type [MoonC.CTypeId],
    offset [number],
    size [number],
    align [number],
    bit_offset [optional [number]],
    bit_width [optional [number]],
  },
  product. CLayoutFact {
    interned,
    field. type [MoonC.CTypeId],
    size [number],
    align [number],
    fields [many [MoonC.CFieldLayout]],
  },
  product. CFuncSigId { interned, text [str], },
  product. CFuncSig {
    interned,
    field. id [MoonC.CFuncSigId],
    params [many [MoonC.CTypeId]],
    result [MoonC.CTypeId],
  },
  product. CExternFunc {
    interned,
    moon_name [str],
    symbol [str],
    sig [MoonC.CFuncSigId],
    library [optional [str]],
  },
  product. CLibrary {
    interned,
    field. name [str],
    link_name [optional [str]],
    path [optional [str]],
    symbols [many [str]],
  },
  product. CBackendName { interned, text [str], },
  product. CBackendLabel { interned, text [str], },
  product. CBackendLocalId { interned, text [str], },
  product. CBackendGlobalId { interned, text [str], },
  product. CBackendHelperId { interned, text [str], },
  product. CBackendFuncSigId { interned, text [str], },
  sum. CBackendDialect { CBackendC99, CBackendC11, CBackendGnuC, CBackendClangC, },
  sum. CBackendPlatform {
    CBackendHostedNative,
    CBackendFreestanding,
    CBackendWasmCapable,
    CBackendEmbedded,
  },
  sum. CBackendEndian { CBackendLittleEndian, CBackendBigEndian, },
  product. CBackendTarget {
    interned,
    dialect [MoonC.CBackendDialect],
    platform [MoonC.CBackendPlatform],
    pointer_bits [number],
    index_bits [number],
    endian [MoonC.CBackendEndian],
    hosted [bool],
  },
  sum. CBackendType {
    CBackendVoid,
    CBackendBool8,
    CBackendScalar { variant_unique, scalar [MoonCore.Scalar], },
    CBackendIndex,
    CBackendDataPtr { variant_unique, pointee [optional [MoonC.CBackendType]], },
    CBackendCodePtr { variant_unique, sig [MoonC.CBackendFuncSigId], },
    CBackendNamed { variant_unique, field. id [MoonC.CTypeId], },
    CBackendArray { variant_unique, elem [MoonC.CBackendType], count [number], },
    CBackendSliceDescriptor { variant_unique, elem [MoonC.CBackendType], },
    CBackendByteSpanDescriptor,
    CBackendViewDescriptor { variant_unique, elem [MoonC.CBackendType], },
    CBackendClosureDescriptor {
      variant_unique,
      sig [MoonC.CBackendFuncSigId],
      ctx [optional [MoonC.CBackendType]],
    },
    CBackendAbiHiddenOutPtr { variant_unique, result [MoonC.CBackendType], },
    CBackendImportedCodePtr { variant_unique, sig [MoonC.CFuncSigId], },
    CBackendVector { variant_unique, elem [MoonC.CBackendType], lanes [number], },
  },
  product. CBackendParam {
    interned,
    field. name [MoonC.CBackendName],
    field. ty [MoonC.CBackendType],
  },
  sum. CBackendFuncLinkage {
    CBackendLinkInternal,
    CBackendLinkExport,
    CBackendLinkExtern,
    CBackendLinkDecl,
    CBackendLinkWrapper,
    CBackendLinkIndirect,
  },
  sum. CBackendAbiParamRole {
    CBackendAbiParamDirect,
    CBackendAbiParamByAddress,
    CBackendAbiParamDescriptor,
    CBackendAbiParamHiddenOut,
  },
  sum. CBackendAbiResultRole {
    CBackendAbiResultVoid,
    CBackendAbiResultDirect,
    CBackendAbiResultByAddress,
    CBackendAbiResultHiddenOut,
    CBackendAbiResultDescriptor,
  },
  product. CBackendAbiParam {
    interned,
    field. name [MoonC.CBackendName],
    source_ty [MoonC.CBackendType],
    lowered_ty [MoonC.CBackendType],
    role [MoonC.CBackendAbiParamRole],
  },
  product. CBackendAbiResult {
    interned,
    source_ty [MoonC.CBackendType],
    lowered_ty [MoonC.CBackendType],
    role [MoonC.CBackendAbiResultRole],
  },
  product. CBackendFuncAbi {
    interned,
    field. id [MoonC.CBackendFuncSigId],
    linkage [MoonC.CBackendFuncLinkage],
    params [many [MoonC.CBackendAbiParam]],
    result [MoonC.CBackendAbiResult],
    imported_sig [optional [MoonC.CFuncSigId]],
  },
  product. CBackendFuncSig {
    interned,
    field. id [MoonC.CBackendFuncSigId],
    params [many [MoonC.CBackendType]],
    result [MoonC.CBackendType],
  },
  product. CBackendField {
    interned,
    field. name [MoonC.CBackendName],
    field. ty [MoonC.CBackendType],
    offset [optional [number]],
    size [optional [number]],
    align [optional [number]],
  },
  sum. CBackendTypeDecl {
    CBackendTypedef {
      variant_unique,
      field. id [MoonC.CTypeId],
      field. ty [MoonC.CBackendType],
    },
    CBackendStructDecl {
      variant_unique,
      field. id [MoonC.CTypeId],
      fields [many [MoonC.CBackendField]],
      size [optional [number]],
      align [optional [number]],
    },
    CBackendUnionDecl {
      variant_unique,
      field. id [MoonC.CTypeId],
      fields [many [MoonC.CBackendField]],
      size [optional [number]],
      align [optional [number]],
    },
    CBackendOpaqueDecl { variant_unique, field. id [MoonC.CTypeId], },
  },
  sum. CBackendResidence {
    CBackendResidenceValue,
    CBackendResidenceAddressed,
    CBackendResidenceAggregate,
    CBackendResidenceDescriptor,
  },
  sum. CBackendLocalInitState {
    CBackendLocalUninitialized,
    CBackendLocalZeroInitialized,
    CBackendLocalInitialized,
  },
  sum. CBackendPlace {
    CBackendPlaceLocal {
      variant_unique,
      field. local_id [MoonC.CBackendLocalId],
      field. ty [MoonC.CBackendType],
    },
    CBackendPlaceGlobal {
      variant_unique,
      global [MoonC.CBackendGlobalId],
      field. ty [MoonC.CBackendType],
    },
    CBackendPlaceDeref {
      variant_unique,
      addr [MoonC.CBackendAtom],
      field. ty [MoonC.CBackendType],
      align [optional [number]],
    },
    CBackendPlaceField {
      variant_unique,
      base [MoonC.CBackendPlace],
      field. field [MoonC.CBackendName],
      field. ty [MoonC.CBackendType],
      offset [number],
      size [optional [number]],
      align [optional [number]],
    },
    CBackendPlaceIndex {
      variant_unique,
      base [MoonC.CBackendPlace],
      index [MoonC.CBackendAtom],
      field. ty [MoonC.CBackendType],
      elem_size [number],
    },
    CBackendPlaceBytes {
      variant_unique,
      base [MoonC.CBackendAtom],
      offset [number],
      field. ty [MoonC.CBackendType],
      size [number],
      align [number],
    },
  },
  product. CBackendLocalStorage {
    interned,
    field. id [MoonC.CBackendLocalId],
    field. name [MoonC.CBackendName],
    field. ty [MoonC.CBackendType],
    residence [MoonC.CBackendResidence],
    init_state [MoonC.CBackendLocalInitState],
    address_taken [bool],
  },
  sum. CBackendRelocTarget {
    CBackendRelocGlobal { variant_unique, global [MoonC.CBackendGlobalId], },
    CBackendRelocFunc { variant_unique, func [MoonC.CBackendName], },
    CBackendRelocExtern { variant_unique, extern [MoonC.CBackendName], },
  },
  sum. CBackendDataInit {
    CBackendDataZero { variant_unique, offset [number], size [number], },
    CBackendDataBytes { variant_unique, offset [number], bytes [str], },
    CBackendDataScalar {
      variant_unique,
      offset [number],
      field. ty [MoonC.CBackendType],
      literal [MoonCore.Literal],
    },
    CBackendDataReloc {
      variant_unique,
      offset [number],
      target [MoonC.CBackendRelocTarget],
      addend [number],
    },
  },
  product. CBackendGlobal {
    interned,
    field. id [MoonC.CBackendGlobalId],
    field. name [MoonC.CBackendName],
    visibility [MoonCore.Visibility],
    field. ty [MoonC.CBackendType],
    size [number],
    align [number],
    inits [many [MoonC.CBackendDataInit]],
  },
  product. CBackendExtern {
    interned,
    field. name [MoonC.CBackendName],
    symbol [str],
    sig [MoonC.CBackendFuncSigId],
    header [optional [str]],
  },
  sum. CBackendAtom {
    CBackendAtomLocal { variant_unique, field. local_id [MoonC.CBackendLocalId], },
    CBackendAtomGlobal { variant_unique, global [MoonC.CBackendGlobalId], },
    CBackendAtomLiteral {
      variant_unique,
      field. ty [MoonC.CBackendType],
      literal [MoonCore.Literal],
    },
    CBackendAtomNull { variant_unique, field. ty [MoonC.CBackendType], },
  },
  sum. CBackendRValue {
    CBackendRAtom { variant_unique, atom [MoonC.CBackendAtom], },
    CBackendRCompare {
      variant_unique,
      op [MoonCore.CmpOp],
      field. ty [MoonC.CBackendType],
      lhs [MoonC.CBackendAtom],
      rhs [MoonC.CBackendAtom],
    },
    CBackendRCast {
      variant_unique,
      op [MoonCore.MachineCastOp],
      to [MoonC.CBackendType],
      field. value [MoonC.CBackendAtom],
    },
    CBackendRSelect {
      variant_unique,
      field. ty [MoonC.CBackendType],
      cond [MoonC.CBackendAtom],
      then_value [MoonC.CBackendAtom],
      else_value [MoonC.CBackendAtom],
    },
    CBackendRFuncAddr {
      variant_unique,
      func [MoonC.CBackendName],
      sig [MoonC.CBackendFuncSigId],
    },
    CBackendRExternAddr {
      variant_unique,
      extern [MoonC.CBackendName],
      sig [MoonC.CBackendFuncSigId],
    },
    CBackendRPtrOffset {
      variant_unique,
      base [MoonC.CBackendAtom],
      index [MoonC.CBackendAtom],
      elem_size [number],
      const_offset [number],
    },
    CBackendRAddrOfPlace { variant_unique, place [MoonC.CBackendPlace], },
  },
  sum. CBackendTrapMode { CBackendMayTrap, CBackendMustNotTrap, CBackendCheckedTrap, },
  product. CBackendMemoryAccess {
    interned,
    field. ty [MoonC.CBackendType],
    align [number],
    trap [MoonC.CBackendTrapMode],
    volatile [bool],
    ordering [optional [MoonCore.AtomicOrdering]],
  },
  sum. CBackendIntOverflow {
    CBackendIntWrap,
    CBackendIntTrapOnOverflow,
    CBackendIntAssumeNoOverflow,
  },
  sum. CBackendDivMode { CBackendDivTrapOnZero, CBackendDivTrapOnZeroOrOverflow, },
  sum. CBackendShiftMode { CBackendShiftMaskCount, CBackendShiftTrapOutOfRange, },
  sum. CBackendTargetFeature {
    CBackendFeatureC11Atomics,
    CBackendFeatureLibm,
    CBackendFeatureBuiltinOverflow,
    CBackendFeatureBuiltinBitops,
    CBackendFeatureUnalignedAccess,
    CBackendFeatureStaticAssert,
    CBackendFeatureHostedRuntime,
  },
  product. CBackendLayoutAssertion {
    interned,
    field. id [MoonC.CTypeId],
    size [number],
    align [number],
  },
  sum. CBackendHelperKind {
    CBackendHelperUnary {
      variant_unique,
      op [MoonCore.UnaryOp],
      field. ty [MoonC.CBackendType],
    },
    CBackendHelperBoolNormalize { variant_unique, field. ty [MoonC.CBackendType], },
    CBackendHelperCast {
      variant_unique,
      op [MoonCore.MachineCastOp],
      from [MoonC.CBackendType],
      to [MoonC.CBackendType],
    },
    CBackendHelperPtrOffset {
      variant_unique,
      pointee [MoonC.CBackendType],
      elem_size [number],
      checked [bool],
    },
    CBackendHelperIntBinary {
      variant_unique,
      op [MoonCore.BinaryOp],
      field. ty [MoonC.CBackendType],
      overflow [MoonC.CBackendIntOverflow],
    },
    CBackendHelperDivRem {
      variant_unique,
      op [MoonCore.BinaryOp],
      field. ty [MoonC.CBackendType],
      mode [MoonC.CBackendDivMode],
    },
    CBackendHelperShift {
      variant_unique,
      op [MoonCore.BinaryOp],
      field. ty [MoonC.CBackendType],
      mode [MoonC.CBackendShiftMode],
    },
    CBackendHelperIntrinsic {
      variant_unique,
      intrinsic [MoonCore.Intrinsic],
      field. ty [MoonC.CBackendType],
    },
    CBackendHelperLoad { variant_unique, access [MoonC.CBackendMemoryAccess], },
    CBackendHelperStore { variant_unique, access [MoonC.CBackendMemoryAccess], },
    CBackendHelperAtomicLoad { variant_unique, access [MoonC.CBackendMemoryAccess], },
    CBackendHelperAtomicStore { variant_unique, access [MoonC.CBackendMemoryAccess], },
    CBackendHelperAtomicRmw {
      variant_unique,
      op [MoonCore.AtomicRmwOp],
      access [MoonC.CBackendMemoryAccess],
    },
    CBackendHelperAtomicCas {
      variant_unique,
      access [MoonC.CBackendMemoryAccess],
      success_ordering [MoonCore.AtomicOrdering],
      failure_ordering [MoonCore.AtomicOrdering],
    },
    CBackendHelperAtomicFence { variant_unique, ordering [MoonCore.AtomicOrdering], },
    CBackendHelperMemcpy,
    CBackendHelperTypedMemcpy {
      variant_unique,
      field. ty [MoonC.CBackendType],
      size [number],
      align [number],
    },
    CBackendHelperMemset,
    CBackendHelperTypedMemset {
      variant_unique,
      field. ty [MoonC.CBackendType],
      size [number],
      align [number],
    },
    CBackendHelperMemcmp,
    CBackendHelperLayoutAssert { variant_unique, assertion [MoonC.CBackendLayoutAssertion], },
    CBackendHelperRequireFeature {
      variant_unique,
      feature [MoonC.CBackendTargetFeature],
      reason [str],
    },
    CBackendHelperTrap,
  },
  product. CBackendHelperUse {
    interned,
    field. id [MoonC.CBackendHelperId],
    kind [MoonC.CBackendHelperKind],
  },
  product. CBackendLocal {
    interned,
    field. id [MoonC.CBackendLocalId],
    field. name [MoonC.CBackendName],
    field. ty [MoonC.CBackendType],
  },
  product. CBackendAggregateFieldInit {
    interned,
    field. field [MoonC.CBackendName],
    field. value [MoonC.CBackendAtom],
    offset [optional [number]],
  },
  product. CBackendArrayElemInit {
    interned,
    index [number],
    field. value [MoonC.CBackendAtom],
  },
  sum. CBackendCallTarget {
    CBackendCallDirect { variant_unique, func [MoonC.CBackendName], },
    CBackendCallExtern { variant_unique, extern [MoonC.CBackendName], },
    CBackendCallIndirect {
      variant_unique,
      callee [MoonC.CBackendAtom],
      sig [MoonC.CBackendFuncSigId],
    },
    CBackendCallClosure {
      variant_unique,
      closure [MoonC.CBackendAtom],
      sig [MoonC.CBackendFuncSigId],
    },
  },
  sum. CBackendStmt {
    CBackendAssign {
      variant_unique,
      dst [MoonC.CBackendLocalId],
      rhs [MoonC.CBackendRValue],
    },
    CBackendHelperCall {
      variant_unique,
      dst [optional [MoonC.CBackendLocalId]],
      helper [MoonC.CBackendHelperId],
      args [many [MoonC.CBackendAtom]],
    },
    CBackendLoad {
      variant_unique,
      dst [MoonC.CBackendLocalId],
      addr [MoonC.CBackendAtom],
      access [MoonC.CBackendMemoryAccess],
    },
    CBackendStore {
      variant_unique,
      addr [MoonC.CBackendAtom],
      field. value [MoonC.CBackendAtom],
      access [MoonC.CBackendMemoryAccess],
    },
    CBackendPlaceLoad {
      variant_unique,
      dst [MoonC.CBackendLocalId],
      place [MoonC.CBackendPlace],
    },
    CBackendPlaceStore {
      variant_unique,
      place [MoonC.CBackendPlace],
      field. value [MoonC.CBackendAtom],
    },
    CBackendZeroInit {
      variant_unique,
      place [MoonC.CBackendPlace],
      field. ty [MoonC.CBackendType],
      size [number],
    },
    CBackendAggregateInit {
      variant_unique,
      place [MoonC.CBackendPlace],
      field. ty [MoonC.CBackendType],
      fields [many [MoonC.CBackendAggregateFieldInit]],
    },
    CBackendArrayInit {
      variant_unique,
      place [MoonC.CBackendPlace],
      field. ty [MoonC.CBackendType],
      elems [many [MoonC.CBackendArrayElemInit]],
    },
    CBackendCall {
      variant_unique,
      dst [optional [MoonC.CBackendLocalId]],
      target [MoonC.CBackendCallTarget],
      args [many [MoonC.CBackendAtom]],
    },
    CBackendComment { variant_unique, text [str], },
  },
  product. CBackendSwitchCase {
    interned,
    literal [MoonCore.Literal],
    dest [MoonC.CBackendLabel],
    args [many [MoonC.CBackendAtom]],
  },
  sum. CBackendTerminator {
    CBackendGoto {
      variant_unique,
      dest [MoonC.CBackendLabel],
      args [many [MoonC.CBackendAtom]],
    },
    CBackendIfGoto {
      variant_unique,
      cond [MoonC.CBackendAtom],
      then_dest [MoonC.CBackendLabel],
      then_args [many [MoonC.CBackendAtom]],
      else_dest [MoonC.CBackendLabel],
      else_args [many [MoonC.CBackendAtom]],
    },
    CBackendSwitchGoto {
      variant_unique,
      field. value [MoonC.CBackendAtom],
      cases [many [MoonC.CBackendSwitchCase]],
      default_dest [MoonC.CBackendLabel],
      default_args [many [MoonC.CBackendAtom]],
    },
    CBackendReturnVoid,
    CBackendReturn { variant_unique, field. value [MoonC.CBackendAtom], },
    CBackendTrap,
  },
  product. CBackendBlockParam {
    interned,
    field. local_id [MoonC.CBackendLocalId],
    field. ty [MoonC.CBackendType],
  },
  product. CBackendBlock {
    interned,
    label [MoonC.CBackendLabel],
    params [many [MoonC.CBackendBlockParam]],
    stmts [many [MoonC.CBackendStmt]],
    term [MoonC.CBackendTerminator],
  },
  product. CBackendFunc {
    interned,
    field. name [MoonC.CBackendName],
    symbol [str],
    visibility [MoonCore.Visibility],
    sig [MoonC.CBackendFuncSigId],
    params [many [MoonC.CBackendLocal]],
    locals [many [MoonC.CBackendLocal]],
    blocks [many [MoonC.CBackendBlock]],
  },
  product. CBackendUnit {
    interned,
    module_name [str],
    target [MoonC.CBackendTarget],
    sigs [many [MoonC.CBackendFuncSig]],
    types [many [MoonC.CBackendTypeDecl]],
    globals [many [MoonC.CBackendGlobal]],
    externs [many [MoonC.CBackendExtern]],
    helpers [many [MoonC.CBackendHelperUse]],
    funcs [many [MoonC.CBackendFunc]],
  },
  sum. CBackendValidationIssue {
    CBackendIssueDuplicateSig { variant_unique, sig [MoonC.CBackendFuncSigId], },
    CBackendIssueMissingSig { variant_unique, sig [MoonC.CBackendFuncSigId], },
    CBackendIssueDuplicateFunc { variant_unique, func [MoonC.CBackendName], },
    CBackendIssueMissingFunc { variant_unique, func [MoonC.CBackendName], },
    CBackendIssueDuplicateExtern { variant_unique, extern [MoonC.CBackendName], },
    CBackendIssueMissingExtern { variant_unique, extern [MoonC.CBackendName], },
    CBackendIssueDuplicateGlobal { variant_unique, global [MoonC.CBackendGlobalId], },
    CBackendIssueMissingGlobal { variant_unique, global [MoonC.CBackendGlobalId], },
    CBackendIssueDuplicateHelper { variant_unique, helper [MoonC.CBackendHelperId], },
    CBackendIssueMissingHelper { variant_unique, helper [MoonC.CBackendHelperId], },
    CBackendIssueDuplicateLocal {
      variant_unique,
      func [MoonC.CBackendName],
      field. local_id [MoonC.CBackendLocalId],
    },
    CBackendIssueMissingLocal {
      variant_unique,
      func [MoonC.CBackendName],
      field. local_id [MoonC.CBackendLocalId],
    },
    CBackendIssueDuplicateLabel {
      variant_unique,
      func [MoonC.CBackendName],
      label [MoonC.CBackendLabel],
    },
    CBackendIssueMissingLabel {
      variant_unique,
      func [MoonC.CBackendName],
      label [MoonC.CBackendLabel],
    },
    CBackendIssueInvalidCName {
      variant_unique,
      site [str],
      field. name [MoonC.CBackendName],
    },
    CBackendIssueDuplicateCName {
      variant_unique,
      site [str],
      field. name [MoonC.CBackendName],
    },
    CBackendIssueFuncSigMismatch {
      variant_unique,
      func [MoonC.CBackendName],
      expected [MoonC.CBackendType],
      actual [MoonC.CBackendType],
    },
    CBackendIssueBlockArgCount {
      variant_unique,
      func [MoonC.CBackendName],
      label [MoonC.CBackendLabel],
      expected [number],
      actual [number],
    },
    CBackendIssueBlockArgType {
      variant_unique,
      func [MoonC.CBackendName],
      label [MoonC.CBackendLabel],
      index [number],
      expected [MoonC.CBackendType],
      actual [MoonC.CBackendType],
    },
    CBackendIssueCallArgCount {
      variant_unique,
      site [str],
      sig [MoonC.CBackendFuncSigId],
      expected [number],
      actual [number],
    },
    CBackendIssueCallArgType {
      variant_unique,
      site [str],
      sig [MoonC.CBackendFuncSigId],
      index [number],
      expected [MoonC.CBackendType],
      actual [MoonC.CBackendType],
    },
    CBackendIssueCallResultType {
      variant_unique,
      site [str],
      sig [MoonC.CBackendFuncSigId],
      expected [MoonC.CBackendType],
      actual [MoonC.CBackendType],
    },
    CBackendIssueIndirectCallNonCodePtr {
      variant_unique,
      site [str],
      actual [MoonC.CBackendType],
    },
    CBackendIssueDataCodePtrConfusion {
      variant_unique,
      site [str],
      field. ty [MoonC.CBackendType],
    },
    CBackendIssueHelperMismatch {
      variant_unique,
      helper [MoonC.CBackendHelperId],
      message [str],
    },
    CBackendIssueInvalidAlignment { variant_unique, site [str], align [number], },
    CBackendIssueDataInitOutOfBounds {
      variant_unique,
      global [MoonC.CBackendGlobalId],
      offset [number],
      size [number],
      global_size [number],
    },
    CBackendIssueCoverageMissing { variant_unique, field. sum [str], variant [str], },
    CBackendIssueInvalidTargetFeature {
      variant_unique,
      feature [MoonC.CBackendTargetFeature],
      reason [str],
    },
    CBackendIssueLayoutAssertionMissing { variant_unique, field. id [MoonC.CTypeId], },
    CBackendIssueLayoutAssertionMismatch {
      variant_unique,
      field. id [MoonC.CTypeId],
      expected_size [number],
      actual_size [number],
      expected_align [number],
      actual_align [number],
    },
    CBackendIssuePlaceTypeMismatch {
      variant_unique,
      site [str],
      place [MoonC.CBackendPlace],
      expected [MoonC.CBackendType],
      actual [MoonC.CBackendType],
    },
    CBackendIssueLoadStoreTypeMismatch {
      variant_unique,
      site [str],
      expected [MoonC.CBackendType],
      actual [MoonC.CBackendType],
    },
    CBackendIssueUnmaterializedAddressTakenValue {
      variant_unique,
      func [MoonC.CBackendName],
      field. local_id [MoonC.CBackendLocalId],
    },
    CBackendIssueUninitializedLocal {
      variant_unique,
      func [MoonC.CBackendName],
      field. local_id [MoonC.CBackendLocalId],
    },
    CBackendIssueHelperSignatureMismatch {
      variant_unique,
      helper [MoonC.CBackendHelperId],
      expected [many [MoonC.CBackendType]],
      actual [many [MoonC.CBackendType]],
    },
    CBackendIssueDataInitPrecisionFailure {
      variant_unique,
      global [MoonC.CBackendGlobalId],
      offset [number],
      field. ty [MoonC.CBackendType],
      literal [MoonCore.Literal],
      reason [str],
    },
    CBackendIssueDataRelocFailure {
      variant_unique,
      global [MoonC.CBackendGlobalId],
      offset [number],
      target [MoonC.CBackendRelocTarget],
      reason [str],
    },
    CBackendIssueAbiMismatch {
      variant_unique,
      site [str],
      sig [MoonC.CBackendFuncSigId],
      reason [str],
    },
    CBackendIssueUnsupportedConstruct {
      variant_unique,
      field. sum [str],
      variant [str],
      reason [str],
    },
    CBackendIssueUnreachableConstruct {
      variant_unique,
      field. sum [str],
      variant [str],
      reason [str],
    },
  },
  product. CBackendStorageRecord {
    interned,
    func [MoonC.CBackendName],
    storage [many [MoonC.CBackendLocalStorage]],
  },
  product. CBackendValidationInput {
    interned,
    unit [MoonC.CBackendUnit],
    storage [many [MoonC.CBackendStorageRecord]],
    abi_issues [many [MoonC.CBackendValidationIssue]],
  },
  product. CBackendValidationReport {
    interned,
    issues [many [MoonC.CBackendValidationIssue]],
  },
}
