local S = require("moonlift.schema.dsl")
S.use()

return schema. MoonCAst {
  sum. CKeyword {
    CKwAuto,
    CKwBreak,
    CKwCase,
    CKwChar,
    CKwConst,
    CKwContinue,
    CKwDefault,
    CKwDo,
    CKwDouble,
    CKwElse,
    CKwEnum,
    CKwExtern,
    CKwFloat,
    CKwFor,
    CKwGoto,
    CKwIf,
    CKwInline,
    CKwInt,
    CKwLong,
    CKwRegister,
    CKwRestrict,
    CKwReturn,
    CKwShort,
    CKwSigned,
    CKwSizeof,
    CKwStatic,
    CKwStruct,
    CKwSwitch,
    CKwTypedef,
    CKwUnion,
    CKwUnsigned,
    CKwVoid,
    CKwVolatile,
    CKwWhile,
    CKwBool,
    CKwComplex,
    CKwInline2,
    CKwRestrict2,
  },
  sum. CDirectiveKind {
    CDirDefine,
    CDirUndef,
    CDirInclude,
    CDirIf,
    CDirIfdef,
    CDirIfndef,
    CDirElif,
    CDirElse,
    CDirEndif,
    CDirError,
    CDirPragma,
    CDirLine,
  },
  sum. CToken {
    CTokIdent { variant_unique, field. name [str], },
    CTokKeyword { variant_unique, kw [MoonCAst.CKeyword], },
    CTokIntLiteral { variant_unique, raw [str], suffix [str], },
    CTokFloatLiteral { variant_unique, raw [str], suffix [str], },
    CTokCharLiteral { variant_unique, raw [str], },
    CTokStringLiteral { variant_unique, raw [str], prefix [str], },
    CTokPunct { variant_unique, text [str], },
    CTokDirective { variant_unique, kind [MoonCAst.CDirectiveKind], },
    CTokNewline,
    CTokEOF,
  },
  sum. CppDirective {
    CCppDefine { variant_unique, macro [MoonCAst.CMacro], },
    CCppUndef { variant_unique, field. name [str], },
    CCppInclude { variant_unique, kind [MoonCAst.CIncludeKind], path [str], },
    CCppIf { variant_unique, tokens [many [MoonCAst.CToken]], },
    CCppIfdef { variant_unique, field. name [str], },
    CCppIfndef { variant_unique, field. name [str], },
    CCppElif { variant_unique, tokens [many [MoonCAst.CToken]], },
    CCppElse,
    CCppEndif,
    CCppError { variant_unique, message [str], },
    CCppPragma { variant_unique, tokens [many [MoonCAst.CToken]], },
    CCppLine { variant_unique, line [number], file [optional [str]], },
  },
  sum. CIncludeKind { CIncludeAngle, CIncludeQuoted, },
  sum. CMacroKind {
    CObjectLike,
    CFunctionLike { variant_unique, params [many [str]], variadic [bool], },
  },
  product. CMacro {
    interned,
    field. name [str],
    kind [MoonCAst.CMacroKind],
    body [many [MoonCAst.CToken]],
    location [MoonSource.SourceRange],
  },
  product. TranslationUnit { interned, items [many [MoonCAst.TopLevelItem]], },
  sum. TopLevelItem {
    CATopDecl { variant_unique, decl [MoonCAst.Decl], },
    CATopFuncDef { variant_unique, func [MoonCAst.FuncDef], },
    CATopCpp { variant_unique, directive [MoonCAst.CppDirective], },
  },
  sum. StorageClass {
    CStorageTypedef,
    CStorageExtern,
    CStorageStatic,
    CStorageAuto,
    CStorageRegister,
  },
  sum. Qualifier { CQualConst, CQualRestrict, CQualVolatile, CQualInline, },
  sum. TypeSpec {
    CTyVoid,
    CTyChar,
    CTyShort,
    CTyInt,
    CTyLong,
    CTyLongLong,
    CTyFloat,
    CTyDouble,
    CTyLongDouble,
    CTySigned,
    CTyUnsigned,
    CTyBool,
    CTyComplex,
    CTyStructOrUnion {
      variant_unique,
      kind [MoonCAst.StructKind],
      field. name [optional [str]],
      members [optional [many [MoonCAst.FieldDecl]]],
    },
    CTyEnum {
      variant_unique,
      field. name [optional [str]],
      enumerators [optional [many [MoonCAst.Enumerator]]],
    },
    CTyNamed { variant_unique, field. name [str], },
    CTyTypeof { variant_unique, field. expr [MoonCAst.Expr], },
  },
  sum. StructKind { CStructKindStruct, CStructKindUnion, },
  product. Decl {
    interned,
    storage [optional [MoonCAst.StorageClass]],
    qualifiers [many [MoonCAst.Qualifier]],
    type_spec [MoonCAst.TypeSpec],
    declarators [many [MoonCAst.Declarator]],
  },
  product. Declarator {
    interned,
    field. name [optional [str]],
    derived [many [MoonCAst.DerivedType]],
    initializer [optional [MoonCAst.Initializer]],
  },
  sum. DerivedType {
    CDerivedPointer { variant_unique, qualifiers [many [MoonCAst.Qualifier]], },
    CDerivedArray { variant_unique, size [optional [MoonCAst.Expr]], },
    CDerivedFunction { variant_unique, params [many [MoonCAst.ParamDecl]], variadic [bool], },
  },
  product. FieldDecl {
    interned,
    type_spec [MoonCAst.TypeSpec],
    declarators [many [MoonCAst.FieldDeclarator]],
  },
  product. FieldDeclarator {
    interned,
    declarator [optional [MoonCAst.Declarator]],
    bit_width [optional [MoonCAst.Expr]],
  },
  product. Enumerator {
    interned,
    field. name [str],
    field. value [optional [MoonCAst.Expr]],
  },
  product. ParamDecl {
    interned,
    type_spec [MoonCAst.TypeSpec],
    qualifiers [many [MoonCAst.Qualifier]],
    declarator [optional [MoonCAst.Declarator]],
  },
  product. FuncDef {
    interned,
    storage [optional [MoonCAst.StorageClass]],
    qualifiers [many [MoonCAst.Qualifier]],
    type_spec [MoonCAst.TypeSpec],
    declarator [MoonCAst.Declarator],
    body [MoonCAst.Stmt],
  },
  product. TypeName {
    interned,
    type_spec [MoonCAst.TypeSpec],
    derived [many [MoonCAst.DerivedType]],
  },
  sum. Expr {
    CEIntLit { variant_unique, raw [str], suffix [str], },
    CEFloatLit { variant_unique, raw [str], suffix [str], },
    CECharLit { variant_unique, raw [str], },
    CEStrLit { variant_unique, raw [str], },
    CEBoolLit { variant_unique, field. value [bool], },
    CEIdent { variant_unique, field. name [str], },
    CEParen { variant_unique, field. expr [MoonCAst.Expr], },
    CEPreInc { variant_unique, operand [MoonCAst.Expr], },
    CEPreDec { variant_unique, operand [MoonCAst.Expr], },
    CEPostInc { variant_unique, operand [MoonCAst.Expr], },
    CEPostDec { variant_unique, operand [MoonCAst.Expr], },
    CEAddrOf { variant_unique, operand [MoonCAst.Expr], },
    CEDeref { variant_unique, operand [MoonCAst.Expr], },
    CEPlus { variant_unique, operand [MoonCAst.Expr], },
    CEMinus { variant_unique, operand [MoonCAst.Expr], },
    CEBitNot { variant_unique, operand [MoonCAst.Expr], },
    CENot { variant_unique, operand [MoonCAst.Expr], },
    CESizeofExpr { variant_unique, field. expr [MoonCAst.Expr], },
    CESizeofType { variant_unique, type_name [MoonCAst.TypeName], },
    CECast {
      variant_unique,
      type_name [MoonCAst.TypeName],
      field. expr [MoonCAst.Expr],
    },
    CEBinary {
      variant_unique,
      op [MoonCAst.BinaryOp],
      left [MoonCAst.Expr],
      right [MoonCAst.Expr],
    },
    CETernary {
      variant_unique,
      cond [MoonCAst.Expr],
      then_expr [MoonCAst.Expr],
      else_expr [MoonCAst.Expr],
    },
    CEAssign {
      variant_unique,
      op [MoonCAst.AssignOp],
      left [MoonCAst.Expr],
      right [MoonCAst.Expr],
    },
    CEDot { variant_unique, base [MoonCAst.Expr], field. field [str], },
    CEArrow { variant_unique, base [MoonCAst.Expr], field. field [str], },
    CESubscript { variant_unique, base [MoonCAst.Expr], index [MoonCAst.Expr], },
    CECall { variant_unique, callee [MoonCAst.Expr], args [many [MoonCAst.Expr]], },
    CECompoundLit {
      variant_unique,
      type_name [MoonCAst.TypeName],
      initializer [MoonCAst.Initializer],
    },
    CEStmtExpr {
      variant_unique,
      items [many [MoonCAst.BlockItem]],
      result [MoonCAst.Expr],
    },
    CEComma { variant_unique, left [MoonCAst.Expr], right [MoonCAst.Expr], },
  },
  sum. BinaryOp {
    CBinAdd,
    CBinSub,
    CBinMul,
    CBinDiv,
    CBinMod,
    CBinShl,
    CBinShr,
    CBinLt,
    CBinLe,
    CBinGt,
    CBinGe,
    CBinEq,
    CBinNe,
    CBinBitAnd,
    CBinBitXor,
    CBinBitOr,
    CBinLogAnd,
    CBinLogOr,
  },
  sum. AssignOp {
    CAssign,
    CAddAssign,
    CSubAssign,
    CMulAssign,
    CDivAssign,
    CModAssign,
    CShlAssign,
    CShrAssign,
    CAndAssign,
    CXorAssign,
    COrAssign,
  },
  sum. Stmt {
    CSLabeled { variant_unique, label [str], stmt [MoonCAst.Stmt], },
    CSCase { variant_unique, field. value [MoonCAst.Expr], stmt [MoonCAst.Stmt], },
    CSDefault { variant_unique, stmt [MoonCAst.Stmt], },
    CSExpr { variant_unique, field. expr [optional [MoonCAst.Expr]], },
    CSCompound { variant_unique, items [many [MoonCAst.BlockItem]], },
    CSIf {
      variant_unique,
      cond [MoonCAst.Expr],
      then_stmt [MoonCAst.Stmt],
      else_stmt [optional [MoonCAst.Stmt]],
    },
    CSSwitch { variant_unique, cond [MoonCAst.Expr], body [MoonCAst.Stmt], },
    CSWhile { variant_unique, cond [MoonCAst.Expr], body [MoonCAst.Stmt], },
    CSDoWhile { variant_unique, body [MoonCAst.Stmt], cond [MoonCAst.Expr], },
    CSFor {
      variant_unique,
      init [optional [MoonCAst.ForInit]],
      cond [optional [MoonCAst.Expr]],
      incr [optional [MoonCAst.Expr]],
      body [MoonCAst.Stmt],
    },
    CSGoto { variant_unique, label [str], },
    CSContinue,
    CSBreak,
    CSReturn { variant_unique, field. expr [optional [MoonCAst.Expr]], },
  },
  sum. ForInit {
    CFInitExpr { variant_unique, field. expr [MoonCAst.Expr], },
    CFInitDecl { variant_unique, decl [MoonCAst.Decl], },
  },
  sum. BlockItem {
    CBlockDecl { variant_unique, decl [MoonCAst.Decl], },
    CBlockStmt { variant_unique, stmt [MoonCAst.Stmt], },
  },
  sum. Initializer {
    CInitExpr { variant_unique, field. expr [MoonCAst.Expr], },
    CInitList { variant_unique, items [many [MoonCAst.InitItem]], },
  },
  product. InitItem {
    interned,
    designator [optional [many [MoonCAst.Designator]]],
    field. value [MoonCAst.Initializer],
  },
  sum. Designator {
    CDesigField { variant_unique, field. name [str], },
    CDesigIndex { variant_unique, index [MoonCAst.Expr], },
    CDesigRange { variant_unique, lo [MoonCAst.Expr], hi [MoonCAst.Expr], },
  },
}
