local S = require("moonlift.schema.dsl")
S.use()

return schema. MoonCode {
  product. CodeModuleId { interned, text [str], },
  product. CodeFuncId { interned, text [str], },
  product. CodeExternId { interned, text [str], },
  product. CodeGlobalId { interned, text [str], },
  product. CodeDataId { interned, text [str], },
  product. CodeRelocId { interned, text [str], },
  product. CodeSigId { interned, text [str], },
  product. CodeBlockId { interned, text [str], },
  product. CodeInstId { interned, text [str], },
  product. CodeTermId { interned, text [str], },
  product. CodeValueId { interned, text [str], },
  product. CodeLocalId { interned, text [str], },
  product. CodeTypeId { interned, text [str], },
  sum. CodeOrigin {
    CodeOriginUnknown,
    CodeOriginSource { variant_unique, label [str], },
    CodeOriginBinding { variant_unique, binding [MoonBind.Binding], },
    CodeOriginGenerated { variant_unique, reason [str], },
  },
  sum. CodeIntSignedness { CodeSigned, CodeUnsigned, },
  sum. CodeType {
    CodeTyVoid,
    CodeTyBool8,
    CodeTyInt { variant_unique, bits [number], signedness [MoonCode.CodeIntSignedness], },
    CodeTyFloat { variant_unique, bits [number], },
    CodeTyIndex,
    CodeTyDataPtr { variant_unique, pointee [optional [MoonCode.CodeType]], },
    CodeTyCodePtr { variant_unique, sig [MoonCode.CodeSigId], },
    CodeTyNamed {
      variant_unique,
      module_name [str],
      type_name [str],
      source_ty [MoonType.Type],
    },
    CodeTyArray { variant_unique, elem [MoonCode.CodeType], count [number], },
    CodeTySlice { variant_unique, elem [MoonCode.CodeType], },
    CodeTyView { variant_unique, elem [MoonCode.CodeType], },
    CodeTyHandle { variant_unique, repr [MoonCode.CodeType], source_ty [MoonType.Type], },
    CodeTyLease { variant_unique, base [MoonCode.CodeType], source_ty [MoonType.Type], },
    CodeTyClosure { variant_unique, sig [MoonCode.CodeSigId], },
    CodeTyImportedC { variant_unique, field. id [MoonC.CTypeId], },
    CodeTyImportedCFuncPtr { variant_unique, sig [MoonC.CFuncSigId], },
    CodeTyVector { variant_unique, elem [MoonCode.CodeType], lanes [number], },
  },
  product. CodeTypeDecl {
    interned,
    field. id [MoonCode.CodeTypeId],
    field. name [str],
    field. ty [MoonCode.CodeType],
    origin [MoonCode.CodeOrigin],
  },
  product. CodeParam {
    interned,
    field. value [MoonCode.CodeValueId],
    field. name [str],
    field. ty [MoonCode.CodeType],
    origin [MoonCode.CodeOrigin],
  },
  product. CodeSig {
    interned,
    field. id [MoonCode.CodeSigId],
    params [many [MoonCode.CodeType]],
    results [many [MoonCode.CodeType]],
  },
  sum. CodeResidence {
    CodeResidenceValue,
    CodeResidenceAddressed,
    CodeResidenceAggregate,
    CodeResidenceDescriptor,
    CodeResidenceStatic,
  },
  product. CodeLocal {
    interned,
    field. id [MoonCode.CodeLocalId],
    field. name [str],
    field. ty [MoonCode.CodeType],
    residence [MoonCode.CodeResidence],
    origin [MoonCode.CodeOrigin],
  },
  sum. CodePlace {
    CodePlaceLocal {
      variant_unique,
      field. local_id [MoonCode.CodeLocalId],
      field. ty [MoonCode.CodeType],
    },
    CodePlaceGlobal {
      variant_unique,
      global [MoonCode.CodeGlobalId],
      field. ty [MoonCode.CodeType],
    },
    CodePlaceData {
      variant_unique,
      data [MoonCode.CodeDataId],
      field. ty [MoonCode.CodeType],
    },
    CodePlaceDeref {
      variant_unique,
      addr [MoonCode.CodeValueId],
      field. ty [MoonCode.CodeType],
      align [optional [number]],
    },
    CodePlaceField {
      variant_unique,
      base [MoonCode.CodePlace],
      field. field [MoonSem.FieldRef],
      field. ty [MoonCode.CodeType],
      offset [number],
      size [optional [number]],
      align [optional [number]],
    },
    CodePlaceIndex {
      variant_unique,
      base [MoonCode.CodePlace],
      index [MoonCode.CodeValueId],
      field. ty [MoonCode.CodeType],
      elem_size [number],
    },
    CodePlaceBytes {
      variant_unique,
      base [MoonCode.CodeValueId],
      offset [number],
      field. ty [MoonCode.CodeType],
      size [number],
      align [number],
    },
  },
  sum. CodeTrapMode { CodeMayTrap, CodeMustNotTrap, CodeCheckedTrap, },
  sum. CodeMemoryMode { CodeMemoryRead, CodeMemoryWrite, CodeMemoryReadWrite, },
  product. CodeMemoryAccess {
    interned,
    mode [MoonCode.CodeMemoryMode],
    field. ty [MoonCode.CodeType],
    align [number],
    trap [MoonCode.CodeTrapMode],
    volatile [bool],
    ordering [optional [MoonCore.AtomicOrdering]],
  },
  sum. CodeConst {
    CodeConstLiteral {
      variant_unique,
      field. ty [MoonCode.CodeType],
      literal [MoonCore.Literal],
    },
    CodeConstNull { variant_unique, field. ty [MoonCode.CodeType], },
    CodeConstUndef { variant_unique, field. ty [MoonCode.CodeType], reason [str], },
  },
  sum. CodeIntOverflow {
    CodeIntWrap,
    CodeIntTrapOnOverflow,
    CodeIntAssumeNoOverflow { variant_unique, reason [str], },
  },
  sum. CodeDivMode { CodeDivTrapOnZero, CodeDivTrapOnZeroOrOverflow, },
  sum. CodeShiftMode { CodeShiftMaskCount, CodeShiftTrapOutOfRange, },
  product. CodeIntSemantics {
    interned,
    overflow [MoonCode.CodeIntOverflow],
    div [MoonCode.CodeDivMode],
    shift [MoonCode.CodeShiftMode],
  },
  sum. CodeFloatMode {
    CodeFloatStrict,
    CodeFloatReassoc { variant_unique, reason [str], },
    CodeFloatFastMath { variant_unique, reason [str], },
  },
  sum. CodeCallTarget {
    CodeCallDirect { variant_unique, func [MoonCode.CodeFuncId], },
    CodeCallExtern { variant_unique, extern [MoonCode.CodeExternId], },
    CodeCallIndirect {
      variant_unique,
      callee [MoonCode.CodeValueId],
      sig [MoonCode.CodeSigId],
    },
    CodeCallClosure {
      variant_unique,
      closure [MoonCode.CodeValueId],
      sig [MoonCode.CodeSigId],
    },
  },
  sum. CodeGlobalRef {
    CodeGlobalRefData { variant_unique, data [MoonCode.CodeDataId], },
    CodeGlobalRefGlobal { variant_unique, global [MoonCode.CodeGlobalId], },
    CodeGlobalRefFunc { variant_unique, func [MoonCode.CodeFuncId], },
    CodeGlobalRefExtern { variant_unique, extern [MoonCode.CodeExternId], },
  },
  product. CodeReloc {
    interned,
    field. id [MoonCode.CodeRelocId],
    offset [number],
    target [MoonCode.CodeGlobalRef],
    addend [number],
    origin [MoonCode.CodeOrigin],
  },
  product. CodeFieldValue {
    interned,
    field. field [MoonSem.FieldRef],
    field. value [MoonCode.CodeValueId],
  },
  product. CodeArrayValue { interned, index [number], field. value [MoonCode.CodeValueId], },
  product. CodeVariantRef {
    interned,
    owner_ty [MoonCode.CodeType],
    variant_name [str],
    tag_value [number],
    payload_ty [optional [MoonCode.CodeType]],
  },
  product. CodeVariantCase {
    interned,
    variant [MoonCode.CodeVariantRef],
    dest [MoonCode.CodeBlockId],
    args [many [MoonCode.CodeValueId]],
  },
  product. CodeSwitchCase {
    interned,
    literal [MoonCore.Literal],
    dest [MoonCode.CodeBlockId],
    args [many [MoonCode.CodeValueId]],
  },
  sum. CodeInstKind {
    CodeInstConst {
      variant_unique,
      dst [MoonCode.CodeValueId],
      const [MoonCode.CodeConst],
    },
    CodeInstAlias {
      variant_unique,
      dst [MoonCode.CodeValueId],
      field. ty [MoonCode.CodeType],
      src [MoonCode.CodeValueId],
    },
    CodeInstUnary {
      variant_unique,
      dst [MoonCode.CodeValueId],
      op [MoonCore.UnaryOp],
      field. ty [MoonCode.CodeType],
      field. value [MoonCode.CodeValueId],
    },
    CodeInstBinary {
      variant_unique,
      dst [MoonCode.CodeValueId],
      op [MoonCore.BinaryOp],
      field. ty [MoonCode.CodeType],
      semantics [MoonCode.CodeIntSemantics],
      lhs [MoonCode.CodeValueId],
      rhs [MoonCode.CodeValueId],
    },
    CodeInstFloatBinary {
      variant_unique,
      dst [MoonCode.CodeValueId],
      op [MoonCore.BinaryOp],
      field. ty [MoonCode.CodeType],
      mode [MoonCode.CodeFloatMode],
      lhs [MoonCode.CodeValueId],
      rhs [MoonCode.CodeValueId],
    },
    CodeInstCompare {
      variant_unique,
      dst [MoonCode.CodeValueId],
      op [MoonCore.CmpOp],
      operand_ty [MoonCode.CodeType],
      lhs [MoonCode.CodeValueId],
      rhs [MoonCode.CodeValueId],
    },
    CodeInstCast {
      variant_unique,
      dst [MoonCode.CodeValueId],
      op [MoonCore.MachineCastOp],
      from [MoonCode.CodeType],
      to [MoonCode.CodeType],
      field. value [MoonCode.CodeValueId],
    },
    CodeInstSelect {
      variant_unique,
      dst [MoonCode.CodeValueId],
      field. ty [MoonCode.CodeType],
      cond [MoonCode.CodeValueId],
      then_value [MoonCode.CodeValueId],
      else_value [MoonCode.CodeValueId],
    },
    CodeInstIntrinsic {
      variant_unique,
      dst [optional [MoonCode.CodeValueId]],
      op [MoonCore.Intrinsic],
      field. ty [MoonCode.CodeType],
      args [many [MoonCode.CodeValueId]],
    },
    CodeInstAddrOf {
      variant_unique,
      dst [MoonCode.CodeValueId],
      ptr_ty [MoonCode.CodeType],
      place [MoonCode.CodePlace],
    },
    CodeInstGlobalRef {
      variant_unique,
      dst [MoonCode.CodeValueId],
      field. ref [MoonCode.CodeGlobalRef],
      ptr_ty [MoonCode.CodeType],
    },
    CodeInstPtrOffset {
      variant_unique,
      dst [MoonCode.CodeValueId],
      ptr_ty [MoonCode.CodeType],
      base [MoonCode.CodeValueId],
      index [MoonCode.CodeValueId],
      elem_size [number],
      const_offset [number],
    },
    CodeInstLoad {
      variant_unique,
      dst [MoonCode.CodeValueId],
      place [MoonCode.CodePlace],
      access [MoonCode.CodeMemoryAccess],
    },
    CodeInstStore {
      variant_unique,
      place [MoonCode.CodePlace],
      field. value [MoonCode.CodeValueId],
      access [MoonCode.CodeMemoryAccess],
    },
    CodeInstAggregate {
      variant_unique,
      dst [MoonCode.CodeValueId],
      field. ty [MoonCode.CodeType],
      fields [many [MoonCode.CodeFieldValue]],
    },
    CodeInstArray {
      variant_unique,
      dst [MoonCode.CodeValueId],
      field. ty [MoonCode.CodeType],
      elems [many [MoonCode.CodeArrayValue]],
    },
    CodeInstViewMake {
      variant_unique,
      dst [MoonCode.CodeValueId],
      elem_ty [MoonCode.CodeType],
      data [MoonCode.CodeValueId],
      len [MoonCode.CodeValueId],
      stride [MoonCode.CodeValueId],
    },
    CodeInstViewData {
      variant_unique,
      dst [MoonCode.CodeValueId],
      view [MoonCode.CodeValueId],
    },
    CodeInstViewLen {
      variant_unique,
      dst [MoonCode.CodeValueId],
      view [MoonCode.CodeValueId],
    },
    CodeInstViewStride {
      variant_unique,
      dst [MoonCode.CodeValueId],
      view [MoonCode.CodeValueId],
    },
    CodeInstClosure {
      variant_unique,
      dst [MoonCode.CodeValueId],
      field. ty [MoonCode.CodeType],
      fn [MoonCode.CodeValueId],
      ctx [MoonCode.CodeValueId],
      sig [MoonCode.CodeSigId],
    },
    CodeInstVariantCtor {
      variant_unique,
      dst [MoonCode.CodeValueId],
      field. ty [MoonCode.CodeType],
      variant [MoonCode.CodeVariantRef],
      payload [optional [MoonCode.CodeValueId]],
    },
    CodeInstVariantTag {
      variant_unique,
      dst [MoonCode.CodeValueId],
      tag_ty [MoonCode.CodeType],
      field. value [MoonCode.CodeValueId],
    },
    CodeInstVariantPayload {
      variant_unique,
      dst [MoonCode.CodeValueId],
      variant [MoonCode.CodeVariantRef],
      field. value [MoonCode.CodeValueId],
    },
    CodeInstCall {
      variant_unique,
      dst [optional [MoonCode.CodeValueId]],
      target [MoonCode.CodeCallTarget],
      sig [MoonCode.CodeSigId],
      args [many [MoonCode.CodeValueId]],
    },
    CodeInstAtomicLoad {
      variant_unique,
      dst [MoonCode.CodeValueId],
      place [MoonCode.CodePlace],
      access [MoonCode.CodeMemoryAccess],
      ordering [MoonCore.AtomicOrdering],
    },
    CodeInstAtomicStore {
      variant_unique,
      place [MoonCode.CodePlace],
      field. value [MoonCode.CodeValueId],
      access [MoonCode.CodeMemoryAccess],
      ordering [MoonCore.AtomicOrdering],
    },
    CodeInstAtomicRmw {
      variant_unique,
      dst [MoonCode.CodeValueId],
      op [MoonCore.AtomicRmwOp],
      place [MoonCode.CodePlace],
      field. value [MoonCode.CodeValueId],
      access [MoonCode.CodeMemoryAccess],
      ordering [MoonCore.AtomicOrdering],
    },
    CodeInstAtomicCas {
      variant_unique,
      dst [MoonCode.CodeValueId],
      place [MoonCode.CodePlace],
      expected [MoonCode.CodeValueId],
      replacement [MoonCode.CodeValueId],
      access [MoonCode.CodeMemoryAccess],
      ordering [MoonCore.AtomicOrdering],
    },
    CodeInstAtomicFence { variant_unique, ordering [MoonCore.AtomicOrdering], },
  },
  product. CodeInst {
    interned,
    field. id [MoonCode.CodeInstId],
    kind [MoonCode.CodeInstKind],
    origin [MoonCode.CodeOrigin],
  },
  sum. CodeTermKind {
    CodeTermJump {
      variant_unique,
      dest [MoonCode.CodeBlockId],
      args [many [MoonCode.CodeValueId]],
    },
    CodeTermBranch {
      variant_unique,
      cond [MoonCode.CodeValueId],
      then_dest [MoonCode.CodeBlockId],
      then_args [many [MoonCode.CodeValueId]],
      else_dest [MoonCode.CodeBlockId],
      else_args [many [MoonCode.CodeValueId]],
    },
    CodeTermSwitch {
      variant_unique,
      field. value [MoonCode.CodeValueId],
      cases [many [MoonCode.CodeSwitchCase]],
      default_dest [MoonCode.CodeBlockId],
      default_args [many [MoonCode.CodeValueId]],
    },
    CodeTermVariantSwitch {
      variant_unique,
      tag [MoonCode.CodeValueId],
      cases [many [MoonCode.CodeVariantCase]],
      default_dest [MoonCode.CodeBlockId],
      default_args [many [MoonCode.CodeValueId]],
    },
    CodeTermReturn { variant_unique, values [many [MoonCode.CodeValueId]], },
    CodeTermTrap { variant_unique, reason [str], },
    CodeTermUnreachable { variant_unique, reason [str], },
  },
  product. CodeTerm {
    interned,
    field. id [MoonCode.CodeTermId],
    kind [MoonCode.CodeTermKind],
    origin [MoonCode.CodeOrigin],
  },
  product. CodeBlock {
    interned,
    field. id [MoonCode.CodeBlockId],
    field. name [str],
    params [many [MoonCode.CodeParam]],
    insts [many [MoonCode.CodeInst]],
    term [MoonCode.CodeTerm],
    origin [MoonCode.CodeOrigin],
  },
  sum. CodeLinkage {
    CodeLinkageLocal,
    CodeLinkageExport,
    CodeLinkageImport,
    CodeLinkageDeclaration,
  },
  sum. CodeDataInit {
    CodeDataZero { variant_unique, offset [number], size [number], },
    CodeDataBytes { variant_unique, offset [number], bytes [str], },
    CodeDataScalar {
      variant_unique,
      offset [number],
      field. ty [MoonCode.CodeType],
      literal [MoonCore.Literal],
    },
    CodeDataReloc { variant_unique, reloc [MoonCode.CodeReloc], },
  },
  product. CodeData {
    interned,
    field. id [MoonCode.CodeDataId],
    field. name [str],
    linkage [MoonCode.CodeLinkage],
    size [number],
    align [number],
    inits [many [MoonCode.CodeDataInit]],
    origin [MoonCode.CodeOrigin],
  },
  product. CodeGlobal {
    interned,
    field. id [MoonCode.CodeGlobalId],
    field. name [str],
    field. ty [MoonCode.CodeType],
    linkage [MoonCode.CodeLinkage],
    size [optional [number]],
    align [optional [number]],
    inits [many [MoonCode.CodeDataInit]],
    origin [MoonCode.CodeOrigin],
  },
  product. CodeExtern {
    interned,
    field. id [MoonCode.CodeExternId],
    field. name [str],
    symbol [str],
    sig [MoonCode.CodeSigId],
    origin [MoonCode.CodeOrigin],
  },
  sum. CodeContractFact {
    CodeContractBounds {
      variant_unique,
      base [MoonCode.CodeValueId],
      len [MoonCode.CodeValueId],
    },
    CodeContractWindowBounds {
      variant_unique,
      base [MoonCode.CodeValueId],
      base_len [MoonCode.CodeValueId],
      start [MoonCode.CodeValueId],
      len [MoonCode.CodeValueId],
    },
    CodeContractDisjoint {
      variant_unique,
      a [MoonCode.CodeValueId],
      b [MoonCode.CodeValueId],
    },
    CodeContractSameLen {
      variant_unique,
      a [MoonCode.CodeValueId],
      b [MoonCode.CodeValueId],
    },
    CodeContractNoAlias { variant_unique, base [MoonCode.CodeValueId], },
    CodeContractReadonly { variant_unique, base [MoonCode.CodeValueId], },
    CodeContractWriteonly { variant_unique, base [MoonCode.CodeValueId], },
    CodeContractInvalidate { variant_unique, base [MoonCode.CodeValueId], },
    CodeContractPreserve { variant_unique, base [MoonCode.CodeValueId], },
    CodeContractRejected { variant_unique, reason [str], },
  },
  product. CodeFuncContractFact {
    interned,
    func [MoonCode.CodeFuncId],
    fact [MoonCode.CodeContractFact],
    origin [MoonCode.CodeOrigin],
  },
  product. CodeContractFactSet {
    interned,
    field. module [MoonCode.CodeModuleId],
    facts [many [MoonCode.CodeFuncContractFact]],
  },
  product. CodeFunc {
    interned,
    field. id [MoonCode.CodeFuncId],
    field. name [str],
    linkage [MoonCode.CodeLinkage],
    sig [MoonCode.CodeSigId],
    params [many [MoonCode.CodeParam]],
    locals [many [MoonCode.CodeLocal]],
    entry [MoonCode.CodeBlockId],
    blocks [many [MoonCode.CodeBlock]],
    origin [MoonCode.CodeOrigin],
  },
  product. CodeModule {
    interned,
    field. id [MoonCode.CodeModuleId],
    sigs [many [MoonCode.CodeSig]],
    types [many [MoonCode.CodeTypeDecl]],
    data [many [MoonCode.CodeData]],
    globals [many [MoonCode.CodeGlobal]],
    externs [many [MoonCode.CodeExtern]],
    funcs [many [MoonCode.CodeFunc]],
    origin [MoonCode.CodeOrigin],
  },
  sum. CodeIssue {
    CodeIssueMissingValue { variant_unique, field. value [MoonCode.CodeValueId], },
    CodeIssueDuplicateValue { variant_unique, field. value [MoonCode.CodeValueId], },
    CodeIssueMissingBlock { variant_unique, block [MoonCode.CodeBlockId], },
    CodeIssueDuplicateBlock { variant_unique, block [MoonCode.CodeBlockId], },
    CodeIssueMissingSig { variant_unique, sig [MoonCode.CodeSigId], },
    CodeIssueMissingFunc { variant_unique, func [MoonCode.CodeFuncId], },
    CodeIssueMissingExtern { variant_unique, extern [MoonCode.CodeExternId], },
    CodeIssueMissingGlobal { variant_unique, global [MoonCode.CodeGlobalId], },
    CodeIssueMissingData { variant_unique, data [MoonCode.CodeDataId], },
    CodeIssueDuplicateSig { variant_unique, sig [MoonCode.CodeSigId], },
    CodeIssueDuplicateFunc { variant_unique, func [MoonCode.CodeFuncId], },
    CodeIssueDuplicateExtern { variant_unique, extern [MoonCode.CodeExternId], },
    CodeIssueDuplicateGlobal { variant_unique, global [MoonCode.CodeGlobalId], },
    CodeIssueDuplicateData { variant_unique, data [MoonCode.CodeDataId], },
    CodeIssueDuplicateInst { variant_unique, inst [MoonCode.CodeInstId], },
    CodeIssueDuplicateTerm { variant_unique, term [MoonCode.CodeTermId], },
    CodeIssueJumpArity {
      variant_unique,
      block [MoonCode.CodeBlockId],
      expected [number],
      actual [number],
    },
    CodeIssueCallArity {
      variant_unique,
      sig [MoonCode.CodeSigId],
      expected [number],
      actual [number],
    },
    CodeIssueTypeMismatch {
      variant_unique,
      site [str],
      expected [MoonCode.CodeType],
      actual [MoonCode.CodeType],
    },
    CodeIssueBlockParamMismatch {
      variant_unique,
      block [MoonCode.CodeBlockId],
      index [number],
      expected [MoonCode.CodeType],
      actual [MoonCode.CodeType],
    },
    CodeIssueUnterminatedBlock { variant_unique, block [MoonCode.CodeBlockId], },
    CodeIssueInvalidTerminator { variant_unique, site [str], term [MoonCode.CodeTermId], },
    CodeIssueInvalidMemoryAccess {
      variant_unique,
      site [str],
      access [MoonCode.CodeMemoryAccess],
    },
    CodeIssueInvalidReloc { variant_unique, reloc [MoonCode.CodeReloc], reason [str], },
    CodeIssueDataCodePointerConfusion {
      variant_unique,
      site [str],
      field. ty [MoonCode.CodeType],
    },
    CodeIssueUnsupportedSource { variant_unique, site [str], reason [str], },
  },
  product. CodeValidationReport { interned, issues [many [MoonCode.CodeIssue]], },
}
