local S = require("moonlift.schema.dsl")
S.use()

return schema. MoonCore {
  product. Name { interned, text [str], },
  product. Path { interned, parts [many [MoonCore.Name]], },
  product. Id { interned, text [str], },
  product. ModuleId { interned, text [str], },
  product. ItemId { interned, text [str], },
  product. FieldId { interned, text [str], },
  sum. Phase { PhaseSurface, PhaseTyped, PhaseOpen, PhaseSem, PhaseCode, },
  sum. Visibility { VisibilityLocal, VisibilityExport, },
  sum. Scalar {
    ScalarVoid,
    ScalarBool,
    ScalarI8,
    ScalarI16,
    ScalarI32,
    ScalarI64,
    ScalarU8,
    ScalarU16,
    ScalarU32,
    ScalarU64,
    ScalarF32,
    ScalarF64,
    ScalarRawPtr,
    ScalarIndex,
  },
  sum. ScalarFamily {
    ScalarFamilyVoid,
    ScalarFamilyBool,
    ScalarFamilySignedInt,
    ScalarFamilyUnsignedInt,
    ScalarFamilyFloat,
    ScalarFamilyRawPtr,
    ScalarFamilyIndex,
  },
  product. ScalarBits { interned, bits [number], },
  product. ScalarInfo {
    interned,
    family [MoonCore.ScalarFamily],
    bits [MoonCore.ScalarBits],
  },
  sum. Literal {
    LitInt { variant_unique, raw [str], },
    LitFloat { variant_unique, raw [str], },
    LitBool { variant_unique, field. value [bool], },
    LitString { variant_unique, bytes [str], },
    LitNil,
  },
  sum. UnaryOp { UnaryNeg, UnaryNot, UnaryBitNot, },
  sum. BinaryOp {
    BinAdd,
    BinSub,
    BinMul,
    BinDiv,
    BinRem,
    BinBitAnd,
    BinBitOr,
    BinBitXor,
    BinShl,
    BinLShr,
    BinAShr,
  },
  sum. CmpOp { CmpEq, CmpNe, CmpLt, CmpLe, CmpGt, CmpGe, },
  sum. LogicOp { LogicAnd, LogicOr, },
  sum. SurfaceCastOp {
    SurfaceCast,
    SurfaceTrunc,
    SurfaceZExt,
    SurfaceSExt,
    SurfaceBitcast,
    SurfaceSatCast,
  },
  sum. MachineCastOp {
    MachineCastIdentity,
    MachineCastBitcast,
    MachineCastIreduce,
    MachineCastSextend,
    MachineCastUextend,
    MachineCastFpromote,
    MachineCastFdemote,
    MachineCastSToF,
    MachineCastUToF,
    MachineCastFToS,
    MachineCastFToU,
  },
  sum. Intrinsic {
    IntrinsicPopcount,
    IntrinsicClz,
    IntrinsicCtz,
    IntrinsicRotl,
    IntrinsicRotr,
    IntrinsicBswap,
    IntrinsicFma,
    IntrinsicSqrt,
    IntrinsicAbs,
    IntrinsicFloor,
    IntrinsicCeil,
    IntrinsicTruncFloat,
    IntrinsicRound,
    IntrinsicTrap,
    IntrinsicAssume,
  },
  sum. AtomicOrdering { AtomicSeqCst, },
  sum. AtomicRmwOp {
    AtomicRmwAdd,
    AtomicRmwSub,
    AtomicRmwAnd,
    AtomicRmwOr,
    AtomicRmwXor,
    AtomicRmwXchg,
  },
  sum. UnaryOpClass { UnaryClassArithmetic, UnaryClassLogical, UnaryClassBitwise, },
  sum. BinaryOpClass {
    BinaryClassArithmetic,
    BinaryClassDivision,
    BinaryClassRemainder,
    BinaryClassBitwise,
    BinaryClassShift,
  },
  sum. CmpOpClass { CmpClassEquality, CmpClassOrdering, },
  sum. IntrinsicClass {
    IntrinsicClassBit,
    IntrinsicClassFloat,
    IntrinsicClassFused,
    IntrinsicClassControl,
  },
  product. TypeSym { interned, key [str], field. name [str], },
  product. FuncSym { interned, key [str], field. name [str], },
  product. ExternSym { interned, key [str], field. name [str], symbol [str], },
  product. ConstSym { interned, key [str], field. name [str], },
  product. StaticSym { interned, key [str], field. name [str], },
  product. DataId { interned, text [str], },
  sum. SymKind { SymKindFunc, SymKindExtern, SymKindConst, SymKindStatic, SymKindType, },
  product. OpenSym {
    interned,
    kind [MoonCore.SymKind],
    key [str],
    field. name [str],
    symbol [str],
  },
}
