local S = require("moonlift.schema.dsl")
S.use()

return schema. MoonDasm {
  product. DModuleId { interned, text [str], },
  product. DBlockId { interned, text [str], },
  product. DValId { interned, text [str], },
  product. DLabelId { interned, text [str], },
  product. DVirtualRegId { interned, text [str], },
  product. DPhysRegId { interned, field. number [number], },
  sum. DRegClass { DGpr, DXmm, DFlags, },
  sum. DValueClass {
    DValueGpr { variant_unique, scalar [MoonBack.BackScalar], },
    DValueXmm { variant_unique, scalar [MoonBack.BackScalar], },
    DValueFlags,
    DValueVector { variant_unique, elem [MoonBack.BackScalar], lanes [number], },
  },
  product. DSigEntry {
    interned,
    key [str],
    params [many [MoonBack.BackScalar]],
    results [many [MoonBack.BackScalar]],
  },
  product. DFuncEntry {
    interned,
    key [str],
    sig [str],
    visibility [str],
    body [many [MoonBack.Cmd]],
  },
  product. DExternEntry { interned, key [str], symbol [str], sig [str], },
  product. DDataEntry { interned, key [str], buf [any], size [number], align [number], },
  product. DLabelPair { interned, key [str], label [str], },
  product. DLabelMap {
    interned,
    funcs [many [MoonDasm.DLabelPair]],
    externs [many [MoonDasm.DLabelPair]],
    datas [many [MoonDasm.DLabelPair]],
  },
  product. DPhaseModule {
    interned,
    sigs [many [MoonDasm.DSigEntry]],
    funcs [many [MoonDasm.DFuncEntry]],
    externs [many [MoonDasm.DExternEntry]],
    datas [many [MoonDasm.DDataEntry]],
    func_order [many [str]],
    extern_order [many [str]],
    data_order [many [str]],
    labels [MoonDasm.DLabelMap],
  },
  product. DTargetFacts {
    interned,
    target [MoonBack.BackTargetModel],
    pointer_bits [number],
    index_bits [number],
    endianness [str],
    features [many [str]],
  },
  product. DFuncBody { interned, func [MoonBack.BackFuncId], cmds [many [MoonBack.Cmd]], },
  product. DPhaseFunc {
    interned,
    func [optional [MoonBack.BackFuncId]],
    cmds [many [MoonBack.Cmd]],
  },
  product. DScalarMapEntry { interned, key [str], scalar [str], },
  product. DTypedFunc {
    interned,
    func [MoonBack.BackFuncId],
    cmds [many [MoonBack.Cmd]],
    value_scalars [many [MoonDasm.DScalarMapEntry]],
  },
  product. DBlockParam {
    interned,
    field. value [MoonBack.BackValId],
    field. ty [MoonBack.BackShape],
  },
  product. DEdgeArg {
    interned,
    src [MoonBack.BackValId],
    dst_param [MoonBack.BackValId],
  },
  product. DSwitchCase { interned, raw [str], dest [MoonBack.BackBlockId], },
  sum. DTerminator {
    DTermJump {
      variant_unique,
      dest [MoonBack.BackBlockId],
      args [many [MoonDasm.DEdgeArg]],
    },
    DTermBrIf {
      variant_unique,
      cond [MoonBack.BackValId],
      then_block [MoonBack.BackBlockId],
      then_args [many [MoonDasm.DEdgeArg]],
      else_block [MoonBack.BackBlockId],
      else_args [many [MoonDasm.DEdgeArg]],
    },
    DTermSwitch {
      variant_unique,
      field. value [MoonBack.BackValId],
      field. ty [MoonBack.BackScalar],
      cases [many [MoonDasm.DSwitchCase]],
      default_dest [MoonBack.BackBlockId],
    },
    DTermReturnVoid,
    DTermReturnValue { variant_unique, field. value [MoonBack.BackValId], },
    DTermTrap,
  },
  product. DCfgBlock {
    interned,
    field. id [MoonBack.BackBlockId],
    params [many [MoonDasm.DBlockParam]],
    body [many [MoonBack.Cmd]],
    term [MoonDasm.DTerminator],
  },
  product. DFuncCFG {
    interned,
    func [MoonBack.BackFuncId],
    sig [MoonBack.BackSigId],
    entry [MoonBack.BackBlockId],
    blocks [many [MoonDasm.DCfgBlock]],
    stack_slots [many [MoonBack.BackStackSlotId]],
  },
  sum. DValueFact {
    DValueShapeFact {
      variant_unique,
      field. value [MoonBack.BackValId],
      shape [MoonBack.BackShape],
    },
    DValueClassFact {
      variant_unique,
      field. value [MoonBack.BackValId],
      class [MoonDasm.DValueClass],
    },
    DValueDefFact {
      variant_unique,
      field. value [MoonBack.BackValId],
      block [MoonBack.BackBlockId],
      index [number],
    },
    DValueUseFact {
      variant_unique,
      field. value [MoonBack.BackValId],
      block [MoonBack.BackBlockId],
      index [number],
      slot [number],
    },
    DValueConstIntFact { variant_unique, field. value [MoonBack.BackValId], raw [str], },
    DValueConstFloatFact { variant_unique, field. value [MoonBack.BackValId], raw [str], },
  },
  sum. DEdgeKind {
    DEdgeEntry,
    DEdgeJump,
    DEdgeThen,
    DEdgeElse,
    DEdgeSwitchCase,
    DEdgeSwitchDefault,
    DEdgeCriticalSplit,
  },
  product. DEdgeRef {
    interned,
    pred [MoonBack.BackBlockId],
    succ [MoonBack.BackBlockId],
    kind [MoonDasm.DEdgeKind],
    ordinal [number],
  },
  product. DParallelMove {
    interned,
    dst [MoonBack.BackValId],
    src [MoonBack.BackValId],
    class [MoonDasm.DValueClass],
  },
  product. DParallelCopy {
    interned,
    edge [MoonDasm.DEdgeRef],
    moves [many [MoonDasm.DParallelMove]],
  },
  sum. DControlFact {
    DControlEdgeFact {
      variant_unique,
      edge [MoonDasm.DEdgeRef],
      args [many [MoonDasm.DEdgeArg]],
    },
    DParallelCopyFact { variant_unique, copy [MoonDasm.DParallelCopy], },
  },
  sum. DMemoryFact {
    DMemoryLoadFact {
      variant_unique,
      dst [MoonBack.BackValId],
      addr [MoonBack.BackAddress],
      memory [MoonBack.BackMemoryInfo],
      field. ty [MoonBack.BackShape],
    },
    DMemoryStoreFact {
      variant_unique,
      addr [MoonBack.BackAddress],
      field. value [MoonBack.BackValId],
      memory [MoonBack.BackMemoryInfo],
      field. ty [MoonBack.BackShape],
    },
  },
  sum. DCallFact {
    DCallSiteFact {
      variant_unique,
      index [number],
      sig [MoonBack.BackSigId],
      target [MoonBack.BackCallTarget],
      args [many [MoonBack.BackValId]],
      result [optional [MoonBack.BackCallResult]],
    },
    DCallClobberFact { variant_unique, index [number], clobbers [many [MoonDasm.DPhysRegId]], },
  },
  product. DFuncFacts {
    interned,
    cfg [MoonDasm.DFuncCFG],
    value_facts [many [MoonDasm.DValueFact]],
    control_facts [many [MoonDasm.DControlFact]],
    memory_facts [many [MoonDasm.DMemoryFact]],
    call_facts [many [MoonDasm.DCallFact]],
  },
  sum. DConstKind {
    DConstUnknown,
    DConstInt { variant_unique, raw [str], },
    DConstFloat { variant_unique, raw [str], },
    DConstBool { variant_unique, field. value [bool], },
    DConstNull,
  },
  sum. DAddrBaseKind { DBaseValue, DBaseStack, DBaseData, DBaseUnknown, },
  sum. DFamilyKind {
    DFamilyCopy,
    DFamilyIntBin,
    DFamilyBitBin,
    DFamilyShiftRotate,
    DFamilyCompareBranch,
    DFamilyLoadStore,
    DFamilyAddress,
    DFamilyCall,
    DFamilyControl,
    DFamilyReturn,
    DFamilyOther,
  },
  sum. DFamilyKey {
    DKeyCopy {
      variant_unique,
      class [MoonDasm.DValueClass],
      src_const [MoonDasm.DConstKind],
      same_value [bool],
    },
    DKeyIntBin {
      variant_unique,
      op [str],
      scalar [MoonBack.BackScalar],
      lhs_const [MoonDasm.DConstKind],
      rhs_const [MoonDasm.DConstKind],
      commutative [bool],
      rhs_pow2 [bool],
    },
    DKeyBitBin {
      variant_unique,
      op [str],
      scalar [MoonBack.BackScalar],
      rhs_const [MoonDasm.DConstKind],
    },
    DKeyShiftRotate {
      variant_unique,
      op [str],
      scalar [MoonBack.BackScalar],
      rhs_const [MoonDasm.DConstKind],
      rhs_small_imm [bool],
    },
    DKeyCompareBranch {
      variant_unique,
      op [str],
      scalar [MoonBack.BackScalar],
      rhs_const [MoonDasm.DConstKind],
      fused_branch [bool],
      rhs_is_zero [bool],
    },
    DKeyLoadStore {
      variant_unique,
      is_load [bool],
      shape [MoonBack.BackShape],
      base_kind [MoonDasm.DAddrBaseKind],
      has_index [bool],
      const_disp [bool],
      align_bytes [number],
      trap_kind [str],
    },
    DKeyAddress {
      variant_unique,
      base_kind [MoonDasm.DAddrBaseKind],
      elem_size [number],
      const_offset [number],
    },
    DKeyCall {
      variant_unique,
      target_kind [str],
      argc [number],
      has_result [bool],
      result_class [MoonDasm.DValueClass],
    },
    DKeyControl { variant_unique, kind [str], },
    DKeyReturn { variant_unique, has_value [bool], class [MoonDasm.DValueClass], },
    DKeyOther { variant_unique, kind [str], },
  },
  product. DFamilyInstance {
    interned,
    cmd_index [number],
    block [optional [MoonBack.BackBlockId]],
    family [MoonDasm.DFamilyKind],
    key [MoonDasm.DFamilyKey],
  },
  sum. DFactAtom {
    DFactCmdKind { variant_unique, cmd_index [number], kind [str], },
    DFactValueShape {
      variant_unique,
      field. value [MoonBack.BackValId],
      shape [MoonBack.BackShape],
    },
    DFactValueClass {
      variant_unique,
      field. value [MoonBack.BackValId],
      class [MoonDasm.DValueClass],
    },
    DFactValueConst {
      variant_unique,
      field. value [MoonBack.BackValId],
      const_kind [MoonDasm.DConstKind],
    },
    DFactUse {
      variant_unique,
      field. value [MoonBack.BackValId],
      cmd_index [number],
      slot [number],
    },
    DFactDef { variant_unique, field. value [MoonBack.BackValId], cmd_index [number], },
    DFactBlockAt { variant_unique, cmd_index [number], block [MoonBack.BackBlockId], },
  },
  product. DFactSet {
    interned,
    func [optional [MoonBack.BackFuncId]],
    cmds [many [MoonBack.Cmd]],
    atoms [many [MoonDasm.DFactAtom]],
    families [many [MoonDasm.DFamilyInstance]],
  },
  product. DLowerDecision {
    interned,
    cmd_index [number],
    rule [str],
    cost [number],
    shape [MoonDasm.DAsmShape],
  },
  product. DLoweredFunc {
    interned,
    func [optional [MoonBack.BackFuncId]],
    cmds [many [MoonBack.Cmd]],
    facts [MoonDasm.DFactSet],
    decisions [many [MoonDasm.DLowerDecision]],
    asm [MoonDasm.DAsmFunc],
  },
  product. DAddress {
    interned,
    base [optional [MoonDasm.DPhysRegId]],
    index [optional [MoonDasm.DPhysRegId]],
    scale [number],
    disp [number],
  },
  sum. DOperand {
    DOpVReg { variant_unique, vreg [MoonDasm.DVirtualRegId], },
    DOpPReg { variant_unique, preg [MoonDasm.DPhysRegId], },
    DOpImmI64 { variant_unique, raw [str], },
    DOpLabel { variant_unique, label [MoonDasm.DLabelId], },
    DOpMem { variant_unique, addr [MoonDasm.DAddress], },
  },
  sum. DCondCode { DccE, DccNE, DccL, DccLE, DccG, DccGE, DccB, DccBE, DccA, DccAE, DccP, DccNP, },
  sum. DAsmShape {
    DAsmLabel { variant_unique, label [MoonDasm.DLabelId], },
    DAsmMove {
      variant_unique,
      dst [MoonDasm.DOperand],
      src [MoonDasm.DOperand],
      class [MoonDasm.DValueClass],
    },
    DAsmUnary {
      variant_unique,
      op [str],
      dst [MoonDasm.DOperand],
      src [MoonDasm.DOperand],
      scalar [MoonBack.BackScalar],
    },
    DAsmBinary {
      variant_unique,
      op [str],
      dst [MoonDasm.DOperand],
      lhs [MoonDasm.DOperand],
      rhs [MoonDasm.DOperand],
      scalar [MoonBack.BackScalar],
    },
    DAsmCompareSet {
      variant_unique,
      cc [MoonDasm.DCondCode],
      dst [MoonDasm.DOperand],
      lhs [MoonDasm.DOperand],
      rhs [MoonDasm.DOperand],
      scalar [MoonBack.BackScalar],
    },
    DAsmLoad {
      variant_unique,
      dst [MoonDasm.DOperand],
      addr [MoonDasm.DOperand],
      field. ty [MoonBack.BackShape],
    },
    DAsmStore {
      variant_unique,
      addr [MoonDasm.DOperand],
      field. value [MoonDasm.DOperand],
      field. ty [MoonBack.BackShape],
    },
    DAsmLea { variant_unique, dst [MoonDasm.DOperand], addr [MoonDasm.DOperand], },
    DAsmJump { variant_unique, dest [MoonDasm.DLabelId], },
    DAsmBrIf {
      variant_unique,
      cond [MoonDasm.DOperand],
      then_label [MoonDasm.DLabelId],
      else_label [MoonDasm.DLabelId],
    },
    DAsmCall {
      variant_unique,
      target [MoonDasm.DOperand],
      args [many [MoonDasm.DOperand]],
      result [optional [MoonDasm.DOperand]],
    },
    DAsmRetVoid,
    DAsmRetValue { variant_unique, field. value [MoonDasm.DOperand], },
    DAsmPrologue,
    DAsmEpilogue,
    DAsmTrap,
    DAsmComment { variant_unique, text [str], },
  },
  product. DAsmInst {
    interned,
    shape [MoonDasm.DAsmShape],
    defs [many [MoonDasm.DVirtualRegId]],
    uses [many [MoonDasm.DVirtualRegId]],
    clobbers [many [MoonDasm.DPhysRegId]],
  },
  product. DAsmBlock {
    interned,
    field. id [MoonBack.BackBlockId],
    insts [many [MoonDasm.DAsmInst]],
  },
  product. DAsmFunc {
    interned,
    func [MoonBack.BackFuncId],
    blocks [many [MoonDasm.DAsmBlock]],
  },
  sum. DAllocLoc {
    DLocReg { variant_unique, preg [MoonDasm.DPhysRegId], },
    DLocStack { variant_unique, offset [number], size [number], align [number], },
  },
  product. DValueAlloc {
    interned,
    vreg [MoonDasm.DVirtualRegId],
    loc [MoonDasm.DAllocLoc],
    class [MoonDasm.DValueClass],
  },
  product. DBankedRegalloc {
    interned,
    allocs [many [MoonDasm.DValueAlloc]],
    used_callee_saved [many [MoonDasm.DPhysRegId]],
    spill_size [number],
  },
  product. DFrameSlot {
    interned,
    slot [MoonBack.BackStackSlotId],
    offset [number],
    size [number],
    align [number],
  },
  product. DFramePlan {
    interned,
    stack_size [number],
    spill_size [number],
    slot_size [number],
    callee_saved [many [MoonDasm.DPhysRegId]],
    slots [many [MoonDasm.DFrameSlot]],
  },
  product. DFragment { interned, offset [number], args [many [number]], bytes [str], },
  product. DFragmentBundle { interned, fragments [many [MoonDasm.DFragment]], },
  product. DGlobalEntry { interned, kind [str], key [str], label [str], slot_index [number], },
  product. DFuncPtrEntry { interned, func [MoonBack.BackFuncId], global_slot [number], },
  product. DEmitPlan {
    interned,
    globals [many [MoonDasm.DGlobalEntry]],
    fragments [many [MoonDasm.DFragment]],
    func_ptrs [many [MoonDasm.DFuncPtrEntry]],
    code_size_hint [number],
  },
}
