local S = require("moonlift.schema.dsl")
S.use()

return schema. MoonEditor {
  sum. ServerMode {
    ServerCreated,
    ServerInitializing,
    ServerReady,
    ServerShutdownRequested,
    ServerStopped,
  },
  sum. ClientCapability {
    ClientCapability { variant_unique, field. name [str], field. value [str], },
  },
  product. WorkspaceRoot { interned, uri [MoonSource.DocUri], },
  sum. WorkspaceFileOrigin { WorkspaceFileOpen, WorkspaceFileDisk, },
  product. WorkspaceFile {
    uri [MoonSource.DocUri],
    path [str],
    language [MoonSource.LanguageId],
    version [MoonSource.DocVersion],
    origin [MoonEditor.WorkspaceFileOrigin],
    fingerprint [str],
  },
  product. WorkspaceIndex { generation [number], files [many [MoonEditor.WorkspaceFile]], },
  product. WorkspaceState {
    mode [MoonEditor.ServerMode],
    roots [many [MoonEditor.WorkspaceRoot]],
    capabilities [many [MoonEditor.ClientCapability]],
    open_docs [many [MoonSource.DocumentSnapshot]],
    index [MoonEditor.WorkspaceIndex],
  },
  sum. RpcId {
    RpcIdNone,
    RpcIdNumber { variant_unique, field. value [number], },
    RpcIdString { variant_unique, field. value [str], },
  },
  product. PositionQuery {
    uri [MoonSource.DocUri],
    version [MoonSource.DocVersion],
    pos [MoonSource.SourcePos],
  },
  product. RangeQuery {
    uri [MoonSource.DocUri],
    version [MoonSource.DocVersion],
    range [MoonSource.SourceRange],
  },
  product. ReferenceQuery { position [MoonEditor.PositionQuery], include_declaration [bool], },
  product. RenameQuery { position [MoonEditor.PositionQuery], new_name [str], },
  product. CodeActionQuery {
    range [MoonEditor.RangeQuery],
    diagnostics [many [MoonEditor.DiagnosticFact]],
  },
  sum. ClientEvent {
    ClientInitialize {
      field. id [MoonEditor.RpcId],
      roots [many [MoonEditor.WorkspaceRoot]],
      capabilities [many [MoonEditor.ClientCapability]],
    },
    ClientInitialized,
    ClientShutdown { field. id [MoonEditor.RpcId], },
    ClientExit,
    ClientDidOpen { document [MoonSource.DocumentSnapshot], },
    ClientDidChange { edit [MoonSource.DocumentEdit], },
    ClientDidClose { uri [MoonSource.DocUri], },
    ClientDidSave { uri [MoonSource.DocUri], },
    ClientHover { field. id [MoonEditor.RpcId], query [MoonEditor.PositionQuery], },
    ClientDefinition { field. id [MoonEditor.RpcId], query [MoonEditor.PositionQuery], },
    ClientReferences { field. id [MoonEditor.RpcId], query [MoonEditor.ReferenceQuery], },
    ClientDocumentHighlight {
      field. id [MoonEditor.RpcId],
      query [MoonEditor.PositionQuery],
    },
    ClientDocumentSymbol { field. id [MoonEditor.RpcId], uri [MoonSource.DocUri], },
    ClientWorkspaceSymbol { field. id [MoonEditor.RpcId], query [str], },
    ClientDiagnostic { field. id [MoonEditor.RpcId], uri [MoonSource.DocUri], },
    ClientCompletion { field. id [MoonEditor.RpcId], query [MoonEditor.PositionQuery], },
    ClientSignatureHelp {
      field. id [MoonEditor.RpcId],
      query [MoonEditor.PositionQuery],
    },
    ClientSemanticTokensFull { field. id [MoonEditor.RpcId], uri [MoonSource.DocUri], },
    ClientSemanticTokensRange {
      field. id [MoonEditor.RpcId],
      query [MoonEditor.RangeQuery],
    },
    ClientPrepareRename {
      field. id [MoonEditor.RpcId],
      query [MoonEditor.PositionQuery],
    },
    ClientRename { field. id [MoonEditor.RpcId], query [MoonEditor.RenameQuery], },
    ClientCodeAction {
      field. id [MoonEditor.RpcId],
      query [MoonEditor.CodeActionQuery],
    },
    ClientFoldingRange { field. id [MoonEditor.RpcId], uri [MoonSource.DocUri], },
    ClientSelectionRange {
      field. id [MoonEditor.RpcId],
      positions [many [MoonEditor.PositionQuery]],
    },
    ClientInlayHint { field. id [MoonEditor.RpcId], query [MoonEditor.RangeQuery], },
    ClientUnsupported { field. id [MoonEditor.RpcId], method [str], },
    ClientIgnoredNotification { method [str], },
  },
  product. Transition {
    before [MoonEditor.WorkspaceState],
    event [MoonEditor.ClientEvent],
    after [MoonEditor.WorkspaceState],
  },
  sum. DiagnosticSeverity {
    DiagnosticError,
    DiagnosticWarning,
    DiagnosticInformation,
    DiagnosticHint,
  },
  sum. DiagnosticOrigin {
    DiagFromParse { variant_unique, issue [MoonParse.ParseIssue], },
    DiagFromHost { variant_unique, issue [MoonHost.HostIssue], },
    DiagFromOpen { variant_unique, issue [MoonOpen.ValidationIssue], },
    DiagFromType { variant_unique, issue [MoonTree.TypeIssue], },
    DiagFromBack { variant_unique, issue [MoonBack.BackValidationIssue], },
    DiagFromBindingResolution { variant_unique, resolution [MoonEditor.BindingResolution], },
    DiagFromSource { variant_unique, issue [MoonSource.SourceApplyIssue], },
    DiagFromTransport { variant_unique, code [str], message [str], },
  },
  product. DiagnosticContextFrame {
    label [str],
    message [str],
    range [optional [MoonSource.SourceRange]],
  },
  product. DiagnosticFact {
    interned,
    severity [MoonEditor.DiagnosticSeverity],
    origin [MoonEditor.DiagnosticOrigin],
    code [str],
    message [str],
    range [MoonSource.SourceRange],
    context [many [MoonEditor.DiagnosticContextFrame]],
  },
  sum. Subject {
    SubjectKeyword { variant_unique, text [str], },
    SubjectScalar { variant_unique, scalar [MoonCore.Scalar], },
    SubjectType { variant_unique, field. ty [MoonType.Type], },
    SubjectHostStruct { variant_unique, decl [MoonHost.HostStructDecl], },
    SubjectHostField {
      variant_unique,
      owner [MoonHost.HostStructDecl],
      field. field [MoonHost.HostFieldDecl],
    },
    SubjectHostExpose { variant_unique, decl [MoonHost.HostExposeDecl], },
    SubjectHostAccessor { variant_unique, decl [MoonHost.HostAccessorDecl], },
    SubjectTreeFunc { variant_unique, func [MoonTree.Func], },
    SubjectTreeExtern { variant_unique, func [MoonTree.ExternFunc], },
    SubjectTreeModule { variant_unique, field. module [MoonTree.Module], },
    SubjectRegionFrag { variant_unique, frag [MoonOpen.RegionFrag], },
    SubjectExprFrag { variant_unique, frag [MoonOpen.ExprFrag], },
    SubjectBinding { variant_unique, binding [MoonBind.Binding], },
    SubjectContinuation {
      variant_unique,
      scope [MoonSource.AnchorId],
      label [MoonTree.BlockLabel],
    },
    SubjectBuiltin { variant_unique, field. name [str], },
    SubjectDiagnostic { variant_unique, diagnostic [MoonEditor.DiagnosticFact], },
    SubjectMissing { variant_unique, reason [str], },
  },
  product. SubjectPick {
    query [MoonEditor.PositionQuery],
    anchors [many [MoonSource.AnchorSpan]],
    subject [MoonEditor.Subject],
  },
  sum. SymbolKind {
    SymFile,
    SymModule,
    SymNamespace,
    SymPackage,
    SymClass,
    SymMethod,
    SymProperty,
    SymField,
    SymConstructor,
    SymEnum,
    SymInterface,
    SymFunction,
    SymVariable,
    SymConstant,
    SymString,
    SymNumber,
    SymBoolean,
    SymArray,
    SymObject,
    SymKey,
    SymNull,
    SymEnumMember,
    SymStruct,
    SymEvent,
    SymOperator,
    SymTypeParameter,
  },
  product. SymbolId { interned, text [str], },
  product. SymbolFact {
    interned,
    field. id [MoonEditor.SymbolId],
    parent [MoonEditor.SymbolId],
    field. name [str],
    kind [MoonEditor.SymbolKind],
    detail [str],
    range [MoonSource.SourceRange],
    selection_range [MoonSource.SourceRange],
    subject [MoonEditor.Subject],
  },
  product. SymbolTree { interned, symbols [many [MoonEditor.SymbolFact]], },
  sum. BindingRole {
    BindingDef,
    BindingUse,
    BindingRead,
    BindingWrite,
    BindingCall,
    BindingTypeUse,
  },
  product. BindingScopeId { interned, text [str], },
  sum. BindingScopeKind {
    BindingScopeDocument,
    BindingScopeIsland,
    BindingScopeFunction,
    BindingScopeRegion,
    BindingScopeExpr,
    BindingScopeControlBlock,
    BindingScopeBranch,
    BindingScopeModule,
    BindingScopeOpaque { variant_unique, field. name [str], },
  },
  product. BindingScopeFact {
    interned,
    field. id [MoonEditor.BindingScopeId],
    parent [MoonEditor.BindingScopeId],
    kind [MoonEditor.BindingScopeKind],
    range [MoonSource.SourceRange],
  },
  product. ScopedBinding {
    interned,
    binding [MoonBind.Binding],
    scope [MoonEditor.BindingScopeId],
    visible_range [MoonSource.SourceRange],
    anchor [MoonSource.AnchorSpan],
  },
  product. BindingUseSite {
    interned,
    anchor [MoonSource.AnchorSpan],
    role [MoonEditor.BindingRole],
    scope [MoonEditor.BindingScopeId],
  },
  sum. BindingResolution {
    BindingResolved {
      variant_unique,
      use [MoonEditor.BindingUseSite],
      binding [MoonEditor.ScopedBinding],
    },
    BindingUnresolved { variant_unique, use [MoonEditor.BindingUseSite], reason [str], },
  },
  product. BindingScopeReport {
    interned,
    scopes [many [MoonEditor.BindingScopeFact]],
    bindings [many [MoonEditor.ScopedBinding]],
    resolutions [many [MoonEditor.BindingResolution]],
  },
  product. BindingFact {
    interned,
    field. id [MoonEditor.SymbolId],
    role [MoonEditor.BindingRole],
    subject [MoonEditor.Subject],
    anchor [MoonSource.AnchorSpan],
  },
  sum. DefinitionResult {
    DefinitionHit {
      variant_unique,
      subject [MoonEditor.Subject],
      ranges [many [MoonSource.SourceRange]],
    },
    DefinitionMiss { variant_unique, reason [str], },
  },
  sum. ReferenceResult {
    ReferenceHit {
      variant_unique,
      subject [MoonEditor.Subject],
      ranges [many [MoonSource.SourceRange]],
    },
    ReferenceMiss { variant_unique, reason [str], },
  },
  sum. DocumentHighlightKind { HighlightText, HighlightRead, HighlightWrite, },
  product. DocumentHighlight {
    interned,
    range [MoonSource.SourceRange],
    kind [MoonEditor.DocumentHighlightKind],
  },
  product. RenameEdit { interned, range [MoonSource.SourceRange], new_text [str], },
  sum. RenameResult {
    RenameOk { variant_unique, edits [many [MoonEditor.RenameEdit]], },
    RenameRejected { variant_unique, reason [str], },
  },
  sum. PrepareRenameResult {
    PrepareRenameOk { variant_unique, range [MoonSource.SourceRange], placeholder [str], },
    PrepareRenameRejected { variant_unique, reason [str], },
  },
  sum. MarkupKind { MarkupPlainText, MarkupMarkdown, },
  sum. HoverInfo {
    HoverInfo {
      variant_unique,
      kind [MoonEditor.MarkupKind],
      field. value [str],
      range [MoonSource.SourceRange],
    },
    HoverMissing { variant_unique, reason [str], },
  },
  sum. CompletionContext {
    CompletionTopLevel,
    CompletionModuleItem,
    CompletionStructField,
    CompletionTypePosition,
    CompletionExprPosition,
    CompletionPlacePosition,
    CompletionExposeSubject,
    CompletionExposeTarget,
    CompletionExposeMode,
    CompletionRegionStatement,
    CompletionContinuationArgs,
    CompletionBuiltinPath,
    CompletionLuaOpaque,
    CompletionInvalid { variant_unique, reason [str], },
  },
  sum. CompletionKind {
    CompletionText,
    CompletionMethod,
    CompletionFunction,
    CompletionConstructor,
    CompletionField,
    CompletionVariable,
    CompletionClass,
    CompletionInterface,
    CompletionModule,
    CompletionProperty,
    CompletionUnit,
    CompletionValue,
    CompletionEnum,
    CompletionKeyword,
    CompletionSnippet,
    CompletionColor,
    CompletionFile,
    CompletionReference,
    CompletionFolder,
    CompletionEnumMember,
    CompletionConstant,
    CompletionStruct,
    CompletionEvent,
    CompletionOperator,
    CompletionTypeParameter,
  },
  sum. CompletionInsertFormat { CompletionInsertPlainText, CompletionInsertSnippet, },
  product. CompletionQuery {
    position [MoonEditor.PositionQuery],
    context [MoonEditor.CompletionContext],
  },
  product. CompletionItem {
    interned,
    label [str],
    kind [MoonEditor.CompletionKind],
    detail [str],
    documentation [str],
    insert_text [str],
    insert_format [MoonEditor.CompletionInsertFormat],
  },
  sum. SignatureContext {
    SignatureCall {
      variant_unique,
      callee [str],
      active_parameter [number],
      callee_range [MoonSource.SourceRange],
    },
    SignatureNoCall { variant_unique, reason [str], },
  },
  product. SignatureParameter { interned, label [str], documentation [str], },
  product. SignatureInfo {
    interned,
    label [str],
    documentation [str],
    params [many [MoonEditor.SignatureParameter]],
  },
  sum. SignatureHelp {
    SignatureHelp {
      variant_unique,
      signatures [many [MoonEditor.SignatureInfo]],
      active_signature [number],
      active_parameter [number],
    },
    SignatureHelpMissing { variant_unique, reason [str], },
  },
  sum. SemanticTokenType {
    TokNamespace,
    TokType,
    TokClass,
    TokEnum,
    TokInterface,
    TokStruct,
    TokTypeParameter,
    TokParameter,
    TokVariable,
    TokProperty,
    TokEnumMember,
    TokEvent,
    TokFunction,
    TokMethod,
    TokMacro,
    TokKeyword,
    TokModifier,
    TokComment,
    TokString,
    TokNumber,
    TokRegexp,
    TokOperator,
    TokDecorator,
  },
  sum. SemanticTokenModifier {
    TokModDeclaration,
    TokModDefinition,
    TokModReadonly,
    TokModStatic,
    TokModDeprecated,
    TokModAbstract,
    TokModAsync,
    TokModModification,
    TokModDocumentation,
    TokModDefaultLibrary,
    TokModMutable,
    TokModExported,
    TokModStorage,
    TokModDiagnostic,
  },
  product. SemanticTokenSpan {
    interned,
    range [MoonSource.SourceRange],
    token_type [MoonEditor.SemanticTokenType],
    modifiers [many [MoonEditor.SemanticTokenModifier]],
  },
  sum. CodeActionKind {
    CodeActionQuickFix,
    CodeActionRefactor,
    CodeActionSource,
    CodeActionOrganizeImports,
  },
  product. TextEdit { interned, range [MoonSource.SourceRange], new_text [str], },
  product. WorkspaceEdit { interned, edits [many [MoonEditor.TextEdit]], },
  product. CodeAction {
    interned,
    title [str],
    kind [MoonEditor.CodeActionKind],
    diagnostics [many [MoonEditor.DiagnosticFact]],
    edit [MoonEditor.WorkspaceEdit],
  },
  product. FoldingRange { interned, range [MoonSource.SourceRange], kind [str], },
  product. SelectionRange {
    interned,
    range [MoonSource.SourceRange],
    parents [many [MoonSource.SourceRange]],
  },
  product. InlayHint { interned, pos [MoonSource.SourcePos], label [str], kind [str], },
}
