local S = require("moonlift.schema.dsl")
S.use()

return schema. MoonHost {
  sum. HostIssue {
    HostIssueInvalidName { variant_unique, site [str], field. name [str], },
    HostIssueExpected { variant_unique, site [str], expected [str], actual [str], },
    HostIssueDuplicateField { variant_unique, type_name [str], field_name [str], },
    HostIssueDuplicateType { variant_unique, module_name [str], type_name [str], },
    HostIssueDuplicateDecl { variant_unique, field. name [str], },
    HostIssueDuplicateFunc { variant_unique, module_name [str], func_name [str], },
    HostIssueUnsealedType { variant_unique, module_name [str], type_name [str], },
    HostIssueSealedMutation { variant_unique, type_name [str], },
    HostIssueAlreadySealed { variant_unique, type_name [str], },
    HostIssueUnknownBinding { variant_unique, site [str], field. name [str], },
    HostIssueInvalidEmitFill { variant_unique, fragment_name [str], fill_name [str], },
    HostIssueMissingEmitFill { variant_unique, fragment_name [str], fill_name [str], },
    HostIssueInvalidPackedAlign { variant_unique, type_name [str], align [number], },
    HostIssueBareBoolInBoundaryStruct { variant_unique, type_name [str], field_name [str], },
    HostIssueArgCount { variant_unique, site [str], expected [number], actual [number], },
    HostIssueSpliceExpected { variant_unique, splice_id [str], expected [str], actual [str], },
    HostIssueSpliceEvalError { variant_unique, splice_id [str], message [str], },
    HostIssueLuaStepError { variant_unique, step_id [str], message [str], },
    HostIssueTemplateParseError { variant_unique, template_id [str], message [str], },
    HostIssueRegionComposeMissingExit { variant_unique, fragment_name [str], exit_name [str], },
    HostIssueRegionComposeIncompatibleCont {
      variant_unique,
      fragment_name [str],
      exit_name [str],
      expected [str],
      actual [str],
    },
    HostIssueRegionComposeIncompleteRoute { variant_unique, fragment_name [str], exit_name [str], },
    HostIssueRegionComposeContextMismatch { variant_unique, left [str], right [str], },
  },
  product. HostReport { interned, issues [many [MoonHost.HostIssue]], },
  product. HostLayoutId { interned, key [str], field. name [str], },
  product. HostFieldId { interned, key [str], field. name [str], },
  sum. HostEndian { HostEndianLittle, HostEndianBig, },
  product. HostTargetModel {
    interned,
    pointer_bits [number],
    index_bits [number],
    endian [MoonHost.HostEndian],
  },
  sum. HostLayoutKind {
    HostLayoutStruct,
    HostLayoutSlice,
    HostLayoutArray,
    HostLayoutViewDescriptor,
    HostLayoutOpaque,
  },
  sum. HostOwner {
    HostOwnerBufferView,
    HostOwnerHostSession,
    HostOwnerBorrowed,
    HostOwnerStatic,
    HostOwnerOpaque,
  },
  sum. HostBoolEncoding { HostBoolU8, HostBoolI32, HostBoolNative, },
  sum. HostRepr {
    HostReprC,
    HostReprPacked { variant_unique, align [number], },
    HostReprOpaque { variant_unique, field. name [str], },
  },
  sum. HostFieldAttr {
    HostFieldReadonly,
    HostFieldMutable,
    HostFieldNoalias,
    HostFieldOpaque { variant_unique, field. name [str], },
  },
  sum. HostStorageRep {
    HostStorageSame,
    HostStorageScalar { variant_unique, scalar [MoonCore.Scalar], },
    HostStorageBool {
      variant_unique,
      encoding [MoonHost.HostBoolEncoding],
      scalar [MoonCore.Scalar],
    },
    HostStoragePtr { variant_unique, pointee [MoonType.Type], },
    HostStorageSlice { variant_unique, elem [MoonType.Type], },
    HostStorageView { variant_unique, elem [MoonType.Type], },
    HostStorageOpaque { variant_unique, field. name [str], },
  },
  product. HostStructDecl {
    interned,
    field. id [MoonHost.HostLayoutId],
    field. name [str],
    repr [MoonHost.HostRepr],
    fields [many [MoonHost.HostFieldDecl]],
  },
  product. HostFieldDecl {
    interned,
    field. id [MoonHost.HostFieldId],
    field. name [str],
    expose_ty [MoonType.Type],
    storage [MoonHost.HostStorageRep],
    attrs [many [MoonHost.HostFieldAttr]],
  },
  sum. HostAccessorDecl {
    HostAccessorField { variant_unique, owner_name [str], field. name [str], field_name [str], },
    HostAccessorLua { variant_unique, owner_name [str], field. name [str], lua_symbol [str], },
    HostAccessorMoonlift {
      variant_unique,
      owner_name [str],
      field. name [str],
      func [MoonTree.Func],
    },
  },
  sum. HostDecl {
    HostDeclStruct { variant_unique, decl [MoonHost.HostStructDecl], },
    HostDeclExpose { variant_unique, decl [MoonHost.HostExposeDecl], },
    HostDeclAccessor { variant_unique, decl [MoonHost.HostAccessorDecl], },
  },
  product. HostDeclSet { interned, field. decls [many [MoonHost.HostDecl]], },
  sum. HostDeclSource {
    HostDeclSourceSet { variant_unique, set [MoonHost.HostDeclSet], },
    HostDeclSourceDecls { variant_unique, field. decls [many [MoonHost.HostDecl]], },
  },
  product. MluaSource { interned, field. name [str], source [str], },
  product. MluaParseResult {
    interned,
    field. decls [MoonHost.HostDeclSet],
    field. module [MoonTree.Module],
    region_frags [many [MoonOpen.RegionFrag]],
    expr_frags [many [MoonOpen.ExprFrag]],
    issues [many [MoonParse.ParseIssue]],
  },
  product. MluaHostPipelineResult {
    interned,
    parsed [MoonHost.MluaParseResult],
    report [MoonHost.HostReport],
    layout_env [MoonHost.HostLayoutEnv],
  },
  product. HostValueId { interned, key [str], pretty [str], },
  sum. HostValueKind {
    HostValueRegionFrag,
    HostValueExprFrag,
    HostValueType,
    HostValueDecl,
    HostValueModule,
    HostValueLua,
  },
  product. HostValueRef {
    interned,
    field. id [MoonHost.HostValueId],
    kind [MoonHost.HostValueKind],
  },
  product. ProtocolRole { interned, role [str], target [str], },
  product. RegionProtocol {
    interned,
    field. name [str],
    roles [many [MoonHost.ProtocolRole]],
  },
  product. FragmentDeps {
    interned,
    region_frags [many [MoonOpen.RegionFrag]],
    expr_frags [many [MoonOpen.ExprFrag]],
  },
  product. RegionFragMeta {
    interned,
    field. name [str],
    frag [MoonOpen.RegionFrag],
    protocol [optional [MoonHost.RegionProtocol]],
    deps [MoonHost.FragmentDeps],
  },
  product. MluaRegionTypeResult {
    interned,
    frag [MoonOpen.RegionFrag],
    issues [many [MoonTree.TypeIssue]],
  },
  product. MluaLoopExpandResult {
    interned,
    entry [MoonTree.EntryControlBlock],
    blocks [many [MoonTree.ControlBlock]],
    issues [many [MoonTree.TypeIssue]],
  },
  sum. MluaLoopSource {
    MluaLoopControlStmt { variant_unique, region [MoonTree.ControlStmtRegion], },
    MluaLoopControlExpr { variant_unique, region [MoonTree.ControlExprRegion], },
  },
  sum. HostFieldRep {
    HostRepScalar { variant_unique, scalar [MoonCore.Scalar], },
    HostRepBool {
      variant_unique,
      encoding [MoonHost.HostBoolEncoding],
      storage [MoonCore.Scalar],
    },
    HostRepPtr { variant_unique, pointee [MoonType.Type], },
    HostRepRef { variant_unique, layout [MoonHost.HostLayoutId], },
    HostRepSlice { variant_unique, elem [MoonHost.HostFieldRep], },
    HostRepView { variant_unique, elem [MoonType.Type], },
    HostRepStruct { variant_unique, layout [MoonHost.HostLayoutId], },
    HostRepOpaque { variant_unique, field. name [str], },
  },
  product. HostFieldLayout {
    interned,
    field. id [MoonHost.HostFieldId],
    field. name [str],
    cfield [str],
    rep [MoonHost.HostFieldRep],
    offset [number],
    size [number],
    align [number],
  },
  product. HostTypeLayout {
    interned,
    field. id [MoonHost.HostLayoutId],
    field. name [str],
    ctype [str],
    kind [MoonHost.HostLayoutKind],
    size [number],
    align [number],
    fields [many [MoonHost.HostFieldLayout]],
  },
  product. HostLayoutEnv { interned, layouts [many [MoonHost.HostTypeLayout]], },
  product. HostCdef { interned, layout [MoonHost.HostLayoutId], source [str], },
  product. HostLuaFfiPlan {
    interned,
    module_name [str],
    cdefs [many [MoonHost.HostCdef]],
    access_plans [many [MoonHost.HostAccessPlan]],
  },
  product. HostTerraPlan {
    interned,
    module_name [str],
    source [str],
    layouts [many [MoonHost.HostTypeLayout]],
    views [many [MoonHost.HostViewDescriptor]],
  },
  product. HostCPlan {
    interned,
    header_name [str],
    source [str],
    layouts [many [MoonHost.HostTypeLayout]],
    views [many [MoonHost.HostViewDescriptor]],
  },
  sum. HostExportAbi {
    HostExportDescriptorPtr { variant_unique, descriptor [MoonHost.HostViewDescriptor], },
    HostExportExpandedScalars { variant_unique, field. ty [MoonType.Type], },
  },
  sum. HostExposeSubject {
    HostExposeType { variant_unique, field. ty [MoonType.Type], },
    HostExposePtr { variant_unique, pointee [MoonType.Type], },
    HostExposeView { variant_unique, elem [MoonType.Type], },
  },
  sum. HostStrideUnit { HostStrideElements, HostStrideBytes, },
  sum. HostViewAbi {
    HostViewAbiContiguous { variant_unique, elem_layout [MoonHost.HostTypeLayout], },
    HostViewAbiStrided {
      variant_unique,
      elem_layout [MoonHost.HostTypeLayout],
      stride_unit [MoonHost.HostStrideUnit],
    },
  },
  product. HostViewDescriptor {
    interned,
    field. id [MoonHost.HostLayoutId],
    field. name [str],
    abi [MoonHost.HostViewAbi],
    descriptor_layout [MoonHost.HostTypeLayout],
  },
  sum. HostExposeTarget { HostExposeLua, HostExposeTerra, HostExposeC, HostExposeMoonlift, },
  sum. HostMutability { HostReadonly, HostMutable, HostInteriorMutable, },
  sum. HostBoundsPolicy { HostBoundsChecked, HostBoundsUnchecked, },
  sum. HostProxyKind {
    HostProxyPtr,
    HostProxyView,
    HostProxyBufferView,
    HostProxyTypedRecord,
    HostProxyOpaque,
  },
  sum. HostProxyCachePolicy { HostProxyCacheNone, HostProxyCacheLazy, HostProxyCacheEager, },
  sum. HostMaterializePolicy {
    HostMaterializeProjectedFields,
    HostMaterializeFullCopy,
    HostMaterializeBorrowedView,
  },
  sum. HostExposeMode {
    HostExposeProxy {
      variant_unique,
      kind [MoonHost.HostProxyKind],
      cache [MoonHost.HostProxyCachePolicy],
      mutability [MoonHost.HostMutability],
      bounds [MoonHost.HostBoundsPolicy],
    },
    HostExposeEagerTable { variant_unique, policy [MoonHost.HostMaterializePolicy], },
    HostExposeScalar { variant_unique, rep [MoonHost.HostFieldRep], },
    HostExposeOpaque { variant_unique, reason [str], },
  },
  sum. HostExposeAbi {
    HostExposeAbiDefault,
    HostExposeAbiPointer,
    HostExposeAbiDescriptor,
    HostExposeAbiDataLenStride,
    HostExposeAbiExpandedScalars,
    HostExposeAbiOpaque { variant_unique, reason [str], },
  },
  product. HostExposeFacet {
    interned,
    target [MoonHost.HostExposeTarget],
    abi [MoonHost.HostExposeAbi],
    mode [MoonHost.HostExposeMode],
  },
  product. HostExposeDecl {
    interned,
    subject [MoonHost.HostExposeSubject],
    public_name [str],
    facets [many [MoonHost.HostExposeFacet]],
  },
  sum. HostLifetime {
    HostLifetimeStatic,
    HostLifetimeOwned,
    HostLifetimeBorrowed { variant_unique, owner_name [str], },
    HostLifetimeGeneration { variant_unique, session_id [number], generation [number], },
    HostLifetimeExternal { variant_unique, field. name [str], },
  },
  sum. HostAccessSubject {
    HostAccessRecord { variant_unique, layout [MoonHost.HostTypeLayout], },
    HostAccessPtr { variant_unique, layout [MoonHost.HostTypeLayout], },
    HostAccessView { variant_unique, descriptor [MoonHost.HostViewDescriptor], },
  },
  sum. HostAccessKey {
    HostAccessField { variant_unique, field. name [str], },
    HostAccessIndex,
    HostAccessLen,
    HostAccessData,
    HostAccessStride,
    HostAccessMethod { variant_unique, field. name [str], },
    HostAccessPairs,
    HostAccessIpairs,
    HostAccessToTable,
  },
  sum. HostAccessOp {
    HostAccessDirectField { variant_unique, field. field [MoonHost.HostFieldLayout], },
    HostAccessDecodeBool { variant_unique, field. field [MoonHost.HostFieldLayout], },
    HostAccessEncodeBool { variant_unique, field. field [MoonHost.HostFieldLayout], },
    HostAccessViewIndex { variant_unique, descriptor [MoonHost.HostViewDescriptor], },
    HostAccessViewFieldAt {
      variant_unique,
      descriptor [MoonHost.HostViewDescriptor],
      field. field [MoonHost.HostFieldLayout],
    },
    HostAccessViewLen { variant_unique, descriptor [MoonHost.HostViewDescriptor], },
    HostAccessViewData { variant_unique, descriptor [MoonHost.HostViewDescriptor], },
    HostAccessViewStride { variant_unique, descriptor [MoonHost.HostViewDescriptor], },
    HostAccessPointerCast { variant_unique, layout [MoonHost.HostTypeLayout], },
    HostAccessIterateFields { variant_unique, layout [MoonHost.HostLayoutId], },
    HostAccessMaterializeTable { variant_unique, subject [MoonHost.HostAccessSubject], },
    HostAccessReject { variant_unique, reason [str], },
  },
  product. HostAccessEntry {
    interned,
    key [MoonHost.HostAccessKey],
    op [MoonHost.HostAccessOp],
  },
  product. HostAccessPlan {
    interned,
    subject [MoonHost.HostAccessSubject],
    entries [many [MoonHost.HostAccessEntry]],
  },
  product. HostViewPlan {
    interned,
    layout [MoonHost.HostTypeLayout],
    owner [MoonHost.HostOwner],
    expose [MoonHost.HostExposeMode],
    access [MoonHost.HostAccessPlan],
  },
  sum. HostProducerKind {
    HostProducerLowLevelMoonlift,
    HostProducerLuaFfi,
    HostProducerTypedRecordMemory,
    HostProducerExternal,
  },
  product. HostProducerPlan {
    interned,
    field. name [str],
    kind [MoonHost.HostProducerKind],
    outputs [many [MoonHost.HostTypeLayout]],
  },
  sum. HostLayoutFact {
    HostFactTypeLayout { variant_unique, layout [MoonHost.HostTypeLayout], },
    HostFactCdef { variant_unique, cdef [MoonHost.HostCdef], },
    HostFactField {
      variant_unique,
      owner [MoonHost.HostLayoutId],
      field. field [MoonHost.HostFieldLayout],
    },
    HostFactViewDescriptor { variant_unique, descriptor [MoonHost.HostViewDescriptor], },
    HostFactExpose {
      variant_unique,
      public_name [str],
      layout [MoonHost.HostLayoutId],
      facet [MoonHost.HostExposeFacet],
    },
    HostFactAccessPlan { variant_unique, plan [MoonHost.HostAccessPlan], },
    HostFactViewPlan { variant_unique, plan [MoonHost.HostViewPlan], },
    HostFactLuaFfi { variant_unique, plan [MoonHost.HostLuaFfiPlan], },
    HostFactTerra { variant_unique, plan [MoonHost.HostTerraPlan], },
    HostFactC { variant_unique, plan [MoonHost.HostCPlan], },
    HostFactProducer { variant_unique, plan [MoonHost.HostProducerPlan], },
  },
  product. HostFactSet { interned, facts [many [MoonHost.HostLayoutFact]], },
  sum. HostLayoutReject {
    HostRejectJsonInTypedRecordMemory,
    HostRejectDynamicObjectArena { variant_unique, reason [str], },
    HostRejectUnknownFieldKind { variant_unique, kind [str], },
    HostRejectInvalidLayout { variant_unique, reason [str], },
    HostRejectBareBoolInBoundaryStruct { variant_unique, type_name [str], field_name [str], },
    HostRejectInvalidPackedAlign { variant_unique, type_name [str], align [number], },
    HostRejectConflictingCdef { variant_unique, layout [MoonHost.HostLayoutId], },
  },
}
