local S = require("moonlift.schema.dsl")
S.use()

return schema. MoonLink {
  product. LinkPath { interned, text [str], },
  product. LinkSymbol { interned, field. name [str], },
  product. LinkEnv { interned, key [str], field. value [str], },
  sum. LinkPlatform {
    LinkPlatformLinux,
    LinkPlatformMacOS,
    LinkPlatformWindows,
    LinkPlatformWasm,
    LinkPlatformUnknown { variant_unique, field. name [str], },
  },
  sum. LinkArch {
    LinkArchX86_64,
    LinkArchAArch64,
    LinkArchX86,
    LinkArchArm,
    LinkArchWasm32,
    LinkArchUnknown { variant_unique, field. name [str], },
  },
  sum. LinkObjectFormat {
    LinkFormatElf,
    LinkFormatMachO,
    LinkFormatCoff,
    LinkFormatWasm,
    LinkFormatUnknown { variant_unique, field. name [str], },
  },
  sum. LinkRelocationModel { LinkRelocStatic, LinkRelocPic, LinkRelocPie, },
  product. LinkTargetModel {
    interned,
    backend [MoonBack.BackTargetModel],
    platform [MoonLink.LinkPlatform],
    arch [MoonLink.LinkArch],
    object_format [MoonLink.LinkObjectFormat],
    relocation [MoonLink.LinkRelocationModel],
  },
  sum. LinkArtifactKind {
    LinkArtifactObject,
    LinkArtifactStaticArchive,
    LinkArtifactSharedLibrary,
    LinkArtifactExecutable,
  },
  sum. LinkerKind {
    LinkerSystemCc,
    LinkerCc,
    LinkerClang,
    LinkerGcc,
    LinkerLd,
    LinkerLld,
    LinkerAr,
    LinkerLibtool,
    LinkerCustom { variant_unique, field. name [str], },
  },
  product. LinkTool { interned, kind [MoonLink.LinkerKind], path [MoonLink.LinkPath], },
  sum. LinkInput {
    LinkInputObject { variant_unique, path [MoonLink.LinkPath], },
    LinkInputStaticArchive { variant_unique, path [MoonLink.LinkPath], },
    LinkInputSharedLibrary { variant_unique, path [MoonLink.LinkPath], },
    LinkInputSystemLibrary { variant_unique, field. name [str], },
    LinkInputFramework { variant_unique, field. name [str], },
    LinkInputLibrarySearchPath { variant_unique, path [MoonLink.LinkPath], },
    LinkInputLinkerScript { variant_unique, path [MoonLink.LinkPath], },
  },
  sum. LinkExportPolicy {
    LinkExportAll,
    LinkExportNone,
    LinkExportSymbols { variant_unique, symbols [many [MoonLink.LinkSymbol]], },
    LinkExportVersionScript { variant_unique, path [MoonLink.LinkPath], },
  },
  sum. LinkExternPolicy { LinkExternRequireResolved, LinkExternAllowUnresolved, },
  sum. LinkDebugPolicy { LinkDebugDefault, LinkDebugKeep, LinkDebugStrip, },
  sum. LinkRuntimePath {
    LinkRpath { variant_unique, path [MoonLink.LinkPath], },
    LinkRunpath { variant_unique, path [MoonLink.LinkPath], },
  },
  sum. LinkOption {
    LinkOptRuntimePath { variant_unique, path [MoonLink.LinkRuntimePath], },
    LinkOptEntry { variant_unique, symbol [MoonLink.LinkSymbol], },
    LinkOptSoname { variant_unique, field. name [str], },
    LinkOptInstallName { variant_unique, field. name [str], },
    LinkOptOutputImplib { variant_unique, path [MoonLink.LinkPath], },
    LinkOptDebug { variant_unique, policy [MoonLink.LinkDebugPolicy], },
    LinkOptWholeArchiveBegin,
    LinkOptWholeArchiveEnd,
    LinkOptNoDefaultLibs,
    LinkOptStaticLibgcc,
    LinkOptCustomArg { variant_unique, },
  },
  product. LinkPlan {
    interned,
    target [MoonLink.LinkTargetModel],
    kind [MoonLink.LinkArtifactKind],
    tool [MoonLink.LinkTool],
    output [MoonLink.LinkPath],
    inputs [many [MoonLink.LinkInput]],
    exports [MoonLink.LinkExportPolicy],
    externs [MoonLink.LinkExternPolicy],
    options [many [MoonLink.LinkOption]],
  },
  sum. LinkIssue {
    LinkIssueMissingOutput,
    LinkIssueNoInputs,
    LinkIssueMissingInput { variant_unique, path [MoonLink.LinkPath], },
    LinkIssueUnsupportedPlatform {
      variant_unique,
      platform [MoonLink.LinkPlatform],
      kind [MoonLink.LinkArtifactKind],
    },
    LinkIssueUnsupportedInput { variant_unique, input [MoonLink.LinkInput], reason [str], },
    LinkIssueUnsupportedOption { variant_unique, option [MoonLink.LinkOption], reason [str], },
    LinkIssueUnresolvedSymbol { variant_unique, symbol [MoonLink.LinkSymbol], },
    LinkIssueDuplicateSymbol { variant_unique, symbol [MoonLink.LinkSymbol], },
    LinkIssueToolUnavailable { variant_unique, tool [MoonLink.LinkTool], },
    LinkIssueCommandFailed { variant_unique, index [number], code [number], stderr [str], },
  },
  product. LinkReport { interned, issues [many [MoonLink.LinkIssue]], },
  sum. LinkCommand {
    LinkCmdRun {
      variant_unique,
      tool [MoonLink.LinkTool],
      args [many [str]],
      env [many [MoonLink.LinkEnv]],
    },
    LinkCmdWriteFile { variant_unique, path [MoonLink.LinkPath], contents [str], },
    LinkCmdRemoveFile { variant_unique, path [MoonLink.LinkPath], },
  },
  product. LinkCommandPlan {
    interned,
    plan [MoonLink.LinkPlan],
    commands [many [MoonLink.LinkCommand]],
  },
  sum. LinkResult {
    LinkOk { variant_unique, output [MoonLink.LinkPath], },
    LinkFailed { variant_unique, report [MoonLink.LinkReport], },
  },
}
