local S = require("moonlift.schema.dsl")
S.use()

return schema. MoonLsp {
  product. ProtocolPosition { line [number], character [number], },
  product. ProtocolRange {
    start [MoonLsp.ProtocolPosition],
    stop [MoonLsp.ProtocolPosition],
  },
  product. Location { uri [MoonSource.DocUri], range [MoonLsp.ProtocolRange], },
  product. InitializeResult {
    interned,
    server_name [str],
    position_encoding [str],
    capabilities_json [str],
  },
  product. DiagnosticContextPayload {
    label [str],
    message [str],
    range [optional [MoonLsp.ProtocolRange]],
  },
  product. DiagnosticPayload {
    range [MoonLsp.ProtocolRange],
    severity [number],
    code [str],
    message [str],
    context [many [MoonLsp.DiagnosticContextPayload]],
  },
  product. DiagnosticReport {
    uri [MoonSource.DocUri],
    version [MoonSource.DocVersion],
    diagnostics [many [MoonLsp.DiagnosticPayload]],
  },
  product. DiagnosticDocumentReport { kind [str], items [many [MoonLsp.DiagnosticPayload]], },
  sum. Hover {
    Hover {
      kind [MoonEditor.MarkupKind],
      field. value [str],
      range [MoonLsp.ProtocolRange],
    },
    HoverNull,
  },
  product. CompletionPayload {
    label [str],
    kind [number],
    detail [str],
    documentation [str],
    insert_text [str],
    insert_text_format [number],
  },
  product. CompletionList { incomplete [bool], items [many [MoonLsp.CompletionPayload]], },
  product. DocumentSymbolPayload {
    field. name [str],
    detail [str],
    kind [number],
    range [MoonLsp.ProtocolRange],
    selection_range [MoonLsp.ProtocolRange],
    children [many [MoonLsp.DocumentSymbolPayload]],
  },
  product. WorkspaceSymbolPayload {
    field. name [str],
    detail [str],
    kind [number],
    location [MoonLsp.Location],
    container_name [str],
  },
  product. SignatureParameterPayload { label [str], documentation [str], },
  product. SignatureInformationPayload {
    label [str],
    documentation [str],
    params [many [MoonLsp.SignatureParameterPayload]],
  },
  product. SignatureHelpPayload {
    signatures [many [MoonLsp.SignatureInformationPayload]],
    active_signature [number],
    active_parameter [number],
  },
  product. SemanticTokens { data [many [number]], },
  product. DocumentHighlightPayload { range [MoonLsp.ProtocolRange], kind [number], },
  product. PrepareRenamePayload { range [MoonLsp.ProtocolRange], placeholder [str], },
  product. TextEditPayload { range [MoonLsp.ProtocolRange], new_text [str], },
  product. WorkspaceEditPayload {
    uri [MoonSource.DocUri],
    edits [many [MoonLsp.TextEditPayload]],
  },
  product. CodeActionPayload {
    title [str],
    kind [str],
    diagnostics [many [MoonLsp.DiagnosticPayload]],
    edits [many [MoonLsp.WorkspaceEditPayload]],
  },
  product. FoldingRangePayload {
    start_line [number],
    start_character [number],
    end_line [number],
    end_character [number],
    kind [str],
  },
  product. SelectionRangePayload {
    range [MoonLsp.ProtocolRange],
    parents [many [MoonLsp.SelectionRangePayload]],
  },
  product. InlayHintPayload { position [MoonLsp.ProtocolPosition], label [str], kind [str], },
  sum. Payload {
    PayloadNull,
    PayloadInitialize { result [MoonLsp.InitializeResult], },
    PayloadDiagnostics { report [MoonLsp.DiagnosticReport], },
    PayloadDiagnosticDocumentReport { report [MoonLsp.DiagnosticDocumentReport], },
    PayloadHover { hover [MoonLsp.Hover], },
    PayloadCompletion { completion [MoonLsp.CompletionList], },
    PayloadDocumentSymbols { symbols [many [MoonLsp.DocumentSymbolPayload]], },
    PayloadWorkspaceSymbols { symbols [many [MoonLsp.WorkspaceSymbolPayload]], },
    PayloadSignatureHelp { help [MoonLsp.SignatureHelpPayload], },
    PayloadLocations { locations [many [MoonLsp.Location]], },
    PayloadDocumentHighlights { highlights [many [MoonLsp.DocumentHighlightPayload]], },
    PayloadPrepareRename { result [MoonLsp.PrepareRenamePayload], },
    PayloadSemanticTokens { tokens [MoonLsp.SemanticTokens], },
    PayloadWorkspaceEdit { edits [many [MoonLsp.WorkspaceEditPayload]], },
    PayloadCodeActions { actions [many [MoonLsp.CodeActionPayload]], },
    PayloadFoldingRanges { ranges [many [MoonLsp.FoldingRangePayload]], },
    PayloadSelectionRanges { ranges [many [MoonLsp.SelectionRangePayload]], },
    PayloadInlayHints { hints [many [MoonLsp.InlayHintPayload]], },
    PayloadError { code [str], message [str], },
  },
}
