local S = require("moonlift.schema.dsl")
S.use()

return schema. MoonMem {
  product. MemAccessId { interned, text [str], },
  product. MemObjectId { interned, text [str], },
  product. MemBaseId { interned, text [str], },
  product. MemScopeId { interned, text [str], },
  product. MemProofId { interned, text [str], },
  product. MemLeaseId { interned, text [str], },
  sum. MemAccessKind {
    MemLoad,
    MemStore,
    MemAtomicLoad,
    MemAtomicStore,
    MemAtomicRmw,
    MemAtomicCas,
  },
  sum. MemBase {
    MemBaseValue { variant_unique, field. value [MoonCode.CodeValueId], },
    MemBaseLocal { variant_unique, field. local_id [MoonCode.CodeLocalId], },
    MemBaseGlobal { variant_unique, global [MoonCode.CodeGlobalId], },
    MemBaseData { variant_unique, data [MoonCode.CodeDataId], },
    MemBaseArgument {
      variant_unique,
      field. name [str],
      field. value [MoonCode.CodeValueId],
    },
    MemBaseProjection {
      variant_unique,
      base [MoonMem.MemBase],
      projection [MoonMem.MemProjectionKind],
      byte_offset [number],
    },
    MemBaseUnknown { variant_unique, reason [str], },
  },
  sum. MemObjectKind {
    MemObjectParam,
    MemObjectLocal,
    MemObjectGlobal,
    MemObjectData,
    MemObjectView,
    MemObjectSlice,
    MemObjectByteSpan,
    MemObjectContract,
    MemObjectDerived,
    MemObjectLease,
    MemObjectUnknown,
  },
  sum. MemProjectionKind {
    MemProjectField,
    MemProjectBytes,
    MemProjectPtrOffset,
    MemProjectViewData,
    MemProjectSlice,
    MemProjectWindow,
    MemProjectElement,
    MemProjectUnknown { variant_unique, reason [str], },
  },
  sum. MemObjectProvenance {
    MemProvValue { variant_unique, field. value [MoonCode.CodeValueId], },
    MemProvLocal { variant_unique, field. local_id [MoonCode.CodeLocalId], },
    MemProvGlobal { variant_unique, global [MoonCode.CodeGlobalId], },
    MemProvData { variant_unique, data [MoonCode.CodeDataId], },
    MemProvView {
      variant_unique,
      view [MoonCode.CodeValueId],
      data [MoonCode.CodeValueId],
      len [MoonCode.CodeValueId],
      stride [optional [MoonCode.CodeValueId]],
    },
    MemProvSlice {
      variant_unique,
      slice [MoonCode.CodeValueId],
      data [MoonCode.CodeValueId],
      len [MoonCode.CodeValueId],
    },
    MemProvByteSpan {
      variant_unique,
      span [MoonCode.CodeValueId],
      data [MoonCode.CodeValueId],
      len [MoonCode.CodeValueId],
    },
    MemProvContract { variant_unique, fact [MoonCode.CodeFuncContractFact], },
    MemProvLease { variant_unique, lease [MoonMem.MemLeaseId], },
    MemProvProjection {
      variant_unique,
      parent [MoonMem.MemObjectId],
      projection [MoonMem.MemProjectionKind],
      byte_offset [number],
    },
    MemProvUnknown { variant_unique, reason [str], },
  },
  sum. MemObjectExtent {
    MemExtentUnknown { variant_unique, reason [str], },
    MemExtentElements {
      variant_unique,
      len [MoonCode.CodeValueId],
      elem_ty [MoonCode.CodeType],
      reason [str],
    },
    MemExtentBytes { variant_unique, bytes [number], reason [str], },
    MemExtentContract { variant_unique, fact [MoonCode.CodeFuncContractFact], reason [str], },
  },
  sum. MemObjectStride {
    MemStrideUnknown { variant_unique, reason [str], },
    MemStrideUnit,
    MemStrideConstElems { variant_unique, elems [number], },
    MemStrideValue { variant_unique, field. value [MoonCode.CodeValueId], },
  },
  product. MemObjectFact {
    interned,
    field. id [MoonMem.MemObjectId],
    func [optional [MoonCode.CodeFuncId]],
    kind [MoonMem.MemObjectKind],
    provenance [MoonMem.MemObjectProvenance],
    elem_ty [optional [MoonCode.CodeType]],
    extent [MoonMem.MemObjectExtent],
    stride [MoonMem.MemObjectStride],
  },
  product. MemLeaseGrant {
    interned,
    field. id [MoonMem.MemLeaseId],
    domain [optional [MoonFlow.FlowDomain]],
    lease_value [MoonCode.CodeValueId],
    handle [optional [MoonCode.CodeValueId]],
    object [MoonMem.MemObjectId],
    base [MoonMem.MemBase],
    extent [MoonMem.MemObjectExtent],
    stride [MoonMem.MemObjectStride],
    proof [MoonMem.MemProof],
  },
  sum. MemIndex {
    MemIndexNone,
    MemIndexValue {
      variant_unique,
      field. value [MoonCode.CodeValueId],
      elem_size [number],
      const_offset [number],
    },
    MemIndexInduction {
      variant_unique,
      induction [MoonFlow.FlowInduction],
      elem_size [number],
      const_offset [number],
    },
  },
  sum. MemAccessPattern {
    MemAccessScalar,
    MemAccessContiguous,
    MemAccessStrided { variant_unique, stride_elems [number], },
    MemAccessGather,
    MemAccessScatter,
    MemAccessUnknown,
  },
  sum. MemAlignment {
    MemAlignUnknown,
    MemAlignKnown { variant_unique, bytes [number], },
    MemAlignAtLeast { variant_unique, bytes [number], },
    MemAlignAssumed { variant_unique, bytes [number], proof [MoonMem.MemProof], },
  },
  sum. MemBounds {
    MemBoundsUnknown { variant_unique, reason [str], },
    MemBoundsInObject { variant_unique, reason [str], },
    MemBoundsRange {
      variant_unique,
      start [MoonCode.CodeValueId],
      len [MoonCode.CodeValueId],
      reason [str],
    },
    MemBoundsAssumed { variant_unique, proof [MoonMem.MemProof], },
  },
  sum. MemTrap {
    MemMayTrap,
    MemNonTrapping { variant_unique, reason [str], },
    MemCheckedTrap { variant_unique, reason [str], },
  },
  product. MemAccessFact {
    interned,
    field. id [MoonMem.MemAccessId],
    func [MoonCode.CodeFuncId],
    block [MoonGraph.GraphBlockId],
    inst [optional [MoonCode.CodeInstId]],
    kind [MoonMem.MemAccessKind],
    place [MoonCode.CodePlace],
    access [MoonCode.CodeMemoryAccess],
    base [MoonMem.MemBase],
    index [MoonMem.MemIndex],
    pattern [MoonMem.MemAccessPattern],
    alignment [MoonMem.MemAlignment],
    bounds [MoonMem.MemBounds],
    trap [MoonMem.MemTrap],
  },
  product. MemAccessInterval {
    interned,
    access [MoonMem.MemAccessId],
    object [MoonMem.MemObjectId],
    loop [optional [MoonGraph.GraphLoopId]],
    start [MoonMem.MemIndex],
    length_elems [MoonFlow.FlowBound],
    elem_size [number],
    const_byte_offset [number],
    reason [str],
  },
  sum. MemAccessSafetyFact {
    MemAccessInBounds {
      variant_unique,
      interval [MoonMem.MemAccessInterval],
      proof [MoonMem.MemProof],
    },
    MemAccessNonTrap {
      variant_unique,
      access [MoonMem.MemAccessId],
      proof [MoonMem.MemProof],
    },
    MemAccessMovable {
      variant_unique,
      access [MoonMem.MemAccessId],
      proof [MoonMem.MemProof],
    },
    MemAccessDerefBytes {
      variant_unique,
      access [MoonMem.MemAccessId],
      bytes [number],
      proof [MoonMem.MemProof],
    },
    MemAccessAlignKnown {
      variant_unique,
      access [MoonMem.MemAccessId],
      bytes [number],
      proof [MoonMem.MemProof],
    },
  },
  sum. MemObjectEffectFact {
    MemObjectReadonly {
      variant_unique,
      object [MoonMem.MemObjectId],
      proof [MoonMem.MemProof],
    },
    MemObjectWriteonly {
      variant_unique,
      object [MoonMem.MemObjectId],
      proof [MoonMem.MemProof],
    },
  },
  sum. MemObjectRelation {
    MemObjectsSameLen {
      variant_unique,
      a [MoonMem.MemObjectId],
      b [MoonMem.MemObjectId],
      proof [MoonMem.MemProof],
    },
    MemObjectWindowOf {
      variant_unique,
      window [MoonMem.MemObjectId],
      parent [MoonMem.MemObjectId],
      start [MoonCode.CodeValueId],
      len [MoonCode.CodeValueId],
      proof [MoonMem.MemProof],
    },
    MemObjectSliceOf {
      variant_unique,
      slice [MoonMem.MemObjectId],
      parent [MoonMem.MemObjectId],
      start [MoonCode.CodeValueId],
      len [MoonCode.CodeValueId],
      proof [MoonMem.MemProof],
    },
    MemObjectSameStore {
      variant_unique,
      a [MoonMem.MemObjectId],
      b [MoonMem.MemObjectId],
      proof [MoonMem.MemProof],
    },
  },
  sum. MemAliasFact {
    MemAliasUnknown {
      variant_unique,
      a [MoonMem.MemAccessId],
      b [MoonMem.MemAccessId],
      reason [str],
    },
    MemMayAlias {
      variant_unique,
      a [MoonMem.MemAccessId],
      b [MoonMem.MemAccessId],
      reason [str],
    },
    MemNoAlias {
      variant_unique,
      a [MoonMem.MemAccessId],
      b [MoonMem.MemAccessId],
      proof [MoonMem.MemProof],
    },
    MemSameBaseSameIndexSafe {
      variant_unique,
      a [MoonMem.MemAccessId],
      b [MoonMem.MemAccessId],
      proof [MoonMem.MemProof],
    },
    MemAliasScope {
      variant_unique,
      access [MoonMem.MemAccessId],
      scope [MoonMem.MemScopeId],
    },
  },
  sum. MemDependenceFact {
    MemDependenceUnknown {
      variant_unique,
      before [MoonMem.MemAccessId],
      after [MoonMem.MemAccessId],
      reason [str],
    },
    MemReadReadIndependent {
      variant_unique,
      a [MoonMem.MemAccessId],
      b [MoonMem.MemAccessId],
      reason [str],
    },
    MemNoDependence {
      variant_unique,
      before [MoonMem.MemAccessId],
      after [MoonMem.MemAccessId],
      proof [MoonMem.MemProof],
    },
    MemNoLoopCarriedDependence {
      variant_unique,
      before [MoonMem.MemAccessId],
      after [MoonMem.MemAccessId],
      loop [MoonGraph.GraphLoopId],
      proof [MoonMem.MemProof],
    },
    MemDependenceDistance {
      variant_unique,
      before [MoonMem.MemAccessId],
      after [MoonMem.MemAccessId],
      loop [MoonGraph.GraphLoopId],
      distance_elems [str],
      proof [MoonMem.MemProof],
    },
    MemLoopCarriedDependence {
      variant_unique,
      before [MoonMem.MemAccessId],
      after [MoonMem.MemAccessId],
      loop [MoonGraph.GraphLoopId],
      reason [str],
    },
  },
  sum. MemProof {
    MemProofBounds { variant_unique, reason [str], },
    MemProofAlignment { variant_unique, reason [str], },
    MemProofAlias { variant_unique, fact [MoonMem.MemAliasFact], reason [str], },
    MemProofNoDependence {
      variant_unique,
      accesses [many [MoonMem.MemAccessId]],
      reason [str],
    },
    MemProofContract { variant_unique, fact [MoonCode.CodeFuncContractFact], reason [str], },
    MemProofFlow { variant_unique, loop [MoonGraph.GraphLoopId], reason [str], },
    MemProofObject { variant_unique, object [MoonMem.MemObjectId], reason [str], },
    MemProofInterval { variant_unique, interval [MoonMem.MemAccessInterval], reason [str], },
    MemProofBackend { variant_unique, access [MoonMem.MemAccessId], reason [str], },
  },
  product. MemBackendAccessInfo {
    interned,
    access [MoonMem.MemAccessId],
    trap [MoonMem.MemTrap],
    alignment [MoonMem.MemAlignment],
    bounds [MoonMem.MemBounds],
    deref_bytes [optional [number]],
    movable [bool],
    proofs [many [MoonMem.MemProof]],
  },
  product. MemSemanticFactSet {
    interned,
    field. module [MoonCode.CodeModuleId],
    objects [many [MoonMem.MemObjectFact]],
    leases [many [MoonMem.MemLeaseGrant]],
    accesses [many [MoonMem.MemAccessFact]],
    intervals [many [MoonMem.MemAccessInterval]],
    safety [many [MoonMem.MemAccessSafetyFact]],
    effects [many [MoonMem.MemObjectEffectFact]],
    dependences [many [MoonMem.MemDependenceFact]],
    relations [many [MoonMem.MemObjectRelation]],
    backend_info [many [MoonMem.MemBackendAccessInfo]],
    proofs [many [MoonMem.MemProof]],
  },
  product. MemFactSet {
    interned,
    field. module [MoonCode.CodeModuleId],
    accesses [many [MoonMem.MemAccessFact]],
    aliases [many [MoonMem.MemAliasFact]],
    dependences [many [MoonMem.MemDependenceFact]],
    proofs [many [MoonMem.MemProof]],
  },
}
