local S = require("moonlift.schema.dsl")
S.use()

return schema. MoonSource {
  product. DocUri { interned, text [str], },
  product. DocVersion { interned, field. value [number], },
  sum. LanguageId {
    LangMlua,
    LangMoonlift,
    LangLua,
    LangUnknown { variant_unique, field. name [str], },
  },
  product. DocumentSnapshot {
    uri [MoonSource.DocUri],
    version [MoonSource.DocVersion],
    language [MoonSource.LanguageId],
    text [str],
  },
  sum. PositionEncoding { PosUtf8Bytes, PosUtf16CodeUnits, PosUtf32Codepoints, },
  product. SourcePos { interned, line [number], byte_col [number], utf16_col [number], },
  product. SourceRange {
    interned,
    uri [MoonSource.DocUri],
    start_offset [number],
    stop_offset [number],
    start [MoonSource.SourcePos],
    stop [MoonSource.SourcePos],
  },
  sum. TextChange {
    ReplaceAll { text [str], },
    ReplaceRange { range [MoonSource.SourceRange], text [str], },
  },
  product. DocumentEdit {
    uri [MoonSource.DocUri],
    version [MoonSource.DocVersion],
    changes [many [MoonSource.TextChange]],
  },
  product. SourceSlice { text [str], },
  product. SourceOccurrence {
    slice [MoonSource.SourceSlice],
    range [MoonSource.SourceRange],
  },
  product. AnchorId { interned, text [str], },
  sum. AnchorKind {
    AnchorDocument,
    AnchorLuaOpaque,
    AnchorHostedIsland,
    AnchorIslandBody,
    AnchorKeyword,
    AnchorScalarType,
    AnchorStructName,
    AnchorFieldName,
    AnchorFieldUse,
    AnchorFunctionName,
    AnchorFunctionUse,
    AnchorMethodName,
    AnchorParamName,
    AnchorLocalName,
    AnchorBindingDef,
    AnchorBindingUse,
    AnchorRegionName,
    AnchorExprName,
    AnchorContinuationName,
    AnchorContinuationUse,
    AnchorBuiltinName,
    AnchorPackedAlign,
    AnchorDiagnostic,
    AnchorExposeName,
    AnchorModuleName,
    AnchorOpaque { variant_unique, field. name [str], },
  },
  product. Anchor {
    interned,
    field. id [MoonSource.AnchorId],
    kind [MoonSource.AnchorKind],
    label [str],
  },
  product. AnchorSpan {
    interned,
    field. id [MoonSource.AnchorId],
    kind [MoonSource.AnchorKind],
    label [str],
    range [MoonSource.SourceRange],
  },
  product. AnchorSet { interned, anchors [many [MoonSource.AnchorSpan]], },
  product. SourceLineSpan {
    interned,
    line [number],
    start_offset [number],
    stop_offset [number],
    next_offset [number],
  },
  product. PositionIndex {
    document [MoonSource.DocumentSnapshot],
    lines [many [MoonSource.SourceLineSpan]],
  },
  sum. SourceApplyIssue {
    SourceIssueWrongDocument {
      variant_unique,
      expected [MoonSource.DocUri],
      actual [MoonSource.DocUri],
    },
    SourceIssueStaleVersion {
      variant_unique,
      expected_after [MoonSource.DocVersion],
      actual [MoonSource.DocVersion],
    },
    SourceIssueInvalidRange { variant_unique, reason [str], },
    SourceIssueOverlappingRanges {
      variant_unique,
      previous [MoonSource.SourceRange],
      current [MoonSource.SourceRange],
    },
    SourceIssueMixedReplaceAll,
  },
  sum. SourceApplyResult {
    SourceApplyOk { document [MoonSource.DocumentSnapshot], },
    SourceApplyRejected {
      document [MoonSource.DocumentSnapshot],
      issues [many [MoonSource.SourceApplyIssue]],
    },
  },
  sum. SourcePositionResult {
    SourcePositionHit { variant_unique, pos [MoonSource.SourcePos], },
    SourcePositionMiss { variant_unique, reason [str], },
  },
  sum. SourceOffsetResult {
    SourceOffsetHit { variant_unique, offset [number], },
    SourceOffsetMiss { variant_unique, reason [str], },
  },
  product. AnchorIndex {
    interned,
    set [MoonSource.AnchorSet],
    anchors [many [MoonSource.AnchorSpan]],
  },
  sum. AnchorQuery {
    AnchorQueryPosition {
      variant_unique,
      index [MoonSource.AnchorIndex],
      uri [MoonSource.DocUri],
      offset [number],
    },
    AnchorQueryRange {
      variant_unique,
      index [MoonSource.AnchorIndex],
      range [MoonSource.SourceRange],
    },
    AnchorQueryId {
      variant_unique,
      index [MoonSource.AnchorIndex],
      field. id [MoonSource.AnchorId],
    },
  },
  sum. AnchorLookupResult {
    AnchorLookup { variant_unique, anchors [many [MoonSource.AnchorSpan]], },
  },
}
