local S = require("moonlift.schema.dsl")
S.use()

return schema. MoonTree {
  sum. ExprHeader {
    ExprSurface,
    ExprTyped { variant_unique, field. ty [MoonType.Type], },
    ExprOpen { variant_unique, field. ty [MoonType.Type], open [MoonOpen.OpenSet], },
  },
  sum. PlaceHeader {
    PlaceSurface,
    PlaceTyped { variant_unique, field. ty [MoonType.Type], },
    PlaceOpen { variant_unique, field. ty [MoonType.Type], open [MoonOpen.OpenSet], },
  },
  sum. StmtHeader {
    StmtSurface,
    StmtOpen { variant_unique, open [MoonOpen.OpenSet], },
    StmtFlow { variant_unique, flow [MoonSem.FlowClass], },
  },
  sum. RegionUseMode { RegionUseEmit, RegionUseCall, },
  product. FieldInit {
    interned,
    field. name [str],
    field. value [MoonTree.Expr],
    offset [number],
  },
  product. VariantBind { interned, field. name [str], field. ty [MoonType.Type], },
  product. SwitchStmtArm { interned, raw_key [str], body [many [MoonTree.Stmt]], },
  product. SwitchExprArm {
    interned,
    raw_key [str],
    body [many [MoonTree.Stmt]],
    result [MoonTree.Expr],
  },
  product. SwitchVariantStmtArm {
    interned,
    variant_name [str],
    binds [many [MoonTree.VariantBind]],
    body [many [MoonTree.Stmt]],
  },
  product. SwitchVariantExprArm {
    interned,
    variant_name [str],
    binds [many [MoonTree.VariantBind]],
    body [many [MoonTree.Stmt]],
    result [MoonTree.Expr],
  },
  sum. View {
    ViewFromExpr { variant_unique, base [MoonTree.Expr], elem [MoonType.Type], },
    ViewContiguous {
      variant_unique,
      data [MoonTree.Expr],
      elem [MoonType.Type],
      len [MoonTree.Expr],
    },
    ViewStrided {
      variant_unique,
      data [MoonTree.Expr],
      elem [MoonType.Type],
      len [MoonTree.Expr],
      stride [MoonTree.Expr],
    },
    ViewRestrided {
      variant_unique,
      base [MoonTree.View],
      elem [MoonType.Type],
      stride [MoonTree.Expr],
    },
    ViewWindow {
      variant_unique,
      base [MoonTree.View],
      start [MoonTree.Expr],
      len [MoonTree.Expr],
    },
    ViewRowBase {
      variant_unique,
      base [MoonTree.View],
      row_offset [MoonTree.Expr],
      elem [MoonType.Type],
    },
    ViewInterleaved {
      variant_unique,
      data [MoonTree.Expr],
      elem [MoonType.Type],
      len [MoonTree.Expr],
      stride [MoonTree.Expr],
      lane [MoonTree.Expr],
    },
    ViewInterleavedView {
      variant_unique,
      base [MoonTree.View],
      elem [MoonType.Type],
      stride [MoonTree.Expr],
      lane [MoonTree.Expr],
    },
  },
  sum. Domain {
    DomainRange { variant_unique, stop [MoonTree.Expr], },
    DomainRange2 { variant_unique, start [MoonTree.Expr], stop [MoonTree.Expr], },
    DomainZipEqValues { variant_unique, values [many [MoonTree.Expr]], },
    DomainValue { variant_unique, field. value [MoonTree.Expr], },
    DomainView { variant_unique, view [MoonTree.View], },
    DomainZipEqViews { variant_unique, views [many [MoonTree.View]], },
    DomainSlotValue { variant_unique, slot [MoonOpen.DomainSlot], },
  },
  sum. IndexBase {
    IndexBaseExpr { variant_unique, base [MoonTree.Expr], },
    IndexBasePlace { variant_unique, base [MoonTree.Place], elem [MoonType.Type], },
    IndexBaseView { variant_unique, view [MoonTree.View], },
  },
  sum. Place {
    PlaceRef {
      variant_unique,
      h [MoonTree.PlaceHeader],
      field. ref [MoonBind.ValueRef],
    },
    PlaceDeref { variant_unique, h [MoonTree.PlaceHeader], base [MoonTree.Expr], },
    PlaceDot {
      variant_unique,
      h [MoonTree.PlaceHeader],
      base [MoonTree.Place],
      field. name [str],
    },
    PlaceField {
      variant_unique,
      h [MoonTree.PlaceHeader],
      base [MoonTree.Place],
      field. field [MoonSem.FieldRef],
    },
    PlaceIndex {
      variant_unique,
      h [MoonTree.PlaceHeader],
      base [MoonTree.IndexBase],
      index [MoonTree.Expr],
    },
    PlaceSlotValue {
      variant_unique,
      h [MoonTree.PlaceHeader],
      slot [MoonOpen.PlaceSlot],
    },
  },
  product. BlockLabel { interned, field. name [str], },
  product. BlockParam { interned, field. name [str], field. ty [MoonType.Type], },
  product. EntryBlockParam {
    interned,
    field. name [str],
    field. ty [MoonType.Type],
    init [MoonTree.Expr],
  },
  product. JumpArg { interned, field. name [str], field. value [MoonTree.Expr], },
  sum. FuncContract {
    ContractBounds { variant_unique, base [MoonTree.Expr], len [MoonTree.Expr], },
    ContractWindowBounds {
      variant_unique,
      base [MoonTree.Expr],
      base_len [MoonTree.Expr],
      start [MoonTree.Expr],
      len [MoonTree.Expr],
    },
    ContractDisjoint { variant_unique, a [MoonTree.Expr], b [MoonTree.Expr], },
    ContractSameLen { variant_unique, a [MoonTree.Expr], b [MoonTree.Expr], },
    ContractNoAlias { variant_unique, base [MoonTree.Expr], },
    ContractReadonly { variant_unique, base [MoonTree.Expr], },
    ContractWriteonly { variant_unique, base [MoonTree.Expr], },
    ContractInvalidate { variant_unique, base [MoonTree.Expr], },
    ContractPreserve { variant_unique, base [MoonTree.Expr], },
  },
  sum. ContractFact {
    ContractFactBounds {
      variant_unique,
      base [MoonBind.Binding],
      len [MoonBind.Binding],
    },
    ContractFactWindowBounds {
      variant_unique,
      base [MoonBind.Binding],
      base_len [MoonTree.Expr],
      start [MoonTree.Expr],
      len [MoonTree.Expr],
    },
    ContractFactDisjoint { variant_unique, a [MoonBind.Binding], b [MoonBind.Binding], },
    ContractFactSameLen { variant_unique, a [MoonBind.Binding], b [MoonBind.Binding], },
    ContractFactNoAlias { variant_unique, base [MoonBind.Binding], },
    ContractFactReadonly { variant_unique, base [MoonBind.Binding], },
    ContractFactWriteonly { variant_unique, base [MoonBind.Binding], },
    ContractFactInvalidate { variant_unique, base [MoonBind.Binding], },
    ContractFactPreserve { variant_unique, base [MoonBind.Binding], },
    ContractFactRejected { variant_unique, issue [MoonTree.TypeIssue], },
  },
  product. ContractFactSet { interned, facts [many [MoonTree.ContractFact]], },
  product. EntryControlBlock {
    interned,
    label [MoonTree.BlockLabel],
    params [many [MoonTree.EntryBlockParam]],
    body [many [MoonTree.Stmt]],
  },
  product. ControlBlock {
    interned,
    label [MoonTree.BlockLabel],
    params [many [MoonTree.BlockParam]],
    body [many [MoonTree.Stmt]],
  },
  product. ControlStmtRegion {
    interned,
    region_id [str],
    entry [MoonTree.EntryControlBlock],
    blocks [many [MoonTree.ControlBlock]],
  },
  product. ControlExprRegion {
    interned,
    region_id [str],
    result_ty [MoonType.Type],
    entry [MoonTree.EntryControlBlock],
    blocks [many [MoonTree.ControlBlock]],
  },
  sum. ControlFact {
    ControlFactEntryBlock { variant_unique, region_id [str], label [MoonTree.BlockLabel], },
    ControlFactBlock { variant_unique, region_id [str], label [MoonTree.BlockLabel], },
    ControlFactEntryParam {
      variant_unique,
      region_id [str],
      label [MoonTree.BlockLabel],
      index [number],
      field. name [str],
      field. ty [MoonType.Type],
    },
    ControlFactBlockParam {
      variant_unique,
      region_id [str],
      label [MoonTree.BlockLabel],
      index [number],
      field. name [str],
      field. ty [MoonType.Type],
    },
    ControlFactJump {
      variant_unique,
      region_id [str],
      from_label [MoonTree.BlockLabel],
      to_label [MoonTree.BlockLabel],
    },
    ControlFactJumpArg {
      variant_unique,
      region_id [str],
      from_label [MoonTree.BlockLabel],
      to_label [MoonTree.BlockLabel],
      field. name [str],
      field. ty [MoonType.Type],
    },
    ControlFactYieldVoid { variant_unique, region_id [str], from_label [MoonTree.BlockLabel], },
    ControlFactYieldValue {
      variant_unique,
      region_id [str],
      from_label [MoonTree.BlockLabel],
      field. ty [MoonType.Type],
    },
    ControlFactReturn { variant_unique, region_id [str], from_label [MoonTree.BlockLabel], },
    ControlFactBackedge {
      variant_unique,
      region_id [str],
      from_label [MoonTree.BlockLabel],
      to_label [MoonTree.BlockLabel],
    },
    ControlFactVariantSwitch {
      variant_unique,
      region_id [str],
      from_label [MoonTree.BlockLabel],
      switch_on [str],
      arms [many [MoonTree.ControlVariantArmFact]],
      default_label [MoonTree.BlockLabel],
    },
  },
  product. ControlVariantArmFact {
    interned,
    variant_name [str],
    tag_value [number],
    label [MoonTree.BlockLabel],
    binds [many [MoonTree.BlockParam]],
  },
  product. ControlFactSet { interned, facts [many [MoonTree.ControlFact]], },
  sum. ControlReject {
    ControlRejectDuplicateLabel {
      variant_unique,
      region_id [str],
      label [MoonTree.BlockLabel],
    },
    ControlRejectMissingLabel { variant_unique, region_id [str], label [MoonTree.BlockLabel], },
    ControlRejectMissingJumpArg {
      variant_unique,
      region_id [str],
      label [MoonTree.BlockLabel],
      field. name [str],
    },
    ControlRejectExtraJumpArg {
      variant_unique,
      region_id [str],
      label [MoonTree.BlockLabel],
      field. name [str],
    },
    ControlRejectDuplicateJumpArg {
      variant_unique,
      region_id [str],
      label [MoonTree.BlockLabel],
      field. name [str],
    },
    ControlRejectJumpType {
      variant_unique,
      region_id [str],
      label [MoonTree.BlockLabel],
      field. name [str],
      expected [MoonType.Type],
      actual [MoonType.Type],
    },
    ControlRejectYieldOutsideRegion { variant_unique, reason [str], },
    ControlRejectYieldType {
      variant_unique,
      region_id [str],
      expected [MoonType.Type],
      actual [MoonType.Type],
    },
    ControlRejectUnterminatedBlock {
      variant_unique,
      region_id [str],
      label [MoonTree.BlockLabel],
    },
    ControlRejectIrreducible { variant_unique, region_id [str], reason [str], },
    ControlRejectUnknownVariant { variant_unique, region_id [str], variant_name [str], },
  },
  sum. ControlDecision {
    ControlDecisionReducible {
      variant_unique,
      region_id [str],
      facts [many [MoonTree.ControlFact]],
    },
    ControlDecisionIrreducible {
      variant_unique,
      region_id [str],
      reject [MoonTree.ControlReject],
    },
  },
  sum. Expr {
    ExprLit { variant_unique, h [MoonTree.ExprHeader], field. value [MoonCore.Literal], },
    ExprRef { variant_unique, h [MoonTree.ExprHeader], field. ref [MoonBind.ValueRef], },
    ExprDot {
      variant_unique,
      h [MoonTree.ExprHeader],
      base [MoonTree.Expr],
      field. name [str],
    },
    ExprUnary {
      variant_unique,
      h [MoonTree.ExprHeader],
      op [MoonCore.UnaryOp],
      field. value [MoonTree.Expr],
    },
    ExprBinary {
      variant_unique,
      h [MoonTree.ExprHeader],
      op [MoonCore.BinaryOp],
      lhs [MoonTree.Expr],
      rhs [MoonTree.Expr],
    },
    ExprCompare {
      variant_unique,
      h [MoonTree.ExprHeader],
      op [MoonCore.CmpOp],
      lhs [MoonTree.Expr],
      rhs [MoonTree.Expr],
    },
    ExprLogic {
      variant_unique,
      h [MoonTree.ExprHeader],
      op [MoonCore.LogicOp],
      lhs [MoonTree.Expr],
      rhs [MoonTree.Expr],
    },
    ExprCast {
      variant_unique,
      h [MoonTree.ExprHeader],
      op [MoonCore.SurfaceCastOp],
      field. ty [MoonType.Type],
      field. value [MoonTree.Expr],
    },
    ExprMachineCast {
      variant_unique,
      h [MoonTree.ExprHeader],
      op [MoonCore.MachineCastOp],
      field. ty [MoonType.Type],
      field. value [MoonTree.Expr],
    },
    ExprIntrinsic {
      variant_unique,
      h [MoonTree.ExprHeader],
      op [MoonCore.Intrinsic],
      args [many [MoonTree.Expr]],
    },
    ExprAddrOf { variant_unique, h [MoonTree.ExprHeader], place [MoonTree.Place], },
    ExprDeref { variant_unique, h [MoonTree.ExprHeader], field. value [MoonTree.Expr], },
    ExprCall {
      variant_unique,
      h [MoonTree.ExprHeader],
      callee [MoonTree.Expr],
      args [many [MoonTree.Expr]],
    },
    ExprLen { variant_unique, h [MoonTree.ExprHeader], field. value [MoonTree.Expr], },
    ExprField {
      variant_unique,
      h [MoonTree.ExprHeader],
      base [MoonTree.Expr],
      field. field [MoonSem.FieldRef],
    },
    ExprIndex {
      variant_unique,
      h [MoonTree.ExprHeader],
      base [MoonTree.IndexBase],
      index [MoonTree.Expr],
    },
    ExprAgg {
      variant_unique,
      h [MoonTree.ExprHeader],
      field. ty [MoonType.Type],
      fields [many [MoonTree.FieldInit]],
    },
    ExprArray {
      variant_unique,
      h [MoonTree.ExprHeader],
      elem_ty [MoonType.Type],
      elems [many [MoonTree.Expr]],
    },
    ExprIf {
      variant_unique,
      h [MoonTree.ExprHeader],
      cond [MoonTree.Expr],
      then_expr [MoonTree.Expr],
      else_expr [MoonTree.Expr],
    },
    ExprSelect {
      variant_unique,
      h [MoonTree.ExprHeader],
      cond [MoonTree.Expr],
      then_expr [MoonTree.Expr],
      else_expr [MoonTree.Expr],
    },
    ExprSwitch {
      variant_unique,
      h [MoonTree.ExprHeader],
      field. value [MoonTree.Expr],
      arms [many [MoonTree.SwitchExprArm]],
      variant_arms [many [MoonTree.SwitchVariantExprArm]],
      default_body [many [MoonTree.Stmt]],
      default_expr [MoonTree.Expr],
    },
    ExprControl {
      variant_unique,
      h [MoonTree.ExprHeader],
      region [MoonTree.ControlExprRegion],
    },
    ExprBlock {
      variant_unique,
      h [MoonTree.ExprHeader],
      stmts [many [MoonTree.Stmt]],
      result [MoonTree.Expr],
    },
    ExprClosure {
      variant_unique,
      h [MoonTree.ExprHeader],
      params [many [MoonType.Param]],
      result [MoonType.Type],
      body [many [MoonTree.Stmt]],
    },
    ExprView { variant_unique, h [MoonTree.ExprHeader], view [MoonTree.View], },
    ExprLoad {
      variant_unique,
      h [MoonTree.ExprHeader],
      field. ty [MoonType.Type],
      addr [MoonTree.Expr],
    },
    ExprAtomicLoad {
      variant_unique,
      h [MoonTree.ExprHeader],
      field. ty [MoonType.Type],
      addr [MoonTree.Expr],
      ordering [MoonCore.AtomicOrdering],
    },
    ExprAtomicRmw {
      variant_unique,
      h [MoonTree.ExprHeader],
      op [MoonCore.AtomicRmwOp],
      field. ty [MoonType.Type],
      addr [MoonTree.Expr],
      field. value [MoonTree.Expr],
      ordering [MoonCore.AtomicOrdering],
    },
    ExprAtomicCas {
      variant_unique,
      h [MoonTree.ExprHeader],
      field. ty [MoonType.Type],
      addr [MoonTree.Expr],
      expected [MoonTree.Expr],
      replacement [MoonTree.Expr],
      ordering [MoonCore.AtomicOrdering],
    },
    ExprSlotValue { variant_unique, h [MoonTree.ExprHeader], slot [MoonOpen.ExprSlot], },
    ExprUseExprFrag {
      variant_unique,
      h [MoonTree.ExprHeader],
      use_id [str],
      frag [MoonOpen.ExprFragRef],
      args [many [MoonTree.Expr]],
      fills [many [MoonOpen.SlotBinding]],
    },
    ExprCtor {
      variant_unique,
      h [MoonTree.ExprHeader],
      type_name [str],
      variant_name [str],
      args [many [MoonTree.Expr]],
    },
    ExprNull { variant_unique, h [MoonTree.ExprHeader], elem [MoonType.Type], },
    ExprSizeOf { variant_unique, h [MoonTree.ExprHeader], field. ty [MoonType.Type], },
    ExprAlignOf { variant_unique, h [MoonTree.ExprHeader], field. ty [MoonType.Type], },
    ExprIsNull { variant_unique, h [MoonTree.ExprHeader], field. value [MoonTree.Expr], },
  },
  sum. Stmt {
    StmtLet {
      variant_unique,
      h [MoonTree.StmtHeader],
      binding [MoonBind.Binding],
      init [MoonTree.Expr],
    },
    StmtVar {
      variant_unique,
      h [MoonTree.StmtHeader],
      binding [MoonBind.Binding],
      init [MoonTree.Expr],
    },
    StmtSet {
      variant_unique,
      h [MoonTree.StmtHeader],
      place [MoonTree.Place],
      field. value [MoonTree.Expr],
    },
    StmtAtomicStore {
      variant_unique,
      h [MoonTree.StmtHeader],
      field. ty [MoonType.Type],
      addr [MoonTree.Expr],
      field. value [MoonTree.Expr],
      ordering [MoonCore.AtomicOrdering],
    },
    StmtAtomicFence {
      variant_unique,
      h [MoonTree.StmtHeader],
      ordering [MoonCore.AtomicOrdering],
    },
    StmtExpr { variant_unique, h [MoonTree.StmtHeader], field. expr [MoonTree.Expr], },
    StmtAssert { variant_unique, h [MoonTree.StmtHeader], cond [MoonTree.Expr], },
    StmtIf {
      variant_unique,
      h [MoonTree.StmtHeader],
      cond [MoonTree.Expr],
      then_body [many [MoonTree.Stmt]],
      else_body [many [MoonTree.Stmt]],
    },
    StmtSwitch {
      variant_unique,
      h [MoonTree.StmtHeader],
      field. value [MoonTree.Expr],
      arms [many [MoonTree.SwitchStmtArm]],
      variant_arms [many [MoonTree.SwitchVariantStmtArm]],
      default_body [many [MoonTree.Stmt]],
    },
    StmtJump {
      variant_unique,
      h [MoonTree.StmtHeader],
      target [MoonTree.BlockLabel],
      args [many [MoonTree.JumpArg]],
    },
    StmtJumpCont {
      variant_unique,
      h [MoonTree.StmtHeader],
      slot [MoonOpen.ContSlot],
      args [many [MoonTree.JumpArg]],
    },
    StmtYieldVoid { variant_unique, h [MoonTree.StmtHeader], },
    StmtYieldValue {
      variant_unique,
      h [MoonTree.StmtHeader],
      field. value [MoonTree.Expr],
    },
    StmtReturnVoid { variant_unique, h [MoonTree.StmtHeader], },
    StmtReturnValue {
      variant_unique,
      h [MoonTree.StmtHeader],
      field. value [MoonTree.Expr],
    },
    StmtControl {
      variant_unique,
      h [MoonTree.StmtHeader],
      region [MoonTree.ControlStmtRegion],
    },
    StmtUseRegionSlot {
      variant_unique,
      h [MoonTree.StmtHeader],
      slot [MoonOpen.RegionSlot],
    },
    StmtUseRegionFrag {
      variant_unique,
      h [MoonTree.StmtHeader],
      mode [MoonTree.RegionUseMode],
      use_id [str],
      frag [MoonOpen.RegionFragRef],
      args [many [MoonTree.Expr]],
      fills [many [MoonOpen.SlotBinding]],
      cont_fills [many [MoonOpen.ContBinding]],
    },
    StmtTrap { variant_unique, h [MoonTree.StmtHeader], },
  },
  sum. Func {
    FuncLocal {
      variant_unique,
      field. name [str],
      params [many [MoonType.Param]],
      result [MoonType.Type],
      body [many [MoonTree.Stmt]],
    },
    FuncExport {
      variant_unique,
      field. name [str],
      params [many [MoonType.Param]],
      result [MoonType.Type],
      body [many [MoonTree.Stmt]],
    },
    FuncLocalContract {
      variant_unique,
      field. name [str],
      params [many [MoonType.Param]],
      result [MoonType.Type],
      contracts [many [MoonTree.FuncContract]],
      body [many [MoonTree.Stmt]],
    },
    FuncExportContract {
      variant_unique,
      field. name [str],
      params [many [MoonType.Param]],
      result [MoonType.Type],
      contracts [many [MoonTree.FuncContract]],
      body [many [MoonTree.Stmt]],
    },
    FuncDecl {
      variant_unique,
      field. name [str],
      params [many [MoonType.Param]],
      result [MoonType.Type],
    },
    FuncOpen {
      variant_unique,
      sym [MoonCore.FuncSym],
      visibility [MoonCore.Visibility],
      params [many [MoonOpen.OpenParam]],
      open [MoonOpen.OpenSet],
      result [MoonType.Type],
      body [many [MoonTree.Stmt]],
    },
  },
  sum. ExternFunc {
    ExternFunc {
      variant_unique,
      field. name [str],
      symbol [str],
      params [many [MoonType.Param]],
      result [MoonType.Type],
    },
    ExternFuncOpen {
      variant_unique,
      sym [MoonCore.ExternSym],
      params [many [MoonOpen.OpenParam]],
      result [MoonType.Type],
    },
  },
  sum. ConstItem {
    ConstItem {
      variant_unique,
      field. name [str],
      field. ty [MoonType.Type],
      field. value [MoonTree.Expr],
    },
    ConstItemOpen {
      variant_unique,
      sym [MoonCore.ConstSym],
      open [MoonOpen.OpenSet],
      field. ty [MoonType.Type],
      field. value [MoonTree.Expr],
    },
  },
  sum. StaticItem {
    StaticItem {
      variant_unique,
      field. name [str],
      field. ty [MoonType.Type],
      field. value [MoonTree.Expr],
    },
    StaticItemOpen {
      variant_unique,
      sym [MoonCore.StaticSym],
      open [MoonOpen.OpenSet],
      field. ty [MoonType.Type],
      field. value [MoonTree.Expr],
    },
  },
  product. ImportItem { interned, path [MoonCore.Path], },
  sum. TypeDecl {
    TypeDeclStruct { variant_unique, field. name [str], fields [many [MoonType.FieldDecl]], },
    TypeDeclUnion { variant_unique, field. name [str], fields [many [MoonType.FieldDecl]], },
    TypeDeclEnumSugar { variant_unique, field. name [str], variants [many [MoonCore.Name]], },
    TypeDeclTaggedUnionSugar {
      variant_unique,
      field. name [str],
      variants [many [MoonType.VariantDecl]],
    },
    TypeDeclHandle {
      variant_unique,
      field. name [str],
      repr [MoonType.HandleRepr],
      invalid [MoonType.HandleInvalid],
      facts [many [MoonType.HandleFact]],
    },
    TypeDeclOpenStruct {
      variant_unique,
      sym [MoonCore.TypeSym],
      fields [many [MoonType.FieldDecl]],
    },
    TypeDeclOpenUnion {
      variant_unique,
      sym [MoonCore.TypeSym],
      fields [many [MoonType.FieldDecl]],
    },
  },
  sum. Item {
    ItemFunc { variant_unique, func [MoonTree.Func], },
    ItemExtern { variant_unique, func [MoonTree.ExternFunc], },
    ItemConst { variant_unique, c [MoonTree.ConstItem], },
    ItemStatic { variant_unique, s [MoonTree.StaticItem], },
    ItemImport { variant_unique, imp [MoonTree.ImportItem], },
    ItemType { variant_unique, t [MoonTree.TypeDecl], },
    ItemRegionFrag { variant_unique, frag [MoonOpen.RegionFrag], },
    ItemExprFrag { variant_unique, frag [MoonOpen.ExprFrag], },
    ItemUseTypeDeclSlot { variant_unique, slot [MoonOpen.TypeDeclSlot], },
    ItemUseItemsSlot { variant_unique, slot [MoonOpen.ItemsSlot], },
    ItemUseModule {
      variant_unique,
      use_id [str],
      field. module [MoonTree.Module],
      fills [many [MoonOpen.SlotBinding]],
    },
    ItemUseModuleSlot {
      variant_unique,
      use_id [str],
      slot [MoonOpen.ModuleSlot],
      fills [many [MoonOpen.SlotBinding]],
    },
    ItemData { variant_unique, data [MoonTree.DataItem], },
  },
  product. DataItem {
    interned,
    field. id [MoonCore.DataId],
    size [number],
    align [number],
    bytes [str],
  },
  sum. ModuleHeader {
    ModuleSurface,
    ModuleTyped { variant_unique, module_name [str], },
    ModuleOpen {
      variant_unique,
      field. name [MoonOpen.ModuleNameFacet],
      open [MoonOpen.OpenSet],
    },
    ModuleSem { variant_unique, module_name [str], },
    ModuleCode { variant_unique, module_name [str], },
  },
  product. Module { interned, h [MoonTree.ModuleHeader], items [many [MoonTree.Item]], },
  sum. TypeIssue {
    TypeIssueUnresolvedValue { variant_unique, field. name [str], },
    TypeIssueUnresolvedPath { variant_unique, path [MoonCore.Path], },
    TypeIssueExpected {
      variant_unique,
      site [str],
      expected [MoonType.Type],
      actual [MoonType.Type],
    },
    TypeIssueArgCount { variant_unique, site [str], expected [number], actual [number], },
    TypeIssueNotCallable { variant_unique, field. ty [MoonType.Type], },
    TypeIssueNotIndexable { variant_unique, field. ty [MoonType.Type], },
    TypeIssueNotPointer { variant_unique, field. ty [MoonType.Type], },
    TypeIssueInvalidUnary { variant_unique, op [str], field. ty [MoonType.Type], },
    TypeIssueInvalidBinary {
      variant_unique,
      op [str],
      lhs [MoonType.Type],
      rhs [MoonType.Type],
    },
    TypeIssueInvalidCompare {
      variant_unique,
      op [str],
      lhs [MoonType.Type],
      rhs [MoonType.Type],
    },
    TypeIssueInvalidLogic {
      variant_unique,
      op [str],
      lhs [MoonType.Type],
      rhs [MoonType.Type],
    },
    TypeIssueMissingJumpTarget {
      variant_unique,
      region_id [str],
      label [MoonTree.BlockLabel],
    },
    TypeIssueMissingJumpArg {
      variant_unique,
      region_id [str],
      label [MoonTree.BlockLabel],
      field. name [str],
    },
    TypeIssueExtraJumpArg {
      variant_unique,
      region_id [str],
      label [MoonTree.BlockLabel],
      field. name [str],
    },
    TypeIssueDuplicateJumpArg {
      variant_unique,
      region_id [str],
      label [MoonTree.BlockLabel],
      field. name [str],
    },
    TypeIssueUnexpectedYield { variant_unique, site [str], },
    TypeIssueInvalidControl {
      variant_unique,
      region_id [str],
      reject [MoonTree.ControlReject],
    },
    TypeIssueUnknownVariant { variant_unique, type_name [str], variant_name [str], },
    TypeIssueVariantPayloadMismatch {
      variant_unique,
      type_name [str],
      variant_name [str],
      expected [MoonType.Type],
      actual [MoonType.Type],
    },
    TypeIssueDuplicateVariant { variant_unique, type_name [str], variant_name [str], },
  },
  sum. TypeYieldMode {
    TypeYieldNone,
    TypeYieldVoid,
    TypeYieldValue { variant_unique, field. ty [MoonType.Type], },
  },
  product. TypeCheckEnv {
    interned,
    env [MoonBind.Env],
    return_ty [MoonType.Type],
    yield [MoonTree.TypeYieldMode],
    region_frags [many [MoonOpen.RegionFrag]],
  },
  sum. TypeViewResult {
    TypeViewResult {
      variant_unique,
      view [MoonTree.View],
      issues [many [MoonTree.TypeIssue]],
    },
  },
  sum. TypeIndexBaseResult {
    TypeIndexBaseResult {
      variant_unique,
      base [MoonTree.IndexBase],
      elem [MoonType.Type],
      issues [many [MoonTree.TypeIssue]],
    },
  },
  sum. TypeControlStmtRegionResult {
    TypeControlStmtRegionResult {
      variant_unique,
      region [MoonTree.ControlStmtRegion],
      issues [many [MoonTree.TypeIssue]],
    },
  },
  sum. TypeControlExprRegionResult {
    TypeControlExprRegionResult {
      variant_unique,
      region [MoonTree.ControlExprRegion],
      issues [many [MoonTree.TypeIssue]],
    },
  },
  sum. TypeExprResult {
    TypeExprResult {
      variant_unique,
      field. expr [MoonTree.Expr],
      field. ty [MoonType.Type],
      issues [many [MoonTree.TypeIssue]],
    },
  },
  sum. TypePlaceResult {
    TypePlaceResult {
      variant_unique,
      place [MoonTree.Place],
      field. ty [MoonType.Type],
      issues [many [MoonTree.TypeIssue]],
    },
  },
  sum. TypeStmtResult {
    TypeStmtResult {
      variant_unique,
      env [MoonTree.TypeCheckEnv],
      stmts [many [MoonTree.Stmt]],
      issues [many [MoonTree.TypeIssue]],
    },
  },
  sum. TypeFuncResult {
    TypeFuncResult {
      variant_unique,
      func [MoonTree.Func],
      issues [many [MoonTree.TypeIssue]],
    },
  },
  sum. TypeItemResult {
    TypeItemResult {
      variant_unique,
      items [many [MoonTree.Item]],
      issues [many [MoonTree.TypeIssue]],
    },
  },
  sum. TypeModuleResult {
    TypeModuleResult {
      variant_unique,
      field. module [MoonTree.Module],
      issues [many [MoonTree.TypeIssue]],
    },
  },
  sum. TreeBackLocal {
    TreeBackScalarLocal {
      variant_unique,
      binding [MoonBind.Binding],
      field. value [MoonBack.BackValId],
      field. ty [MoonBack.BackScalar],
    },
    TreeBackStackLocal {
      variant_unique,
      binding [MoonBind.Binding],
      slot [MoonBack.BackStackSlotId],
      field. ty [MoonBack.BackScalar],
    },
    TreeBackViewLocal {
      variant_unique,
      binding [MoonBind.Binding],
      data [MoonBack.BackValId],
      len [MoonBack.BackValId],
    },
    TreeBackStridedViewLocal {
      variant_unique,
      binding [MoonBind.Binding],
      data [MoonBack.BackValId],
      len [MoonBack.BackValId],
      stride [MoonBack.BackValId],
    },
  },
  sum. TreeBackReturn {
    TreeBackReturnScalar,
    TreeBackReturnView { variant_unique, out [MoonBack.BackValId], },
  },
  product. TreeBackEnv {
    interned,
    locals [many [MoonTree.TreeBackLocal]],
    next_value [number],
    next_block [number],
    ret [MoonTree.TreeBackReturn],
  },
  sum. TreeBackExprResult {
    TreeBackExprValue {
      variant_unique,
      env [MoonTree.TreeBackEnv],
      cmds [many [MoonBack.Cmd]],
      field. value [MoonBack.BackValId],
      field. ty [MoonBack.BackScalar],
    },
    TreeBackExprView {
      variant_unique,
      env [MoonTree.TreeBackEnv],
      cmds [many [MoonBack.Cmd]],
      data [MoonBack.BackValId],
      len [MoonBack.BackValId],
    },
    TreeBackExprStridedView {
      variant_unique,
      env [MoonTree.TreeBackEnv],
      cmds [many [MoonBack.Cmd]],
      data [MoonBack.BackValId],
      len [MoonBack.BackValId],
      stride [MoonBack.BackValId],
    },
    TreeBackExprUnsupported {
      variant_unique,
      env [MoonTree.TreeBackEnv],
      cmds [many [MoonBack.Cmd]],
      reason [str],
    },
  },
  sum. TreeBackStmtResult {
    TreeBackStmtResult {
      variant_unique,
      env [MoonTree.TreeBackEnv],
      cmds [many [MoonBack.Cmd]],
      flow [MoonBack.BackFlow],
    },
  },
  sum. TreeBackFuncResult {
    TreeBackFuncResult { variant_unique, cmds [many [MoonBack.Cmd]], },
  },
  sum. TreeBackItemResult {
    TreeBackItemResult { variant_unique, cmds [many [MoonBack.Cmd]], },
  },
}
