local S = require("moonlift.schema.dsl")
S.use()

return schema. MoonType {
  sum. TypeRef {
    TypeRefPath { variant_unique, path [MoonCore.Path], },
    TypeRefGlobal { variant_unique, module_name [str], type_name [str], },
    TypeRefLocal { variant_unique, sym [MoonCore.TypeSym], },
    TypeRefSlot { variant_unique, slot [MoonOpen.TypeSlot], },
  },
  sum. ArrayLen {
    ArrayLenExpr { variant_unique, field. expr [MoonTree.Expr], },
    ArrayLenConst { variant_unique, count [number], },
    ArrayLenSlot { variant_unique, slot [MoonOpen.ExprSlot], },
  },
  sum. HandleRepr { HandleReprScalar { variant_unique, scalar [MoonCore.Scalar], }, },
  sum. HandleInvalid { HandleInvalidNone, HandleInvalidInt { variant_unique, raw [str], }, },
  sum. HandleFact {
    HandleDomain { variant_unique, domain [MoonType.TypeRef], },
    HandleTarget { variant_unique, target [MoonType.TypeRef], },
  },
  sum. LeaseOrigin { LeaseOriginUnknown, LeaseOriginParam { variant_unique, field. name [str], }, },
  sum. TypeAccess {
    TypeAccessNoAlias,
    TypeAccessReadonly,
    TypeAccessWriteonly,
    TypeAccessNoEscape,
    TypeAccessInvalidate,
    TypeAccessPreserve,
  },
  sum. Type {
    TScalar { variant_unique, scalar [MoonCore.Scalar], },
    TPtr { variant_unique, elem [MoonType.Type], },
    TArray { variant_unique, count [MoonType.ArrayLen], elem [MoonType.Type], },
    TSlice { variant_unique, elem [MoonType.Type], },
    TView { variant_unique, elem [MoonType.Type], },
    TLease { variant_unique, base [MoonType.Type], origin [MoonType.LeaseOrigin], },
    TOwned { variant_unique, base [MoonType.Type], },
    TAccess { variant_unique, access [MoonType.TypeAccess], base [MoonType.Type], },
    THandle {
      variant_unique,
      field. ref [MoonType.TypeRef],
      repr [MoonType.HandleRepr],
    },
    TFunc { variant_unique, params [many [MoonType.Type]], result [MoonType.Type], },
    TClosure { variant_unique, params [many [MoonType.Type]], result [MoonType.Type], },
    TNamed { variant_unique, field. ref [MoonType.TypeRef], },
    TSlot { variant_unique, slot [MoonOpen.TypeSlot], },
    TCType { variant_unique, field. id [MoonC.CTypeId], },
    TCFuncPtr { variant_unique, sig [MoonC.CFuncSigId], },
  },
  sum. TypeClass {
    TypeClassScalar { variant_unique, scalar [MoonCore.Scalar], },
    TypeClassPointer { variant_unique, elem [MoonType.Type], },
    TypeClassArray { variant_unique, elem [MoonType.Type], count [number], },
    TypeClassSlice { variant_unique, elem [MoonType.Type], },
    TypeClassView { variant_unique, elem [MoonType.Type], },
    TypeClassLease {
      variant_unique,
      base [MoonType.Type],
      origin [MoonType.LeaseOrigin],
    },
    TypeClassOwned { variant_unique, base [MoonType.Type], },
    TypeClassHandle { variant_unique, repr [MoonType.HandleRepr], },
    TypeClassCallable {
      variant_unique,
      params [many [MoonType.Type]],
      result [MoonType.Type],
    },
    TypeClassClosure {
      variant_unique,
      params [many [MoonType.Type]],
      result [MoonType.Type],
    },
    TypeClassAggregate { variant_unique, module_name [str], type_name [str], },
    TypeClassUnknown,
  },
  sum. TypeBackScalarResult {
    TypeBackScalarKnown { variant_unique, scalar [MoonBack.BackScalar], },
    TypeBackScalarUnavailable {
      variant_unique,
      field. ty [MoonType.Type],
      class [MoonType.TypeClass],
    },
  },
  sum. TypeMemLayoutResult {
    TypeMemLayoutKnown { variant_unique, layout [MoonSem.MemLayout], },
    TypeMemLayoutUnknown {
      variant_unique,
      field. ty [MoonType.Type],
      class [MoonType.TypeClass],
    },
  },
  sum. AbiClass {
    AbiIgnore,
    AbiDirect { variant_unique, scalar [MoonBack.BackScalar], },
    AbiIndirect { variant_unique, layout [MoonSem.MemLayout], },
    AbiDescriptor { variant_unique, layout [MoonSem.MemLayout], },
    AbiUnknown { variant_unique, class [MoonType.TypeClass], },
  },
  product. AbiDecision {
    interned,
    field. ty [MoonType.Type],
    class [MoonType.AbiClass],
  },
  sum. AbiParamPlan {
    AbiParamScalar {
      variant_unique,
      field. name [str],
      binding [MoonBind.Binding],
      scalar [MoonBack.BackScalar],
      field. value [MoonBack.BackValId],
    },
    AbiParamView {
      variant_unique,
      field. name [str],
      binding [MoonBind.Binding],
      data [MoonBack.BackValId],
      len [MoonBack.BackValId],
      stride [MoonBack.BackValId],
    },
    AbiParamRejected {
      variant_unique,
      field. name [str],
      field. ty [MoonType.Type],
      reason [str],
    },
  },
  sum. AbiResultPlan {
    AbiResultVoid,
    AbiResultScalar { variant_unique, scalar [MoonBack.BackScalar], },
    AbiResultView { variant_unique, elem [MoonType.Type], out [MoonBack.BackValId], },
    AbiResultRejected { variant_unique, field. ty [MoonType.Type], reason [str], },
  },
  product. FuncAbiPlan {
    interned,
    func_name [str],
    params [many [MoonType.AbiParamPlan]],
    result [MoonType.AbiResultPlan],
  },
  product. Param { interned, field. name [str], field. ty [MoonType.Type], },
  product. FieldDecl { interned, field_name [str], field. ty [MoonType.Type], },
  product. VariantDecl {
    interned,
    field. name [str],
    payload [MoonType.Type],
    fields [many [MoonType.FieldDecl]],
  },
}
