local S = require("moonlift.schema.dsl")
S.use()

return schema. MoonValue {
  product. ValueFactId { interned, text [str], },
  product. AlgebraFactId { interned, text [str], },
  sum. ValueExpr {
    ValueExprConst { variant_unique, const [MoonCode.CodeConst], },
    ValueExprValue { variant_unique, field. value [MoonCode.CodeValueId], },
    ValueExprAdd {
      variant_unique,
      a [MoonValue.ValueExpr],
      b [MoonValue.ValueExpr],
      field. ty [MoonCode.CodeType],
      sem [optional [MoonCode.CodeIntSemantics]],
    },
    ValueExprSub {
      variant_unique,
      a [MoonValue.ValueExpr],
      b [MoonValue.ValueExpr],
      field. ty [MoonCode.CodeType],
      sem [optional [MoonCode.CodeIntSemantics]],
    },
    ValueExprMul {
      variant_unique,
      a [MoonValue.ValueExpr],
      b [MoonValue.ValueExpr],
      field. ty [MoonCode.CodeType],
      sem [optional [MoonCode.CodeIntSemantics]],
    },
    ValueExprDiv {
      variant_unique,
      a [MoonValue.ValueExpr],
      b [MoonValue.ValueExpr],
      field. ty [MoonCode.CodeType],
      sem [optional [MoonCode.CodeIntSemantics]],
    },
    ValueExprSelect {
      variant_unique,
      cond [MoonValue.ValueExpr],
      t [MoonValue.ValueExpr],
      f [MoonValue.ValueExpr],
    },
    ValueExprCmp {
      variant_unique,
      op [MoonCore.CmpOp],
      field. ty [MoonCode.CodeType],
      a [MoonValue.ValueExpr],
      b [MoonValue.ValueExpr],
    },
    ValueExprAffine { variant_unique, affine [MoonValue.AffineExpr], },
  },
  product. AffineTerm { interned, field. value [MoonCode.CodeValueId], coeff [str], },
  product. AffineExpr {
    interned,
    constant [str],
    terms [many [MoonValue.AffineTerm]],
    field. ty [MoonCode.CodeType],
    sem [optional [MoonCode.CodeIntSemantics]],
  },
  sum. ValueRange {
    ValueRangeUnknown { variant_unique, reason [str], },
    ValueRangeInt {
      variant_unique,
      field. value [MoonCode.CodeValueId],
      lo [MoonValue.ValueExpr],
      hi [MoonValue.ValueExpr],
      inclusive_hi [bool],
      proof [MoonValue.AlgebraProof],
    },
  },
  sum. ReductionKind {
    ReductionAdd,
    ReductionMul,
    ReductionMin,
    ReductionMax,
    ReductionAnd,
    ReductionOr,
    ReductionXor,
  },
  product. ReductionFact {
    interned,
    field. id [MoonValue.AlgebraFactId],
    domain [MoonFlow.FlowDomain],
    accumulator [MoonCode.CodeValueId],
    kind [MoonValue.ReductionKind],
    init [MoonValue.ValueExpr],
    contribution [MoonValue.ValueExpr],
    field. ty [MoonCode.CodeType],
    int_semantics [optional [MoonCode.CodeIntSemantics]],
    float_mode [optional [MoonCode.CodeFloatMode]],
    proof [MoonValue.AlgebraProof],
  },
  product. ClosedFormFact {
    interned,
    field. id [MoonValue.AlgebraFactId],
    reduction [MoonValue.ReductionFact],
    field. expr [MoonValue.ValueExpr],
    proof [MoonValue.AlgebraProof],
  },
  sum. AlgebraProof {
    AlgebraProofFlow { variant_unique, domain [MoonFlow.FlowDomain], reason [str], },
    AlgebraProofNoWrap { variant_unique, field. value [MoonCode.CodeValueId], reason [str], },
    AlgebraProofIdentity { variant_unique, reason [str], },
    AlgebraProofReduction { variant_unique, fact [MoonValue.ReductionFact], reason [str], },
    AlgebraProofComposite {
      variant_unique,
      proofs [many [MoonValue.AlgebraProof]],
      reason [str],
    },
  },
  sum. ValueFact {
    ValueExprFact {
      variant_unique,
      field. value [MoonCode.CodeValueId],
      field. expr [MoonValue.ValueExpr],
      proof [MoonValue.AlgebraProof],
    },
    ValueRangeFact { variant_unique, range [MoonValue.ValueRange], },
    ValueNoWrapFact {
      variant_unique,
      field. value [MoonCode.CodeValueId],
      sem [MoonCode.CodeIntSemantics],
      proof [MoonValue.AlgebraProof],
    },
    ValueFloatModeFact {
      variant_unique,
      field. value [MoonCode.CodeValueId],
      mode [MoonCode.CodeFloatMode],
      proof [MoonValue.AlgebraProof],
    },
  },
  product. ValueFactSet {
    interned,
    field. module [MoonCode.CodeModuleId],
    values [many [MoonValue.ValueFact]],
    reductions [many [MoonValue.ReductionFact]],
    closed_forms [many [MoonValue.ClosedFormFact]],
  },
}
